/* Çeviri sözlüğü (otomatik üretildi; scratchpad/diller_uret.py). Anahtar = sayfadaki Türkçe metin. Türkçe metinler HTML'de durur. */
window.DILLER = {
 "en": {
  "__title": "Karahan Uçar — Philosophy, metaphysics and philosophy of mind",
  "__desc": "Karahan Uçar: philosophy researcher. Metaphysics, philosophy of mind, epistemology and philosophy of language; publications, talks and knowledge content.",
  "Ana menü": "Main menu",
  "Hakkında": "About",
  "Yayınlar": "Publications",
  "Kanal & Sunumlar": "Channel & Talks",
  "Bilgi": "Knowledge",
  "Randevu": "Appointment",
  "İletişim": "Contact",
  "Dil": "Language",
  "Karahan Uçar logosu: altın rengi phi ve alev": "Karahan Uçar logo: a golden phi and flame",
  "Felsefe araştırmacısı": "Philosophy researcher",
  "Varlığı, zihni, bilgiyi ve dili düşünmeye çalışıyorum; bu sayfa yayınlarımı, sunumlarımı ve bilgi notlarımı bir araya getiriyor.": "I try to think about being, mind, knowledge and language; this page brings together my publications, talks and notes.",
  "Çalışma alanları": "Fields of work",
  "Metafizik": "Metaphysics",
  "Varlık felsefesi": "Philosophy of being",
  "Zihin felsefesi": "Philosophy of mind",
  "Epistemoloji": "Epistemology",
  "Bilgi felsefesi": "Philosophy of knowledge",
  "Dil felsefesi": "Philosophy of language",
  "Mum ışığında bir kütüphanede kitap okuyan kuzgun maskot": "A raven mascot reading a book in a candlelit library",
  "Düşüncenin eşiğinde": "On the threshold of thought",
  "Ormanın ortasında kitaplıklı bir kabin: taş şömine yanıyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "A cabin with bookshelves in the middle of the forest: a stone fireplace burns, and beyond the arched window a snowy pine forest and a full moon are visible",
  "Karahan Uçar’ın portresi": "Portrait of Karahan Uçar",
  "İstanbul Üniversitesi’nde felsefe lisansımı tamamladım; şimdi İstanbul Üniversitesi ve Ruhr-Universität Bochum’da yüksek lisans yapıyorum. Metafizik, zihin felsefesi, epistemoloji ve dil felsefesiyle ilgileniyorum; özellikle varlık felsefesinde soyut ve olmayan nesneler üzerine çalışıyorum. Bu sitede yayınlarımı, sunumlarımı ve bilgi notlarımı paylaşıyorum.": "I completed my undergraduate degree in philosophy at Istanbul University; I am now doing my master’s at Istanbul University and Ruhr-Universität Bochum. I am interested in metaphysics, philosophy of mind, epistemology and philosophy of language; in the philosophy of being I work in particular on abstract and non-existent objects. On this site I share my publications, talks and notes.",
  "taslak": "draft",
  "Kanadını çenesine dayamış, meraklı bakan kuzgun maskot": "A curious raven mascot with a wing resting against its chin",
  "Lisans, İstanbul Üniversitesi": "Bachelor’s degree, Istanbul University",
  "2024 – sürüyor": "2024 – present",
  "Yüksek lisans, İstanbul Üniversitesi ve Ruhr-Universität Bochum": "Master’s degree, Istanbul University and Ruhr-Universität Bochum",
  "Yayınlar ve sunumlar": "Publications and talks",
  "Sunum, seminer ve proje çalışmaları. Yayımlanan makaleler ve bildiriler eklendikçe burada listelenecek; tam liste profillerimde.": "Talks, seminars and project work. Published articles and papers will be listed here as they are added; the full list is on my profiles.",
  "Europa Macht Schule (EMS) projesi": "Europa Macht Schule (EMS) project",
  "Haziran 2026 · Sunum": "June 2026 · Talk",
  "Temmuz 2026 · Sunum": "July 2026 · Talk",
  "Mayıs 2026 · Proje": "May 2026 · Project",
  "PhilPeople profilim": "My PhilPeople profile",
  "Academia profilim": "My Academia profile",
  "LinkedIn profilim": "My LinkedIn profile",
  "“Düşüncenin Eşiğinde” — merak, akıl, anlam. Konu anlatımları ve etkileşimli sunumlar.": "“On the Threshold of Thought” — curiosity, reason, meaning. Topic explanations and interactive presentations.",
  "Neşeli kuzgun maskot iki kanadını açmış": "A cheerful raven mascot with both wings spread",
  "Yaşamın sınırları": "The limits of life",
  "Biyoloji felsefesi üzerine etkileşimli sunum.": "An interactive presentation on the philosophy of biology.",
  "Sunumu aç →": "Open the presentation →",
  "Aristoteles’ten Hegel’e metafizik sorunlar.": "Metaphysical problems from Aristotle to Hegel.",
  "YouTube kanalı": "YouTube channel",
  "Videolar ve yeni yayınlar.": "Videos and new releases.",
  "Kanala git →": "Go to the channel →",
  "Bilgi içerikleri": "Knowledge content",
  "Alan alan düzenlenmiş notlar ve kaynak listeleri.": "Notes and reading lists organised by field.",
  "Felsefe": "Philosophy",
  "Epistemoloji, normatiflik, argüman haritaları, metin tahlilleri.": "Epistemology, normativity, argument maps, text analyses.",
  "Diller": "Languages",
  "Dil öğrenim notları, sözlük ve çeviri çalışmaları.": "Language-learning notes, dictionary and translation work.",
  "Bilimler": "Sciences",
  "Doğa, formel ve sosyal bilimlerden notlar.": "Notes from the natural, formal and social sciences.",
  "Görüşme, danışma ya da sohbet için ücretsiz randevu. Uygun saatleri Google Takvim sayfasından seçebilirsin.": "A free appointment for a meeting, consultation or chat. You can pick a suitable time on the Google Calendar page.",
  "Randevu al →": "Book an appointment →",
  "Akademik profillerim ve sosyal hesaplarım. Görüşmek için yukarıdaki randevu bağlantısını kullanabilirsin.": "My academic profiles and social accounts. To get in touch, you can use the appointment link above.",
  "Gözlüklü kuzgun maskot kanadını kaldırıp selam veriyor": "A raven mascot with a monocle raising a wing to say hello",
  "Akademik profiller": "Academic profiles",
  "Sosyal hesaplar": "Social accounts",
  "Sayfayı okumak istediğin dili seç.": "Choose the language you would like to read the page in.",
  "Türkçe": "Turkish",
  "İngilizce": "English",
  "Almanca": "German",
  "Fransızca": "French",
  "Latince": "Latin",
  "Grekçe": "Greek",
  "Arapça": "Arabic",
  "MERAK · AKIL · ANLAM": "CURIOSITY · REASON · MEANING",
  "Ses:": "Sound:",
  "Şömine": "Fireplace",
  "Yağmur": "Rain",
  "Rüzgâr": "Wind",
  "Kapalı": "Off",
  "Dışarıda:": "Outside:",
  "Kar": "Snow",
  "Ortam sesi": "Ambient sound",
  "Dışarıdaki hava": "Weather outside",
  "İçeriğe geç": "Skip to content",
  "Kütüphaneye gir →": "Enter the library →",
  "Etkileşimli sunum": "Interactive presentation",
  "Video": "Video",
  "Alanlara göre süz": "Filter by field",
  "Tümü": "All",
  "Doğa Bilimleri": "Natural Sciences",
  "Formel Bilimler": "Formal Sciences",
  "Sosyal Bilimler": "Social Sciences",
  "Estetik": "Aesthetics",
  "Beceriler": "Skills",
  "Bir cilde dokun; o alandaki içerikler aşağıda süzülür.": "Touch a volume; the content in that field is filtered below.",
  "Son eklenenler": "Recently added",
  "Okuma": "Reading",
  "Sunum": "Talk",
  "Yakında": "Coming soon",
  "Sıradaki okuma": "The next reading",
  "Yeni bir adım adım okuma hazırlanıyor.": "A new step-by-step reading is in preparation.",
  "Bu rafta henüz içerik yok; yakında eklenecek.": "Nothing on this shelf yet; it will be added soon.",
  "Evren bir matematiksel yapı mı?": "Is the universe a mathematical structure?",
  "Tegmark’ın “Matematiksel Evren” makalesi kaydırarak, adım adım: dış gerçeklik, yapılar, Gödel ve soyut nesneler sorusu.": "Tegmark’s “The Mathematical Universe”, scrolled step by step: external reality, structures, Gödel and the question of abstract objects.",
  "Ortam": "Ambience",
  "Alt menü": "Footer menu",
  "Başa dön ↑": "Back to top ↑",
  "Bu sitede çerez ya da izleyici yok; müzik yalnız gramofona dokununca YouTube’dan yüklenir.": "This site uses no cookies or trackers; music loads from YouTube only when you touch the gramophone.",
  "Müzik çal": "Play music",
  "Müzik yükleniyor…": "Loading music…",
  "Müzik çubuğu": "Music bar",
  "Önceki parça": "Previous track",
  "Çal / Duraklat": "Play / Pause",
  "Sonraki parça": "Next track",
  "Sesi kapat/aç": "Mute/unmute",
  "Müziği kapat": "Close music",
  "Ormanın ortasında kitaplıklı bir kabin: kuzgun maskot şöminenin önündeki deri koltukta kitap okuyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "A cabin with bookshelves in the middle of the forest: the raven mascot reads a book in a leather armchair by the fireplace; beyond the arched window a snowy pine forest and a full moon are visible",
  "Kanal kapağı: karlı bir gecede şömineli kütüphane, ortada altın phi-alev logo, masada kitap okuyan kuzgun maskot": "Channel cover: a library with a fireplace on a snowy night, the golden phi-flame logo in the centre, and the raven mascot reading a book at the desk",
  "Işıklı ciltler kendi dünyalarına açılır; diğerleri aşağıdaki dizini süzer.": "Glowing volumes open into their own worlds; the others filter the index below.",
  "Kütüphane": "Library",
  "Kütüphaneye dön": "Back to the library",
  "Parıldayan nesnelere dokun.": "Touch the glowing objects.",
  "Bu alandaki içerikler": "Content in this field",
  "Paneli kapat": "Close panel",
  "Antik Yunanca": "Ancient Greek",
  "Biyoloji": "Biology",
  "Astronomi": "Astronomy",
  "Fizik": "Physics",
  "Kimya": "Chemistry",
  "Yer Bilimleri": "Earth Sciences",
  "Etik": "Ethics",
  "Mantık": "Logic",
  "Bilgi Felsefesi": "Epistemology",
  "Dil Felsefesi": "Philosophy of Language",
  "Varlık Felsefesi": "Ontology",
  "Zihin Felsefesi": "Philosophy of Mind",
  "Mantık Felsefesi": "Philosophy of Logic",
  "Bilim Felsefesi": "Philosophy of Science",
  "Politik Felsefe": "Political Philosophy",
  "Din Felsefesi": "Philosophy of Religion",
  "Tarih Felsefesi": "Philosophy of History",
  "Sanat Felsefesi": "Philosophy of Art",
  "Felsefe Tarihi": "History of Philosophy",
  "Metafelsefe": "Metaphilosophy",
  "Sözlükçe": "Glossary",
  "Ekoloji": "Ecology",
  "Jeoloji": "Geology",
  "Mühendislik": "Engineering",
  "Tıp": "Medicine",
  "Bilişim": "Computing",
  "Geometri": "Geometry",
  "Matematik": "Mathematics",
  "Antropoloji": "Anthropology",
  "Arkeoloji": "Archaeology",
  "Coğrafya": "Geography",
  "Dilbilimi": "Linguistics",
  "Ekonomi": "Economics",
  "Hukuk": "Law",
  "İlahiyat": "Theology",
  "Siyaset ve Sosyoloji": "Politics and Sociology",
  "Psikoloji ve Psikanaliz": "Psychology and Psychoanalysis",
  "Tarih": "History",
  "Edebiyat": "Literature",
  "Görsel Sanatlar": "Visual Arts",
  "Müzik": "Music",
  "Her raf bir alan. Pirinç levhaya dokununca alanın odası, kitaba dokununca o dalın dünyası açılır; parıldayan kitapların kendi sahnesi var.": "Each shelf is a field. Touch the brass plate to enter the field’s room, or a book to open that branch’s world; glowing books have their own scene.",
  "Sahne": "Scene",
  "Ormanın içinde biyoloji": "Biology in the forest",
  "Karınca izleri, yapraklar ve mantarlar arasında hücre, evrim ve genetik.": "Cells, evolution and genetics among ant trails, leaves and mushrooms.",
  "Platon’un Mağarası": "Plato’s Cave",
  "Duvarda kayan gölgeler, ateş ve gün ışığı: bilgi nedir, nereden bileceğiz?": "Shadows gliding on the wall, fire and daylight: what is knowledge, and how would we know?",
  "Roma Senatosu’nda Latince": "Latin in the Roman Senate",
  "Cicero kürsüde: alfabe, dilbilgisi, Latincenin serüveni ve ünlü sözler.": "Cicero at the rostrum: the alphabet, grammar, the journey of Latin and famous sayings.",
  "Tık sesi": "Click sound",
  "Önceki": "Previous",
  "Sonraki": "Next",
  "Akışı durdur": "Pause the flow",
  "Akışı başlat": "Resume the flow",
  "Ses açık": "Sound on",
  "Ses kapalı": "Sound off",
  "Arşiv sandığı": "Archive chest",
  "içerik": "items",
  "Sandığı kapat": "Close the chest",
  "Yeni not, sunum, video ya da çeviri eklemek için: js/arsiv.js dosyasında bu sahnenin temasına bir satır ekle; dosyaları arsiv/ klasörüne koy.": "To add a new note, talk, video or translation: add a line to this scene’s theme in js/arsiv.js and put the files in the arsiv/ folder.",
  "Bu çekmece henüz boş; yakında dolacak.": "This drawer is still empty; it will fill up soon.",
  "İzle": "Watch",
  "Aç": "Open",
  "Terim ara": "Search terms",
  "terim": "terms",
  "Not": "Note",
  "Çeviri": "Translation",
  "Görsel": "Image",
  "Bağlantı": "Link",
  "Film": "Film",
  "Ocak": "January",
  "Şubat": "February",
  "Mart": "March",
  "Nisan": "April",
  "Mayıs": "May",
  "Haziran": "June",
  "Temmuz": "July",
  "Ağustos": "August",
  "Eylül": "September",
  "Ekim": "October",
  "Kasım": "November",
  "Aralık": "December",
  "Kanal": "Channel",
  "(Metafizik)": "(Metaphysics)",
  "(Epistemoloji)": "(theory of knowledge)",
  "Alıştırma": "Exercise",
  "Bildiri": "Conference paper",
  "Çalıştay": "Workshop",
  "İzlence": "Syllabus",
  "Kitap": "Book",
  "Konferans": "Conference",
  "Makale": "Article",
  "Notlar": "Notes",
  "Ödevler": "Assignments",
  "Poster": "Poster",
  "Proje": "Project",
  "Seminer": "Seminar",
  "Sempozyum": "Symposium",
  "Tezler": "Theses",
  "Modalite üzerine sunum: zorunluluk, olanak ve olası dünyalar.": "A talk on modality: necessity, possibility and possible worlds.",
  "Meinong’un olmayan nesneler kuramı ve yönelimsellik sorunu üzerine seminer sunumu.": "Seminar talk on Meinong’s theory of non-existent objects and the problem of intentionality.",
  "Avrupalı öğrencilerin okullarda kendi ülkelerini ve dillerini tanıttığı değişim projesi.": "An exchange project in which European students introduce their countries and languages in schools.",
  "Düşüncenin Eşiğinde — YouTube kanalım": "On the Threshold of Thought — my YouTube channel",
  "Merak, akıl, anlam: konu anlatımları ve yeni videolar. Videolar eklendikçe burada, oynatıcıda izlenebilecek.": "Curiosity, reason, meaning: topic explainers and new videos. As videos are added, they can be watched here in the player.",
  "Makaleler, bildiriler, sunum metinleri ve diğer belgeler. Bir başlığa dokununca açıklaması ve indirme bağlantısı açılır.": "Articles, papers, talk texts and other documents. Tap a title to see its description and download link.",
  "Belge yakında eklenecek": "Document coming soon",
  "Belgeyi indir": "Download the document",
  "“Düşüncenin Eşiğinde” — merak, akıl, anlam. Konu anlatımları ve videolar; seçtiğin video aşağıdaki ekranda oynar.": "“On the Threshold of Thought” — curiosity, reason, meaning. Explainers and videos; the video you choose plays on the screen below.",
  "YouTube’da aç ↗": "Open on YouTube ↗",
  "Şimdi seçili": "Now selected",
  "Son yüklenenler": "Latest uploads",
  "Ses": "Sound",
  "Dışarıda": "Outside",
  "Çalışmalarım": "My works",
  "{ad} haritası": "Map of {ad}",
  "Harita": "Map",
  "Haritayı kapat": "Close map",
  "İndir": "Download",
  "Dış yörüngedeki odalar yakında açılacak": "Rooms on the outer orbit open soon",
  "Sürükle ya da kenara yaklaş: sahne kayar": "Drag or move to the edge: the scene pans",
  "Yeni bir çalışma eklemek için: js/icerik.js dosyasına bir kayıt ekle ve sandik alanına bu sahnenin adını yaz.": "To add a new work: add an entry to js/icerik.js and put this scene’s name in its sandik field."
 },
 "de": {
  "__title": "Karahan Uçar — Philosophie, Metaphysik und Philosophie des Geistes",
  "__desc": "Karahan Uçar: Philosophische Forschung. Metaphysik, Philosophie des Geistes, Erkenntnistheorie und Sprachphilosophie; Veröffentlichungen, Vorträge und Wissensinhalte.",
  "Ana menü": "Hauptmenü",
  "Hakkında": "Über mich",
  "Yayınlar": "Veröffentlichungen",
  "Kanal & Sunumlar": "Kanal & Vorträge",
  "Bilgi": "Wissen",
  "Randevu": "Termin",
  "İletişim": "Kontakt",
  "Dil": "Sprache",
  "Karahan Uçar logosu: altın rengi phi ve alev": "Logo von Karahan Uçar: goldenes Phi und Flamme",
  "Felsefe araştırmacısı": "Philosophische Forschung",
  "Varlığı, zihni, bilgiyi ve dili düşünmeye çalışıyorum; bu sayfa yayınlarımı, sunumlarımı ve bilgi notlarımı bir araya getiriyor.": "Ich versuche, über Sein, Geist, Erkenntnis und Sprache nachzudenken; diese Seite versammelt meine Veröffentlichungen, Vorträge und Notizen.",
  "Çalışma alanları": "Arbeitsgebiete",
  "Metafizik": "Metaphysik",
  "Varlık felsefesi": "Philosophie des Seins",
  "Zihin felsefesi": "Philosophie des Geistes",
  "Epistemoloji": "Erkenntnistheorie",
  "Bilgi felsefesi": "Wissensphilosophie",
  "Dil felsefesi": "Sprachphilosophie",
  "Mum ışığında bir kütüphanede kitap okuyan kuzgun maskot": "Ein Raben-Maskottchen liest im Kerzenlicht in einer Bibliothek",
  "Düşüncenin eşiğinde": "An der Schwelle des Denkens",
  "Ormanın ortasında kitaplıklı bir kabin: taş şömine yanıyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "Eine Hütte mit Bücherregalen mitten im Wald: ein Steinkamin brennt, hinter dem Bogenfenster sind ein verschneiter Kiefernwald und der Vollmond zu sehen",
  "Karahan Uçar’ın portresi": "Porträt von Karahan Uçar",
  "İstanbul Üniversitesi’nde felsefe lisansımı tamamladım; şimdi İstanbul Üniversitesi ve Ruhr-Universität Bochum’da yüksek lisans yapıyorum. Metafizik, zihin felsefesi, epistemoloji ve dil felsefesiyle ilgileniyorum; özellikle varlık felsefesinde soyut ve olmayan nesneler üzerine çalışıyorum. Bu sitede yayınlarımı, sunumlarımı ve bilgi notlarımı paylaşıyorum.": "Ich habe mein Philosophiestudium (Bachelor) an der Universität Istanbul abgeschlossen; derzeit absolviere ich meinen Master an der Universität Istanbul und der Ruhr-Universität Bochum. Ich interessiere mich für Metaphysik, Philosophie des Geistes, Erkenntnistheorie und Sprachphilosophie; in der Ontologie arbeite ich insbesondere zu abstrakten und nicht-existierenden Gegenständen. Auf dieser Seite teile ich meine Veröffentlichungen, Vorträge und Notizen.",
  "taslak": "Entwurf",
  "Kanadını çenesine dayamış, meraklı bakan kuzgun maskot": "Ein neugieriges Raben-Maskottchen, das den Flügel ans Kinn stützt",
  "Lisans, İstanbul Üniversitesi": "Bachelor, Universität Istanbul",
  "2024 – sürüyor": "2024 – heute",
  "Yüksek lisans, İstanbul Üniversitesi ve Ruhr-Universität Bochum": "Master, Universität Istanbul und Ruhr-Universität Bochum",
  "Yayınlar ve sunumlar": "Veröffentlichungen und Vorträge",
  "Sunum, seminer ve proje çalışmaları. Yayımlanan makaleler ve bildiriler eklendikçe burada listelenecek; tam liste profillerimde.": "Vorträge, Seminare und Projektarbeiten. Veröffentlichte Aufsätze und Beiträge werden hier ergänzt; die vollständige Liste findest du in meinen Profilen.",
  "Europa Macht Schule (EMS) projesi": "Projekt Europa Macht Schule (EMS)",
  "Haziran 2026 · Sunum": "Juni 2026 · Vortrag",
  "Temmuz 2026 · Sunum": "Juli 2026 · Vortrag",
  "Mayıs 2026 · Proje": "Mai 2026 · Projekt",
  "PhilPeople profilim": "Mein PhilPeople-Profil",
  "Academia profilim": "Mein Academia-Profil",
  "LinkedIn profilim": "Mein LinkedIn-Profil",
  "“Düşüncenin Eşiğinde” — merak, akıl, anlam. Konu anlatımları ve etkileşimli sunumlar.": "„An der Schwelle des Denkens“ — Neugier, Vernunft, Sinn. Themenerklärungen und interaktive Präsentationen.",
  "Neşeli kuzgun maskot iki kanadını açmış": "Ein fröhliches Raben-Maskottchen mit ausgebreiteten Flügeln",
  "Yaşamın sınırları": "Die Grenzen des Lebens",
  "Biyoloji felsefesi üzerine etkileşimli sunum.": "Eine interaktive Präsentation zur Philosophie der Biologie.",
  "Sunumu aç →": "Präsentation öffnen →",
  "Aristoteles’ten Hegel’e metafizik sorunlar.": "Metaphysische Probleme von Aristoteles bis Hegel.",
  "YouTube kanalı": "YouTube-Kanal",
  "Videolar ve yeni yayınlar.": "Videos und neue Beiträge.",
  "Kanala git →": "Zum Kanal →",
  "Bilgi içerikleri": "Wissensinhalte",
  "Alan alan düzenlenmiş notlar ve kaynak listeleri.": "Nach Fachgebieten geordnete Notizen und Quellenlisten.",
  "Felsefe": "Philosophie",
  "Epistemoloji, normatiflik, argüman haritaları, metin tahlilleri.": "Erkenntnistheorie, Normativität, Argumentkarten, Textanalysen.",
  "Diller": "Sprachen",
  "Dil öğrenim notları, sözlük ve çeviri çalışmaları.": "Notizen zum Sprachenlernen, Wörterbuch- und Übersetzungsarbeiten.",
  "Bilimler": "Wissenschaften",
  "Doğa, formel ve sosyal bilimlerden notlar.": "Notizen aus den Natur-, Formal- und Sozialwissenschaften.",
  "Görüşme, danışma ya da sohbet için ücretsiz randevu. Uygun saatleri Google Takvim sayfasından seçebilirsin.": "Ein kostenloser Termin für ein Gespräch, eine Beratung oder einen Austausch. Passende Zeiten kannst du auf der Google-Kalender-Seite auswählen.",
  "Randevu al →": "Termin buchen →",
  "Akademik profillerim ve sosyal hesaplarım. Görüşmek için yukarıdaki randevu bağlantısını kullanabilirsin.": "Meine akademischen Profile und sozialen Konten. Für ein Gespräch kannst du den Terminlink oben nutzen.",
  "Gözlüklü kuzgun maskot kanadını kaldırıp selam veriyor": "Ein Raben-Maskottchen mit Monokel hebt grüßend einen Flügel",
  "Akademik profiller": "Akademische Profile",
  "Sosyal hesaplar": "Soziale Konten",
  "Sayfayı okumak istediğin dili seç.": "Wähle die Sprache, in der du die Seite lesen möchtest.",
  "Türkçe": "Türkisch",
  "İngilizce": "Englisch",
  "Almanca": "Deutsch",
  "Fransızca": "Französisch",
  "Latince": "Latein",
  "Grekçe": "Griechisch",
  "Arapça": "Arabisch",
  "MERAK · AKIL · ANLAM": "NEUGIER · VERNUNFT · SINN",
  "Ses:": "Ton:",
  "Şömine": "Kamin",
  "Yağmur": "Regen",
  "Rüzgâr": "Wind",
  "Kapalı": "Aus",
  "Dışarıda:": "Draußen:",
  "Kar": "Schnee",
  "Ortam sesi": "Umgebungsgeräusch",
  "Dışarıdaki hava": "Wetter draußen",
  "İçeriğe geç": "Zum Inhalt springen",
  "Kütüphaneye gir →": "Die Bibliothek betreten →",
  "Etkileşimli sunum": "Interaktive Präsentation",
  "Video": "Video",
  "Alanlara göre süz": "Nach Fachgebiet filtern",
  "Tümü": "Alle",
  "Doğa Bilimleri": "Naturwissenschaften",
  "Formel Bilimler": "Formalwissenschaften",
  "Sosyal Bilimler": "Sozialwissenschaften",
  "Estetik": "Ästhetik",
  "Beceriler": "Fertigkeiten",
  "Bir cilde dokun; o alandaki içerikler aşağıda süzülür.": "Tippe auf einen Band; die Inhalte dieses Gebiets werden unten gefiltert.",
  "Son eklenenler": "Zuletzt hinzugefügt",
  "Okuma": "Lektüre",
  "Sunum": "Vortrag",
  "Yakında": "Demnächst",
  "Sıradaki okuma": "Die nächste Lektüre",
  "Yeni bir adım adım okuma hazırlanıyor.": "Eine neue Schritt-für-Schritt-Lektüre ist in Vorbereitung.",
  "Bu rafta henüz içerik yok; yakında eklenecek.": "Auf diesem Regal steht noch nichts; bald kommt etwas hinzu.",
  "Evren bir matematiksel yapı mı?": "Ist das Universum eine mathematische Struktur?",
  "Tegmark’ın “Matematiksel Evren” makalesi kaydırarak, adım adım: dış gerçeklik, yapılar, Gödel ve soyut nesneler sorusu.": "Tegmarks „The Mathematical Universe“, Schritt für Schritt beim Scrollen: äußere Realität, Strukturen, Gödel und die Frage nach abstrakten Gegenständen.",
  "Ortam": "Ambiente",
  "Alt menü": "Fußzeilenmenü",
  "Başa dön ↑": "Nach oben ↑",
  "Bu sitede çerez ya da izleyici yok; müzik yalnız gramofona dokununca YouTube’dan yüklenir.": "Diese Seite nutzt keine Cookies oder Tracker; Musik wird erst dann von YouTube geladen, wenn du das Grammophon berührst.",
  "Müzik çal": "Musik abspielen",
  "Müzik yükleniyor…": "Musik wird geladen…",
  "Müzik çubuğu": "Musikleiste",
  "Önceki parça": "Vorheriger Titel",
  "Çal / Duraklat": "Abspielen / Pause",
  "Sonraki parça": "Nächster Titel",
  "Sesi kapat/aç": "Ton aus/an",
  "Müziği kapat": "Musik schließen",
  "Ormanın ortasında kitaplıklı bir kabin: kuzgun maskot şöminenin önündeki deri koltukta kitap okuyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "Eine Hütte voller Bücherregale mitten im Wald: Das Raben-Maskottchen liest in einem Ledersessel vor dem Kamin; hinter dem Bogenfenster sind ein verschneiter Kiefernwald und der Vollmond zu sehen",
  "Kanal kapağı: karlı bir gecede şömineli kütüphane, ortada altın phi-alev logo, masada kitap okuyan kuzgun maskot": "Kanalbanner: eine Bibliothek mit Kamin in einer verschneiten Nacht, in der Mitte das goldene Phi-Flammen-Logo, am Tisch liest das Raben-Maskottchen ein Buch",
  "Işıklı ciltler kendi dünyalarına açılır; diğerleri aşağıdaki dizini süzer.": "Leuchtende Bände öffnen sich zu eigenen Welten; die anderen filtern das Verzeichnis unten.",
  "Kütüphane": "Bibliothek",
  "Kütüphaneye dön": "Zurück zur Bibliothek",
  "Parıldayan nesnelere dokun.": "Berühre die leuchtenden Gegenstände.",
  "Bu alandaki içerikler": "Inhalte in diesem Gebiet",
  "Paneli kapat": "Panel schließen",
  "Antik Yunanca": "Altgriechisch",
  "Biyoloji": "Biologie",
  "Astronomi": "Astronomie",
  "Fizik": "Physik",
  "Kimya": "Chemie",
  "Yer Bilimleri": "Geowissenschaften",
  "Etik": "Ethik",
  "Mantık": "Logik",
  "Bilgi Felsefesi": "Erkenntnistheorie",
  "Dil Felsefesi": "Sprachphilosophie",
  "Varlık Felsefesi": "Ontologie",
  "Zihin Felsefesi": "Philosophie des Geistes",
  "Mantık Felsefesi": "Philosophie der Logik",
  "Bilim Felsefesi": "Wissenschaftsphilosophie",
  "Politik Felsefe": "Politische Philosophie",
  "Din Felsefesi": "Religionsphilosophie",
  "Tarih Felsefesi": "Geschichtsphilosophie",
  "Sanat Felsefesi": "Kunstphilosophie",
  "Felsefe Tarihi": "Philosophiegeschichte",
  "Metafelsefe": "Metaphilosophie",
  "Sözlükçe": "Glossar",
  "Ekoloji": "Ökologie",
  "Jeoloji": "Geologie",
  "Mühendislik": "Ingenieurwesen",
  "Tıp": "Medizin",
  "Bilişim": "Informatik",
  "Geometri": "Geometrie",
  "Matematik": "Mathematik",
  "Antropoloji": "Anthropologie",
  "Arkeoloji": "Archäologie",
  "Coğrafya": "Geographie",
  "Dilbilimi": "Sprachwissenschaft",
  "Ekonomi": "Wirtschaftswissenschaft",
  "Hukuk": "Rechtswissenschaft",
  "İlahiyat": "Theologie",
  "Siyaset ve Sosyoloji": "Politik und Soziologie",
  "Psikoloji ve Psikanaliz": "Psychologie und Psychoanalyse",
  "Tarih": "Geschichte",
  "Edebiyat": "Literatur",
  "Görsel Sanatlar": "Bildende Kunst",
  "Müzik": "Musik",
  "Her raf bir alan. Pirinç levhaya dokununca alanın odası, kitaba dokununca o dalın dünyası açılır; parıldayan kitapların kendi sahnesi var.": "Jedes Regal ist ein Fachgebiet. Tippe auf das Messingschild, um den Raum des Gebiets zu betreten, oder auf ein Buch, um die Welt dieses Zweigs zu öffnen; leuchtende Bücher haben eine eigene Szene.",
  "Sahne": "Szene",
  "Ormanın içinde biyoloji": "Biologie im Wald",
  "Karınca izleri, yapraklar ve mantarlar arasında hücre, evrim ve genetik.": "Zellen, Evolution und Genetik zwischen Ameisenstraßen, Blättern und Pilzen.",
  "Platon’un Mağarası": "Platons Höhle",
  "Duvarda kayan gölgeler, ateş ve gün ışığı: bilgi nedir, nereden bileceğiz?": "Über die Wand gleitende Schatten, Feuer und Tageslicht: Was ist Wissen, und woher sollen wir es wissen?",
  "Roma Senatosu’nda Latince": "Latein im römischen Senat",
  "Cicero kürsüde: alfabe, dilbilgisi, Latincenin serüveni ve ünlü sözler.": "Cicero am Rednerpult: Alphabet, Grammatik, die Geschichte des Lateins und berühmte Sprüche.",
  "Tık sesi": "Klickton",
  "Önceki": "Zurück",
  "Sonraki": "Weiter",
  "Akışı durdur": "Ablauf anhalten",
  "Akışı başlat": "Ablauf fortsetzen",
  "Ses açık": "Ton an",
  "Ses kapalı": "Ton aus",
  "Arşiv sandığı": "Archivtruhe",
  "içerik": "Einträge",
  "Sandığı kapat": "Truhe schließen",
  "Yeni not, sunum, video ya da çeviri eklemek için: js/arsiv.js dosyasında bu sahnenin temasına bir satır ekle; dosyaları arsiv/ klasörüne koy.": "Neue Notiz, Präsentation, Video oder Übersetzung hinzufügen: in js/arsiv.js eine Zeile zum Thema dieser Szene ergänzen und die Dateien in den Ordner arsiv/ legen.",
  "Bu çekmece henüz boş; yakında dolacak.": "Diese Schublade ist noch leer; bald füllt sie sich.",
  "İzle": "Ansehen",
  "Aç": "Öffnen",
  "Terim ara": "Begriff suchen",
  "terim": "Begriffe",
  "Not": "Notiz",
  "Çeviri": "Übersetzung",
  "Görsel": "Bild",
  "Bağlantı": "Link",
  "Film": "Film",
  "Ocak": "Januar",
  "Şubat": "Februar",
  "Mart": "März",
  "Nisan": "April",
  "Mayıs": "Mai",
  "Haziran": "Juni",
  "Temmuz": "Juli",
  "Ağustos": "August",
  "Eylül": "September",
  "Ekim": "Oktober",
  "Kasım": "November",
  "Aralık": "Dezember",
  "Kanal": "Kanal",
  "(Metafizik)": "(Metaphysik)",
  "(Epistemoloji)": "(Epistemologie)",
  "Alıştırma": "Übung",
  "Bildiri": "Tagungsbeitrag",
  "Çalıştay": "Workshop",
  "İzlence": "Lehrplan",
  "Kitap": "Buch",
  "Konferans": "Konferenz",
  "Makale": "Aufsatz",
  "Notlar": "Notizen",
  "Ödevler": "Hausarbeiten",
  "Poster": "Poster",
  "Proje": "Projekt",
  "Seminer": "Seminar",
  "Sempozyum": "Symposium",
  "Tezler": "Abschlussarbeiten",
  "Modalite üzerine sunum: zorunluluk, olanak ve olası dünyalar.": "Vortrag über Modalität: Notwendigkeit, Möglichkeit und mögliche Welten.",
  "Meinong’un olmayan nesneler kuramı ve yönelimsellik sorunu üzerine seminer sunumu.": "Seminarvortrag über Meinongs Theorie nichtexistierender Gegenstände und das Problem der Intentionalität.",
  "Avrupalı öğrencilerin okullarda kendi ülkelerini ve dillerini tanıttığı değişim projesi.": "Austauschprojekt, in dem europäische Studierende an Schulen ihre Länder und Sprachen vorstellen.",
  "Düşüncenin Eşiğinde — YouTube kanalım": "An der Schwelle des Denkens — mein YouTube-Kanal",
  "Merak, akıl, anlam: konu anlatımları ve yeni videolar. Videolar eklendikçe burada, oynatıcıda izlenebilecek.": "Neugier, Vernunft, Sinn: Themenerklärungen und neue Videos. Neue Videos lassen sich hier im Player ansehen.",
  "Makaleler, bildiriler, sunum metinleri ve diğer belgeler. Bir başlığa dokununca açıklaması ve indirme bağlantısı açılır.": "Aufsätze, Tagungsbeiträge, Vortragstexte und andere Dokumente. Ein Titel öffnet Beschreibung und Download-Link.",
  "Belge yakında eklenecek": "Dokument folgt in Kürze",
  "Belgeyi indir": "Dokument herunterladen",
  "“Düşüncenin Eşiğinde” — merak, akıl, anlam. Konu anlatımları ve videolar; seçtiğin video aşağıdaki ekranda oynar.": "„An der Schwelle des Denkens“ — Neugier, Vernunft, Sinn. Erklärungen und Videos; das gewählte Video läuft im Bildschirm unten.",
  "YouTube’da aç ↗": "Auf YouTube öffnen ↗",
  "Şimdi seçili": "Gerade gewählt",
  "Son yüklenenler": "Neueste Videos",
  "Ses": "Klang",
  "Dışarıda": "Draußen",
  "Çalışmalarım": "Meine Arbeiten",
  "{ad} haritası": "Karte: {ad}",
  "Harita": "Karte",
  "Haritayı kapat": "Karte schließen",
  "İndir": "Herunterladen",
  "Dış yörüngedeki odalar yakında açılacak": "Räume auf der äußeren Umlaufbahn öffnen bald",
  "Sürükle ya da kenara yaklaş: sahne kayar": "Ziehen oder an den Rand fahren: die Szene gleitet",
  "Yeni bir çalışma eklemek için: js/icerik.js dosyasına bir kayıt ekle ve sandik alanına bu sahnenin adını yaz.": "Neue Arbeit hinzufügen: in js/icerik.js einen Eintrag anlegen und im Feld sandik den Namen dieser Szene eintragen."
 },
 "fr": {
  "__title": "Karahan Uçar — Philosophie, métaphysique et philosophie de l’esprit",
  "__desc": "Karahan Uçar : recherche en philosophie. Métaphysique, philosophie de l’esprit, épistémologie et philosophie du langage ; publications, exposés et contenus de savoir.",
  "Ana menü": "Menu principal",
  "Hakkında": "À propos",
  "Yayınlar": "Publications",
  "Kanal & Sunumlar": "Chaîne & exposés",
  "Bilgi": "Savoirs",
  "Randevu": "Rendez-vous",
  "İletişim": "Contact",
  "Dil": "Langue",
  "Karahan Uçar logosu: altın rengi phi ve alev": "Logo de Karahan Uçar : phi doré et flamme",
  "Felsefe araştırmacısı": "Recherche en philosophie",
  "Varlığı, zihni, bilgiyi ve dili düşünmeye çalışıyorum; bu sayfa yayınlarımı, sunumlarımı ve bilgi notlarımı bir araya getiriyor.": "J’essaie de penser l’être, l’esprit, la connaissance et le langage ; cette page réunit mes publications, mes exposés et mes notes.",
  "Çalışma alanları": "Domaines de travail",
  "Metafizik": "Métaphysique",
  "Varlık felsefesi": "Philosophie de l’être",
  "Zihin felsefesi": "Philosophie de l’esprit",
  "Epistemoloji": "Épistémologie",
  "Bilgi felsefesi": "Philosophie de la connaissance",
  "Dil felsefesi": "Philosophie du langage",
  "Mum ışığında bir kütüphanede kitap okuyan kuzgun maskot": "Une mascotte corbeau lit un livre dans une bibliothèque éclairée à la bougie",
  "Düşüncenin eşiğinde": "Au seuil de la pensée",
  "Ormanın ortasında kitaplıklı bir kabin: taş şömine yanıyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "Une cabane avec des bibliothèques au milieu de la forêt : une cheminée de pierre flambe, et derrière la fenêtre en arc on voit une forêt de pins enneigée et la pleine lune",
  "Karahan Uçar’ın portresi": "Portrait de Karahan Uçar",
  "İstanbul Üniversitesi’nde felsefe lisansımı tamamladım; şimdi İstanbul Üniversitesi ve Ruhr-Universität Bochum’da yüksek lisans yapıyorum. Metafizik, zihin felsefesi, epistemoloji ve dil felsefesiyle ilgileniyorum; özellikle varlık felsefesinde soyut ve olmayan nesneler üzerine çalışıyorum. Bu sitede yayınlarımı, sunumlarımı ve bilgi notlarımı paylaşıyorum.": "J’ai obtenu ma licence de philosophie à l’Université d’Istanbul ; je prépare actuellement un master à l’Université d’Istanbul et à la Ruhr-Universität Bochum. Je m’intéresse à la métaphysique, à la philosophie de l’esprit, à l’épistémologie et à la philosophie du langage ; en philosophie de l’être, je travaille en particulier sur les objets abstraits et non existants. Sur ce site, je partage mes publications, mes exposés et mes notes.",
  "taslak": "brouillon",
  "Kanadını çenesine dayamış, meraklı bakan kuzgun maskot": "Une mascotte corbeau curieuse, l’aile appuyée contre le menton",
  "Lisans, İstanbul Üniversitesi": "Licence, Université d’Istanbul",
  "2024 – sürüyor": "2024 – en cours",
  "Yüksek lisans, İstanbul Üniversitesi ve Ruhr-Universität Bochum": "Master, Université d’Istanbul et Ruhr-Universität Bochum",
  "Yayınlar ve sunumlar": "Publications et exposés",
  "Sunum, seminer ve proje çalışmaları. Yayımlanan makaleler ve bildiriler eklendikçe burada listelenecek; tam liste profillerimde.": "Exposés, séminaires et travaux de projet. Les articles et communications publiés seront ajoutés ici ; la liste complète se trouve sur mes profils.",
  "Europa Macht Schule (EMS) projesi": "Projet Europa Macht Schule (EMS)",
  "Haziran 2026 · Sunum": "Juin 2026 · Exposé",
  "Temmuz 2026 · Sunum": "Juillet 2026 · Exposé",
  "Mayıs 2026 · Proje": "Mai 2026 · Projet",
  "PhilPeople profilim": "Mon profil PhilPeople",
  "Academia profilim": "Mon profil Academia",
  "LinkedIn profilim": "Mon profil LinkedIn",
  "“Düşüncenin Eşiğinde” — merak, akıl, anlam. Konu anlatımları ve etkileşimli sunumlar.": "« Au seuil de la pensée » — curiosité, raison, sens. Explications thématiques et présentations interactives.",
  "Neşeli kuzgun maskot iki kanadını açmış": "Une mascotte corbeau joyeuse, les deux ailes déployées",
  "Yaşamın sınırları": "Les limites de la vie",
  "Biyoloji felsefesi üzerine etkileşimli sunum.": "Une présentation interactive sur la philosophie de la biologie.",
  "Sunumu aç →": "Ouvrir la présentation →",
  "Aristoteles’ten Hegel’e metafizik sorunlar.": "Problèmes métaphysiques d’Aristote à Hegel.",
  "YouTube kanalı": "Chaîne YouTube",
  "Videolar ve yeni yayınlar.": "Vidéos et nouveautés.",
  "Kanala git →": "Aller à la chaîne →",
  "Bilgi içerikleri": "Contenus de savoir",
  "Alan alan düzenlenmiş notlar ve kaynak listeleri.": "Notes et listes de sources classées par domaine.",
  "Felsefe": "Philosophie",
  "Epistemoloji, normatiflik, argüman haritaları, metin tahlilleri.": "Épistémologie, normativité, cartes d’arguments, analyses de textes.",
  "Diller": "Langues",
  "Dil öğrenim notları, sözlük ve çeviri çalışmaları.": "Notes d’apprentissage des langues, dictionnaire et travaux de traduction.",
  "Bilimler": "Sciences",
  "Doğa, formel ve sosyal bilimlerden notlar.": "Notes issues des sciences naturelles, formelles et sociales.",
  "Görüşme, danışma ya da sohbet için ücretsiz randevu. Uygun saatleri Google Takvim sayfasından seçebilirsin.": "Un rendez-vous gratuit pour un entretien, un conseil ou une discussion. Tu peux choisir un créneau sur la page Google Agenda.",
  "Randevu al →": "Prendre rendez-vous →",
  "Akademik profillerim ve sosyal hesaplarım. Görüşmek için yukarıdaki randevu bağlantısını kullanabilirsin.": "Mes profils académiques et mes comptes sociaux. Pour me contacter, tu peux utiliser le lien de rendez-vous ci-dessus.",
  "Gözlüklü kuzgun maskot kanadını kaldırıp selam veriyor": "Une mascotte corbeau à monocle lève une aile pour saluer",
  "Akademik profiller": "Profils académiques",
  "Sosyal hesaplar": "Comptes sociaux",
  "Sayfayı okumak istediğin dili seç.": "Choisis la langue dans laquelle tu veux lire la page.",
  "Türkçe": "Turc",
  "İngilizce": "Anglais",
  "Almanca": "Allemand",
  "Fransızca": "Français",
  "Latince": "Latin",
  "Grekçe": "Grec",
  "Arapça": "Arabe",
  "MERAK · AKIL · ANLAM": "CURIOSITÉ · RAISON · SENS",
  "Ses:": "Son :",
  "Şömine": "Cheminée",
  "Yağmur": "Pluie",
  "Rüzgâr": "Vent",
  "Kapalı": "Désactivé",
  "Dışarıda:": "Dehors :",
  "Kar": "Neige",
  "Ortam sesi": "Ambiance sonore",
  "Dışarıdaki hava": "Météo dehors",
  "İçeriğe geç": "Aller au contenu",
  "Kütüphaneye gir →": "Entrer dans la bibliothèque →",
  "Etkileşimli sunum": "Présentation interactive",
  "Video": "Vidéo",
  "Alanlara göre süz": "Filtrer par domaine",
  "Tümü": "Tout",
  "Doğa Bilimleri": "Sciences naturelles",
  "Formel Bilimler": "Sciences formelles",
  "Sosyal Bilimler": "Sciences sociales",
  "Estetik": "Esthétique",
  "Beceriler": "Savoir-faire",
  "Bir cilde dokun; o alandaki içerikler aşağıda süzülür.": "Touche un volume : les contenus de ce domaine sont filtrés ci-dessous.",
  "Son eklenenler": "Ajouts récents",
  "Okuma": "Lecture",
  "Sunum": "Exposé",
  "Yakında": "Bientôt",
  "Sıradaki okuma": "La prochaine lecture",
  "Yeni bir adım adım okuma hazırlanıyor.": "Une nouvelle lecture pas à pas est en préparation.",
  "Bu rafta henüz içerik yok; yakında eklenecek.": "Rien sur cette étagère pour l’instant ; ce sera bientôt ajouté.",
  "Evren bir matematiksel yapı mı?": "L’univers est-il une structure mathématique ?",
  "Tegmark’ın “Matematiksel Evren” makalesi kaydırarak, adım adım: dış gerçeklik, yapılar, Gödel ve soyut nesneler sorusu.": "« The Mathematical Universe » de Tegmark, pas à pas en faisant défiler : réalité extérieure, structures, Gödel et la question des objets abstraits.",
  "Ortam": "Ambiance",
  "Alt menü": "Menu de pied de page",
  "Başa dön ↑": "Retour en haut ↑",
  "Bu sitede çerez ya da izleyici yok; müzik yalnız gramofona dokununca YouTube’dan yüklenir.": "Ce site n’utilise ni cookies ni traceurs ; la musique ne se charge depuis YouTube que lorsque tu touches le gramophone.",
  "Müzik çal": "Lancer la musique",
  "Müzik yükleniyor…": "Chargement de la musique…",
  "Müzik çubuğu": "Barre musicale",
  "Önceki parça": "Morceau précédent",
  "Çal / Duraklat": "Lecture / Pause",
  "Sonraki parça": "Morceau suivant",
  "Sesi kapat/aç": "Couper/rétablir le son",
  "Müziği kapat": "Fermer la musique",
  "Ormanın ortasında kitaplıklı bir kabin: kuzgun maskot şöminenin önündeki deri koltukta kitap okuyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "Une cabane remplie de livres au milieu de la forêt : la mascotte corbeau lit dans un fauteuil en cuir devant la cheminée ; derrière la fenêtre cintrée, une forêt de pins enneigée et la pleine lune",
  "Kanal kapağı: karlı bir gecede şömineli kütüphane, ortada altın phi-alev logo, masada kitap okuyan kuzgun maskot": "Bannière de la chaîne : une bibliothèque avec cheminée par une nuit enneigée, au centre le logo doré phi-flamme, et la mascotte corbeau lisant un livre au bureau",
  "Işıklı ciltler kendi dünyalarına açılır; diğerleri aşağıdaki dizini süzer.": "Les volumes lumineux s’ouvrent sur leurs propres mondes ; les autres filtrent l’index ci-dessous.",
  "Kütüphane": "Bibliothèque",
  "Kütüphaneye dön": "Retour à la bibliothèque",
  "Parıldayan nesnelere dokun.": "Touche les objets qui scintillent.",
  "Bu alandaki içerikler": "Contenus de ce domaine",
  "Paneli kapat": "Fermer le panneau",
  "Antik Yunanca": "Grec ancien",
  "Biyoloji": "Biologie",
  "Astronomi": "Astronomie",
  "Fizik": "Physique",
  "Kimya": "Chimie",
  "Yer Bilimleri": "Sciences de la Terre",
  "Etik": "Éthique",
  "Mantık": "Logique",
  "Bilgi Felsefesi": "Épistémologie",
  "Dil Felsefesi": "Philosophie du langage",
  "Varlık Felsefesi": "Ontologie",
  "Zihin Felsefesi": "Philosophie de l’esprit",
  "Mantık Felsefesi": "Philosophie de la logique",
  "Bilim Felsefesi": "Philosophie des sciences",
  "Politik Felsefe": "Philosophie politique",
  "Din Felsefesi": "Philosophie de la religion",
  "Tarih Felsefesi": "Philosophie de l’histoire",
  "Sanat Felsefesi": "Philosophie de l’art",
  "Felsefe Tarihi": "Histoire de la philosophie",
  "Metafelsefe": "Métaphilosophie",
  "Sözlükçe": "Glossaire",
  "Ekoloji": "Écologie",
  "Jeoloji": "Géologie",
  "Mühendislik": "Ingénierie",
  "Tıp": "Médecine",
  "Bilişim": "Informatique",
  "Geometri": "Géométrie",
  "Matematik": "Mathématiques",
  "Antropoloji": "Anthropologie",
  "Arkeoloji": "Archéologie",
  "Coğrafya": "Géographie",
  "Dilbilimi": "Linguistique",
  "Ekonomi": "Économie",
  "Hukuk": "Droit",
  "İlahiyat": "Théologie",
  "Siyaset ve Sosyoloji": "Politique et sociologie",
  "Psikoloji ve Psikanaliz": "Psychologie et psychanalyse",
  "Tarih": "Histoire",
  "Edebiyat": "Littérature",
  "Görsel Sanatlar": "Arts visuels",
  "Müzik": "Musique",
  "Her raf bir alan. Pirinç levhaya dokununca alanın odası, kitaba dokununca o dalın dünyası açılır; parıldayan kitapların kendi sahnesi var.": "Chaque étagère est un domaine. Touche la plaque de laiton pour entrer dans sa salle, ou un livre pour ouvrir le monde de cette branche ; les livres lumineux ont leur propre scène.",
  "Sahne": "Scène",
  "Ormanın içinde biyoloji": "La biologie en forêt",
  "Karınca izleri, yapraklar ve mantarlar arasında hücre, evrim ve genetik.": "Cellules, évolution et génétique parmi les pistes de fourmis, les feuilles et les champignons.",
  "Platon’un Mağarası": "La caverne de Platon",
  "Duvarda kayan gölgeler, ateş ve gün ışığı: bilgi nedir, nereden bileceğiz?": "Des ombres qui glissent sur le mur, le feu et la lumière du jour : qu’est-ce que le savoir, et comment le saurions-nous ?",
  "Roma Senatosu’nda Latince": "Le latin au Sénat romain",
  "Cicero kürsüde: alfabe, dilbilgisi, Latincenin serüveni ve ünlü sözler.": "Cicéron à la tribune : l’alphabet, la grammaire, l’histoire du latin et des sentences célèbres.",
  "Tık sesi": "Son des clics",
  "Önceki": "Précédent",
  "Sonraki": "Suivant",
  "Akışı durdur": "Mettre en pause",
  "Akışı başlat": "Reprendre le défilement",
  "Ses açık": "Son activé",
  "Ses kapalı": "Son coupé",
  "Arşiv sandığı": "Coffre d’archives",
  "içerik": "éléments",
  "Sandığı kapat": "Fermer le coffre",
  "Yeni not, sunum, video ya da çeviri eklemek için: js/arsiv.js dosyasında bu sahnenin temasına bir satır ekle; dosyaları arsiv/ klasörüne koy.": "Pour ajouter une note, un exposé, une vidéo ou une traduction : ajoute une ligne au thème de cette scène dans js/arsiv.js et place les fichiers dans le dossier arsiv/.",
  "Bu çekmece henüz boş; yakında dolacak.": "Ce tiroir est encore vide ; il se remplira bientôt.",
  "İzle": "Regarder",
  "Aç": "Ouvrir",
  "Terim ara": "Chercher un terme",
  "terim": "termes",
  "Not": "Note",
  "Çeviri": "Traduction",
  "Görsel": "Image",
  "Bağlantı": "Lien",
  "Film": "Film",
  "Ocak": "janvier",
  "Şubat": "février",
  "Mart": "mars",
  "Nisan": "avril",
  "Mayıs": "mai",
  "Haziran": "juin",
  "Temmuz": "juillet",
  "Ağustos": "août",
  "Eylül": "septembre",
  "Ekim": "octobre",
  "Kasım": "novembre",
  "Aralık": "décembre",
  "Kanal": "Chaîne",
  "(Metafizik)": "(Métaphysique)",
  "(Epistemoloji)": "(théorie de la connaissance)",
  "Alıştırma": "Exercice",
  "Bildiri": "Communication",
  "Çalıştay": "Atelier",
  "İzlence": "Programme de cours",
  "Kitap": "Livre",
  "Konferans": "Conférence",
  "Makale": "Article",
  "Notlar": "Notes",
  "Ödevler": "Devoirs",
  "Poster": "Poster",
  "Proje": "Projet",
  "Seminer": "Séminaire",
  "Sempozyum": "Symposium",
  "Tezler": "Thèses",
  "Modalite üzerine sunum: zorunluluk, olanak ve olası dünyalar.": "Exposé sur la modalité : nécessité, possibilité et mondes possibles.",
  "Meinong’un olmayan nesneler kuramı ve yönelimsellik sorunu üzerine seminer sunumu.": "Exposé de séminaire sur la théorie meinongienne des objets inexistants et le problème de l’intentionnalité.",
  "Avrupalı öğrencilerin okullarda kendi ülkelerini ve dillerini tanıttığı değişim projesi.": "Projet d’échange où des étudiants européens présentent leurs pays et leurs langues dans les écoles.",
  "Düşüncenin Eşiğinde — YouTube kanalım": "Au seuil de la pensée — ma chaîne YouTube",
  "Merak, akıl, anlam: konu anlatımları ve yeni videolar. Videolar eklendikçe burada, oynatıcıda izlenebilecek.": "Curiosité, raison, sens : explications et nouvelles vidéos. Les vidéos ajoutées pourront être regardées ici, dans le lecteur.",
  "Makaleler, bildiriler, sunum metinleri ve diğer belgeler. Bir başlığa dokununca açıklaması ve indirme bağlantısı açılır.": "Articles, communications, textes d’exposés et autres documents. Touchez un titre pour voir sa description et le lien de téléchargement.",
  "Belge yakında eklenecek": "Document bientôt disponible",
  "Belgeyi indir": "Télécharger le document",
  "“Düşüncenin Eşiğinde” — merak, akıl, anlam. Konu anlatımları ve videolar; seçtiğin video aşağıdaki ekranda oynar.": "« Au seuil de la pensée » — curiosité, raison, sens. Explications et vidéos ; la vidéo choisie se lit sur l’écran ci-dessous.",
  "YouTube’da aç ↗": "Ouvrir sur YouTube ↗",
  "Şimdi seçili": "Sélection actuelle",
  "Son yüklenenler": "Dernières vidéos",
  "Ses": "Son",
  "Dışarıda": "Dehors",
  "Çalışmalarım": "Mes travaux",
  "{ad} haritası": "Carte : {ad}",
  "Harita": "Carte",
  "Haritayı kapat": "Fermer la carte",
  "İndir": "Télécharger",
  "Dış yörüngedeki odalar yakında açılacak": "Les salles de l’orbite extérieure ouvriront bientôt",
  "Sürükle ya da kenara yaklaş: sahne kayar": "Faites glisser ou approchez du bord : la scène défile",
  "Yeni bir çalışma eklemek için: js/icerik.js dosyasına bir kayıt ekle ve sandik alanına bu sahnenin adını yaz.": "Pour ajouter un travail : ajoutez une entrée dans js/icerik.js et indiquez le nom de cette scène dans le champ sandik."
 },
 "la": {
  "__title": "Karahan Uçar — Philosophia, metaphysica et philosophia mentis",
  "__desc": "Karahan Uçar: investigatio philosophica. Metaphysica, philosophia mentis, epistemologia et philosophia linguae; scripta, orationes et contenta doctrinae.",
  "Ana menü": "Index principalis",
  "Hakkında": "De me",
  "Yayınlar": "Scripta",
  "Kanal & Sunumlar": "Canalis et orationes",
  "Bilgi": "Doctrina",
  "Randevu": "Colloquium",
  "İletişim": "Contactus",
  "Dil": "Lingua",
  "Karahan Uçar logosu: altın rengi phi ve alev": "Signum Karahan Uçar: phi aureum et flamma",
  "Felsefe araştırmacısı": "Investigatio philosophica",
  "Varlığı, zihni, bilgiyi ve dili düşünmeye çalışıyorum; bu sayfa yayınlarımı, sunumlarımı ve bilgi notlarımı bir araya getiriyor.": "Esse, mentem, scientiam linguamque cogitare conor; haec pagina scripta, orationes et adnotationes meas colligit.",
  "Çalışma alanları": "Campi studiorum",
  "Metafizik": "Metaphysica",
  "Varlık felsefesi": "Philosophia essendi",
  "Zihin felsefesi": "Philosophia mentis",
  "Epistemoloji": "Epistemologia",
  "Bilgi felsefesi": "Philosophia scientiae",
  "Dil felsefesi": "Philosophia linguae",
  "Mum ışığında bir kütüphanede kitap okuyan kuzgun maskot": "Corvus mascotus in bibliotheca lumine candelae librum legens",
  "Düşüncenin eşiğinde": "In limine cogitationis",
  "Ormanın ortasında kitaplıklı bir kabin: taş şömine yanıyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "Casa lignea inter silvas cum armariis librorum: focus lapideus ardet, et per fenestram arcuatam pineta nivosa et luna plena conspiciuntur",
  "Karahan Uçar’ın portresi": "Imago Karahan Uçar",
  "İstanbul Üniversitesi’nde felsefe lisansımı tamamladım; şimdi İstanbul Üniversitesi ve Ruhr-Universität Bochum’da yüksek lisans yapıyorum. Metafizik, zihin felsefesi, epistemoloji ve dil felsefesiyle ilgileniyorum; özellikle varlık felsefesinde soyut ve olmayan nesneler üzerine çalışıyorum. Bu sitede yayınlarımı, sunumlarımı ve bilgi notlarımı paylaşıyorum.": "Gradum baccalaurei in philosophia apud Universitatem Istanbulensem confeci; nunc gradum magistri apud Universitatem Istanbulensem et Universitatem Ruhr Bochumensem persequor. Metaphysicam, philosophiam mentis, epistemologiam et philosophiam linguae studeo; in philosophia essendi praesertim de obiectis abstractis et non exsistentibus laboro. In hoc situ scripta, orationes et adnotationes meas communico.",
  "taslak": "adumbratio",
  "Kanadını çenesine dayamış, meraklı bakan kuzgun maskot": "Corvus mascotus curiosus alam mento admovens",
  "Lisans, İstanbul Üniversitesi": "Baccalaureus, Universitas Istanbulensis",
  "2024 – sürüyor": "2024 – nunc",
  "Yüksek lisans, İstanbul Üniversitesi ve Ruhr-Universität Bochum": "Magister, Universitas Istanbulensis et Ruhr-Universität Bochum",
  "Yayınlar ve sunumlar": "Scripta et orationes",
  "Sunum, seminer ve proje çalışmaları. Yayımlanan makaleler ve bildiriler eklendikçe burada listelenecek; tam liste profillerimde.": "Orationes, seminaria et opera consiliorum. Articuli et commentationes editae hic adicientur; index plenus in profilis meis est.",
  "Europa Macht Schule (EMS) projesi": "Consilium Europa Macht Schule (EMS)",
  "Haziran 2026 · Sunum": "Iunius 2026 · Oratio",
  "Temmuz 2026 · Sunum": "Iulius 2026 · Oratio",
  "Mayıs 2026 · Proje": "Maius 2026 · Consilium",
  "PhilPeople profilim": "Profilum meum PhilPeople",
  "Academia profilim": "Profilum meum Academia",
  "LinkedIn profilim": "Profilum meum LinkedIn",
  "“Düşüncenin Eşiğinde” — merak, akıl, anlam. Konu anlatımları ve etkileşimli sunumlar.": "«In limine cogitationis» — curiositas, ratio, sensus. Expositiones argumentorum et praesentationes interactivae.",
  "Neşeli kuzgun maskot iki kanadını açmış": "Corvus mascotus laetus duabus alis expansis",
  "Yaşamın sınırları": "Fines vitae",
  "Biyoloji felsefesi üzerine etkileşimli sunum.": "Praesentatio interactiva de philosophia biologiae.",
  "Sunumu aç →": "Praesentationem aperi →",
  "Aristoteles’ten Hegel’e metafizik sorunlar.": "Quaestiones metaphysicae ab Aristotele ad Hegelium.",
  "YouTube kanalı": "Canalis YouTube",
  "Videolar ve yeni yayınlar.": "Video et nova edita.",
  "Kanala git →": "Ad canalem →",
  "Bilgi içerikleri": "Contenta doctrinae",
  "Alan alan düzenlenmiş notlar ve kaynak listeleri.": "Adnotationes et indices fontium per campos ordinati.",
  "Felsefe": "Philosophia",
  "Epistemoloji, normatiflik, argüman haritaları, metin tahlilleri.": "Epistemologia, normativitas, tabulae argumentorum, analyses textuum.",
  "Diller": "Linguae",
  "Dil öğrenim notları, sözlük ve çeviri çalışmaları.": "Adnotationes ad linguas discendas, lexicon et opera interpretandi.",
  "Bilimler": "Scientiae",
  "Doğa, formel ve sosyal bilimlerden notlar.": "Adnotationes ex scientiis naturalibus, formalibus et socialibus.",
  "Görüşme, danışma ya da sohbet için ücretsiz randevu. Uygun saatleri Google Takvim sayfasından seçebilirsin.": "Colloquium gratuitum ad congressum, consilium vel sermonem. Tempus aptum in pagina Google Calendarii eligere potes.",
  "Randevu al →": "Colloquium pete →",
  "Akademik profillerim ve sosyal hesaplarım. Görüşmek için yukarıdaki randevu bağlantısını kullanabilirsin.": "Profila mea academica et rationes sociales. Ut mecum colloquaris, nexu colloquii supra uti potes.",
  "Gözlüklü kuzgun maskot kanadını kaldırıp selam veriyor": "Corvus mascotus monoculatus alam salutandi causa tollens",
  "Akademik profiller": "Profila academica",
  "Sosyal hesaplar": "Rationes sociales",
  "Sayfayı okumak istediğin dili seç.": "Linguam elige qua paginam legere velis.",
  "Türkçe": "Turcice",
  "İngilizce": "Anglice",
  "Almanca": "Germanice",
  "Fransızca": "Gallice",
  "Latince": "Latine",
  "Grekçe": "Graece",
  "Arapça": "Arabice",
  "MERAK · AKIL · ANLAM": "CURIOSITAS · RATIO · SENSUS",
  "Ses:": "Sonus:",
  "Şömine": "Focus",
  "Yağmur": "Pluvia",
  "Rüzgâr": "Ventus",
  "Kapalı": "Clausum",
  "Dışarıda:": "Foris:",
  "Kar": "Nix",
  "Ortam sesi": "Sonus ambientis",
  "Dışarıdaki hava": "Tempestas foris",
  "İçeriğe geç": "Ad contenta transi",
  "Kütüphaneye gir →": "Bibliothecam intra →",
  "Etkileşimli sunum": "Praesentatio interactiva",
  "Video": "Video",
  "Alanlara göre süz": "Secundum campos cerne",
  "Tümü": "Omnia",
  "Doğa Bilimleri": "Scientiae naturales",
  "Formel Bilimler": "Scientiae formales",
  "Sosyal Bilimler": "Scientiae sociales",
  "Estetik": "Aesthetica",
  "Beceriler": "Peritiae",
  "Bir cilde dokun; o alandaki içerikler aşağıda süzülür.": "Volumen tange; quae ad eum campum pertinent, infra secernuntur.",
  "Son eklenenler": "Nuper addita",
  "Okuma": "Lectio",
  "Sunum": "Oratio",
  "Yakında": "Mox",
  "Sıradaki okuma": "Lectio proxima",
  "Yeni bir adım adım okuma hazırlanıyor.": "Nova lectio gradatim explicata paratur.",
  "Bu rafta henüz içerik yok; yakında eklenecek.": "In hoc pluteo nihil adhuc est; mox addetur.",
  "Evren bir matematiksel yapı mı?": "Estne universum structura mathematica?",
  "Tegmark’ın “Matematiksel Evren” makalesi kaydırarak, adım adım: dış gerçeklik, yapılar, Gödel ve soyut nesneler sorusu.": "Tegmarkii «The Mathematical Universe» gradatim volvendo: realitas externa, structurae, Gödel et quaestio de obiectis abstractis.",
  "Ortam": "Ambitus",
  "Alt menü": "Index infimus",
  "Başa dön ↑": "Ad summum ↑",
  "Bu sitede çerez ya da izleyici yok; müzik yalnız gramofona dokununca YouTube’dan yüklenir.": "Hic situs nec crustulis nec vestigatoribus utitur; musica e YouTube tum demum oneratur, cum gramophonum tetigeris.",
  "Müzik çal": "Musicam incipe",
  "Müzik yükleniyor…": "Musica oneratur…",
  "Müzik çubuğu": "Tabula musica",
  "Önceki parça": "Cantus prior",
  "Çal / Duraklat": "Cane / Siste",
  "Sonraki parça": "Cantus sequens",
  "Sesi kapat/aç": "Sonum tace / redde",
  "Müziği kapat": "Musicam claude",
  "Ormanın ortasında kitaplıklı bir kabin: kuzgun maskot şöminenin önündeki deri koltukta kitap okuyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "Casa libris referta in media silva: corvus mascotus in sella coriacea ante focum librum legit; trans fenestram arcuatam silva pinea nivosa et luna plena conspiciuntur",
  "Kanal kapağı: karlı bir gecede şömineli kütüphane, ortada altın phi-alev logo, masada kitap okuyan kuzgun maskot": "Tegmen canalis: bibliotheca cum foco nocte nivosa, in medio signum aureum phi et flammae, corvus mascotus ad mensam librum legens",
  "Işıklı ciltler kendi dünyalarına açılır; diğerleri aşağıdaki dizini süzer.": "Volumina lucentia in suos mundos aperiuntur; cetera indicem infra secernunt.",
  "Kütüphane": "Bibliotheca",
  "Kütüphaneye dön": "Ad bibliothecam redi",
  "Parıldayan nesnelere dokun.": "Res fulgentes tange.",
  "Bu alandaki içerikler": "Quae ad hunc campum pertinent",
  "Paneli kapat": "Tabulam claude",
  "Antik Yunanca": "Graeca antiqua",
  "Biyoloji": "Biologia",
  "Astronomi": "Astronomia",
  "Fizik": "Physica",
  "Kimya": "Chemia",
  "Yer Bilimleri": "Scientiae terrae",
  "Etik": "Ethica",
  "Mantık": "Logica",
  "Bilgi Felsefesi": "Philosophia cognitionis",
  "Dil Felsefesi": "Philosophia sermonis",
  "Varlık Felsefesi": "Ontologia",
  "Zihin Felsefesi": "Philosophia mentis",
  "Mantık Felsefesi": "Philosophia logicae",
  "Bilim Felsefesi": "Philosophia scientiae",
  "Politik Felsefe": "Philosophia politica",
  "Din Felsefesi": "Philosophia religionis",
  "Tarih Felsefesi": "Philosophia historiae",
  "Sanat Felsefesi": "Philosophia artis",
  "Felsefe Tarihi": "Historia philosophiae",
  "Metafelsefe": "Metaphilosophia",
  "Sözlükçe": "Glossarium",
  "Ekoloji": "Oecologia",
  "Jeoloji": "Geologia",
  "Mühendislik": "Ars machinalis",
  "Tıp": "Medicina",
  "Bilişim": "Informatica",
  "Geometri": "Geometria",
  "Matematik": "Mathematica",
  "Antropoloji": "Anthropologia",
  "Arkeoloji": "Archaeologia",
  "Coğrafya": "Geographia",
  "Dilbilimi": "Linguistica",
  "Ekonomi": "Oeconomia",
  "Hukuk": "Ius",
  "İlahiyat": "Theologia",
  "Siyaset ve Sosyoloji": "Politica et sociologia",
  "Psikoloji ve Psikanaliz": "Psychologia et psychoanalysis",
  "Tarih": "Historia",
  "Edebiyat": "Litterae",
  "Görsel Sanatlar": "Artes visuales",
  "Müzik": "Musica",
  "Her raf bir alan. Pirinç levhaya dokununca alanın odası, kitaba dokununca o dalın dünyası açılır; parıldayan kitapların kendi sahnesi var.": "Quisque pluteus campus est. Laminam aeneam tange ut conclave campi, librum ut mundum rami aperias; libri fulgentes suam scaenam habent.",
  "Sahne": "Scaena",
  "Ormanın içinde biyoloji": "Biologia in silva",
  "Karınca izleri, yapraklar ve mantarlar arasında hücre, evrim ve genetik.": "Cellulae, evolutio et genetica inter formicarum semitas, folia fungosque.",
  "Platon’un Mağarası": "Spelunca Platonis",
  "Duvarda kayan gölgeler, ateş ve gün ışığı: bilgi nedir, nereden bileceğiz?": "Umbrae per parietem labentes, ignis et lux diei: quid est scientia, et unde sciemus?",
  "Roma Senatosu’nda Latince": "Lingua Latina in senatu Romano",
  "Cicero kürsüde: alfabe, dilbilgisi, Latincenin serüveni ve ünlü sözler.": "Cicero in rostris: alphabetum, grammatica, historia linguae Latinae et sententiae clarae.",
  "Tık sesi": "Sonus tactus",
  "Önceki": "Prius",
  "Sonraki": "Sequens",
  "Akışı durdur": "Cursum siste",
  "Akışı başlat": "Cursum resume",
  "Ses açık": "Sonus adest",
  "Ses kapalı": "Sonus abest",
  "Arşiv sandığı": "Arca archivi",
  "içerik": "res",
  "Sandığı kapat": "Arcam claude",
  "Yeni not, sunum, video ya da çeviri eklemek için: js/arsiv.js dosyasında bu sahnenin temasına bir satır ekle; dosyaları arsiv/ klasörüne koy.": "Ut novam adnotationem, orationem, pelliculam vel versionem addas: in js/arsiv.js versum ad argumentum huius scaenae adde et documenta in arsiv/ pone.",
  "Bu çekmece henüz boş; yakında dolacak.": "Hoc loculamentum adhuc vacuum est; mox implebitur.",
  "İzle": "Specta",
  "Aç": "Aperi",
  "Terim ara": "Terminum quaere",
  "terim": "termini",
  "Not": "Adnotatio",
  "Çeviri": "Versio",
  "Görsel": "Imago",
  "Bağlantı": "Nexus",
  "Film": "Pellicula",
  "Ocak": "Ianuarius",
  "Şubat": "Februarius",
  "Mart": "Martius",
  "Nisan": "Aprilis",
  "Mayıs": "Maius",
  "Haziran": "Iunius",
  "Temmuz": "Iulius",
  "Ağustos": "Augustus",
  "Eylül": "September",
  "Ekim": "October",
  "Kasım": "November",
  "Aralık": "December",
  "Kanal": "Canalis",
  "(Metafizik)": "(Metaphysica)",
  "(Epistemoloji)": "(Epistemologia)",
  "Alıştırma": "Exercitatio",
  "Bildiri": "Relatio",
  "Çalıştay": "Officina",
  "İzlence": "Ratio studiorum",
  "Kitap": "Liber",
  "Konferans": "Conventus",
  "Makale": "Commentatio",
  "Notlar": "Adnotationes",
  "Ödevler": "Pensa",
  "Poster": "Tabella",
  "Proje": "Propositum",
  "Seminer": "Seminarium",
  "Sempozyum": "Symposium",
  "Tezler": "Dissertationes",
  "Modalite üzerine sunum: zorunluluk, olanak ve olası dünyalar.": "Oratio de modalitate: de necessitate, possibilitate et mundis possibilibus.",
  "Meinong’un olmayan nesneler kuramı ve yönelimsellik sorunu üzerine seminer sunumu.": "Oratio seminarii de Meinongii doctrina obiectorum non exsistentium et de quaestione intentionalitatis.",
  "Avrupalı öğrencilerin okullarda kendi ülkelerini ve dillerini tanıttığı değişim projesi.": "Consilium commutationis, quo studiosi Europaei in scholis patrias linguasque suas exponunt.",
  "Düşüncenin Eşiğinde — YouTube kanalım": "In limine cogitationis — canalis meus YouTube",
  "Merak, akıl, anlam: konu anlatımları ve yeni videolar. Videolar eklendikçe burada, oynatıcıda izlenebilecek.": "Curiositas, ratio, sensus: explicationes et novae pelliculae. Quae addentur, hic in lectore spectari poterunt.",
  "Makaleler, bildiriler, sunum metinleri ve diğer belgeler. Bir başlığa dokununca açıklaması ve indirme bağlantısı açılır.": "Commentationes, relationes, orationum textus aliaque documenta. Titulum tange: descriptio et nexus ad deponendum aperientur.",
  "Belge yakında eklenecek": "Documentum mox addetur",
  "Belgeyi indir": "Documentum depone",
  "“Düşüncenin Eşiğinde” — merak, akıl, anlam. Konu anlatımları ve videolar; seçtiğin video aşağıdaki ekranda oynar.": "«In limine cogitationis» — curiositas, ratio, sensus. Explicationes et pelliculae; quam elegeris, in tabula infra agitur.",
  "YouTube’da aç ↗": "In YouTube aperi ↗",
  "Şimdi seçili": "Nunc electum",
  "Son yüklenenler": "Nuper addita",
  "Ses": "Sonus",
  "Dışarıda": "Foris",
  "Çalışmalarım": "Opera mea",
  "{ad} haritası": "Tabula: {ad}",
  "Harita": "Tabula",
  "Haritayı kapat": "Tabulam claude",
  "İndir": "Depone",
  "Dış yörüngedeki odalar yakında açılacak": "Conclavia in orbe exteriore mox aperientur",
  "Sürükle ya da kenara yaklaş: sahne kayar": "Trahe aut ad oram accede: scaena movetur",
  "Yeni bir çalışma eklemek için: js/icerik.js dosyasına bir kayıt ekle ve sandik alanına bu sahnenin adını yaz.": "Ut novum opus addas: in js/icerik.js inscriptionem adde et in campo sandik nomen huius scaenae scribe."
 },
 "el": {
  "__title": "Karahan Uçar — Φιλοσοφία, μεταφυσική καὶ φιλοσοφία τοῦ νοῦ",
  "__desc": "Karahan Uçar: φιλοσοφικὴ ζήτησις. Μεταφυσική, φιλοσοφία τοῦ νοῦ, ἐπιστημολογία καὶ φιλοσοφία τῆς γλώττης· συγγράμματα, ἐπιδείξεις καὶ περιεχόμενα γνώσεως.",
  "Ana menü": "Κύριος πίναξ",
  "Hakkında": "Περὶ ἐμοῦ",
  "Yayınlar": "Συγγράμματα",
  "Kanal & Sunumlar": "Κανάλι καὶ ἐπιδείξεις",
  "Bilgi": "Γνῶσις",
  "Randevu": "Συνάντησις",
  "İletişim": "Ἐπικοινωνία",
  "Dil": "Γλῶττα",
  "Karahan Uçar logosu: altın rengi phi ve alev": "Σῆμα τοῦ Karahan Uçar: χρυσοῦν φῖ καὶ φλόξ",
  "Felsefe araştırmacısı": "Φιλοσοφικὴ ζήτησις",
  "Varlığı, zihni, bilgiyi ve dili düşünmeye çalışıyorum; bu sayfa yayınlarımı, sunumlarımı ve bilgi notlarımı bir araya getiriyor.": "Τὸ ὄν, τὸν νοῦν, τὴν γνῶσιν καὶ τὴν γλῶτταν διανοεῖσθαι πειρῶμαι· ἥδε δὲ ἡ σελὶς τὰ συγγράμματα καὶ τὰς ἐπιδείξεις καὶ τὰ ὑπομνήματά μου συνάγει.",
  "Çalışma alanları": "Πεδία μελέτης",
  "Metafizik": "Μεταφυσική",
  "Varlık felsefesi": "Φιλοσοφία τοῦ ὄντος",
  "Zihin felsefesi": "Φιλοσοφία τοῦ νοῦ",
  "Epistemoloji": "Ἐπιστημολογία",
  "Bilgi felsefesi": "Φιλοσοφία τῆς γνώσεως",
  "Dil felsefesi": "Φιλοσοφία τῆς γλώττης",
  "Mum ışığında bir kütüphanede kitap okuyan kuzgun maskot": "Κόραξ-σύμβολον ἐν βιβλιοθήκῃ πρὸς φῶς κηροῦ βιβλίον ἀναγιγνώσκων",
  "Düşüncenin eşiğinde": "Ἐπὶ τῷ οὐδῷ τῆς διανοίας",
  "Ormanın ortasında kitaplıklı bir kabin: taş şömine yanıyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "Οἴκημα ἐν μέσῳ τῷ δρυμῷ βιβλιοθήκας ἔχον· ἑστία λιθίνη καίεται, καὶ διὰ τῆς τοξοειδοῦς θυρίδος πευκὼν χιονώδης καὶ πανσέληνος ὁρῶνται.",
  "Karahan Uçar’ın portresi": "Εἰκὼν τοῦ Karahan Uçar",
  "İstanbul Üniversitesi’nde felsefe lisansımı tamamladım; şimdi İstanbul Üniversitesi ve Ruhr-Universität Bochum’da yüksek lisans yapıyorum. Metafizik, zihin felsefesi, epistemoloji ve dil felsefesiyle ilgileniyorum; özellikle varlık felsefesinde soyut ve olmayan nesneler üzerine çalışıyorum. Bu sitede yayınlarımı, sunumlarımı ve bilgi notlarımı paylaşıyorum.": "Τὸ προπτυχιακὸν τῆς φιλοσοφίας ἐν τῷ Πανεπιστημίῳ τῆς Κωνσταντινουπόλεως ἐξεπλήρωσα· νῦν δὲ τὸ μεταπτυχιακὸν ἐν τῷ Πανεπιστημίῳ τῆς Κωνσταντινουπόλεως καὶ ἐν τῷ Ruhr-Universität Bochum μετέρχομαι. Μεταφυσικῇ, φιλοσοφίᾳ τοῦ νοῦ, ἐπιστημολογίᾳ καὶ φιλοσοφίᾳ τῆς γλώττης προσέχω τὸν νοῦν· ἐν δὲ τῇ περὶ τοῦ ὄντος φιλοσοφίᾳ μάλιστα περὶ τὰ ἀφῃρημένα καὶ τὰ μὴ ὄντα πράγματα πραγματεύομαι. Ἐν τῷδε τῷ ἱστοτόπῳ τὰ συγγράμματα καὶ τὰς ἐπιδείξεις καὶ τὰ ὑπομνήματά μου κοινοῦμαι.",
  "taslak": "προσχέδιον",
  "Kanadını çenesine dayamış, meraklı bakan kuzgun maskot": "Κόραξ-σύμβολον φιλομαθής, τὴν πτέρυγα πρὸς τὸ γένειον ἐπερείδων",
  "Lisans, İstanbul Üniversitesi": "Προπτυχιακόν, Πανεπιστήμιον Κωνσταντινουπόλεως",
  "2024 – sürüyor": "2024 – ἕως νῦν",
  "Yüksek lisans, İstanbul Üniversitesi ve Ruhr-Universität Bochum": "Μεταπτυχιακόν, Πανεπιστήμιον Κωνσταντινουπόλεως καὶ Ruhr-Universität Bochum",
  "Yayınlar ve sunumlar": "Συγγράμματα καὶ ἐπιδείξεις",
  "Sunum, seminer ve proje çalışmaları. Yayımlanan makaleler ve bildiriler eklendikçe burada listelenecek; tam liste profillerimde.": "Ἐπιδείξεις, σεμινάρια καὶ ἔργα. Τὰ ἐκδοθέντα ἄρθρα καὶ αἱ ἀνακοινώσεις ἐνταῦθα προστεθήσονται· ὁ δὲ πλήρης κατάλογος ἐν τοῖς προφὶλ μου ἐστίν.",
  "Europa Macht Schule (EMS) projesi": "Ἔργον Europa Macht Schule (EMS)",
  "Haziran 2026 · Sunum": "Ἰούνιος 2026 · Ἐπίδειξις",
  "Temmuz 2026 · Sunum": "Ἰούλιος 2026 · Ἐπίδειξις",
  "Mayıs 2026 · Proje": "Μάιος 2026 · Ἔργον",
  "PhilPeople profilim": "Τὸ ἐμὸν προφὶλ ἐν τῷ PhilPeople",
  "Academia profilim": "Τὸ ἐμὸν προφὶλ ἐν τῷ Academia",
  "LinkedIn profilim": "Τὸ ἐμὸν προφὶλ ἐν τῷ LinkedIn",
  "“Düşüncenin Eşiğinde” — merak, akıl, anlam. Konu anlatımları ve etkileşimli sunumlar.": "«Ἐπὶ τῷ οὐδῷ τῆς διανοίας» — φιλομάθεια, λόγος, νόημα. Ἐξηγήσεις τῶν πραγμάτων καὶ ἐπιδείξεις διαδραστικαί.",
  "Neşeli kuzgun maskot iki kanadını açmış": "Κόραξ-σύμβολον χαίρων, ἀμφοτέρας τὰς πτέρυγας ἀναπετάσας",
  "Yaşamın sınırları": "Τὰ ὅρια τοῦ βίου",
  "Biyoloji felsefesi üzerine etkileşimli sunum.": "Ἐπίδειξις διαδραστικὴ περὶ τῆς φιλοσοφίας τῆς βιολογίας.",
  "Sunumu aç →": "Τὴν ἐπίδειξιν ἄνοιξον →",
  "Aristoteles’ten Hegel’e metafizik sorunlar.": "Τὰ μεταφυσικὰ προβλήματα ἀπὸ Ἀριστοτέλους μέχρι Ἡγέλου.",
  "YouTube kanalı": "Κανάλι YouTube",
  "Videolar ve yeni yayınlar.": "Βίντεο καὶ νέα ἐκδοθέντα.",
  "Kanala git →": "Ἐπὶ τὸ κανάλι ἴθι →",
  "Bilgi içerikleri": "Περιεχόμενα γνώσεως",
  "Alan alan düzenlenmiş notlar ve kaynak listeleri.": "Ὑπομνήματα καὶ πηγῶν κατάλογοι κατὰ πεδία.",
  "Felsefe": "Φιλοσοφία",
  "Epistemoloji, normatiflik, argüman haritaları, metin tahlilleri.": "Ἐπιστημολογία, κανονιστικότης, ἐπιχειρημάτων χάρται, κειμένων ἀναλύσεις.",
  "Diller": "Γλῶτται",
  "Dil öğrenim notları, sözlük ve çeviri çalışmaları.": "Ὑπομνήματα τῆς τῶν γλωττῶν μαθήσεως, λεξικὸν καὶ μεταφράσεις.",
  "Bilimler": "Ἐπιστῆμαι",
  "Doğa, formel ve sosyal bilimlerden notlar.": "Ὑπομνήματα ἐκ τῶν φυσικῶν, τυπικῶν καὶ κοινωνικῶν ἐπιστημῶν.",
  "Görüşme, danışma ya da sohbet için ücretsiz randevu. Uygun saatleri Google Takvim sayfasından seçebilirsin.": "Δωρεὰν συνάντησις πρὸς ὁμιλίαν, συμβουλὴν ἢ διάλογον. Τὴν ἁρμόττουσαν ὥραν ἐν τῇ σελίδι τοῦ Ἡμερολογίου Google ἐκλέγεσθαι δύνασαι.",
  "Randevu al →": "Συνάντησιν αἴτησαι →",
  "Akademik profillerim ve sosyal hesaplarım. Görüşmek için yukarıdaki randevu bağlantısını kullanabilirsin.": "Τὰ ἀκαδημαϊκά μου προφὶλ καὶ οἱ κοινωνικοί μου λογαριασμοί. Ἵνα ὁμιλήσωμεν, τῷ ἄνω συνδέσμῳ τῆς συναντήσεως χρῆσθαι δύνασαι.",
  "Gözlüklü kuzgun maskot kanadını kaldırıp selam veriyor": "Κόραξ-σύμβολον μετὰ μονοκλίου τὴν πτέρυγα πρὸς χαιρετισμὸν αἴρων",
  "Akademik profiller": "Ἀκαδημαϊκὰ προφίλ",
  "Sosyal hesaplar": "Κοινωνικοὶ λογαριασμοί",
  "Sayfayı okumak istediğin dili seç.": "Ἐκλέγου τὴν γλῶτταν ἐν ᾗ τὴν σελίδα ἀναγιγνώσκειν βούλει.",
  "Türkçe": "Τουρκικά",
  "İngilizce": "Ἀγγλικά",
  "Almanca": "Γερμανικά",
  "Fransızca": "Γαλλικά",
  "Latince": "Λατινικά",
  "Grekçe": "Ἑλληνικά",
  "Arapça": "Ἀραβικά",
  "MERAK · AKIL · ANLAM": "ΦΙΛΟΜΑΘΕΙΑ · ΛΟΓΟΣ · ΝΟΗΜΑ",
  "Ses:": "Ἦχος:",
  "Şömine": "Ἑστία",
  "Yağmur": "Ὑετός",
  "Rüzgâr": "Ἄνεμος",
  "Kapalı": "Σιγή",
  "Dışarıda:": "Ἔξω:",
  "Kar": "Χιών",
  "Ortam sesi": "Ἦχος τοῦ περιέχοντος",
  "Dışarıdaki hava": "Ὁ ἔξωθεν καιρός",
  "İçeriğe geç": "Ἐπὶ τὰ περιεχόμενα ἴθι",
  "Kütüphaneye gir →": "Εἰς τὴν βιβλιοθήκην εἴσελθε →",
  "Etkileşimli sunum": "Ἐπίδειξις διαδραστική",
  "Video": "Βίντεο",
  "Alanlara göre süz": "Κατὰ πεδία διάκρινε",
  "Tümü": "Πάντα",
  "Doğa Bilimleri": "Φυσικαὶ ἐπιστῆμαι",
  "Formel Bilimler": "Τυπικαὶ ἐπιστῆμαι",
  "Sosyal Bilimler": "Πολιτικαὶ ἐπιστῆμαι",
  "Estetik": "Αἰσθητική",
  "Beceriler": "Τέχναι",
  "Bir cilde dokun; o alandaki içerikler aşağıda süzülür.": "Βιβλίου ἅψαι· τὰ τοῦ πεδίου ἐκείνου κάτω διακρίνεται.",
  "Son eklenenler": "Νεωστὶ προστεθέντα",
  "Okuma": "Ἀνάγνωσις",
  "Sunum": "Ἐπίδειξις",
  "Yakında": "Ὅσον οὔπω",
  "Sıradaki okuma": "Ἡ ἑπομένη ἀνάγνωσις",
  "Yeni bir adım adım okuma hazırlanıyor.": "Νέα ἀνάγνωσις κατὰ βῆμα παρασκευάζεται.",
  "Bu rafta henüz içerik yok; yakında eklenecek.": "Ἐν ταύτῃ τῇ θήκῃ οὐδέν πω ἔνεστιν· ὅσον οὔπω προστεθήσεται.",
  "Evren bir matematiksel yapı mı?": "Ἆρά γε τὸ πᾶν σύστασίς ἐστι μαθηματική;",
  "Tegmark’ın “Matematiksel Evren” makalesi kaydırarak, adım adım: dış gerçeklik, yapılar, Gödel ve soyut nesneler sorusu.": "Τὸ τοῦ Τέγμαρκ «The Mathematical Universe» κατὰ βῆμα κυλιόμενον· τὰ ἔξω ὄντα, αἱ συστάσεις, ὁ Gödel καὶ τὸ περὶ τῶν ἐξ ἀφαιρέσεως ἐρώτημα.",
  "Ortam": "Τὰ πέριξ",
  "Alt menü": "Κάτω πίναξ",
  "Başa dön ↑": "Εἰς τὴν ἀρχήν ↑",
  "Bu sitede çerez ya da izleyici yok; müzik yalnız gramofona dokununca YouTube’dan yüklenir.": "Ἐν τῷδε τῷ τόπῳ οὐδὲν ἰχνεύει τοὺς ἐπιόντας· ἡ δὲ μουσικὴ ἐκ τοῦ YouTube τότε μόνον φέρεται, ὅταν τοῦ γραμμοφώνου ἅψῃ.",
  "Müzik çal": "Μουσικῆς ἄρχου",
  "Müzik yükleniyor…": "Ἡ μουσικὴ φέρεται…",
  "Müzik çubuğu": "Μουσικὸς πίναξ",
  "Önceki parça": "Τὸ πρότερον μέλος",
  "Çal / Duraklat": "Ἄρχου / Παῦε",
  "Sonraki parça": "Τὸ ἑπόμενον μέλος",
  "Sesi kapat/aç": "Σίγα / Φώνει",
  "Müziği kapat": "Τὴν μουσικὴν κλεῖσον",
  "Ormanın ortasında kitaplıklı bir kabin: kuzgun maskot şöminenin önündeki deri koltukta kitap okuyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "Οἴκημα βιβλίων μεστὸν ἐν μέσῃ τῇ ὕλῃ· ὁ κόραξ-σύμβολον ἐν δερματίνῃ καθέδρᾳ πρὸ τῆς ἑστίας ἀναγιγνώσκει, ὑπὲρ δὲ τὴν τοξοειδῆ θυρίδα πευκῶν ὕλη χιονώδης καὶ πανσέληνος φαίνονται",
  "Kanal kapağı: karlı bir gecede şömineli kütüphane, ortada altın phi-alev logo, masada kitap okuyan kuzgun maskot": "Τοῦ καναλιοῦ προκάλυμμα· βιβλιοθήκη μεθ’ ἑστίας ἐν νυκτὶ χιονώδει, ἐν μέσῳ τὸ χρυσοῦν σύμβολον τοῦ φῖ καὶ τῆς φλογός, ὁ δὲ κόραξ-σύμβολον ἐπὶ τῆς τραπέζης βιβλίον ἀναγιγνώσκων",
  "Işıklı ciltler kendi dünyalarına açılır; diğerleri aşağıdaki dizini süzer.": "Τὰ λάμποντα βιβλία εἰς ἰδίους κόσμους ἀνοίγεται· τὰ δ’ ἄλλα τὸν κάτω κατάλογον διακρίνει.",
  "Kütüphane": "Βιβλιοθήκη",
  "Kütüphaneye dön": "Εἰς τὴν βιβλιοθήκην ἐπάνελθε",
  "Parıldayan nesnelere dokun.": "Τῶν λαμπόντων ἅψαι.",
  "Bu alandaki içerikler": "Τὰ τοῦδε τοῦ πεδίου",
  "Paneli kapat": "Τὸν πίνακα κλεῖσον",
  "Antik Yunanca": "Ἀρχαία Ἑλληνική",
  "Biyoloji": "Βιολογία",
  "Astronomi": "Ἀστρονομία",
  "Fizik": "Φυσική",
  "Kimya": "Χημεία",
  "Yer Bilimleri": "Ἐπιστῆμαι τῆς γῆς",
  "Etik": "Ἠθική",
  "Mantık": "Λογική",
  "Bilgi Felsefesi": "Φιλοσοφία τῆς γνώσεως",
  "Dil Felsefesi": "Φιλοσοφία τῆς γλώττης",
  "Varlık Felsefesi": "Ὀντολογία",
  "Zihin Felsefesi": "Φιλοσοφία τοῦ νοῦ",
  "Mantık Felsefesi": "Φιλοσοφία τῆς λογικῆς",
  "Bilim Felsefesi": "Φιλοσοφία τῆς ἐπιστήμης",
  "Politik Felsefe": "Πολιτικὴ φιλοσοφία",
  "Din Felsefesi": "Φιλοσοφία τῆς θρησκείας",
  "Tarih Felsefesi": "Φιλοσοφία τῆς ἱστορίας",
  "Sanat Felsefesi": "Φιλοσοφία τῆς τέχνης",
  "Felsefe Tarihi": "Ἱστορία τῆς φιλοσοφίας",
  "Metafelsefe": "Μεταφιλοσοφία",
  "Sözlükçe": "Γλωσσάριον",
  "Ekoloji": "Οἰκολογία",
  "Jeoloji": "Γεωλογία",
  "Mühendislik": "Μηχανική",
  "Tıp": "Ἰατρική",
  "Bilişim": "Πληροφορική",
  "Geometri": "Γεωμετρία",
  "Matematik": "Μαθηματικά",
  "Antropoloji": "Ἀνθρωπολογία",
  "Arkeoloji": "Ἀρχαιολογία",
  "Coğrafya": "Γεωγραφία",
  "Dilbilimi": "Γλωσσολογία",
  "Ekonomi": "Οἰκονομική",
  "Hukuk": "Νομική",
  "İlahiyat": "Θεολογία",
  "Siyaset ve Sosyoloji": "Πολιτικὴ καὶ κοινωνιολογία",
  "Psikoloji ve Psikanaliz": "Ψυχολογία καὶ ψυχανάλυσις",
  "Tarih": "Ἱστορία",
  "Edebiyat": "Γράμματα",
  "Görsel Sanatlar": "Ὁραταὶ τέχναι",
  "Müzik": "Μουσική",
  "Her raf bir alan. Pirinç levhaya dokununca alanın odası, kitaba dokununca o dalın dünyası açılır; parıldayan kitapların kendi sahnesi var.": "Ἑκάστη θήκη πεδίον ἐστίν. Τῆς χαλκῆς πινακίδος ἅψαι ἵνα τὸ τοῦ πεδίου οἴκημα, βιβλίου δὲ ἵνα ὁ τοῦ κλάδου κόσμος ἀνοιχθῇ· τὰ λάμποντα βιβλία ἰδίαν σκηνὴν ἔχει.",
  "Sahne": "Σκηνή",
  "Ormanın içinde biyoloji": "Βιολογία ἐν τῇ ὕλῃ",
  "Karınca izleri, yapraklar ve mantarlar arasında hücre, evrim ve genetik.": "Κύτταρα, ἐξέλιξις καὶ γενετικὴ μεταξὺ μυρμήκων ἰχνῶν, φύλλων καὶ μυκήτων.",
  "Platon’un Mağarası": "Τὸ τοῦ Πλάτωνος σπήλαιον",
  "Duvarda kayan gölgeler, ateş ve gün ışığı: bilgi nedir, nereden bileceğiz?": "Σκιαὶ ἐπὶ τοῦ τοίχου ὀλισθάνουσαι, πῦρ καὶ φῶς ἡμέρας· τί ἐστιν ἐπιστήμη, καὶ πόθεν εἰσόμεθα;",
  "Roma Senatosu’nda Latince": "Ἡ Λατίνη ἐν τῇ Ῥωμαίων βουλῇ",
  "Cicero kürsüde: alfabe, dilbilgisi, Latincenin serüveni ve ünlü sözler.": "Κικέρων ἐπὶ τοῦ βήματος· τὸ ἀλφάβητον, ἡ γραμματική, ἡ τῆς Λατίνης πορεία καὶ ἀποφθέγματα.",
  "Tık sesi": "Ἦχος τοῦ ψαύματος",
  "Önceki": "Πρότερον",
  "Sonraki": "Ἑπόμενον",
  "Akışı durdur": "Τὴν ῥοὴν παῦσον",
  "Akışı başlat": "Τὴν ῥοὴν ἄρξον",
  "Ses açık": "Ἦχος ἀνοικτός",
  "Ses kapalı": "Ἦχος κεκλεισμένος",
  "Arşiv sandığı": "Κιβωτὸς τοῦ ἀρχείου",
  "içerik": "ἐνόντα",
  "Sandığı kapat": "Τὴν κιβωτὸν κλεῖσον",
  "Yeni not, sunum, video ya da çeviri eklemek için: js/arsiv.js dosyasında bu sahnenin temasına bir satır ekle; dosyaları arsiv/ klasörüne koy.": "Ἵνα νέον ὑπόμνημα, ἐπίδειξιν, βίντεο ἢ μετάφρασιν προσθῇς· ἐν τῷ js/arsiv.js γραμμὴν τῷ τῆς σκηνῆς θέματι πρόσθες καὶ τὰ ἀρχεῖα εἰς τὸν arsiv/ θές.",
  "Bu çekmece henüz boş; yakında dolacak.": "Ἥδε ἡ θήκη ἔτι κενή ἐστιν· ὅσον οὔπω πληρωθήσεται.",
  "İzle": "Θέασαι",
  "Aç": "Ἄνοιξον",
  "Terim ara": "Ὅρον ζήτει",
  "terim": "ὅροι",
  "Not": "Ὑπόμνημα",
  "Çeviri": "Μετάφρασις",
  "Görsel": "Εἰκών",
  "Bağlantı": "Σύνδεσμος",
  "Film": "Κινηματογράφος",
  "Ocak": "Ἰανουάριος",
  "Şubat": "Φεβρουάριος",
  "Mart": "Μάρτιος",
  "Nisan": "Ἀπρίλιος",
  "Mayıs": "Μάιος",
  "Haziran": "Ἰούνιος",
  "Temmuz": "Ἰούλιος",
  "Ağustos": "Αὔγουστος",
  "Eylül": "Σεπτέμβριος",
  "Ekim": "Ὀκτώβριος",
  "Kasım": "Νοέμβριος",
  "Aralık": "Δεκέμβριος",
  "Kanal": "Δίαυλος",
  "(Metafizik)": "(Μεταφυσική)",
  "(Epistemoloji)": "(Ἐπιστημολογία)",
  "Alıştırma": "Ἄσκησις",
  "Bildiri": "Ἀνακοίνωσις",
  "Çalıştay": "Ἐργαστήριον",
  "İzlence": "Πρόγραμμα μαθημάτων",
  "Kitap": "Βιβλίον",
  "Konferans": "Συνέδριον",
  "Makale": "Ἄρθρον",
  "Notlar": "Ὑπομνήματα",
  "Ödevler": "Ἐργασίαι",
  "Poster": "Πίναξ",
  "Proje": "Ἔργον",
  "Seminer": "Σεμινάριον",
  "Sempozyum": "Συμπόσιον",
  "Tezler": "Διατριβαί",
  "Modalite üzerine sunum: zorunluluk, olanak ve olası dünyalar.": "Λόγος περὶ τροπικότητος· ἀνάγκη, δυνατότης καὶ δυνατοὶ κόσμοι.",
  "Meinong’un olmayan nesneler kuramı ve yönelimsellik sorunu üzerine seminer sunumu.": "Λόγος σεμιναρίου περὶ τῆς Μεινόγγου θεωρίας τῶν μὴ ὄντων ἀντικειμένων καὶ τοῦ προβλήματος τῆς προθετικότητος.",
  "Avrupalı öğrencilerin okullarda kendi ülkelerini ve dillerini tanıttığı değişim projesi.": "Ἔργον ἀνταλλαγῆς ἐν ᾧ Εὐρωπαῖοι φοιτηταὶ τὰς πατρίδας καὶ τὰς γλώττας αὑτῶν ἐν τοῖς διδασκαλείοις παρουσιάζουσιν.",
  "Düşüncenin Eşiğinde — YouTube kanalım": "Ἐπὶ τῷ οὐδῷ τῆς διανοίας — ὁ δίαυλός μου ἐν YouTube",
  "Merak, akıl, anlam: konu anlatımları ve yeni videolar. Videolar eklendikçe burada, oynatıcıda izlenebilecek.": "Περιέργεια, λόγος, νόημα· ἐξηγήσεις καὶ νέα βίντεο. Ὅσα προστίθεται, ἐνθάδε θεατὰ ἔσται.",
  "Makaleler, bildiriler, sunum metinleri ve diğer belgeler. Bir başlığa dokununca açıklaması ve indirme bağlantısı açılır.": "Ἄρθρα, ἀνακοινώσεις, κείμενα λόγων καὶ ἄλλα γράμματα. Ἅψαι ἐπιγραφῆς· ἡ περιγραφὴ καὶ ὁ σύνδεσμος ἀνοίγονται.",
  "Belge yakında eklenecek": "Τὸ γράμμα ὅσον οὔπω προστεθήσεται",
  "Belgeyi indir": "Κατέβασον τὸ γράμμα",
  "“Düşüncenin Eşiğinde” — merak, akıl, anlam. Konu anlatımları ve videolar; seçtiğin video aşağıdaki ekranda oynar.": "«Ἐπὶ τῷ οὐδῷ τῆς διανοίας» — περιέργεια, λόγος, νόημα. Ἐξηγήσεις καὶ βίντεο· ὃ ἂν ἕλῃ, ἐν τῇ κάτω ὀθόνῃ δείκνυται.",
  "YouTube’da aç ↗": "Ἄνοιξον ἐν YouTube ↗",
  "Şimdi seçili": "Νῦν ᾑρημένον",
  "Son yüklenenler": "Τὰ νεώτατα",
  "Ses": "Ἦχος",
  "Dışarıda": "Ἔξω",
  "Çalışmalarım": "Τὰ ἔργα μου",
  "{ad} haritası": "Χάρτης· {ad}",
  "Harita": "Χάρτης",
  "Haritayı kapat": "Κλεῖσον τὸν χάρτην",
  "İndir": "Κατέβασον",
  "Dış yörüngedeki odalar yakında açılacak": "Αἱ ἐν τῇ ἔξω τροχιᾷ αἴθουσαι ὅσον οὔπω ἀνοιχθήσονται",
  "Sürükle ya da kenara yaklaş: sahne kayar": "Σύρε ἢ πλησίασον τῷ ἄκρῳ· ἡ σκηνὴ κινεῖται",
  "Yeni bir çalışma eklemek için: js/icerik.js dosyasına bir kayıt ekle ve sandik alanına bu sahnenin adını yaz.": "Ἵνα νέον ἔργον προσθῇς· ἐν τῷ js/icerik.js ἐγγραφὴν πρόσθες καὶ ἐν τῷ πεδίῳ sandik τὸ ὄνομα ταύτης τῆς σκηνῆς γράψον."
 },
 "ar": {
  "__title": "Karahan Uçar — الفلسفة والميتافيزيقا وفلسفة العقل",
  "__desc": "Karahan Uçar: بحث فلسفي. الميتافيزيقا وفلسفة العقل ونظرية المعرفة وفلسفة اللغة؛ منشورات وعروض ومحتوى معرفي.",
  "Ana menü": "القائمة الرئيسية",
  "Hakkında": "نبذة عني",
  "Yayınlar": "المنشورات",
  "Kanal & Sunumlar": "القناة والعروض",
  "Bilgi": "المعرفة",
  "Randevu": "موعد",
  "İletişim": "التواصل",
  "Dil": "اللغة",
  "Karahan Uçar logosu: altın rengi phi ve alev": "شعار Karahan Uçar: حرف فاي ذهبي ولهب",
  "Felsefe araştırmacısı": "البحث الفلسفي",
  "Varlığı, zihni, bilgiyi ve dili düşünmeye çalışıyorum; bu sayfa yayınlarımı, sunumlarımı ve bilgi notlarımı bir araya getiriyor.": "أحاول أن أفكّر في الوجود والعقل والمعرفة واللغة؛ وتجمع هذه الصفحة منشوراتي وعروضي وملاحظاتي.",
  "Çalışma alanları": "مجالات العمل",
  "Metafizik": "الميتافيزيقا",
  "Varlık felsefesi": "فلسفة الوجود",
  "Zihin felsefesi": "فلسفة العقل",
  "Epistemoloji": "نظرية المعرفة",
  "Bilgi felsefesi": "فلسفة المعرفة",
  "Dil felsefesi": "فلسفة اللغة",
  "Mum ışığında bir kütüphanede kitap okuyan kuzgun maskot": "غراب تميمة يقرأ كتابًا في مكتبة على ضوء الشموع",
  "Düşüncenin eşiğinde": "على عتبة الفكر",
  "Ormanın ortasında kitaplıklı bir kabin: taş şömine yanıyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "كوخ مليء بالمكتبات وسط الغابة: موقد حجري مشتعل، ومن خلف النافذة المقوّسة تظهر غابة صنوبر مثلجة وبدر كامل",
  "Karahan Uçar’ın portresi": "صورة شخصية لـ Karahan Uçar",
  "İstanbul Üniversitesi’nde felsefe lisansımı tamamladım; şimdi İstanbul Üniversitesi ve Ruhr-Universität Bochum’da yüksek lisans yapıyorum. Metafizik, zihin felsefesi, epistemoloji ve dil felsefesiyle ilgileniyorum; özellikle varlık felsefesinde soyut ve olmayan nesneler üzerine çalışıyorum. Bu sitede yayınlarımı, sunumlarımı ve bilgi notlarımı paylaşıyorum.": "أنهيتُ درجة البكالوريوس في الفلسفة في جامعة إسطنبول، وأدرس الآن للحصول على درجة الماجستير في جامعة إسطنبول وجامعة رور في بوخوم. أهتمّ بالميتافيزيقا وفلسفة العقل ونظرية المعرفة وفلسفة اللغة، وأعمل في فلسفة الوجود خاصةً على الموضوعات المجرّدة وغير الموجودة. أشارك في هذا الموقع منشوراتي وعروضي وملاحظاتي.",
  "taslak": "مسودة",
  "Kanadını çenesine dayamış, meraklı bakan kuzgun maskot": "غراب تميمة فضولي يسند جناحه إلى ذقنه",
  "Lisans, İstanbul Üniversitesi": "البكالوريوس، جامعة إسطنبول",
  "2024 – sürüyor": "2024 – حتى الآن",
  "Yüksek lisans, İstanbul Üniversitesi ve Ruhr-Universität Bochum": "الماجستير، جامعة إسطنبول وجامعة رور في بوخوم",
  "Yayınlar ve sunumlar": "المنشورات والعروض",
  "Sunum, seminer ve proje çalışmaları. Yayımlanan makaleler ve bildiriler eklendikçe burada listelenecek; tam liste profillerimde.": "عروض وندوات وأعمال مشاريع. ستُضاف هنا المقالات والأوراق المنشورة تباعًا؛ والقائمة الكاملة في ملفاتي الشخصية.",
  "Europa Macht Schule (EMS) projesi": "مشروع Europa Macht Schule (EMS)",
  "Haziran 2026 · Sunum": "يونيو 2026 · عرض",
  "Temmuz 2026 · Sunum": "يوليو 2026 · عرض",
  "Mayıs 2026 · Proje": "مايو 2026 · مشروع",
  "PhilPeople profilim": "ملفي على PhilPeople",
  "Academia profilim": "ملفي على Academia",
  "LinkedIn profilim": "ملفي على LinkedIn",
  "“Düşüncenin Eşiğinde” — merak, akıl, anlam. Konu anlatımları ve etkileşimli sunumlar.": "«على عتبة الفكر» — فضول وعقل ومعنى. شروحات موضوعية وعروض تفاعلية.",
  "Neşeli kuzgun maskot iki kanadını açmış": "غراب تميمة مبتهج ناشر جناحيه",
  "Yaşamın sınırları": "حدود الحياة",
  "Biyoloji felsefesi üzerine etkileşimli sunum.": "عرض تفاعلي عن فلسفة الأحياء.",
  "Sunumu aç →": "افتح العرض ←",
  "Aristoteles’ten Hegel’e metafizik sorunlar.": "مسائل ميتافيزيقية من أرسطو إلى هيغل.",
  "YouTube kanalı": "قناة يوتيوب",
  "Videolar ve yeni yayınlar.": "مقاطع فيديو وإصدارات جديدة.",
  "Kanala git →": "انتقل إلى القناة ←",
  "Bilgi içerikleri": "محتوى معرفي",
  "Alan alan düzenlenmiş notlar ve kaynak listeleri.": "ملاحظات وقوائم مصادر مرتبة حسب المجال.",
  "Felsefe": "الفلسفة",
  "Epistemoloji, normatiflik, argüman haritaları, metin tahlilleri.": "نظرية المعرفة، المعيارية، خرائط الحجج، تحليلات النصوص.",
  "Diller": "اللغات",
  "Dil öğrenim notları, sözlük ve çeviri çalışmaları.": "ملاحظات تعلّم اللغات، ومعجم، وأعمال ترجمة.",
  "Bilimler": "العلوم",
  "Doğa, formel ve sosyal bilimlerden notlar.": "ملاحظات من العلوم الطبيعية والصورية والاجتماعية.",
  "Görüşme, danışma ya da sohbet için ücretsiz randevu. Uygun saatleri Google Takvim sayfasından seçebilirsin.": "موعد مجاني للقاء أو استشارة أو حوار. يمكنك اختيار الوقت المناسب من صفحة تقويم Google.",
  "Randevu al →": "احجز موعدًا ←",
  "Akademik profillerim ve sosyal hesaplarım. Görüşmek için yukarıdaki randevu bağlantısını kullanabilirsin.": "ملفاتي الأكاديمية وحساباتي الاجتماعية. للتواصل يمكنك استخدام رابط الموعد أعلاه.",
  "Gözlüklü kuzgun maskot kanadını kaldırıp selam veriyor": "غراب تميمة يضع عدسة أحادية يرفع جناحه محيّيًا",
  "Akademik profiller": "الملفات الأكاديمية",
  "Sosyal hesaplar": "الحسابات الاجتماعية",
  "Sayfayı okumak istediğin dili seç.": "اختر اللغة التي تريد قراءة الصفحة بها.",
  "Türkçe": "التركية",
  "İngilizce": "الإنجليزية",
  "Almanca": "الألمانية",
  "Fransızca": "الفرنسية",
  "Latince": "اللاتينية",
  "Grekçe": "اليونانية",
  "Arapça": "العربية",
  "MERAK · AKIL · ANLAM": "الفضول · العقل · المعنى",
  "Ses:": "الصوت:",
  "Şömine": "المدفأة",
  "Yağmur": "المطر",
  "Rüzgâr": "الرياح",
  "Kapalı": "إيقاف",
  "Dışarıda:": "في الخارج:",
  "Kar": "الثلج",
  "Ortam sesi": "الصوت المحيط",
  "Dışarıdaki hava": "الطقس في الخارج",
  "İçeriğe geç": "انتقل إلى المحتوى",
  "Kütüphaneye gir →": "ادخل المكتبة ←",
  "Etkileşimli sunum": "عرض تفاعلي",
  "Video": "فيديو",
  "Alanlara göre süz": "صفِّ حسب المجال",
  "Tümü": "الكل",
  "Doğa Bilimleri": "العلوم الطبيعية",
  "Formel Bilimler": "العلوم الصورية",
  "Sosyal Bilimler": "العلوم الاجتماعية",
  "Estetik": "علم الجمال",
  "Beceriler": "المهارات",
  "Bir cilde dokun; o alandaki içerikler aşağıda süzülür.": "المس مجلدًا؛ تُصفّى محتويات ذلك المجال في الأسفل.",
  "Son eklenenler": "أُضيف حديثًا",
  "Okuma": "قراءة",
  "Sunum": "عرض",
  "Yakında": "قريبًا",
  "Sıradaki okuma": "القراءة التالية",
  "Yeni bir adım adım okuma hazırlanıyor.": "يجري إعداد قراءة جديدة خطوة بخطوة.",
  "Bu rafta henüz içerik yok; yakında eklenecek.": "لا شيء على هذا الرف بعد؛ سيُضاف قريبًا.",
  "Evren bir matematiksel yapı mı?": "هل الكون بنية رياضية؟",
  "Tegmark’ın “Matematiksel Evren” makalesi kaydırarak, adım adım: dış gerçeklik, yapılar, Gödel ve soyut nesneler sorusu.": "مقالة تيغمارك «الكون الرياضي» خطوة بخطوة مع التمرير: الواقع الخارجي، والبنى، وغودل، ومسألة الموجودات المجردة.",
  "Ortam": "الأجواء",
  "Alt menü": "قائمة التذييل",
  "Başa dön ↑": "العودة إلى الأعلى ↑",
  "Bu sitede çerez ya da izleyici yok; müzik yalnız gramofona dokununca YouTube’dan yüklenir.": "لا يستخدم هذا الموقع ملفات تعريف الارتباط ولا أدوات تتبّع؛ ولا تُحمَّل الموسيقى من يوتيوب إلا عند لمس الغرامافون.",
  "Müzik çal": "شغّل الموسيقى",
  "Müzik yükleniyor…": "جارٍ تحميل الموسيقى…",
  "Müzik çubuğu": "شريط الموسيقى",
  "Önceki parça": "المقطع السابق",
  "Çal / Duraklat": "تشغيل / إيقاف مؤقت",
  "Sonraki parça": "المقطع التالي",
  "Sesi kapat/aç": "كتم الصوت / إعادته",
  "Müziği kapat": "أغلق الموسيقى",
  "Ormanın ortasında kitaplıklı bir kabin: kuzgun maskot şöminenin önündeki deri koltukta kitap okuyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "كوخ مليء برفوف الكتب وسط الغابة: الغراب التميمة يقرأ كتابًا على كرسي جلدي أمام المدفأة، وخلف النافذة المقوّسة تظهر غابة صنوبر مكسوّة بالثلج وبدر مكتمل",
  "Kanal kapağı: karlı bir gecede şömineli kütüphane, ortada altın phi-alev logo, masada kitap okuyan kuzgun maskot": "غلاف القناة: مكتبة ذات مدفأة في ليلة مثلجة، وفي الوسط شعار فاي واللهب الذهبي، والغراب التميمة يقرأ كتابًا على المكتب",
  "Işıklı ciltler kendi dünyalarına açılır; diğerleri aşağıdaki dizini süzer.": "المجلدات المضيئة تنفتح على عوالمها الخاصة؛ أما البقية فتصفّي الفهرس في الأسفل.",
  "Kütüphane": "المكتبة",
  "Kütüphaneye dön": "العودة إلى المكتبة",
  "Parıldayan nesnelere dokun.": "المس الأشياء المتلألئة.",
  "Bu alandaki içerikler": "محتويات هذا المجال",
  "Paneli kapat": "أغلق اللوحة",
  "Antik Yunanca": "اليونانية القديمة",
  "Biyoloji": "علم الأحياء",
  "Astronomi": "علم الفلك",
  "Fizik": "الفيزياء",
  "Kimya": "الكيمياء",
  "Yer Bilimleri": "علوم الأرض",
  "Etik": "الأخلاق",
  "Mantık": "المنطق",
  "Bilgi Felsefesi": "فلسفة المعرفة",
  "Dil Felsefesi": "فلسفة اللغة",
  "Varlık Felsefesi": "فلسفة الوجود",
  "Zihin Felsefesi": "فلسفة العقل",
  "Mantık Felsefesi": "فلسفة المنطق",
  "Bilim Felsefesi": "فلسفة العلم",
  "Politik Felsefe": "الفلسفة السياسية",
  "Din Felsefesi": "فلسفة الدين",
  "Tarih Felsefesi": "فلسفة التاريخ",
  "Sanat Felsefesi": "فلسفة الفن",
  "Felsefe Tarihi": "تاريخ الفلسفة",
  "Metafelsefe": "ما وراء الفلسفة",
  "Sözlükçe": "مسرد المصطلحات",
  "Ekoloji": "علم البيئة",
  "Jeoloji": "الجيولوجيا",
  "Mühendislik": "الهندسة التطبيقية",
  "Tıp": "الطب",
  "Bilişim": "علوم الحاسوب",
  "Geometri": "الهندسة",
  "Matematik": "الرياضيات",
  "Antropoloji": "علم الإنسان",
  "Arkeoloji": "علم الآثار",
  "Coğrafya": "الجغرافيا",
  "Dilbilimi": "علم اللغة",
  "Ekonomi": "علم الاقتصاد",
  "Hukuk": "القانون",
  "İlahiyat": "علوم الدين",
  "Siyaset ve Sosyoloji": "السياسة وعلم الاجتماع",
  "Psikoloji ve Psikanaliz": "علم النفس والتحليل النفسي",
  "Tarih": "التاريخ",
  "Edebiyat": "الأدب",
  "Görsel Sanatlar": "الفنون البصرية",
  "Müzik": "الموسيقى",
  "Her raf bir alan. Pirinç levhaya dokununca alanın odası, kitaba dokununca o dalın dünyası açılır; parıldayan kitapların kendi sahnesi var.": "كل رف مجال. المس اللوحة النحاسية لتدخل غرفة المجال، أو كتابًا ليُفتح عالم ذلك الفرع؛ وللكتب المتوهجة مشاهدها الخاصة.",
  "Sahne": "مشهد",
  "Ormanın içinde biyoloji": "علم الأحياء في الغابة",
  "Karınca izleri, yapraklar ve mantarlar arasında hücre, evrim ve genetik.": "الخلية والتطور وعلم الوراثة بين مسارات النمل والأوراق والفطر.",
  "Platon’un Mağarası": "كهف أفلاطون",
  "Duvarda kayan gölgeler, ateş ve gün ışığı: bilgi nedir, nereden bileceğiz?": "ظلال تنزلق على الجدار، ونار وضوء النهار: ما المعرفة، وكيف لنا أن نعرف؟",
  "Roma Senatosu’nda Latince": "اللاتينية في مجلس الشيوخ الروماني",
  "Cicero kürsüde: alfabe, dilbilgisi, Latincenin serüveni ve ünlü sözler.": "شيشرون على المنبر: الأبجدية والنحو ومسيرة اللاتينية وأقوال مأثورة.",
  "Tık sesi": "صوت النقر",
  "Önceki": "السابق",
  "Sonraki": "التالي",
  "Akışı durdur": "أوقف التمرير",
  "Akışı başlat": "استأنف التمرير",
  "Ses açık": "الصوت مفعّل",
  "Ses kapalı": "الصوت متوقف",
  "Arşiv sandığı": "صندوق الأرشيف",
  "içerik": "عناصر",
  "Sandığı kapat": "أغلق الصندوق",
  "Yeni not, sunum, video ya da çeviri eklemek için: js/arsiv.js dosyasında bu sahnenin temasına bir satır ekle; dosyaları arsiv/ klasörüne koy.": "لإضافة ملاحظة أو عرض أو فيديو أو ترجمة جديدة: أضف سطرًا إلى موضوع هذا المشهد في js/arsiv.js وضع الملفات في مجلد arsiv/.",
  "Bu çekmece henüz boş; yakında dolacak.": "هذا الدرج ما زال فارغًا؛ سيمتلئ قريبًا.",
  "İzle": "شاهد",
  "Aç": "افتح",
  "Terim ara": "ابحث عن مصطلح",
  "terim": "مصطلحًا",
  "Not": "ملاحظة",
  "Çeviri": "ترجمة",
  "Görsel": "صورة",
  "Bağlantı": "رابط",
  "Film": "السينما",
  "Ocak": "يناير",
  "Şubat": "فبراير",
  "Mart": "مارس",
  "Nisan": "أبريل",
  "Mayıs": "مايو",
  "Haziran": "يونيو",
  "Temmuz": "يوليو",
  "Ağustos": "أغسطس",
  "Eylül": "سبتمبر",
  "Ekim": "أكتوبر",
  "Kasım": "نوفمبر",
  "Aralık": "ديسمبر",
  "Kanal": "القناة",
  "(Metafizik)": "(الميتافيزيقا)",
  "(Epistemoloji)": "(الإبستمولوجيا)",
  "Alıştırma": "تمرين",
  "Bildiri": "ورقة مؤتمر",
  "Çalıştay": "ورشة عمل",
  "İzlence": "منهج دراسي",
  "Kitap": "كتاب",
  "Konferans": "مؤتمر",
  "Makale": "مقالة",
  "Notlar": "ملاحظات",
  "Ödevler": "واجبات",
  "Poster": "ملصق علمي",
  "Proje": "مشروع",
  "Seminer": "حلقة دراسية",
  "Sempozyum": "ندوة",
  "Tezler": "أطروحات",
  "Modalite üzerine sunum: zorunluluk, olanak ve olası dünyalar.": "عرض عن الجهة: الضرورة والإمكان والعوالم الممكنة.",
  "Meinong’un olmayan nesneler kuramı ve yönelimsellik sorunu üzerine seminer sunumu.": "عرض في حلقة دراسية عن نظرية مينونغ في الموضوعات غير الموجودة ومشكلة القصدية.",
  "Avrupalı öğrencilerin okullarda kendi ülkelerini ve dillerini tanıttığı değişim projesi.": "مشروع تبادل يعرّف فيه طلاب أوروبيون ببلدانهم ولغاتهم في المدارس.",
  "Düşüncenin Eşiğinde — YouTube kanalım": "على عتبة الفكر — قناتي على يوتيوب",
  "Merak, akıl, anlam: konu anlatımları ve yeni videolar. Videolar eklendikçe burada, oynatıcıda izlenebilecek.": "فضول، عقل، معنى: شروحات ومقاطع جديدة. كلما أُضيفت مقاطع أمكن مشاهدتها هنا في المشغّل.",
  "Makaleler, bildiriler, sunum metinleri ve diğer belgeler. Bir başlığa dokununca açıklaması ve indirme bağlantısı açılır.": "مقالات وأوراق بحثية ونصوص عروض ووثائق أخرى. المس عنوانًا لتظهر نبذته ورابط التنزيل.",
  "Belge yakında eklenecek": "ستُضاف الوثيقة قريبًا",
  "Belgeyi indir": "نزّل الوثيقة",
  "“Düşüncenin Eşiğinde” — merak, akıl, anlam. Konu anlatımları ve videolar; seçtiğin video aşağıdaki ekranda oynar.": "«على عتبة الفكر» — فضول، عقل، معنى. شروحات ومقاطع؛ يُعرض المقطع الذي تختاره على الشاشة أدناه.",
  "YouTube’da aç ↗": "افتح على يوتيوب ↗",
  "Şimdi seçili": "المحدد الآن",
  "Son yüklenenler": "أحدث المقاطع",
  "Ses": "الصوت",
  "Dışarıda": "في الخارج",
  "Çalışmalarım": "أعمالي",
  "{ad} haritası": "خريطة {ad}",
  "Harita": "خريطة",
  "Haritayı kapat": "أغلق الخريطة",
  "İndir": "نزّل",
  "Dış yörüngedeki odalar yakında açılacak": "الغرف في المدار الخارجي ستُفتح قريبًا",
  "Sürükle ya da kenara yaklaş: sahne kayar": "اسحب أو اقترب من الحافة: يتحرك المشهد",
  "Yeni bir çalışma eklemek için: js/icerik.js dosyasına bir kayıt ekle ve sandik alanına bu sahnenin adını yaz.": "لإضافة عمل جديد: أضف سجلًا إلى js/icerik.js واكتب اسم هذا المشهد في الحقل sandik."
 }
};
