/* Çeviri sözlüğü (otomatik üretildi; scratchpad/diller_uret.py). Anahtar = sayfadaki Türkçe metin. Türkçe metinler HTML'de durur. */
window.DILLER = {
 "en": {
  "__title": "Karahan Uçar — Philosophy, metaphysics and philosophy of mind",
  "__desc": "Karahan Uçar: philosophy researcher. Metaphysics, philosophy of mind, epistemology and philosophy of language; publications, talks and knowledge content.",
  "Ana menü": "Main menu",
  "Hakkında": "About",
  "Yayınlar": "Publications",
  "Kanal & Sunumlar": "Channel & Talks",
  "Bilgi": "Knowledge",
  "Randevu": "Appointment",
  "İletişim": "Contact",
  "Dil": "Language",
  "Karahan Uçar logosu: altın rengi phi ve alev": "Karahan Uçar logo: a golden phi and flame",
  "Felsefe araştırmacısı": "Philosophy researcher",
  "Varlığı, zihni, bilgiyi ve dili düşünmeye çalışıyorum; bu sayfa yayınlarımı, sunumlarımı ve bilgi notlarımı bir araya getiriyor.": "I try to think about being, mind, knowledge and language; this page brings together my publications, talks and notes.",
  "Çalışma alanları": "Fields of work",
  "Metafizik": "Metaphysics",
  "Varlık felsefesi": "Philosophy of being",
  "Zihin felsefesi": "Philosophy of mind",
  "Epistemoloji": "Epistemology",
  "Bilgi felsefesi": "Philosophy of knowledge",
  "Dil felsefesi": "Philosophy of language",
  "Mum ışığında bir kütüphanede kitap okuyan kuzgun maskot": "A raven mascot reading a book in a candlelit library",
  "Düşüncenin eşiğinde": "On the threshold of thought",
  "Ormanın ortasında kitaplıklı bir kabin: taş şömine yanıyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "A cabin with bookshelves in the middle of the forest: a stone fireplace burns, and beyond the arched window a snowy pine forest and a full moon are visible",
  "Karahan Uçar’ın portresi": "Portrait of Karahan Uçar",
  "İstanbul Üniversitesi’nde felsefe lisansımı tamamladım; şimdi İstanbul Üniversitesi ve Ruhr-Universität Bochum’da yüksek lisans yapıyorum. Metafizik, zihin felsefesi, epistemoloji ve dil felsefesiyle ilgileniyorum; özellikle varlık felsefesinde soyut ve olmayan nesneler üzerine çalışıyorum. Bu sitede yayınlarımı, sunumlarımı ve bilgi notlarımı paylaşıyorum.": "I completed my undergraduate degree in philosophy at Istanbul University; I am now doing my master’s at Istanbul University and Ruhr-Universität Bochum. I am interested in metaphysics, philosophy of mind, epistemology and philosophy of language; in the philosophy of being I work in particular on abstract and non-existent objects. On this site I share my publications, talks and notes.",
  "taslak": "draft",
  "Kanadını çenesine dayamış, meraklı bakan kuzgun maskot": "A curious raven mascot with a wing resting against its chin",
  "Lisans, İstanbul Üniversitesi": "Bachelor’s degree, Istanbul University",
  "2024 – sürüyor": "2024 – present",
  "Yüksek lisans, İstanbul Üniversitesi ve Ruhr-Universität Bochum": "Master’s degree, Istanbul University and Ruhr-Universität Bochum",
  "Yayınlar ve sunumlar": "Publications and talks",
  "Sunum, seminer ve proje çalışmaları. Yayımlanan makaleler ve bildiriler eklendikçe burada listelenecek; tam liste profillerimde.": "Talks, seminars and project work. Published articles and papers will be listed here as they are added; the full list is on my profiles.",
  "Europa Macht Schule (EMS) projesi": "Europa Macht Schule (EMS) project",
  "Haziran 2026 · Sunum": "June 2026 · Talk",
  "Temmuz 2026 · Sunum": "July 2026 · Talk",
  "Mayıs 2026 · Proje": "May 2026 · Project",
  "PhilPeople profilim": "My PhilPeople profile",
  "Academia profilim": "My Academia profile",
  "LinkedIn profilim": "My LinkedIn profile",
  "“Düşüncenin Eşiğinde” — merak, akıl, anlam. Konu anlatımları ve etkileşimli sunumlar.": "“On the Threshold of Thought” — curiosity, reason, meaning. Topic explanations and interactive presentations.",
  "Neşeli kuzgun maskot iki kanadını açmış": "A cheerful raven mascot with both wings spread",
  "Yaşamın sınırları": "The limits of life",
  "Biyoloji felsefesi üzerine etkileşimli sunum.": "An interactive presentation on the philosophy of biology.",
  "Sunumu aç →": "Open the presentation →",
  "Aristoteles’ten Hegel’e metafizik sorunlar.": "Metaphysical problems from Aristotle to Hegel.",
  "YouTube kanalı": "YouTube channel",
  "Videolar ve yeni yayınlar.": "Videos and new releases.",
  "Kanala git →": "Go to the channel →",
  "Bilgi içerikleri": "Knowledge content",
  "Alan alan düzenlenmiş notlar ve kaynak listeleri.": "Notes and reading lists organised by field.",
  "Felsefe": "Philosophy",
  "Epistemoloji, normatiflik, argüman haritaları, metin tahlilleri.": "Epistemology, normativity, argument maps, text analyses.",
  "Diller": "Languages",
  "Dil öğrenim notları, sözlük ve çeviri çalışmaları.": "Language-learning notes, dictionary and translation work.",
  "Bilimler": "Sciences",
  "Doğa, formel ve sosyal bilimlerden notlar.": "Notes from the natural, formal and social sciences.",
  "Görüşme, danışma ya da sohbet için ücretsiz randevu. Uygun saatleri Google Takvim sayfasından seçebilirsin.": "A free appointment for a meeting, consultation or chat. You can pick a suitable time on the Google Calendar page.",
  "Randevu al →": "Book an appointment →",
  "Akademik profillerim ve sosyal hesaplarım. Görüşmek için yukarıdaki randevu bağlantısını kullanabilirsin.": "My academic profiles and social accounts. To get in touch, you can use the appointment link above.",
  "Gözlüklü kuzgun maskot kanadını kaldırıp selam veriyor": "A raven mascot with a monocle raising a wing to say hello",
  "Akademik profiller": "Academic profiles",
  "Sosyal hesaplar": "Social accounts",
  "Sayfayı okumak istediğin dili seç.": "Choose the language you would like to read the page in.",
  "Türkçe": "Turkish",
  "İngilizce": "English",
  "Almanca": "German",
  "Fransızca": "French",
  "Latince": "Latin",
  "Grekçe": "Greek",
  "Arapça": "Arabic",
  "MERAK · AKIL · ANLAM": "CURIOSITY · REASON · MEANING",
  "Ses:": "Sound:",
  "Şömine": "Fireplace",
  "Yağmur": "Rain",
  "Rüzgâr": "Wind",
  "Kapalı": "Off",
  "Dışarıda:": "Outside:",
  "Kar": "Snow",
  "Ortam sesi": "Ambient sound",
  "Dışarıdaki hava": "Weather outside",
  "İçeriğe geç": "Skip to content",
  "Kütüphaneye gir →": "Enter the library →",
  "Etkileşimli sunum": "Interactive presentation",
  "Video": "Video",
  "Alanlara göre süz": "Filter by field",
  "Tümü": "All",
  "Doğa Bilimleri": "Natural Sciences",
  "Formel Bilimler": "Formal Sciences",
  "Sosyal Bilimler": "Social Sciences",
  "Estetik": "Aesthetics",
  "Beceriler": "Skills",
  "Bir cilde dokun; o alandaki içerikler aşağıda süzülür.": "Touch a volume; the content in that field is filtered below.",
  "Son eklenenler": "Recently added",
  "Okuma": "Reading",
  "Sunum": "Talk",
  "Yakında": "Coming soon",
  "Sıradaki okuma": "The next reading",
  "Yeni bir adım adım okuma hazırlanıyor.": "A new step-by-step reading is in preparation.",
  "Bu rafta henüz içerik yok; yakında eklenecek.": "Nothing on this shelf yet; it will be added soon.",
  "Evren bir matematiksel yapı mı?": "Is the universe a mathematical structure?",
  "Tegmark’ın “Matematiksel Evren” makalesi kaydırarak, adım adım: dış gerçeklik, yapılar, Gödel ve soyut nesneler sorusu.": "Tegmark’s “The Mathematical Universe”, scrolled step by step: external reality, structures, Gödel and the question of abstract objects.",
  "Ortam": "Ambience",
  "Alt menü": "Footer menu",
  "Başa dön ↑": "Back to top ↑",
  "Bu sitede çerez ya da izleyici yok; müzik yalnız gramofona dokununca YouTube’dan yüklenir.": "This site uses no cookies or trackers; music loads from YouTube only when you touch the gramophone.",
  "Müzik çal": "Play music",
  "Müzik yükleniyor…": "Loading music…",
  "Müzik çubuğu": "Music bar",
  "Önceki parça": "Previous track",
  "Çal / Duraklat": "Play / Pause",
  "Sonraki parça": "Next track",
  "Sesi kapat/aç": "Mute/unmute",
  "Müziği kapat": "Close music",
  "Ormanın ortasında kitaplıklı bir kabin: kuzgun maskot şöminenin önündeki deri koltukta kitap okuyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "A cabin with bookshelves in the middle of the forest: the raven mascot reads a book in a leather armchair by the fireplace; beyond the arched window a snowy pine forest and a full moon are visible",
  "Kanal kapağı: karlı bir gecede şömineli kütüphane, ortada altın phi-alev logo, masada kitap okuyan kuzgun maskot": "Channel cover: a library with a fireplace on a snowy night, the golden phi-flame logo in the centre, and the raven mascot reading a book at the desk"
 },
 "de": {
  "__title": "Karahan Uçar — Philosophie, Metaphysik und Philosophie des Geistes",
  "__desc": "Karahan Uçar: Philosophische Forschung. Metaphysik, Philosophie des Geistes, Erkenntnistheorie und Sprachphilosophie; Veröffentlichungen, Vorträge und Wissensinhalte.",
  "Ana menü": "Hauptmenü",
  "Hakkında": "Über mich",
  "Yayınlar": "Veröffentlichungen",
  "Kanal & Sunumlar": "Kanal & Vorträge",
  "Bilgi": "Wissen",
  "Randevu": "Termin",
  "İletişim": "Kontakt",
  "Dil": "Sprache",
  "Karahan Uçar logosu: altın rengi phi ve alev": "Logo von Karahan Uçar: goldenes Phi und Flamme",
  "Felsefe araştırmacısı": "Philosophische Forschung",
  "Varlığı, zihni, bilgiyi ve dili düşünmeye çalışıyorum; bu sayfa yayınlarımı, sunumlarımı ve bilgi notlarımı bir araya getiriyor.": "Ich versuche, über Sein, Geist, Erkenntnis und Sprache nachzudenken; diese Seite versammelt meine Veröffentlichungen, Vorträge und Notizen.",
  "Çalışma alanları": "Arbeitsgebiete",
  "Metafizik": "Metaphysik",
  "Varlık felsefesi": "Philosophie des Seins",
  "Zihin felsefesi": "Philosophie des Geistes",
  "Epistemoloji": "Erkenntnistheorie",
  "Bilgi felsefesi": "Wissensphilosophie",
  "Dil felsefesi": "Sprachphilosophie",
  "Mum ışığında bir kütüphanede kitap okuyan kuzgun maskot": "Ein Raben-Maskottchen liest im Kerzenlicht in einer Bibliothek",
  "Düşüncenin eşiğinde": "An der Schwelle des Denkens",
  "Ormanın ortasında kitaplıklı bir kabin: taş şömine yanıyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "Eine Hütte mit Bücherregalen mitten im Wald: ein Steinkamin brennt, hinter dem Bogenfenster sind ein verschneiter Kiefernwald und der Vollmond zu sehen",
  "Karahan Uçar’ın portresi": "Porträt von Karahan Uçar",
  "İstanbul Üniversitesi’nde felsefe lisansımı tamamladım; şimdi İstanbul Üniversitesi ve Ruhr-Universität Bochum’da yüksek lisans yapıyorum. Metafizik, zihin felsefesi, epistemoloji ve dil felsefesiyle ilgileniyorum; özellikle varlık felsefesinde soyut ve olmayan nesneler üzerine çalışıyorum. Bu sitede yayınlarımı, sunumlarımı ve bilgi notlarımı paylaşıyorum.": "Ich habe mein Philosophiestudium (Bachelor) an der Universität Istanbul abgeschlossen; derzeit absolviere ich meinen Master an der Universität Istanbul und der Ruhr-Universität Bochum. Ich interessiere mich für Metaphysik, Philosophie des Geistes, Erkenntnistheorie und Sprachphilosophie; in der Ontologie arbeite ich insbesondere zu abstrakten und nicht-existierenden Gegenständen. Auf dieser Seite teile ich meine Veröffentlichungen, Vorträge und Notizen.",
  "taslak": "Entwurf",
  "Kanadını çenesine dayamış, meraklı bakan kuzgun maskot": "Ein neugieriges Raben-Maskottchen, das den Flügel ans Kinn stützt",
  "Lisans, İstanbul Üniversitesi": "Bachelor, Universität Istanbul",
  "2024 – sürüyor": "2024 – heute",
  "Yüksek lisans, İstanbul Üniversitesi ve Ruhr-Universität Bochum": "Master, Universität Istanbul und Ruhr-Universität Bochum",
  "Yayınlar ve sunumlar": "Veröffentlichungen und Vorträge",
  "Sunum, seminer ve proje çalışmaları. Yayımlanan makaleler ve bildiriler eklendikçe burada listelenecek; tam liste profillerimde.": "Vorträge, Seminare und Projektarbeiten. Veröffentlichte Aufsätze und Beiträge werden hier ergänzt; die vollständige Liste findest du in meinen Profilen.",
  "Europa Macht Schule (EMS) projesi": "Projekt Europa Macht Schule (EMS)",
  "Haziran 2026 · Sunum": "Juni 2026 · Vortrag",
  "Temmuz 2026 · Sunum": "Juli 2026 · Vortrag",
  "Mayıs 2026 · Proje": "Mai 2026 · Projekt",
  "PhilPeople profilim": "Mein PhilPeople-Profil",
  "Academia profilim": "Mein Academia-Profil",
  "LinkedIn profilim": "Mein LinkedIn-Profil",
  "“Düşüncenin Eşiğinde” — merak, akıl, anlam. Konu anlatımları ve etkileşimli sunumlar.": "„An der Schwelle des Denkens“ — Neugier, Vernunft, Sinn. Themenerklärungen und interaktive Präsentationen.",
  "Neşeli kuzgun maskot iki kanadını açmış": "Ein fröhliches Raben-Maskottchen mit ausgebreiteten Flügeln",
  "Yaşamın sınırları": "Die Grenzen des Lebens",
  "Biyoloji felsefesi üzerine etkileşimli sunum.": "Eine interaktive Präsentation zur Philosophie der Biologie.",
  "Sunumu aç →": "Präsentation öffnen →",
  "Aristoteles’ten Hegel’e metafizik sorunlar.": "Metaphysische Probleme von Aristoteles bis Hegel.",
  "YouTube kanalı": "YouTube-Kanal",
  "Videolar ve yeni yayınlar.": "Videos und neue Beiträge.",
  "Kanala git →": "Zum Kanal →",
  "Bilgi içerikleri": "Wissensinhalte",
  "Alan alan düzenlenmiş notlar ve kaynak listeleri.": "Nach Fachgebieten geordnete Notizen und Quellenlisten.",
  "Felsefe": "Philosophie",
  "Epistemoloji, normatiflik, argüman haritaları, metin tahlilleri.": "Erkenntnistheorie, Normativität, Argumentkarten, Textanalysen.",
  "Diller": "Sprachen",
  "Dil öğrenim notları, sözlük ve çeviri çalışmaları.": "Notizen zum Sprachenlernen, Wörterbuch- und Übersetzungsarbeiten.",
  "Bilimler": "Wissenschaften",
  "Doğa, formel ve sosyal bilimlerden notlar.": "Notizen aus den Natur-, Formal- und Sozialwissenschaften.",
  "Görüşme, danışma ya da sohbet için ücretsiz randevu. Uygun saatleri Google Takvim sayfasından seçebilirsin.": "Ein kostenloser Termin für ein Gespräch, eine Beratung oder einen Austausch. Passende Zeiten kannst du auf der Google-Kalender-Seite auswählen.",
  "Randevu al →": "Termin buchen →",
  "Akademik profillerim ve sosyal hesaplarım. Görüşmek için yukarıdaki randevu bağlantısını kullanabilirsin.": "Meine akademischen Profile und sozialen Konten. Für ein Gespräch kannst du den Terminlink oben nutzen.",
  "Gözlüklü kuzgun maskot kanadını kaldırıp selam veriyor": "Ein Raben-Maskottchen mit Monokel hebt grüßend einen Flügel",
  "Akademik profiller": "Akademische Profile",
  "Sosyal hesaplar": "Soziale Konten",
  "Sayfayı okumak istediğin dili seç.": "Wähle die Sprache, in der du die Seite lesen möchtest.",
  "Türkçe": "Türkisch",
  "İngilizce": "Englisch",
  "Almanca": "Deutsch",
  "Fransızca": "Französisch",
  "Latince": "Latein",
  "Grekçe": "Griechisch",
  "Arapça": "Arabisch",
  "MERAK · AKIL · ANLAM": "NEUGIER · VERNUNFT · SINN",
  "Ses:": "Ton:",
  "Şömine": "Kamin",
  "Yağmur": "Regen",
  "Rüzgâr": "Wind",
  "Kapalı": "Aus",
  "Dışarıda:": "Draußen:",
  "Kar": "Schnee",
  "Ortam sesi": "Umgebungsgeräusch",
  "Dışarıdaki hava": "Wetter draußen",
  "İçeriğe geç": "Zum Inhalt springen",
  "Kütüphaneye gir →": "Die Bibliothek betreten →",
  "Etkileşimli sunum": "Interaktive Präsentation",
  "Video": "Video",
  "Alanlara göre süz": "Nach Fachgebiet filtern",
  "Tümü": "Alle",
  "Doğa Bilimleri": "Naturwissenschaften",
  "Formel Bilimler": "Formalwissenschaften",
  "Sosyal Bilimler": "Sozialwissenschaften",
  "Estetik": "Ästhetik",
  "Beceriler": "Fertigkeiten",
  "Bir cilde dokun; o alandaki içerikler aşağıda süzülür.": "Tippe auf einen Band; die Inhalte dieses Gebiets werden unten gefiltert.",
  "Son eklenenler": "Zuletzt hinzugefügt",
  "Okuma": "Lektüre",
  "Sunum": "Vortrag",
  "Yakında": "Demnächst",
  "Sıradaki okuma": "Die nächste Lektüre",
  "Yeni bir adım adım okuma hazırlanıyor.": "Eine neue Schritt-für-Schritt-Lektüre ist in Vorbereitung.",
  "Bu rafta henüz içerik yok; yakında eklenecek.": "Auf diesem Regal steht noch nichts; bald kommt etwas hinzu.",
  "Evren bir matematiksel yapı mı?": "Ist das Universum eine mathematische Struktur?",
  "Tegmark’ın “Matematiksel Evren” makalesi kaydırarak, adım adım: dış gerçeklik, yapılar, Gödel ve soyut nesneler sorusu.": "Tegmarks „The Mathematical Universe“, Schritt für Schritt beim Scrollen: äußere Realität, Strukturen, Gödel und die Frage nach abstrakten Gegenständen.",
  "Ortam": "Ambiente",
  "Alt menü": "Fußzeilenmenü",
  "Başa dön ↑": "Nach oben ↑",
  "Bu sitede çerez ya da izleyici yok; müzik yalnız gramofona dokununca YouTube’dan yüklenir.": "Diese Seite nutzt keine Cookies oder Tracker; Musik wird erst dann von YouTube geladen, wenn du das Grammophon berührst.",
  "Müzik çal": "Musik abspielen",
  "Müzik yükleniyor…": "Musik wird geladen…",
  "Müzik çubuğu": "Musikleiste",
  "Önceki parça": "Vorheriger Titel",
  "Çal / Duraklat": "Abspielen / Pause",
  "Sonraki parça": "Nächster Titel",
  "Sesi kapat/aç": "Ton aus/an",
  "Müziği kapat": "Musik schließen",
  "Ormanın ortasında kitaplıklı bir kabin: kuzgun maskot şöminenin önündeki deri koltukta kitap okuyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "Eine Hütte voller Bücherregale mitten im Wald: Das Raben-Maskottchen liest in einem Ledersessel vor dem Kamin; hinter dem Bogenfenster sind ein verschneiter Kiefernwald und der Vollmond zu sehen",
  "Kanal kapağı: karlı bir gecede şömineli kütüphane, ortada altın phi-alev logo, masada kitap okuyan kuzgun maskot": "Kanalbanner: eine Bibliothek mit Kamin in einer verschneiten Nacht, in der Mitte das goldene Phi-Flammen-Logo, am Tisch liest das Raben-Maskottchen ein Buch"
 },
 "fr": {
  "__title": "Karahan Uçar — Philosophie, métaphysique et philosophie de l’esprit",
  "__desc": "Karahan Uçar : recherche en philosophie. Métaphysique, philosophie de l’esprit, épistémologie et philosophie du langage ; publications, exposés et contenus de savoir.",
  "Ana menü": "Menu principal",
  "Hakkında": "À propos",
  "Yayınlar": "Publications",
  "Kanal & Sunumlar": "Chaîne & exposés",
  "Bilgi": "Savoirs",
  "Randevu": "Rendez-vous",
  "İletişim": "Contact",
  "Dil": "Langue",
  "Karahan Uçar logosu: altın rengi phi ve alev": "Logo de Karahan Uçar : phi doré et flamme",
  "Felsefe araştırmacısı": "Recherche en philosophie",
  "Varlığı, zihni, bilgiyi ve dili düşünmeye çalışıyorum; bu sayfa yayınlarımı, sunumlarımı ve bilgi notlarımı bir araya getiriyor.": "J’essaie de penser l’être, l’esprit, la connaissance et le langage ; cette page réunit mes publications, mes exposés et mes notes.",
  "Çalışma alanları": "Domaines de travail",
  "Metafizik": "Métaphysique",
  "Varlık felsefesi": "Philosophie de l’être",
  "Zihin felsefesi": "Philosophie de l’esprit",
  "Epistemoloji": "Épistémologie",
  "Bilgi felsefesi": "Philosophie de la connaissance",
  "Dil felsefesi": "Philosophie du langage",
  "Mum ışığında bir kütüphanede kitap okuyan kuzgun maskot": "Une mascotte corbeau lit un livre dans une bibliothèque éclairée à la bougie",
  "Düşüncenin eşiğinde": "Au seuil de la pensée",
  "Ormanın ortasında kitaplıklı bir kabin: taş şömine yanıyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "Une cabane avec des bibliothèques au milieu de la forêt : une cheminée de pierre flambe, et derrière la fenêtre en arc on voit une forêt de pins enneigée et la pleine lune",
  "Karahan Uçar’ın portresi": "Portrait de Karahan Uçar",
  "İstanbul Üniversitesi’nde felsefe lisansımı tamamladım; şimdi İstanbul Üniversitesi ve Ruhr-Universität Bochum’da yüksek lisans yapıyorum. Metafizik, zihin felsefesi, epistemoloji ve dil felsefesiyle ilgileniyorum; özellikle varlık felsefesinde soyut ve olmayan nesneler üzerine çalışıyorum. Bu sitede yayınlarımı, sunumlarımı ve bilgi notlarımı paylaşıyorum.": "J’ai obtenu ma licence de philosophie à l’Université d’Istanbul ; je prépare actuellement un master à l’Université d’Istanbul et à la Ruhr-Universität Bochum. Je m’intéresse à la métaphysique, à la philosophie de l’esprit, à l’épistémologie et à la philosophie du langage ; en philosophie de l’être, je travaille en particulier sur les objets abstraits et non existants. Sur ce site, je partage mes publications, mes exposés et mes notes.",
  "taslak": "brouillon",
  "Kanadını çenesine dayamış, meraklı bakan kuzgun maskot": "Une mascotte corbeau curieuse, l’aile appuyée contre le menton",
  "Lisans, İstanbul Üniversitesi": "Licence, Université d’Istanbul",
  "2024 – sürüyor": "2024 – en cours",
  "Yüksek lisans, İstanbul Üniversitesi ve Ruhr-Universität Bochum": "Master, Université d’Istanbul et Ruhr-Universität Bochum",
  "Yayınlar ve sunumlar": "Publications et exposés",
  "Sunum, seminer ve proje çalışmaları. Yayımlanan makaleler ve bildiriler eklendikçe burada listelenecek; tam liste profillerimde.": "Exposés, séminaires et travaux de projet. Les articles et communications publiés seront ajoutés ici ; la liste complète se trouve sur mes profils.",
  "Europa Macht Schule (EMS) projesi": "Projet Europa Macht Schule (EMS)",
  "Haziran 2026 · Sunum": "Juin 2026 · Exposé",
  "Temmuz 2026 · Sunum": "Juillet 2026 · Exposé",
  "Mayıs 2026 · Proje": "Mai 2026 · Projet",
  "PhilPeople profilim": "Mon profil PhilPeople",
  "Academia profilim": "Mon profil Academia",
  "LinkedIn profilim": "Mon profil LinkedIn",
  "“Düşüncenin Eşiğinde” — merak, akıl, anlam. Konu anlatımları ve etkileşimli sunumlar.": "« Au seuil de la pensée » — curiosité, raison, sens. Explications thématiques et présentations interactives.",
  "Neşeli kuzgun maskot iki kanadını açmış": "Une mascotte corbeau joyeuse, les deux ailes déployées",
  "Yaşamın sınırları": "Les limites de la vie",
  "Biyoloji felsefesi üzerine etkileşimli sunum.": "Une présentation interactive sur la philosophie de la biologie.",
  "Sunumu aç →": "Ouvrir la présentation →",
  "Aristoteles’ten Hegel’e metafizik sorunlar.": "Problèmes métaphysiques d’Aristote à Hegel.",
  "YouTube kanalı": "Chaîne YouTube",
  "Videolar ve yeni yayınlar.": "Vidéos et nouveautés.",
  "Kanala git →": "Aller à la chaîne →",
  "Bilgi içerikleri": "Contenus de savoir",
  "Alan alan düzenlenmiş notlar ve kaynak listeleri.": "Notes et listes de sources classées par domaine.",
  "Felsefe": "Philosophie",
  "Epistemoloji, normatiflik, argüman haritaları, metin tahlilleri.": "Épistémologie, normativité, cartes d’arguments, analyses de textes.",
  "Diller": "Langues",
  "Dil öğrenim notları, sözlük ve çeviri çalışmaları.": "Notes d’apprentissage des langues, dictionnaire et travaux de traduction.",
  "Bilimler": "Sciences",
  "Doğa, formel ve sosyal bilimlerden notlar.": "Notes issues des sciences naturelles, formelles et sociales.",
  "Görüşme, danışma ya da sohbet için ücretsiz randevu. Uygun saatleri Google Takvim sayfasından seçebilirsin.": "Un rendez-vous gratuit pour un entretien, un conseil ou une discussion. Tu peux choisir un créneau sur la page Google Agenda.",
  "Randevu al →": "Prendre rendez-vous →",
  "Akademik profillerim ve sosyal hesaplarım. Görüşmek için yukarıdaki randevu bağlantısını kullanabilirsin.": "Mes profils académiques et mes comptes sociaux. Pour me contacter, tu peux utiliser le lien de rendez-vous ci-dessus.",
  "Gözlüklü kuzgun maskot kanadını kaldırıp selam veriyor": "Une mascotte corbeau à monocle lève une aile pour saluer",
  "Akademik profiller": "Profils académiques",
  "Sosyal hesaplar": "Comptes sociaux",
  "Sayfayı okumak istediğin dili seç.": "Choisis la langue dans laquelle tu veux lire la page.",
  "Türkçe": "Turc",
  "İngilizce": "Anglais",
  "Almanca": "Allemand",
  "Fransızca": "Français",
  "Latince": "Latin",
  "Grekçe": "Grec",
  "Arapça": "Arabe",
  "MERAK · AKIL · ANLAM": "CURIOSITÉ · RAISON · SENS",
  "Ses:": "Son :",
  "Şömine": "Cheminée",
  "Yağmur": "Pluie",
  "Rüzgâr": "Vent",
  "Kapalı": "Désactivé",
  "Dışarıda:": "Dehors :",
  "Kar": "Neige",
  "Ortam sesi": "Ambiance sonore",
  "Dışarıdaki hava": "Météo dehors",
  "İçeriğe geç": "Aller au contenu",
  "Kütüphaneye gir →": "Entrer dans la bibliothèque →",
  "Etkileşimli sunum": "Présentation interactive",
  "Video": "Vidéo",
  "Alanlara göre süz": "Filtrer par domaine",
  "Tümü": "Tout",
  "Doğa Bilimleri": "Sciences naturelles",
  "Formel Bilimler": "Sciences formelles",
  "Sosyal Bilimler": "Sciences sociales",
  "Estetik": "Esthétique",
  "Beceriler": "Savoir-faire",
  "Bir cilde dokun; o alandaki içerikler aşağıda süzülür.": "Touche un volume : les contenus de ce domaine sont filtrés ci-dessous.",
  "Son eklenenler": "Ajouts récents",
  "Okuma": "Lecture",
  "Sunum": "Exposé",
  "Yakında": "Bientôt",
  "Sıradaki okuma": "La prochaine lecture",
  "Yeni bir adım adım okuma hazırlanıyor.": "Une nouvelle lecture pas à pas est en préparation.",
  "Bu rafta henüz içerik yok; yakında eklenecek.": "Rien sur cette étagère pour l’instant ; ce sera bientôt ajouté.",
  "Evren bir matematiksel yapı mı?": "L’univers est-il une structure mathématique ?",
  "Tegmark’ın “Matematiksel Evren” makalesi kaydırarak, adım adım: dış gerçeklik, yapılar, Gödel ve soyut nesneler sorusu.": "« The Mathematical Universe » de Tegmark, pas à pas en faisant défiler : réalité extérieure, structures, Gödel et la question des objets abstraits.",
  "Ortam": "Ambiance",
  "Alt menü": "Menu de pied de page",
  "Başa dön ↑": "Retour en haut ↑",
  "Bu sitede çerez ya da izleyici yok; müzik yalnız gramofona dokununca YouTube’dan yüklenir.": "Ce site n’utilise ni cookies ni traceurs ; la musique ne se charge depuis YouTube que lorsque tu touches le gramophone.",
  "Müzik çal": "Lancer la musique",
  "Müzik yükleniyor…": "Chargement de la musique…",
  "Müzik çubuğu": "Barre musicale",
  "Önceki parça": "Morceau précédent",
  "Çal / Duraklat": "Lecture / Pause",
  "Sonraki parça": "Morceau suivant",
  "Sesi kapat/aç": "Couper/rétablir le son",
  "Müziği kapat": "Fermer la musique",
  "Ormanın ortasında kitaplıklı bir kabin: kuzgun maskot şöminenin önündeki deri koltukta kitap okuyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "Une cabane remplie de livres au milieu de la forêt : la mascotte corbeau lit dans un fauteuil en cuir devant la cheminée ; derrière la fenêtre cintrée, une forêt de pins enneigée et la pleine lune",
  "Kanal kapağı: karlı bir gecede şömineli kütüphane, ortada altın phi-alev logo, masada kitap okuyan kuzgun maskot": "Bannière de la chaîne : une bibliothèque avec cheminée par une nuit enneigée, au centre le logo doré phi-flamme, et la mascotte corbeau lisant un livre au bureau"
 },
 "la": {
  "__title": "Karahan Uçar — Philosophia, metaphysica et philosophia mentis",
  "__desc": "Karahan Uçar: investigatio philosophica. Metaphysica, philosophia mentis, epistemologia et philosophia linguae; scripta, orationes et contenta doctrinae.",
  "Ana menü": "Index principalis",
  "Hakkında": "De me",
  "Yayınlar": "Scripta",
  "Kanal & Sunumlar": "Canalis et orationes",
  "Bilgi": "Doctrina",
  "Randevu": "Colloquium",
  "İletişim": "Contactus",
  "Dil": "Lingua",
  "Karahan Uçar logosu: altın rengi phi ve alev": "Signum Karahan Uçar: phi aureum et flamma",
  "Felsefe araştırmacısı": "Investigatio philosophica",
  "Varlığı, zihni, bilgiyi ve dili düşünmeye çalışıyorum; bu sayfa yayınlarımı, sunumlarımı ve bilgi notlarımı bir araya getiriyor.": "Esse, mentem, scientiam linguamque cogitare conor; haec pagina scripta, orationes et adnotationes meas colligit.",
  "Çalışma alanları": "Campi studiorum",
  "Metafizik": "Metaphysica",
  "Varlık felsefesi": "Philosophia essendi",
  "Zihin felsefesi": "Philosophia mentis",
  "Epistemoloji": "Epistemologia",
  "Bilgi felsefesi": "Philosophia scientiae",
  "Dil felsefesi": "Philosophia linguae",
  "Mum ışığında bir kütüphanede kitap okuyan kuzgun maskot": "Corvus mascotus in bibliotheca lumine candelae librum legens",
  "Düşüncenin eşiğinde": "In limine cogitationis",
  "Ormanın ortasında kitaplıklı bir kabin: taş şömine yanıyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "Casa lignea inter silvas cum armariis librorum: focus lapideus ardet, et per fenestram arcuatam pineta nivosa et luna plena conspiciuntur",
  "Karahan Uçar’ın portresi": "Imago Karahan Uçar",
  "İstanbul Üniversitesi’nde felsefe lisansımı tamamladım; şimdi İstanbul Üniversitesi ve Ruhr-Universität Bochum’da yüksek lisans yapıyorum. Metafizik, zihin felsefesi, epistemoloji ve dil felsefesiyle ilgileniyorum; özellikle varlık felsefesinde soyut ve olmayan nesneler üzerine çalışıyorum. Bu sitede yayınlarımı, sunumlarımı ve bilgi notlarımı paylaşıyorum.": "Gradum baccalaurei in philosophia apud Universitatem Istanbulensem confeci; nunc gradum magistri apud Universitatem Istanbulensem et Universitatem Ruhr Bochumensem persequor. Metaphysicam, philosophiam mentis, epistemologiam et philosophiam linguae studeo; in philosophia essendi praesertim de obiectis abstractis et non exsistentibus laboro. In hoc situ scripta, orationes et adnotationes meas communico.",
  "taslak": "adumbratio",
  "Kanadını çenesine dayamış, meraklı bakan kuzgun maskot": "Corvus mascotus curiosus alam mento admovens",
  "Lisans, İstanbul Üniversitesi": "Baccalaureus, Universitas Istanbulensis",
  "2024 – sürüyor": "2024 – nunc",
  "Yüksek lisans, İstanbul Üniversitesi ve Ruhr-Universität Bochum": "Magister, Universitas Istanbulensis et Ruhr-Universität Bochum",
  "Yayınlar ve sunumlar": "Scripta et orationes",
  "Sunum, seminer ve proje çalışmaları. Yayımlanan makaleler ve bildiriler eklendikçe burada listelenecek; tam liste profillerimde.": "Orationes, seminaria et opera consiliorum. Articuli et commentationes editae hic adicientur; index plenus in profilis meis est.",
  "Europa Macht Schule (EMS) projesi": "Consilium Europa Macht Schule (EMS)",
  "Haziran 2026 · Sunum": "Iunius 2026 · Oratio",
  "Temmuz 2026 · Sunum": "Iulius 2026 · Oratio",
  "Mayıs 2026 · Proje": "Maius 2026 · Consilium",
  "PhilPeople profilim": "Profilum meum PhilPeople",
  "Academia profilim": "Profilum meum Academia",
  "LinkedIn profilim": "Profilum meum LinkedIn",
  "“Düşüncenin Eşiğinde” — merak, akıl, anlam. Konu anlatımları ve etkileşimli sunumlar.": "«In limine cogitationis» — curiositas, ratio, sensus. Expositiones argumentorum et praesentationes interactivae.",
  "Neşeli kuzgun maskot iki kanadını açmış": "Corvus mascotus laetus duabus alis expansis",
  "Yaşamın sınırları": "Fines vitae",
  "Biyoloji felsefesi üzerine etkileşimli sunum.": "Praesentatio interactiva de philosophia biologiae.",
  "Sunumu aç →": "Praesentationem aperi →",
  "Aristoteles’ten Hegel’e metafizik sorunlar.": "Quaestiones metaphysicae ab Aristotele ad Hegelium.",
  "YouTube kanalı": "Canalis YouTube",
  "Videolar ve yeni yayınlar.": "Video et nova edita.",
  "Kanala git →": "Ad canalem →",
  "Bilgi içerikleri": "Contenta doctrinae",
  "Alan alan düzenlenmiş notlar ve kaynak listeleri.": "Adnotationes et indices fontium per campos ordinati.",
  "Felsefe": "Philosophia",
  "Epistemoloji, normatiflik, argüman haritaları, metin tahlilleri.": "Epistemologia, normativitas, tabulae argumentorum, analyses textuum.",
  "Diller": "Linguae",
  "Dil öğrenim notları, sözlük ve çeviri çalışmaları.": "Adnotationes ad linguas discendas, lexicon et opera interpretandi.",
  "Bilimler": "Scientiae",
  "Doğa, formel ve sosyal bilimlerden notlar.": "Adnotationes ex scientiis naturalibus, formalibus et socialibus.",
  "Görüşme, danışma ya da sohbet için ücretsiz randevu. Uygun saatleri Google Takvim sayfasından seçebilirsin.": "Colloquium gratuitum ad congressum, consilium vel sermonem. Tempus aptum in pagina Google Calendarii eligere potes.",
  "Randevu al →": "Colloquium pete →",
  "Akademik profillerim ve sosyal hesaplarım. Görüşmek için yukarıdaki randevu bağlantısını kullanabilirsin.": "Profila mea academica et rationes sociales. Ut mecum colloquaris, nexu colloquii supra uti potes.",
  "Gözlüklü kuzgun maskot kanadını kaldırıp selam veriyor": "Corvus mascotus monoculatus alam salutandi causa tollens",
  "Akademik profiller": "Profila academica",
  "Sosyal hesaplar": "Rationes sociales",
  "Sayfayı okumak istediğin dili seç.": "Linguam elige qua paginam legere velis.",
  "Türkçe": "Turcice",
  "İngilizce": "Anglice",
  "Almanca": "Germanice",
  "Fransızca": "Gallice",
  "Latince": "Latine",
  "Grekçe": "Graece",
  "Arapça": "Arabice",
  "MERAK · AKIL · ANLAM": "CURIOSITAS · RATIO · SENSUS",
  "Ses:": "Sonus:",
  "Şömine": "Focus",
  "Yağmur": "Pluvia",
  "Rüzgâr": "Ventus",
  "Kapalı": "Clausum",
  "Dışarıda:": "Foris:",
  "Kar": "Nix",
  "Ortam sesi": "Sonus ambientis",
  "Dışarıdaki hava": "Tempestas foris",
  "İçeriğe geç": "Ad contenta transi",
  "Kütüphaneye gir →": "Bibliothecam intra →",
  "Etkileşimli sunum": "Praesentatio interactiva",
  "Video": "Video",
  "Alanlara göre süz": "Secundum campos cerne",
  "Tümü": "Omnia",
  "Doğa Bilimleri": "Scientiae naturales",
  "Formel Bilimler": "Scientiae formales",
  "Sosyal Bilimler": "Scientiae sociales",
  "Estetik": "Aesthetica",
  "Beceriler": "Peritiae",
  "Bir cilde dokun; o alandaki içerikler aşağıda süzülür.": "Volumen tange; quae ad eum campum pertinent, infra secernuntur.",
  "Son eklenenler": "Nuper addita",
  "Okuma": "Lectio",
  "Sunum": "Oratio",
  "Yakında": "Mox",
  "Sıradaki okuma": "Lectio proxima",
  "Yeni bir adım adım okuma hazırlanıyor.": "Nova lectio gradatim explicata paratur.",
  "Bu rafta henüz içerik yok; yakında eklenecek.": "In hoc pluteo nihil adhuc est; mox addetur.",
  "Evren bir matematiksel yapı mı?": "Estne universum structura mathematica?",
  "Tegmark’ın “Matematiksel Evren” makalesi kaydırarak, adım adım: dış gerçeklik, yapılar, Gödel ve soyut nesneler sorusu.": "Tegmarkii «The Mathematical Universe» gradatim volvendo: realitas externa, structurae, Gödel et quaestio de obiectis abstractis.",
  "Ortam": "Ambitus",
  "Alt menü": "Index infimus",
  "Başa dön ↑": "Ad summum ↑",
  "Bu sitede çerez ya da izleyici yok; müzik yalnız gramofona dokununca YouTube’dan yüklenir.": "Hic situs nec crustulis nec vestigatoribus utitur; musica e YouTube tum demum oneratur, cum gramophonum tetigeris.",
  "Müzik çal": "Musicam incipe",
  "Müzik yükleniyor…": "Musica oneratur…",
  "Müzik çubuğu": "Tabula musica",
  "Önceki parça": "Cantus prior",
  "Çal / Duraklat": "Cane / Siste",
  "Sonraki parça": "Cantus sequens",
  "Sesi kapat/aç": "Sonum tace / redde",
  "Müziği kapat": "Musicam claude",
  "Ormanın ortasında kitaplıklı bir kabin: kuzgun maskot şöminenin önündeki deri koltukta kitap okuyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "Casa libris referta in media silva: corvus mascotus in sella coriacea ante focum librum legit; trans fenestram arcuatam silva pinea nivosa et luna plena conspiciuntur",
  "Kanal kapağı: karlı bir gecede şömineli kütüphane, ortada altın phi-alev logo, masada kitap okuyan kuzgun maskot": "Tegmen canalis: bibliotheca cum foco nocte nivosa, in medio signum aureum phi et flammae, corvus mascotus ad mensam librum legens"
 },
 "el": {
  "__title": "Karahan Uçar — Φιλοσοφία, μεταφυσική καὶ φιλοσοφία τοῦ νοῦ",
  "__desc": "Karahan Uçar: φιλοσοφικὴ ζήτησις. Μεταφυσική, φιλοσοφία τοῦ νοῦ, ἐπιστημολογία καὶ φιλοσοφία τῆς γλώττης· συγγράμματα, ἐπιδείξεις καὶ περιεχόμενα γνώσεως.",
  "Ana menü": "Κύριος πίναξ",
  "Hakkında": "Περὶ ἐμοῦ",
  "Yayınlar": "Συγγράμματα",
  "Kanal & Sunumlar": "Κανάλι καὶ ἐπιδείξεις",
  "Bilgi": "Γνῶσις",
  "Randevu": "Συνάντησις",
  "İletişim": "Ἐπικοινωνία",
  "Dil": "Γλῶττα",
  "Karahan Uçar logosu: altın rengi phi ve alev": "Σῆμα τοῦ Karahan Uçar: χρυσοῦν φῖ καὶ φλόξ",
  "Felsefe araştırmacısı": "Φιλοσοφικὴ ζήτησις",
  "Varlığı, zihni, bilgiyi ve dili düşünmeye çalışıyorum; bu sayfa yayınlarımı, sunumlarımı ve bilgi notlarımı bir araya getiriyor.": "Τὸ ὄν, τὸν νοῦν, τὴν γνῶσιν καὶ τὴν γλῶτταν διανοεῖσθαι πειρῶμαι· ἥδε δὲ ἡ σελὶς τὰ συγγράμματα καὶ τὰς ἐπιδείξεις καὶ τὰ ὑπομνήματά μου συνάγει.",
  "Çalışma alanları": "Πεδία μελέτης",
  "Metafizik": "Μεταφυσική",
  "Varlık felsefesi": "Φιλοσοφία τοῦ ὄντος",
  "Zihin felsefesi": "Φιλοσοφία τοῦ νοῦ",
  "Epistemoloji": "Ἐπιστημολογία",
  "Bilgi felsefesi": "Φιλοσοφία τῆς γνώσεως",
  "Dil felsefesi": "Φιλοσοφία τῆς γλώττης",
  "Mum ışığında bir kütüphanede kitap okuyan kuzgun maskot": "Κόραξ-σύμβολον ἐν βιβλιοθήκῃ πρὸς φῶς κηροῦ βιβλίον ἀναγιγνώσκων",
  "Düşüncenin eşiğinde": "Ἐπὶ τῷ οὐδῷ τῆς διανοίας",
  "Ormanın ortasında kitaplıklı bir kabin: taş şömine yanıyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "Οἴκημα ἐν μέσῳ τῷ δρυμῷ βιβλιοθήκας ἔχον· ἑστία λιθίνη καίεται, καὶ διὰ τῆς τοξοειδοῦς θυρίδος πευκὼν χιονώδης καὶ πανσέληνος ὁρῶνται.",
  "Karahan Uçar’ın portresi": "Εἰκὼν τοῦ Karahan Uçar",
  "İstanbul Üniversitesi’nde felsefe lisansımı tamamladım; şimdi İstanbul Üniversitesi ve Ruhr-Universität Bochum’da yüksek lisans yapıyorum. Metafizik, zihin felsefesi, epistemoloji ve dil felsefesiyle ilgileniyorum; özellikle varlık felsefesinde soyut ve olmayan nesneler üzerine çalışıyorum. Bu sitede yayınlarımı, sunumlarımı ve bilgi notlarımı paylaşıyorum.": "Τὸ προπτυχιακὸν τῆς φιλοσοφίας ἐν τῷ Πανεπιστημίῳ τῆς Κωνσταντινουπόλεως ἐξεπλήρωσα· νῦν δὲ τὸ μεταπτυχιακὸν ἐν τῷ Πανεπιστημίῳ τῆς Κωνσταντινουπόλεως καὶ ἐν τῷ Ruhr-Universität Bochum μετέρχομαι. Μεταφυσικῇ, φιλοσοφίᾳ τοῦ νοῦ, ἐπιστημολογίᾳ καὶ φιλοσοφίᾳ τῆς γλώττης προσέχω τὸν νοῦν· ἐν δὲ τῇ περὶ τοῦ ὄντος φιλοσοφίᾳ μάλιστα περὶ τὰ ἀφῃρημένα καὶ τὰ μὴ ὄντα πράγματα πραγματεύομαι. Ἐν τῷδε τῷ ἱστοτόπῳ τὰ συγγράμματα καὶ τὰς ἐπιδείξεις καὶ τὰ ὑπομνήματά μου κοινοῦμαι.",
  "taslak": "προσχέδιον",
  "Kanadını çenesine dayamış, meraklı bakan kuzgun maskot": "Κόραξ-σύμβολον φιλομαθής, τὴν πτέρυγα πρὸς τὸ γένειον ἐπερείδων",
  "Lisans, İstanbul Üniversitesi": "Προπτυχιακόν, Πανεπιστήμιον Κωνσταντινουπόλεως",
  "2024 – sürüyor": "2024 – ἕως νῦν",
  "Yüksek lisans, İstanbul Üniversitesi ve Ruhr-Universität Bochum": "Μεταπτυχιακόν, Πανεπιστήμιον Κωνσταντινουπόλεως καὶ Ruhr-Universität Bochum",
  "Yayınlar ve sunumlar": "Συγγράμματα καὶ ἐπιδείξεις",
  "Sunum, seminer ve proje çalışmaları. Yayımlanan makaleler ve bildiriler eklendikçe burada listelenecek; tam liste profillerimde.": "Ἐπιδείξεις, σεμινάρια καὶ ἔργα. Τὰ ἐκδοθέντα ἄρθρα καὶ αἱ ἀνακοινώσεις ἐνταῦθα προστεθήσονται· ὁ δὲ πλήρης κατάλογος ἐν τοῖς προφὶλ μου ἐστίν.",
  "Europa Macht Schule (EMS) projesi": "Ἔργον Europa Macht Schule (EMS)",
  "Haziran 2026 · Sunum": "Ἰούνιος 2026 · Ἐπίδειξις",
  "Temmuz 2026 · Sunum": "Ἰούλιος 2026 · Ἐπίδειξις",
  "Mayıs 2026 · Proje": "Μάιος 2026 · Ἔργον",
  "PhilPeople profilim": "Τὸ ἐμὸν προφὶλ ἐν τῷ PhilPeople",
  "Academia profilim": "Τὸ ἐμὸν προφὶλ ἐν τῷ Academia",
  "LinkedIn profilim": "Τὸ ἐμὸν προφὶλ ἐν τῷ LinkedIn",
  "“Düşüncenin Eşiğinde” — merak, akıl, anlam. Konu anlatımları ve etkileşimli sunumlar.": "«Ἐπὶ τῷ οὐδῷ τῆς διανοίας» — φιλομάθεια, λόγος, νόημα. Ἐξηγήσεις τῶν πραγμάτων καὶ ἐπιδείξεις διαδραστικαί.",
  "Neşeli kuzgun maskot iki kanadını açmış": "Κόραξ-σύμβολον χαίρων, ἀμφοτέρας τὰς πτέρυγας ἀναπετάσας",
  "Yaşamın sınırları": "Τὰ ὅρια τοῦ βίου",
  "Biyoloji felsefesi üzerine etkileşimli sunum.": "Ἐπίδειξις διαδραστικὴ περὶ τῆς φιλοσοφίας τῆς βιολογίας.",
  "Sunumu aç →": "Τὴν ἐπίδειξιν ἄνοιξον →",
  "Aristoteles’ten Hegel’e metafizik sorunlar.": "Τὰ μεταφυσικὰ προβλήματα ἀπὸ Ἀριστοτέλους μέχρι Ἡγέλου.",
  "YouTube kanalı": "Κανάλι YouTube",
  "Videolar ve yeni yayınlar.": "Βίντεο καὶ νέα ἐκδοθέντα.",
  "Kanala git →": "Ἐπὶ τὸ κανάλι ἴθι →",
  "Bilgi içerikleri": "Περιεχόμενα γνώσεως",
  "Alan alan düzenlenmiş notlar ve kaynak listeleri.": "Ὑπομνήματα καὶ πηγῶν κατάλογοι κατὰ πεδία.",
  "Felsefe": "Φιλοσοφία",
  "Epistemoloji, normatiflik, argüman haritaları, metin tahlilleri.": "Ἐπιστημολογία, κανονιστικότης, ἐπιχειρημάτων χάρται, κειμένων ἀναλύσεις.",
  "Diller": "Γλῶτται",
  "Dil öğrenim notları, sözlük ve çeviri çalışmaları.": "Ὑπομνήματα τῆς τῶν γλωττῶν μαθήσεως, λεξικὸν καὶ μεταφράσεις.",
  "Bilimler": "Ἐπιστῆμαι",
  "Doğa, formel ve sosyal bilimlerden notlar.": "Ὑπομνήματα ἐκ τῶν φυσικῶν, τυπικῶν καὶ κοινωνικῶν ἐπιστημῶν.",
  "Görüşme, danışma ya da sohbet için ücretsiz randevu. Uygun saatleri Google Takvim sayfasından seçebilirsin.": "Δωρεὰν συνάντησις πρὸς ὁμιλίαν, συμβουλὴν ἢ διάλογον. Τὴν ἁρμόττουσαν ὥραν ἐν τῇ σελίδι τοῦ Ἡμερολογίου Google ἐκλέγεσθαι δύνασαι.",
  "Randevu al →": "Συνάντησιν αἴτησαι →",
  "Akademik profillerim ve sosyal hesaplarım. Görüşmek için yukarıdaki randevu bağlantısını kullanabilirsin.": "Τὰ ἀκαδημαϊκά μου προφὶλ καὶ οἱ κοινωνικοί μου λογαριασμοί. Ἵνα ὁμιλήσωμεν, τῷ ἄνω συνδέσμῳ τῆς συναντήσεως χρῆσθαι δύνασαι.",
  "Gözlüklü kuzgun maskot kanadını kaldırıp selam veriyor": "Κόραξ-σύμβολον μετὰ μονοκλίου τὴν πτέρυγα πρὸς χαιρετισμὸν αἴρων",
  "Akademik profiller": "Ἀκαδημαϊκὰ προφίλ",
  "Sosyal hesaplar": "Κοινωνικοὶ λογαριασμοί",
  "Sayfayı okumak istediğin dili seç.": "Ἐκλέγου τὴν γλῶτταν ἐν ᾗ τὴν σελίδα ἀναγιγνώσκειν βούλει.",
  "Türkçe": "Τουρκικά",
  "İngilizce": "Ἀγγλικά",
  "Almanca": "Γερμανικά",
  "Fransızca": "Γαλλικά",
  "Latince": "Λατινικά",
  "Grekçe": "Ἑλληνικά",
  "Arapça": "Ἀραβικά",
  "MERAK · AKIL · ANLAM": "ΦΙΛΟΜΑΘΕΙΑ · ΛΟΓΟΣ · ΝΟΗΜΑ",
  "Ses:": "Ἦχος:",
  "Şömine": "Ἑστία",
  "Yağmur": "Ὑετός",
  "Rüzgâr": "Ἄνεμος",
  "Kapalı": "Σιγή",
  "Dışarıda:": "Ἔξω:",
  "Kar": "Χιών",
  "Ortam sesi": "Ἦχος τοῦ περιέχοντος",
  "Dışarıdaki hava": "Ὁ ἔξωθεν καιρός",
  "İçeriğe geç": "Ἐπὶ τὰ περιεχόμενα ἴθι",
  "Kütüphaneye gir →": "Εἰς τὴν βιβλιοθήκην εἴσελθε →",
  "Etkileşimli sunum": "Ἐπίδειξις διαδραστική",
  "Video": "Βίντεο",
  "Alanlara göre süz": "Κατὰ πεδία διάκρινε",
  "Tümü": "Πάντα",
  "Doğa Bilimleri": "Φυσικαὶ ἐπιστῆμαι",
  "Formel Bilimler": "Τυπικαὶ ἐπιστῆμαι",
  "Sosyal Bilimler": "Πολιτικαὶ ἐπιστῆμαι",
  "Estetik": "Αἰσθητική",
  "Beceriler": "Τέχναι",
  "Bir cilde dokun; o alandaki içerikler aşağıda süzülür.": "Βιβλίου ἅψαι· τὰ τοῦ πεδίου ἐκείνου κάτω διακρίνεται.",
  "Son eklenenler": "Νεωστὶ προστεθέντα",
  "Okuma": "Ἀνάγνωσις",
  "Sunum": "Ἐπίδειξις",
  "Yakında": "Ὅσον οὔπω",
  "Sıradaki okuma": "Ἡ ἑπομένη ἀνάγνωσις",
  "Yeni bir adım adım okuma hazırlanıyor.": "Νέα ἀνάγνωσις κατὰ βῆμα παρασκευάζεται.",
  "Bu rafta henüz içerik yok; yakında eklenecek.": "Ἐν ταύτῃ τῇ θήκῃ οὐδέν πω ἔνεστιν· ὅσον οὔπω προστεθήσεται.",
  "Evren bir matematiksel yapı mı?": "Ἆρά γε τὸ πᾶν σύστασίς ἐστι μαθηματική;",
  "Tegmark’ın “Matematiksel Evren” makalesi kaydırarak, adım adım: dış gerçeklik, yapılar, Gödel ve soyut nesneler sorusu.": "Τὸ τοῦ Τέγμαρκ «The Mathematical Universe» κατὰ βῆμα κυλιόμενον· τὰ ἔξω ὄντα, αἱ συστάσεις, ὁ Gödel καὶ τὸ περὶ τῶν ἐξ ἀφαιρέσεως ἐρώτημα.",
  "Ortam": "Τὰ πέριξ",
  "Alt menü": "Κάτω πίναξ",
  "Başa dön ↑": "Εἰς τὴν ἀρχήν ↑",
  "Bu sitede çerez ya da izleyici yok; müzik yalnız gramofona dokununca YouTube’dan yüklenir.": "Ἐν τῷδε τῷ τόπῳ οὐδὲν ἰχνεύει τοὺς ἐπιόντας· ἡ δὲ μουσικὴ ἐκ τοῦ YouTube τότε μόνον φέρεται, ὅταν τοῦ γραμμοφώνου ἅψῃ.",
  "Müzik çal": "Μουσικῆς ἄρχου",
  "Müzik yükleniyor…": "Ἡ μουσικὴ φέρεται…",
  "Müzik çubuğu": "Μουσικὸς πίναξ",
  "Önceki parça": "Τὸ πρότερον μέλος",
  "Çal / Duraklat": "Ἄρχου / Παῦε",
  "Sonraki parça": "Τὸ ἑπόμενον μέλος",
  "Sesi kapat/aç": "Σίγα / Φώνει",
  "Müziği kapat": "Τὴν μουσικὴν κλεῖσον",
  "Ormanın ortasında kitaplıklı bir kabin: kuzgun maskot şöminenin önündeki deri koltukta kitap okuyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "Οἴκημα βιβλίων μεστὸν ἐν μέσῃ τῇ ὕλῃ· ὁ κόραξ-σύμβολον ἐν δερματίνῃ καθέδρᾳ πρὸ τῆς ἑστίας ἀναγιγνώσκει, ὑπὲρ δὲ τὴν τοξοειδῆ θυρίδα πευκῶν ὕλη χιονώδης καὶ πανσέληνος φαίνονται",
  "Kanal kapağı: karlı bir gecede şömineli kütüphane, ortada altın phi-alev logo, masada kitap okuyan kuzgun maskot": "Τοῦ καναλιοῦ προκάλυμμα· βιβλιοθήκη μεθ’ ἑστίας ἐν νυκτὶ χιονώδει, ἐν μέσῳ τὸ χρυσοῦν σύμβολον τοῦ φῖ καὶ τῆς φλογός, ὁ δὲ κόραξ-σύμβολον ἐπὶ τῆς τραπέζης βιβλίον ἀναγιγνώσκων"
 },
 "ar": {
  "__title": "Karahan Uçar — الفلسفة والميتافيزيقا وفلسفة العقل",
  "__desc": "Karahan Uçar: بحث فلسفي. الميتافيزيقا وفلسفة العقل ونظرية المعرفة وفلسفة اللغة؛ منشورات وعروض ومحتوى معرفي.",
  "Ana menü": "القائمة الرئيسية",
  "Hakkında": "نبذة عني",
  "Yayınlar": "المنشورات",
  "Kanal & Sunumlar": "القناة والعروض",
  "Bilgi": "المعرفة",
  "Randevu": "موعد",
  "İletişim": "التواصل",
  "Dil": "اللغة",
  "Karahan Uçar logosu: altın rengi phi ve alev": "شعار Karahan Uçar: حرف فاي ذهبي ولهب",
  "Felsefe araştırmacısı": "البحث الفلسفي",
  "Varlığı, zihni, bilgiyi ve dili düşünmeye çalışıyorum; bu sayfa yayınlarımı, sunumlarımı ve bilgi notlarımı bir araya getiriyor.": "أحاول أن أفكّر في الوجود والعقل والمعرفة واللغة؛ وتجمع هذه الصفحة منشوراتي وعروضي وملاحظاتي.",
  "Çalışma alanları": "مجالات العمل",
  "Metafizik": "الميتافيزيقا",
  "Varlık felsefesi": "فلسفة الوجود",
  "Zihin felsefesi": "فلسفة العقل",
  "Epistemoloji": "نظرية المعرفة",
  "Bilgi felsefesi": "فلسفة المعرفة",
  "Dil felsefesi": "فلسفة اللغة",
  "Mum ışığında bir kütüphanede kitap okuyan kuzgun maskot": "غراب تميمة يقرأ كتابًا في مكتبة على ضوء الشموع",
  "Düşüncenin eşiğinde": "على عتبة الفكر",
  "Ormanın ortasında kitaplıklı bir kabin: taş şömine yanıyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "كوخ مليء بالمكتبات وسط الغابة: موقد حجري مشتعل، ومن خلف النافذة المقوّسة تظهر غابة صنوبر مثلجة وبدر كامل",
  "Karahan Uçar’ın portresi": "صورة شخصية لـ Karahan Uçar",
  "İstanbul Üniversitesi’nde felsefe lisansımı tamamladım; şimdi İstanbul Üniversitesi ve Ruhr-Universität Bochum’da yüksek lisans yapıyorum. Metafizik, zihin felsefesi, epistemoloji ve dil felsefesiyle ilgileniyorum; özellikle varlık felsefesinde soyut ve olmayan nesneler üzerine çalışıyorum. Bu sitede yayınlarımı, sunumlarımı ve bilgi notlarımı paylaşıyorum.": "أنهيتُ درجة البكالوريوس في الفلسفة في جامعة إسطنبول، وأدرس الآن للحصول على درجة الماجستير في جامعة إسطنبول وجامعة رور في بوخوم. أهتمّ بالميتافيزيقا وفلسفة العقل ونظرية المعرفة وفلسفة اللغة، وأعمل في فلسفة الوجود خاصةً على الموضوعات المجرّدة وغير الموجودة. أشارك في هذا الموقع منشوراتي وعروضي وملاحظاتي.",
  "taslak": "مسودة",
  "Kanadını çenesine dayamış, meraklı bakan kuzgun maskot": "غراب تميمة فضولي يسند جناحه إلى ذقنه",
  "Lisans, İstanbul Üniversitesi": "البكالوريوس، جامعة إسطنبول",
  "2024 – sürüyor": "2024 – حتى الآن",
  "Yüksek lisans, İstanbul Üniversitesi ve Ruhr-Universität Bochum": "الماجستير، جامعة إسطنبول وجامعة رور في بوخوم",
  "Yayınlar ve sunumlar": "المنشورات والعروض",
  "Sunum, seminer ve proje çalışmaları. Yayımlanan makaleler ve bildiriler eklendikçe burada listelenecek; tam liste profillerimde.": "عروض وندوات وأعمال مشاريع. ستُضاف هنا المقالات والأوراق المنشورة تباعًا؛ والقائمة الكاملة في ملفاتي الشخصية.",
  "Europa Macht Schule (EMS) projesi": "مشروع Europa Macht Schule (EMS)",
  "Haziran 2026 · Sunum": "يونيو 2026 · عرض",
  "Temmuz 2026 · Sunum": "يوليو 2026 · عرض",
  "Mayıs 2026 · Proje": "مايو 2026 · مشروع",
  "PhilPeople profilim": "ملفي على PhilPeople",
  "Academia profilim": "ملفي على Academia",
  "LinkedIn profilim": "ملفي على LinkedIn",
  "“Düşüncenin Eşiğinde” — merak, akıl, anlam. Konu anlatımları ve etkileşimli sunumlar.": "«على عتبة الفكر» — فضول وعقل ومعنى. شروحات موضوعية وعروض تفاعلية.",
  "Neşeli kuzgun maskot iki kanadını açmış": "غراب تميمة مبتهج ناشر جناحيه",
  "Yaşamın sınırları": "حدود الحياة",
  "Biyoloji felsefesi üzerine etkileşimli sunum.": "عرض تفاعلي عن فلسفة الأحياء.",
  "Sunumu aç →": "افتح العرض ←",
  "Aristoteles’ten Hegel’e metafizik sorunlar.": "مسائل ميتافيزيقية من أرسطو إلى هيغل.",
  "YouTube kanalı": "قناة يوتيوب",
  "Videolar ve yeni yayınlar.": "مقاطع فيديو وإصدارات جديدة.",
  "Kanala git →": "انتقل إلى القناة ←",
  "Bilgi içerikleri": "محتوى معرفي",
  "Alan alan düzenlenmiş notlar ve kaynak listeleri.": "ملاحظات وقوائم مصادر مرتبة حسب المجال.",
  "Felsefe": "الفلسفة",
  "Epistemoloji, normatiflik, argüman haritaları, metin tahlilleri.": "نظرية المعرفة، المعيارية، خرائط الحجج، تحليلات النصوص.",
  "Diller": "اللغات",
  "Dil öğrenim notları, sözlük ve çeviri çalışmaları.": "ملاحظات تعلّم اللغات، ومعجم، وأعمال ترجمة.",
  "Bilimler": "العلوم",
  "Doğa, formel ve sosyal bilimlerden notlar.": "ملاحظات من العلوم الطبيعية والصورية والاجتماعية.",
  "Görüşme, danışma ya da sohbet için ücretsiz randevu. Uygun saatleri Google Takvim sayfasından seçebilirsin.": "موعد مجاني للقاء أو استشارة أو حوار. يمكنك اختيار الوقت المناسب من صفحة تقويم Google.",
  "Randevu al →": "احجز موعدًا ←",
  "Akademik profillerim ve sosyal hesaplarım. Görüşmek için yukarıdaki randevu bağlantısını kullanabilirsin.": "ملفاتي الأكاديمية وحساباتي الاجتماعية. للتواصل يمكنك استخدام رابط الموعد أعلاه.",
  "Gözlüklü kuzgun maskot kanadını kaldırıp selam veriyor": "غراب تميمة يضع عدسة أحادية يرفع جناحه محيّيًا",
  "Akademik profiller": "الملفات الأكاديمية",
  "Sosyal hesaplar": "الحسابات الاجتماعية",
  "Sayfayı okumak istediğin dili seç.": "اختر اللغة التي تريد قراءة الصفحة بها.",
  "Türkçe": "التركية",
  "İngilizce": "الإنجليزية",
  "Almanca": "الألمانية",
  "Fransızca": "الفرنسية",
  "Latince": "اللاتينية",
  "Grekçe": "اليونانية",
  "Arapça": "العربية",
  "MERAK · AKIL · ANLAM": "الفضول · العقل · المعنى",
  "Ses:": "الصوت:",
  "Şömine": "المدفأة",
  "Yağmur": "المطر",
  "Rüzgâr": "الرياح",
  "Kapalı": "إيقاف",
  "Dışarıda:": "في الخارج:",
  "Kar": "الثلج",
  "Ortam sesi": "الصوت المحيط",
  "Dışarıdaki hava": "الطقس في الخارج",
  "İçeriğe geç": "انتقل إلى المحتوى",
  "Kütüphaneye gir →": "ادخل المكتبة ←",
  "Etkileşimli sunum": "عرض تفاعلي",
  "Video": "فيديو",
  "Alanlara göre süz": "صفِّ حسب المجال",
  "Tümü": "الكل",
  "Doğa Bilimleri": "العلوم الطبيعية",
  "Formel Bilimler": "العلوم الصورية",
  "Sosyal Bilimler": "العلوم الاجتماعية",
  "Estetik": "علم الجمال",
  "Beceriler": "المهارات",
  "Bir cilde dokun; o alandaki içerikler aşağıda süzülür.": "المس مجلدًا؛ تُصفّى محتويات ذلك المجال في الأسفل.",
  "Son eklenenler": "أُضيف حديثًا",
  "Okuma": "قراءة",
  "Sunum": "عرض",
  "Yakında": "قريبًا",
  "Sıradaki okuma": "القراءة التالية",
  "Yeni bir adım adım okuma hazırlanıyor.": "يجري إعداد قراءة جديدة خطوة بخطوة.",
  "Bu rafta henüz içerik yok; yakında eklenecek.": "لا شيء على هذا الرف بعد؛ سيُضاف قريبًا.",
  "Evren bir matematiksel yapı mı?": "هل الكون بنية رياضية؟",
  "Tegmark’ın “Matematiksel Evren” makalesi kaydırarak, adım adım: dış gerçeklik, yapılar, Gödel ve soyut nesneler sorusu.": "مقالة تيغمارك «الكون الرياضي» خطوة بخطوة مع التمرير: الواقع الخارجي، والبنى، وغودل، ومسألة الموجودات المجردة.",
  "Ortam": "الأجواء",
  "Alt menü": "قائمة التذييل",
  "Başa dön ↑": "العودة إلى الأعلى ↑",
  "Bu sitede çerez ya da izleyici yok; müzik yalnız gramofona dokununca YouTube’dan yüklenir.": "لا يستخدم هذا الموقع ملفات تعريف الارتباط ولا أدوات تتبّع؛ ولا تُحمَّل الموسيقى من يوتيوب إلا عند لمس الغرامافون.",
  "Müzik çal": "شغّل الموسيقى",
  "Müzik yükleniyor…": "جارٍ تحميل الموسيقى…",
  "Müzik çubuğu": "شريط الموسيقى",
  "Önceki parça": "المقطع السابق",
  "Çal / Duraklat": "تشغيل / إيقاف مؤقت",
  "Sonraki parça": "المقطع التالي",
  "Sesi kapat/aç": "كتم الصوت / إعادته",
  "Müziği kapat": "أغلق الموسيقى",
  "Ormanın ortasında kitaplıklı bir kabin: kuzgun maskot şöminenin önündeki deri koltukta kitap okuyor, kemerli pencerenin ardında karlı çam ormanı ve dolunay görünüyor": "كوخ مليء برفوف الكتب وسط الغابة: الغراب التميمة يقرأ كتابًا على كرسي جلدي أمام المدفأة، وخلف النافذة المقوّسة تظهر غابة صنوبر مكسوّة بالثلج وبدر مكتمل",
  "Kanal kapağı: karlı bir gecede şömineli kütüphane, ortada altın phi-alev logo, masada kitap okuyan kuzgun maskot": "غلاف القناة: مكتبة ذات مدفأة في ليلة مثلجة، وفي الوسط شعار فاي واللهب الذهبي، والغراب التميمة يقرأ كتابًا على المكتب"
 }
};
