/* HARİTALAR — her alt sahnede başlığın sağında, "Çalışmalarım"ın önündeki "… haritası": konunun tarihine kuşbakışı bir yolculuk.
   Durak: { yil, ad, yer, eser, kavram: [..], metin, soz: { metin, kaynak } }   (yer, eser, kavram, soz isteğe bağlı)
   donemler: [[ilk durak, son durak, "Dönem adı"], …] haritada renkli kuşaklar olarak görünür (sıra numaraları 0'dan başlar).
   Durak eklemek/çıkarmak için listeye bir satır ekle; harita kendini yeniden düzenler. Kavramlar sözlükçede varsa üzerine gelince tanım çıkar. */
(function () {
  function d(yil, ad, yer, eser, kavram, metin, soz) { return { yil: yil, ad: ad, yer: yer, eser: eser, kavram: kavram, metin: metin, soz: soz }; }
  function s(metin, kaynak) { return { metin: metin, kaynak: kaynak }; }
  window.HARITA = {
  epistemoloji: { alt: "Antik Yunan’dan Gettier’ye: “bilgi nedir?” sorusunun yolculuğu.",
    donemler: [[0, 4, "Antik Çağ"], [5, 7, "Yeniçağ"], [8, 9, "Çağdaş"]], duraklar: [
    d("MÖ 5. yy", "Sofistler ve Sokrates", "Atina", "Platon’un erken diyalogları (Savunma)", ["Doxa", "Görecelik", "Elenkhos"],
      "Protagoras “insan her şeyin ölçüsüdür” der: bilgi kişiden kişiye değişir. Sokrates ise sorgulayarak (elenkhos) kanıların çelişkisini ortaya çıkarır; bilmediğini bilmek bilgeliğin başıdır.", s("Bildiğim tek şey, hiçbir şey bilmediğimdir.", "Sokrates’e atfedilir")),
    d("MÖ 369", "Platon, Theaitetos", "Atina · Akademi", "Theaitetos", ["Gerekçelendirilmiş doğru inanç", "Aporia"],
      "Bilgi algı mıdır, doğru kanı mı, yoksa gerekçesi (logos) verilmiş doğru kanı mı? Diyalog üç tanımı da çürütür ve bir sonuca varmadan biter; ama epistemolojinin temel sorusu artık konmuştur."),
    d("MÖ 375", "Platon, Devlet: Mağara", "Atina", "Devlet, VI–VII. kitaplar", ["İdea (form)", "Doxa", "Episteme"],
      "Gölgelerden ateşe, ateşten güneşe: kanıdan (doxa) bilgiye (episteme) yükseliş. Bölünmüş çizgi benzetmesi imgeler, şeyler, matematik nesneleri ve idealar olarak bilginin basamaklarını gösterir.", s("Ἀγεωμέτρητος μηδεὶς εἰσίτω — Geometri bilmeyen girmesin.", "Akademi’nin kapısına yazıldığı söylenir")),
    d("MÖ 4. yy", "Aristoteles, İkinci Analitikler", "Atina · Lykeion", "İkinci Analitikler", ["Kanıtlama", "Tümevarım", "Nous"],
      "Bilimsel bilgi, zorunlu öncüllerden kanıtlamayla elde edilir. Kanıtlamanın dayandığı ilk ilkeler ise tümevarım ve akılla (nous) kavranır: sonsuz geriye gidişi durduran ilk temelcilik."),
    d("MÖ 3. yy – MS 2. yy", "Antik şüphecilik", "Elis · Akademi · İskenderiye", "Sekstos Empirikos, Pyrrhonculuğun Ana Hatları", ["Epokhe", "Ataraksia", "Tropoi"],
      "Pyrrhon, Arkesilaos, Karneades ve Sekstos: her savın karşısına eşit güçte bir sav konabiliyorsa yargıyı askıya almak (epokhe) gerekir. Askıya almanın ardından gelen dinginlik (ataraksia) bir yaşam biçimidir."),
    d("1641", "Descartes, Meditasyonlar", "Hollanda", "Meditationes de prima philosophia", ["Yöntemsel şüphe", "Cogito", "Temelcilik"],
      "Duyular yanılır, düşler gerçeğe benzer, belki bir kötü cin beni aldatıyor. Geriye kalan tek kesinlik: düşündüğüm sürece varım. Bilgi bu sarsılmaz temelin üzerine yeniden kurulmak istenir.", s("Cogito, ergo sum.", "Descartes, İlkeler I.7 (1644)")),
    d("1690 – 1748", "Locke, Berkeley, Hume", "Londra · Dublin · Edinburgh", "Hume, İnsan Anlığı Üzerine Bir Soruşturma", ["Empirizm", "Tabula rasa", "Tümevarım sorunu"],
      "Empiristler: zihin boş bir levhadır, bütün fikirler deneyimden gelir. Berkeley için var olmak algılanmaktır; Hume ise geleceğin geçmişe benzeyeceğini ve nedenselliği akılla temellendiremeyeceğimizi gösterir.", s("Alışkanlık, insan yaşamının büyük kılavuzudur.", "Hume, Soruşturma V")),
    d("1781", "Kant, Saf Aklın Eleştirisi", "Königsberg", "Kritik der reinen Vernunft", ["A priori", "Analitik ve sentetik", "Kategori"],
      "Sentetik a priori yargılar nasıl mümkündür? Kant’ın Kopernikçi devrimi: nesneler bilgimize uyar. Uzay, zaman ve kategoriler deneyimin koşullarıdır; kendinde şeyler bilinemez.", s("İçeriksiz düşünceler boştur, kavramsız görüler kördür.", "Kant, Saf Aklın Eleştirisi, A51/B75")),
    d("1963", "Gettier’nin iki sayfası", "Wayne State Üniversitesi", "“Is Justified True Belief Knowledge?”", ["Gettier problemi", "Epistemik şans"],
      "Smith, işi Jones’un alacağına ve Jones’un cebinde on madeni para olduğuna gerekçeli olarak inanır; işi kendisi alır ve kendi cebinde de on para vardır. İnancı doğru ve gerekçelidir ama bilgi değildir."),
    d("1969 – bugün", "Çağdaş epistemoloji", "—", "Quine, “Epistemology Naturalized”; Goldman, “What Is Justified Belief?”", ["Güvenilircilik", "İçselcilik–dışsalcılık", "Erdem epistemolojisi"],
      "Quine epistemolojiyi psikolojinin bir dalı sayar; Goldman güvenilir süreçlerle oluşan inançları gerekçeli bulur. Bugün tanıklık, uzmanlık, anlaşmazlık ve toplumsal bilgi tartışmanın merkezinde.") ] },

  metafizik: { alt: "İlk ilkeden olmayan nesnelere: varlık sorusunun izinde.",
    donemler: [[0, 2, "Antik Çağ"], [3, 3, "Orta Çağ"], [4, 5, "Yeniçağ"], [6, 9, "Çağdaş"]], duraklar: [
    d("MÖ 6. yy", "Thales ve İyonyalılar", "Milet", "(Aristoteles’in aktarımları)", ["Arkhe", "Apeiron"],
      "Her şeyin ilkesi (arkhe) nedir? Thales için su, Anaksimandros için sınırsız (apeiron), Anaksimenes için hava: değişen dünyanın altında kalıcı bir şey aranır.", s("Her şey tanrılarla doludur.", "Thales, Aristoteles’in aktarımıyla")),
    d("MÖ 5. yy", "Parmenides ve Herakleitos", "Elea · Efes", "Parmenides, Doğa Üzerine (şiir)", ["Varlık", "Oluş", "Logos"],
      "“Olan vardır, olmayan yoktur”: Parmenides’e göre değişim bir yanılsamadır. Herakleitos’a göre ise her şey akar ve karşıtların gerilimi dünyanın düzenidir.", s("Aynı ırmakta iki kez yıkanılmaz.", "Herakleitos, B91")),
    d("MÖ 4. yy", "Platon ve Aristoteles", "Atina", "Aristoteles, Metafizik", ["Töz", "İdea (form)", "Dört neden", "Teleoloji"],
      "Platon’un değişmez idealar dünyası; Aristoteles’in “varlık olmak bakımından varlık” bilimi: töz, madde ve form, dört neden, kendisi hareket etmeyen ilk hareket ettiren.", s("Bütün insanlar doğaları gereği bilmek ister.", "Aristoteles, Metafizik A.1")),
    d("11. – 13. yy", "İbn Sînâ ve Aquinas", "Buhara · Paris", "İbn Sînâ, Kitâbü’ş-Şifâ; Aquinas, De ente et essentia", ["Varlık–mahiyet ayrımı", "Zorunlu varlık"],
      "Bir şeyin ne olduğu (mahiyet) ile var olması ayrıdır; varlığı kendinden olan tek şey Zorunlu Varlık’tır. Bu ayrım Latin dünyasında Aquinas’ın metafiziğine yön verir.", s("Uçan adam kendi varlığını bilir.", "İbn Sînâ’nın düşünce deneyi")),
    d("1641 – 1714", "Descartes, Spinoza, Leibniz", "Amsterdam · Lahey · Hannover", "Spinoza, Ethica; Leibniz, Monadoloji", ["Töz", "Monad", "Yeter neden ilkesi"],
      "İki töz (Descartes), sonsuz sıfatları olan tek töz: Tanrı ya da Doğa (Spinoza), penceresiz sonsuz monadlar (Leibniz). Rasyonalizm tözün ne olduğunu yeniden sorar.", s("Neden hiçbir şey değil de bir şey var?", "Leibniz, 1714")),
    d("1781", "Kant’ın sınırları", "Königsberg", "Saf Aklın Eleştirisi, Diyalektik", ["Kendinde şey", "Antinomiler"],
      "Evrenin başlangıcı, özgürlük, Tanrı: akıl deneyimi aştığında çelişkilere (antinomiler) düşer. Metafizik aklın doğal ama sınırlanması gereken eğilimidir."),
    d("1904 – 1905", "Meinong ve Russell", "Graz · Cambridge", "Meinong, “Über Gegenstandstheorie”; Russell, “On Denoting”", ["Olmayan nesne", "Sosein", "Betimlemeler kuramı"],
      "Meinong: yuvarlak kare gibi olmayan nesneler de nesnedir; nitelikleri (Sosein) varlıklarından (Sein) bağımsızdır. Russell betimlemeler kuramıyla bu nesnelerden mantıksal çözümlemeyle kurtulmak ister.", s("Fransa’nın şimdiki kralı keldir.", "Russell, 1905")),
    d("1948", "Quine, “Ne Var?”", "Harvard", "“On What There Is”", ["Ontolojik bağlanma", "Ockham’ın usturası"],
      "Hangi şeylerin var olduğunu en iyi kuramlarımızın niceleyicileri söyler. Meinong’un “aşırı kalabalık evreni” yerine çöl manzaralarını seven bir ontoloji.", s("Var olmak, bağlı bir değişkenin değeri olmaktır.", "Quine, 1948")),
    d("1970 – 1986", "Kripke ve Lewis", "Princeton", "Kripke, Adlandırma ve Zorunluluk; Lewis, Dünyaların Çokluğu Üzerine", ["Modalite", "Olası dünyalar", "Katı gösterici"],
      "Zorunluluk ve olanak olası dünyalarla düşünülür. Kripke’ye göre adlar bütün dünyalarda aynı şeyi gösterir; Lewis’e göre olası dünyalar bizimki kadar gerçektir."),
    d("Bugün", "Soyut nesneler ve temellendirme", "—", "Zalta, Soyut Nesneler; Priest, Hiçbir Şeye Doğru", ["Temellendirme", "Meta-metafizik", "Yeni Meinongçuluk"],
      "Sayılar ve kurgusal karakterler var mı? Bazı olgular diğerlerine nasıl dayanır? Parsons, Zalta, Priest ve Berto ile Meinongçuluk yeniden ciddiye alınıyor.") ] },

  zihin: { alt: "Ruhtan beyne, beyinden bilince: zihin–beden sorununun haritası.",
    donemler: [[0, 0, "Antik"], [1, 2, "Yeniçağ"], [3, 6, "20. yüzyıl"], [7, 9, "Bilinç çağı"]], duraklar: [
    d("MÖ 4. yy", "Aristoteles, Ruh Üzerine", "Atina", "De Anima", ["Hilomorfizm", "Form"],
      "Ruh, canlı bedenin formudur: balmumu ile üzerindeki mühür gibi, beden ile ruhun bir olup olmadığını sormak gereksizdir. Bitkisel, hayvansal ve düşünen ruh basamakları."),
    d("1641", "Descartes’ın ikiciliği", "Hollanda", "Meditasyonlar, VI", ["Töz ikiciliği", "Res cogitans"],
      "Düşünen şey (res cogitans) ile yer kaplayan şey (res extensa) iki ayrı tözdür. Peki nasıl etkileşirler? Epifiz bezi yanıtı, Bohemyalı Elisabeth’in itirazlarını karşılayamaz."),
    d("1670 – 1714", "Spinoza, Malebranche, Leibniz", "—", "Leibniz, Yeni Sistem", ["Paralelizm", "Vesilecilik", "Önceden kurulmuş uyum"],
      "Zihin ve beden aynı tözün iki yüzü (Spinoza), Tanrı her olayda aracı (Malebranche), baştan ayarlanmış iki saat (Leibniz): etkileşim sorununa rasyonalist çözümler."),
    d("1949", "Ryle, “Makinedeki hayalet”", "Oxford", "The Concept of Mind", ["Davranışçılık", "Kategori yanlışı"],
      "Üniversiteyi gezip “peki üniversite nerede?” diye soran ziyaretçi gibi, zihni bedenin yanında ayrı bir şey sanmak kategori yanlışıdır. Zihin, davranış eğilimlerimizdir."),
    d("1950 – 1959", "Turing ve özdeşlik kuramı", "Manchester · Adelaide", "Turing, “Computing Machinery and Intelligence”", ["Turing testi", "Özdeşlik kuramı"],
      "Turing “makineler düşünebilir mi?” sorusunu bir taklit oyununa çevirir. Place ve Smart: şimşek elektrik boşalmasıysa, acı da C-lifi uyarımıdır."),
    d("1967", "Putnam ve işlevselcilik", "Harvard", "“The Nature of Mental States”", ["İşlevselcilik", "Çoklu gerçekleşebilirlik"],
      "Ahtapot da acı çeker ama C-lifi yoktur: zihinsel durumlar malzemeyle değil işlevle tanımlanır. Zihin, beynin yazılımıdır."),
    d("1974 – 1982", "Yarasa ve Mary", "New York · Adelaide", "Nagel, “What Is It Like to Be a Bat?”; Jackson, “Epiphenomenal Qualia”", ["Qualia", "Bilgi argümanı"],
      "Yarasa olmak nasıl bir şeydir? Siyah-beyaz odada rengi bütün fiziğiyle bilen Mary, kırmızıyı ilk kez görünce yeni bir şey öğrenir mi?", s("Bir organizmanın bilinçli durumları vardır ancak ve ancak o organizma olmanın nasıl bir şey olduğu vardır.", "Nagel, 1974")),
    d("1980", "Searle’ün Çin odası", "Berkeley", "“Minds, Brains, and Programs”", ["Çin odası", "Güçlü yapay zekâ"],
      "Kural kitabını izleyerek Çince simgeleri eşleyen biri Çince anlamaz. Sözdizimi anlambilime yetmez: program çalıştırmak zihin sahibi olmak değildir."),
    d("1995", "Chalmers’ın zor problemi", "Arizona", "“Facing Up to the Problem of Consciousness”", ["Zor problem", "Felsefi zombi"],
      "Dikkati, ayrımı, bildirmeyi açıklamak kolay problemlerdir; bütün bunlara neden bir deneyimin eşlik ettiği zor problemdir. Her yönüyle bize benzeyen ama içi karanlık zombiler düşünülebilir mi?"),
    d("Bugün", "Bilinç kuramları ve yapay zekâ", "—", "Dehaene, Bilinç ve Beyin; Tononi, Φ", ["Küresel çalışma alanı", "Bütünleşik bilgi", "4E biliş"],
      "Bilinç beyindeki küresel bir yayın mı, bütünleşik bilgi mi, bedenle ve çevreyle birlikte mi? Büyük dil modelleri soruyu yeniden açıyor: bilinç ölçülebilir mi?") ] },

  latince: { alt: "Latium’un köylerinden bilimin ve hukukun ortak diline.",
    donemler: [[0, 2, "Eski Latince"], [3, 5, "Klasik ve Geç"], [6, 7, "Orta Çağ"], [8, 9, "Yeniçağ ve bugün"]], duraklar: [
    d("MÖ 8. yy", "Latium ve Roma", "Tiber kıyısı", "Livius, Ab urbe condita I", ["İtalik diller"],
      "Latince, Tiber kıyısındaki Latium bölgesinin İtalik dilidir; Osk ve Umbur dilleriyle akrabadır. Efsaneye göre Roma MÖ 753’te Romulus tarafından kurulur."),
    d("MÖ 7. – 6. yy", "İlk yazıtlar", "Forum · Praeneste", "Lapis Niger; Praeneste fibulası", ["Alfabe"],
      "Etrüskler aracılığıyla Yunan alfabesinden alınan harflerle yazılmış en eski Latince. Fibulada “MANIOS MED FHEFHAKED NUMASIOI”: Manius beni Numerius için yaptı."),
    d("MÖ 3. – 2. yy", "Eski Latince edebiyatı", "Roma", "Plautus, Amphitruo; Terentius, Heauton Timorumenos", ["Komedya"],
      "Livius Andronicus Odysseia’yı çevirir; Plautus ve Terentius Yunan komedyasını Latinceye taşır.", s("Homo sum: humani nihil a me alienum puto.", "Terentius — İnsanım: insana dair hiçbir şey bana yabancı değil.")),
    d("MÖ 1. yy", "Altın Çağ", "Roma", "Cicero, De re publica; Caesar, De bello Gallico; Vergilius, Aeneis", ["Klasik Latince", "Retorik"],
      "Cicero’nun söylevleri ve felsefe dili, Caesar’ın yalın düzyazısı, Vergilius’un destanı, Horatius ve Ovidius: Klasik Latincenin ölçüsü bu yüzyılda konur.", s("Gallia est omnis divisa in partes tres.", "Caesar, Galya Savaşı I.1")),
    d("MS 1. – 2. yy", "Gümüş Çağ", "Roma", "Seneca, Epistulae morales; Tacitus, Annales", ["Stoacılık"],
      "Seneca’nın ahlak mektupları, Tacitus’un keskin tarihi, Plinius’un Doğa Tarihi: daha yoğun ve süslü bir üslup, bütün Akdeniz’de konuşulan bir imparatorluk dili.", s("Dum docemus, discimus.", "Seneca — Öğretirken öğreniriz.")),
    d("MS 4. – 5. yy", "Geç Latince", "Kartaca · Kudüs · Hippo", "Augustinus, Confessiones; Hieronymus, Vulgata", ["Halk Latincesi"],
      "Augustinus’un İtirafları ve Tanrı Devleti, Hieronymus’un İncil çevirisi. Halkın konuştuğu Latince (sermo vulgaris) İtalyanca, İspanyolca, Fransızca, Portekizce ve Rumencenin tohumu olur.", s("Si enim fallor, sum.", "Augustinus — Yanılıyorsam, varım.")),
    d("9. yy", "Karolenj Rönesansı", "Aachen · Tours", "Alcuin’in okul kitapları", ["Karolenj minüskülü"],
      "Şarlman’ın sarayında Alcuin metinleri düzeltir, okullar açılır. Bugünkü küçük harflerin atası olan okunaklı Karolenj yazısı doğar; klasik eserlerin çoğu bu kopyalarla bize ulaşır."),
    d("12. – 15. yy", "Skolastik Latince", "Paris · Oxford · Bologna", "Aquinas, Summa theologiae", ["Skolastik", "Quaestio"],
      "Üniversitelerin dili. Arapçadan ve Yunancadan çevrilen Aristoteles ile İbn Sînâ ve İbn Rüşd okunur; essentia, existentia, substantia gibi felsefe terimleri Latincede biçimlenir.", s("Fides quaerens intellectum.", "Anselmus — Anlamaya çalışan inanç.")),
    d("15. – 17. yy", "Hümanizm, felsefe ve bilim", "Floransa · Amsterdam · Cambridge", "Descartes, Meditationes (1641); Spinoza, Ethica (1677); Newton, Principia (1687)", ["Hümanizm"],
      "Petrarca ve Erasmus Cicero’nun diline döner. Descartes Meditasyonlar’ı, Spinoza Ethica’yı, Kopernik, Kepler ve Newton en büyük eserlerini Latince yazar: Avrupa’nın ortak bilim dili.", s("Hypotheses non fingo.", "Newton, Principia (1713) — Hipotez uydurmam.")),
    d("Bugün", "Yaşayan miras", "—", "Linnaeus, Species plantarum (1753)", ["İkili adlandırma"],
      "Homo sapiens, habeas corpus, per se, a priori: bilimsel adlandırma, hukuk, tıp ve felsefe terimleri. Konuşanı az ama izi her yerde bir dil.") ] },

  yunanca: { alt: "Linear B tabletlerinden Platon’un Attikasına ve bugüne.",
    donemler: [[0, 1, "Arkaik"], [2, 3, "Klasik ve Koine"], [4, 5, "Bizans"], [6, 7, "Modern"]], duraklar: [
    d("MÖ 1450", "Linear B", "Knossos · Pylos", "Pylos tabletleri", ["Hece yazısı"],
      "Miken saraylarının hesap tabletleri: bilinen en eski Yunanca. Hece yazısını 1952’de Michael Ventris çözdü; tabletlerde tanrı adları, zeytinyağı ve savaş arabaları sayılır."),
    d("MÖ 8. yy", "Alfabe ve Homeros", "İonia", "İlyada, Odysseia", ["Alfabe", "Destan"],
      "Fenike harflerine ünlüler eklenerek ilk gerçek alfabe doğar. İlyada ve Odysseia sözlü gelenekten yazıya geçer.", s("Μῆνιν ἄειδε θεά — Öfkeyi söyle, tanrıça.", "İlyada I.1")),
    d("MÖ 5. – 4. yy", "Attika Yunancası", "Atina", "Platon, Devlet; Aristoteles, Metafizik; Thukydides", ["Logos", "Episteme", "Arete"],
      "Tragedyacılar, Thukydides, Platon ve Aristoteles: felsefenin dili. Logos, ousia, episteme, arete: felsefi kavramların çoğu bu dönemin sözcükleridir.", s("Ὁ δὲ ἀνεξέταστος βίος οὐ βιωτὸς ἀνθρώπῳ.", "Platon, Savunma 38a — Sorgulanmamış hayat yaşanmaya değmez.")),
    d("MÖ 4. yy – MS 4. yy", "Koine", "İskenderiye · Antakya", "Septuaginta; Yeni Ahit; Plotinos, Enneadlar", ["Koine"],
      "İskender’in fetihleriyle ortak dil olur. Epikuros, Stoacılar, Plotinos; Septuaginta ve Yeni Ahit bu “ortak” Yunancayla yazılır.", s("Ἐν ἀρχῇ ἦν ὁ λόγος.", "Yuhanna 1:1 — Başlangıçta söz vardı.")),
    d("4. – 15. yy", "Bizans Yunancası", "Konstantinopolis", "Photios, Bibliotheke; Psellos", ["Minüskül"],
      "Bin yıl boyunca antik metinler kopyalanır ve yorumlanır; Photios okuduğu 279 kitabın özetini çıkarır. Bugün elimizdeki Platon elyazmalarının çoğu Bizans kâtiplerindendir."),
    d("1397 – 1453", "İtalya’ya göç", "Floransa · Venedik", "Bessarion’un kütüphanesi (Biblioteca Marciana)", ["Hümanizm"],
      "Manuel Khrysoloras Floransa’da Yunanca öğretir; Gemistos Plethon Platon’u tanıtır, Bessarion elyazmalarını Venedik’e bağışlar. İstanbul’un fethiyle bilginler İtalya’ya göçer."),
    d("19. yy", "Dil sorunu", "Atina", "Korais’in yazıları", ["Diglosi"],
      "Arılaştırılmış Katharevousa ile halkın dili Dimotiki arasındaki tartışma bir yüzyıl sürer; edebiyat Dimotiki’yi, devlet Katharevousa’yı seçer."),
    d("1976 – 1982", "Modern Yunanca", "Atina", "Kavafis, Seferis, Elytis’in şiiri", ["Monotonik yazım"],
      "Dimotiki resmî dil olur; tek vurgulu yazıma geçilir. Seferis ve Elytis Nobel alır; Antik Yunanca okullarda ayrı bir ders olarak kalır.") ] },

  arapca: { alt: "Çöl şiirinden Beytülhikme’ye, oradan modern Arapçaya.",
    donemler: [[0, 1, "Cahiliye"], [2, 3, "Dilin kuruluşu"], [4, 6, "Çeviri ve felsefe"], [7, 8, "Modern"]], duraklar: [
    d("328", "Nemâra yazıtı", "Suriye çölü", "Nemâra mezar taşı", ["Nebati yazısı"],
      "Nebati harfleriyle yazılmış erken Arapça: “bütün Arapların kralı” İmruülkays’ın mezar taşı. Arap alfabesi Nebati yazısından gelişir."),
    d("6. yy", "Cahiliye şiiri", "Ukaz panayırı", "Muallakât", ["Kaside", "Aruz"],
      "Kâbe’ye asıldığı söylenen yedi uzun kaside; İmruülkays, Züheyr ve Antere. Terk edilmiş obanın başında ağlayan şair, Arap şiirinin kurucu imgesidir.", s("Durun, ağlayalım bir sevgilinin ve bir obanın anısına.", "İmruülkays, Muallaka")),
    d("7. yy", "Kur’an ve yazının düzenlenmesi", "Medine · Basra", "Mushaf", ["Hareke", "Nokta"],
      "Dil standartlaşır; Ebü’l-Esved ed-Düelî’ye atfedilen noktalama ve hareke sistemi okumayı güvenceye alır."),
    d("8. yy", "Basra ve Kûfe okulları", "Basra · Kûfe", "Halîl b. Ahmed, Kitâbü’l-Ayn; Sîbeveyhi, el-Kitâb", ["Nahiv", "Sarf", "Aruz"],
      "Halîl ilk sözlüğü ve aruz veznini, öğrencisi Sîbeveyhi ilk büyük dilbilgisini yazar. Kıyas ile semâ arasındaki tartışma iki okulu ayırır."),
    d("830 civarı", "Beytülhikme", "Bağdat", "Huneyn b. İshak’ın Galenos çevirileri", ["Tercüme hareketi"],
      "Abbasi halifesi Me’mûn’un Bağdat’ında Huneyn b. İshak ve çevresi Aristoteles, Galenos ve Öklid’i Süryanice ve Yunancadan Arapçaya çevirir; Arapça bilimin dili olur."),
    d("9. – 10. yy", "Kindî ve Fârâbî", "Bağdat · Şam", "Kindî, İlk Felsefe Üzerine; Fârâbî, Erdemli Şehir", ["Akıl", "Mantık"],
      "“Arapların filozofu” Kindî felsefeyi savunur; “ikinci öğretmen” Fârâbî mantık terimlerini kurar ve Platon’un devletini İslam dünyasında yeniden düşünür.", s("Hakikati nereden gelirse gelsin almaktan utanmamalıyız.", "Kindî, İlk Felsefe Üzerine")),
    d("11. – 14. yy", "İbn Sînâ, Gazzâlî, İbn Rüşd, İbn Haldun", "Buhara · Bağdat · Kurtuba · Tunus", "Şifâ; Tehâfütü’l-Felâsife; Tehâfütü’t-Tehâfüt; Mukaddime", ["Zorunlu varlık", "Nedensellik"],
      "Felsefenin doruğu ve eleştirisi: İbn Sînâ’nın sistemi, Gazzâlî’nin itirazı, İbn Rüşd’ün savunusu; İbn Haldun’un tarih felsefesi. Toledo’daki çeviriler bu eserleri Avrupa’ya taşır."),
    d("19. yy", "Nahda", "Kahire · Beyrut", "Butrus el-Bustânî, Muhît el-Muhît", ["Uyanış"],
      "Matbaa, gazeteler, sözlükler, çeviriler: Arap uyanışı. Modern Standart Arapça yeni kavramlar için sözcük türetir."),
    d("Bugün", "Fushâ ve lehçeler", "—", "Necib Mahfuz, Kahire Üçlemesi (Nobel 1988)", ["Diglosi"],
      "Yazıda ortak Modern Standart Arapça, gündelik hayatta Mısır, Levant, Körfez ve Mağrip lehçeleri: 400 milyonu aşkın konuşur.") ] },

  biyoloji: { alt: "Aristoteles’in hayvanlarından CRISPR’a: yaşamı anlama serüveni.",
    donemler: [[0, 1, "Antik"], [2, 4, "Gözlem ve sınıflama"], [5, 6, "Evrim ve kalıtım"], [7, 8, "Moleküler çağ"]], duraklar: [
    d("MÖ 4. yy", "Aristoteles", "Midilli · Atina", "Hayvanların Tarihi", ["Teleoloji", "Tür"],
      "Midilli’nin lagününde yüzlerce türü gözlemler, sınıflandırır, ahtapotun çiftleşmesini bile anlatır: biyolojinin ilk sistemli çalışması."),
    d("MS 2. yy", "Galenos", "Bergama · Roma", "Vücudun Parçalarının Kullanımı Üzerine", ["Anatomi", "Humoral kuram"],
      "Maymun ve domuz kesimleriyle anatomi ve fizyoloji; yaklaşık 1400 yıl boyunca tıbbın otoritesi olarak kalır."),
    d("1665 – 1676", "Hooke ve Leeuwenhoek", "Londra · Delft", "Micrographia", ["Hücre", "Mikroorganizma"],
      "Hooke mantar dokusundaki küçük odacıklara “cell” der; Leeuwenhoek kendi merceğiyle bir damla suda “küçük hayvancıklar” görür."),
    d("1735 – 1753", "Linnaeus", "Uppsala", "Systema Naturae", ["İkili adlandırma", "Tür"],
      "Her canlıya bir cins ve tür adı: Homo sapiens. Doğa ülkeler, sınıflar ve takımlar hâlinde düzenlenir."),
    d("1838 – 1855", "Hücre kuramı", "Berlin", "Schwann, Mikroskobik Araştırmalar", ["Hücre"],
      "Schleiden ve Schwann: bütün canlılar hücrelerden oluşur. Virchow: omnis cellula e cellula — her hücre bir hücreden gelir."),
    d("1859", "Darwin ve Wallace", "Down House · Malay Takımadaları", "Türlerin Kökeni", ["Evrim", "Doğal seçilim"],
      "Beagle yolculuğu, Galápagos ispinozları ve yirmi yıllık düşünce: doğal seçilimle evrim. Yaşamın çeşitliliği ortak atadan dallanan bir ağaçtır.", s("Yaşama böyle bakmakta bir büyüklük var.", "Darwin, Türlerin Kökeni, son cümle")),
    d("1866", "Mendel", "Brno", "“Bitki Melezleri Üzerine Deneyler”", ["Gen", "Baskınlık"],
      "Manastır bahçesinde 28.000 bezelye: kalıtım karışarak değil, ayrı birimlerle olur. 1900’de yeniden keşfedilince genetiğin temeli olur."),
    d("1953", "DNA’nın çift sarmalı", "Cambridge · Londra", "Watson ve Crick, Nature 171", ["DNA", "Baz eşleşmesi"],
      "Rosalind Franklin’in 51 numaralı X-ışını fotoğrafı ve Wilkins’in verileriyle Watson ve Crick yapıyı kurar: eşleşen bazlar kendini kopyalamanın anahtarıdır."),
    d("2003 – 2012", "Genom ve CRISPR", "Uluslararası · Berkeley", "İnsan Genom Projesi; Jinek vd., Science 337", ["Genom", "Gen düzenleme"],
      "İnsan genomunun 3 milyar harfi okunur; Doudna ve Charpentier bakterilerin savunma sistemini bir “moleküler makasa” çevirir (Nobel 2020).") ] },

  astronomi: { alt: "Babil kulelerinden James Webb’e: göğün haritası.",
    donemler: [[0, 2, "Antik"], [3, 3, "İslam dünyası"], [4, 6, "Bilim devrimi"], [7, 9, "Modern kozmoloji"]], duraklar: [
    d("MÖ 2. binyıl", "Babil gökbilimi", "Babil", "Enuma Anu Enlil tabletleri", ["Takvim"],
      "Venüs’ün doğuşları ve tutulmalar kil tabletlere yazılır; 60 tabanlı sayı sistemi bugün de saat ve açılarda yaşıyor."),
    d("MÖ 3. yy", "Aristarkhos ve Eratosthenes", "Sisam · İskenderiye", "Aristarkhos, Güneş ve Ay’ın Büyüklükleri", ["Güneş merkezlilik"],
      "Aristarkhos Güneş’i merkeze koyar; Eratosthenes Syene ile İskenderiye’deki gölge farkından Dünya’nın çevresini ölçer."),
    d("MS 150", "Batlamyus, Almagest", "İskenderiye", "Mathematike Syntaxis (Almagest)", ["Episikl", "Dış merkezli çember"],
      "Dünya merkezli, çember üstünde çemberlerle göğün matematiksel modeli; Arapçaya çevrildiği adla (el-Mecistî) 1400 yıl kullanılır."),
    d("9. – 15. yy", "İslam dünyasında gökbilim", "Rakka · Merâga · Semerkant", "Sûfî, Sabit Yıldızlar Kitabı; Uluğ Bey, Zîc", ["Usturlap", "Zîc"],
      "Bettânî yılın uzunluğunu düzeltir, Abdurrahman es-Sûfî Andromeda’yı ilk kez kaydeder; Merâga’da Tûsî çifti, Semerkant’ta Uluğ Bey’in dev sekstantı."),
    d("1543", "Kopernik", "Frombork", "De revolutionibus orbium coelestium", ["Güneş merkezlilik"],
      "Güneş merkeze, Dünya gezegenlerin arasına taşınır. Kitabın ilk basılı nüshası Kopernik’e ölüm döşeğinde getirilir."),
    d("1609 – 1610", "Kepler ve Galileo", "Prag · Padova", "Astronomia nova; Sidereus nuncius", ["Eliptik yörünge", "Teleskop"],
      "Kepler, Tycho’nun ölçümleriyle Mars’ın yörüngesinin elips olduğunu bulur; Galileo teleskopla Jüpiter’in uydularını, Venüs’ün evrelerini ve Ay’ın dağlarını görür.", s("E pur si muove — Yine de dönüyor.", "Galileo’ya atfedilir")),
    d("1687", "Newton", "Cambridge", "Philosophiæ Naturalis Principia Mathematica", ["Evrensel kütleçekim"],
      "Elmayı düşüren kuvvet Ay’ı yörüngede tutar: gök ile yeryüzü tek bir yasaya uyar."),
    d("1915 – 1929", "Einstein ve Hubble", "Berlin · Mount Wilson", "Genel görelilik; Hubble, 1929", ["Uzay-zaman", "Genişleyen evren"],
      "Kütle uzay-zamanı büker, ışık bile yolundan sapar (1919 tutulması). Hubble gökadaların uzaklıklarıyla orantılı hızla uzaklaştığını gösterir: evren genişliyor."),
    d("1965", "Kozmik arka plan ışıması", "Holmdel, New Jersey", "Penzias ve Wilson, ApJ 142", ["Büyük Patlama"],
      "Antendeki giderilemeyen uğultu güvercin pisliği değil, Büyük Patlama’nın 2,7 kelvinlik yankısıdır."),
    d("2015 – bugün", "Yeni gözler", "LIGO · EHT · L2 noktası", "EHT, M87* görüntüsü (2019)", ["Kara delik", "Kütleçekim dalgası"],
      "İki kara deliğin birleşmesinden gelen kütleçekim dalgaları, bir kara deliğin ilk görüntüsü ve James Webb’in ilk gökadalara bakan kızılötesi gözü.") ] },

  fizik: { alt: "Kaldıraçtan Higgs bozonuna: doğanın yasalarının peşinde.",
    donemler: [[0, 1, "Antik ve Orta Çağ"], [2, 3, "Klasik mekanik"], [4, 5, "19. yüzyıl"], [6, 8, "Modern fizik"]], duraklar: [
    d("MÖ 3. yy", "Arşimet", "Siraküza", "Yüzen Cisimler Üzerine", ["Kaldırma kuvveti", "Kaldıraç"],
      "Hamamda taşan su: suya batan cisim, taşırdığı suyun ağırlığı kadar kaldırılır. Kaldıraç ve ağırlık merkezi ilk kez matematikle açıklanır.", s("Bana bir dayanak noktası verin, Dünya’yı yerinden oynatayım.", "Arşimet’e atfedilir")),
    d("1011 – 1021", "İbn Heysem", "Kahire", "Kitâbü’l-Menâzır (Optik)", ["Deneysel yöntem", "Karanlık oda"],
      "Görmek, ışığın cisimden göze gelmesidir; karanlık oda (camera obscura) deneyleriyle gösterilir. Gözlem ve deneyi sistemli kullanan ilk bilim insanlarından."),
    d("1638", "Galileo", "Padova · Arcetri", "İki Yeni Bilim Üzerine Söylemler", ["Eylemsizlik", "Serbest düşme"],
      "Eğik düzlemlerde yuvarlanan toplar: cisimler ağırlıklarından bağımsız olarak aynı ivmeyle düşer. Doğanın kitabı matematik diliyle yazılmıştır."),
    d("1687", "Newton, Principia", "Cambridge", "Principia", ["Kuvvet", "Eylemsizlik", "Kütleçekim"],
      "Üç hareket yasası ve evrensel kütleçekim: gök ile yeryüzü aynı yasalara uyar. Kalkülüs doğanın dili olur."),
    d("1824 – 1850", "Termodinamik", "Paris · Manchester · Berlin", "Carnot, Ateşin Hareket Ettirici Gücü", ["Entropi", "Enerjinin korunumu"],
      "Carnot, Joule ve Clausius: enerji korunur, entropi artar. Buhar makinesinden evrenin zaman okuna."),
    d("1865", "Maxwell", "Londra", "“Elektromanyetik Alanın Dinamik Kuramı”", ["Alan", "Elektromanyetik dalga"],
      "Dört denklem: elektrik, manyetizma ve ışık tek bir kuramda birleşir; ışık bir elektromanyetik dalgadır."),
    d("1905", "Einstein’ın mucize yılı", "Bern patent ofisi", "Annalen der Physik’teki dört makale", ["Özel görelilik", "Foton"],
      "Özel görelilik, fotoelektrik olay, Brown hareketi ve E = mc²: zaman ve uzay gözlemciye göre değişir, ışık tanecikli davranır.", s("Tanrı zar atmaz.", "Einstein, Born’a mektup, 1926")),
    d("1925 – 1927", "Kuantum mekaniği", "Göttingen · Zürih · Kopenhag", "Heisenberg, 1925; Schrödinger, 1926", ["Belirsizlik ilkesi", "Dalga fonksiyonu"],
      "Heisenberg’in matrisleri, Schrödinger’in dalgaları, Bohr’un tamamlayıcılığı: konum ve momentum aynı anda keskin bilinemez. Kopenhag yorumu tartışması başlar."),
    d("1970 – 2012", "Standart Model ve Higgs", "CERN", "ATLAS ve CMS, 4 Temmuz 2012", ["Standart Model", "Higgs alanı"],
      "Kuarklar, leptonlar ve kuvvet taşıyıcıları; parçacıklara kütle veren Higgs alanının bozonu 2012’de CERN’de bulunur. Karanlık madde ve kütleçekim hâlâ dışarıda.") ] },

  geometri: { alt: "Nil’in taşkınlarından Öklid dışı uzaylara.",
    donemler: [[0, 3, "Antik"], [4, 4, "Orta Çağ"], [5, 6, "Yeniçağ"], [7, 8, "Modern"]], duraklar: [
    d("MÖ 2. binyıl", "Mısır ve Babil", "Nil · Mezopotamya", "Rhind papirüsü; Plimpton 322", ["Pisagor üçlüsü"],
      "Nil taşkınından sonra tarlaları yeniden ölçmek (geo-metria: yer ölçümü), piramitlerin eğimi, Pisagor üçlülerinin listesi: pratik geometri."),
    d("MÖ 6. yy", "Thales ve Pisagor", "Milet · Kroton", "(Proklos’un aktarımları)", ["Kanıt (ispat)", "Oran"],
      "Geometrik önermeler ilk kez kanıtlanır; Pisagorculara göre sayı ve biçimin uyumu evrenin düzenidir. √2’nin oransızlığı bir krize yol açar."),
    d("MÖ 300", "Öklid, Elemanlar", "İskenderiye", "Stoikheia (Elemanlar), 13 kitap", ["Aksiyom", "Teorem", "Paralellik postulatı"],
      "23 tanım, 5 postulat, 5 ortak kavram ve 465 önerme: aksiyomatik yöntemin iki bin yıllık örneği.", s("Geometriye kral yolu yoktur.", "Öklid’in I. Ptolemaios’a yanıtı (Proklos)")),
    d("MÖ 3. yy", "Arşimet ve Apollonios", "Siraküza · Perge", "Küre ve Silindir Üzerine; Konikler", ["Pi (π)", "Koni kesiti"],
      "Kürenin hacmi silindirin üçte ikisi; π, 96 kenarlı çokgenlerle kuşatılır. Pergeli Apollonios elips, parabol ve hiperbolü adlandırır."),
    d("9. – 12. yy", "Sâbit b. Kurra ve Ömer Hayyam", "Bağdat · Nişabur", "Hayyam, Öklid’in Güçlükleri Üzerine", ["Paralellik postulatı"],
      "Paralellik postulatını kanıtlama denemeleri ve kübik denklemlerin konik kesitlerle geometrik çözümü."),
    d("1637", "Descartes", "Leiden", "La Géométrie", ["Koordinat sistemi"],
      "Koordinatlarla şekiller denklemlere dönüşür: analitik geometri doğar; geometri ile cebir birleşir."),
    d("1820’ler", "Lobaçevski, Bolyai, Gauss", "Kazan · Temeşvar · Göttingen", "Lobaçevski, Geometri Üzerine (1829)", ["Öklid dışı geometri"],
      "Paralellik postulatı olmadan da tutarlı bir geometri kurulabilir: bir üçgenin açıları 180°’den az olabilir.", s("Yoktan yeni ve başka bir dünya yarattım.", "Bolyai, babasına mektup, 1823")),
    d("1854 – 1872", "Riemann ve Klein", "Göttingen · Erlangen", "Riemann, Geometrinin Temelindeki Hipotezler Üzerine", ["Eğrilik", "Dönüşüm grubu"],
      "Eğri uzaylar (Einstein’ın uzay-zamanının dili) ve Erlangen programı: geometri, dönüşümler altında değişmeyenlerin incelenmesidir."),
    d("1899 – bugün", "Hilbert ve sonrası", "Göttingen", "Hilbert, Geometrinin Temelleri", ["Aksiyom", "Topoloji", "Fraktal"],
      "Tam aksiyomlaştırma (“nokta, doğru, düzlem yerine masa, sandalye, bira bardağı da diyebilmeliyiz”), topoloji, Mandelbrot’un fraktalları ve bilgisayar geometrisi.") ] },

  cografya: { alt: "Kil tabletteki dünyadan uydu haritalarına.",
    donemler: [[0, 2, "Antik"], [3, 4, "Orta Çağ ve keşifler"], [5, 7, "Yeniçağ"], [8, 8, "Uydu çağı"]], duraklar: [
    d("MÖ 6. yy", "Anaksimandros ve Hekataios", "Milet", "Hekataios, Dünyanın Betimi", ["Harita"],
      "Bilinen dünyanın ilk haritaları: Okyanus nehriyle çevrili, Delfi merkezli yuvarlak bir kara."),
    d("MÖ 3. yy", "Eratosthenes", "İskenderiye", "Geographika", ["Enlem", "Boylam"],
      "“Coğrafya” sözcüğünü kullanır; Syene’deki kuyuya düşen güneş ışığıyla Dünya’nın çevresini yaklaşık 40.000 km olarak ölçer."),
    d("MS 150", "Batlamyus, Geographia", "İskenderiye", "Geographike Hyphegesis", ["Projeksiyon (harita)"],
      "Sekiz bin yerin koordinatları ve iki harita izdüşümü; 1406’da Latinceye çevrilince Rönesans haritacılığını başlatır."),
    d("1154", "İdrîsî", "Palermo", "Nüzhetü’l-Müştâk (Tabula Rogeriana)", ["Dünya haritası"],
      "Sicilya kralı II. Roger için on beş yıllık çalışma: güneyi yukarıda gösteren, dönemin en ayrıntılı dünya haritası ve gümüş bir küre."),
    d("1300 – 1513", "Portolanlar ve Piri Reis", "Cenova · Gelibolu", "Piri Reis, Kitâb-ı Bahriye", ["Portolan", "Kerte hattı"],
      "Pusula gülleri ve kerte hatlarıyla deniz haritaları; Piri Reis’in 1513 haritası Kolomb’un kayıp haritasından yararlanarak Amerika kıyılarını gösterir."),
    d("1569", "Mercator", "Duisburg", "Nova et aucta orbis terrae descriptio", ["Projeksiyon (harita)"],
      "Pusula rotalarını düz çizgi olarak gösteren izdüşüm: denizcilerin haritası; kutuplara yaklaştıkça büyüyen Grönland’ın da nedeni."),
    d("1799 – 1859", "Humboldt ve Ritter", "Latin Amerika · Berlin", "Humboldt, Kosmos", ["Bitki coğrafyası"],
      "Chimborazo yamacında bitki kuşakları, izotermler, doğanın bir bütün olarak ölçülmesi; modern fiziki ve beşerî coğrafyanın kuruluşu."),
    d("1912", "Wegener", "Marburg", "Kıtaların ve Okyanusların Kökeni", ["Levha tektoniği"],
      "Kıyıların yapboz gibi örtüşmesi, iki kıtada aynı fosiller: kıtalar kayar. Önce reddedilir; 1960’larda levha tektoniğiyle doğrulanır."),
    d("1972 – bugün", "Uydular ve CBS", "Yörünge", "Landsat 1 (1972)", ["CBS", "Uzaktan algılama"],
      "Landsat, GPS ve coğrafi bilgi sistemleri: harita artık canlı, katmanlı bir veritabanıdır.") ] },

  film: { alt: "Koşan attan Altın Palmiye’ye: hareketli görüntünün kısa tarihi.",
    donemler: [[0, 2, "Doğuş"], [3, 4, "Sessizden sesliye"], [5, 7, "Modern sinema"], [8, 8, "Dijital"]], duraklar: [
    d("1878", "Muybridge’in atı", "Palo Alto", "The Horse in Motion", ["Kronofotografi"],
      "On iki kamera, koşan bir at: dört ayağın aynı anda yerden kesildiği an ilk kez görünür olur."),
    d("1895", "Lumière kardeşler", "Paris · Grand Café", "L’arrivée d’un train en gare de La Ciotat", ["Sinematograf"],
      "28 Aralık 1895: ilk halka açık, paralı sinema gösterimi. Trenin gara girişi efsanesi doğar."),
    d("1902", "Méliès, Ay’a Yolculuk", "Montreuil", "Le Voyage dans la Lune", ["Mizansen", "Hileli çekim"],
      "Sihirbaz Méliès’in stüdyosunda hileli çekimler: sinema belgelemekten düş kurmaya geçer; roket Ay’ın gözüne saplanır."),
    d("1920 – 1925", "Dışavurumculuk ve montaj", "Berlin · Moskova", "Dr. Caligari’nin Muayenehanesi; Potemkin Zırhlısı", ["Montaj", "Kuleşov etkisi"],
      "Caligari’nin eğri dekorları ve Eisenstein’ın Odessa merdivenleri: çekimlerin art arda gelişi yeni bir anlam üretir."),
    d("1927", "Sesli sinema", "Hollywood", "The Jazz Singer", ["Senkron ses"],
      "“Bir dakika bekleyin, henüz bir şey duymadınız!”: konuşan film. Sessiz dönemin görsel dili yeni bir ses dünyasıyla buluşur."),
    d("1941 – 1948", "Kane ve yeni gerçekçilik", "Hollywood · Roma", "Yurttaş Kane; Bisiklet Hırsızları", ["Derin odak"],
      "Welles’in derin odak çekimleri ve alçak kamera açıları; savaş sonrası İtalya’da sokakta, amatör oyuncularla çekilen filmler."),
    d("1959 – 1970’ler", "Yeni Dalga ve yazar sineması", "Paris · Stockholm · Moskova", "Serseri Aşıklar; Yedinci Mühür; Ayna", ["Auteur", "Zaman-imge"],
      "Godard, Truffaut, Bergman, Tarkovski: yönetmen bir yazar gibi kendi dilini kurar.", s("Sinema saniyede yirmi dört kare hakikattir.", "Godard, Le Petit Soldat (1963)")),
    d("1950 – 2014", "Türkiye’de sinema", "İstanbul · Cannes", "Yol (1982); Kış Uykusu (2014)", ["Yeşilçam"],
      "Yeşilçam’ın altın yılları, Metin Erksan’ın Susuz Yaz’ı (Berlin 1964), Yılmaz Güney’in Yol’u ve Nuri Bilge Ceylan’ın Kış Uykusu ile gelen Altın Palmiye."),
    d("1983 – bugün", "Film felsefesi ve dijital çağ", "—", "Deleuze, Sinema 1–2; Cavell, The World Viewed", ["Hareket-imge", "Zaman-imge"],
      "Deleuze’ün hareket-imge ve zaman-imgesi, Cavell’in denemeleri; dijital kamera, bilgisayar görüntüsü ve akış platformları.") ] }
  };
})();
