/* HARİTALAR — her alt sahnede başlığın solundaki "… haritası": konunun tarihine kuşbakışı bir yolculuk.
   Her durak { yil, ad, metin }. Durak eklemek/çıkarmak için listeye bir satır ekle; harita kendini yeniden düzenler.
   Metinlerde sözlükçede olan terimler kendiliğinden işaretlenir (üzerine gelince tanım çıkar). */
window.HARITA = {
  epistemoloji: { alt: "Antik Yunan’dan Gettier’ye: “bilgi nedir?” sorusunun yolculuğu.", duraklar: [
    { yil: "MÖ 5. yy", ad: "Sofistler ve Sokrates", metin: "Protagoras “insan her şeyin ölçüsüdür” der; Sokrates ise bilmediğini bilmenin bilgeliğin başı olduğunu gösterir. Bilgi ile kanı ayrımı doğar." },
    { yil: "MÖ 369", ad: "Platon, Theaitetos", metin: "Bilgi algı mıdır, doğru kanı mı, yoksa gerekçesi verilmiş doğru kanı mı? Diyalog bir sonuca varmadan (aporia) biter; ama epistemolojinin sorusu artık konmuştur." },
    { yil: "MÖ 375", ad: "Platon, Devlet: Mağara", metin: "Gölgelerden ateşe, ateşten güneşe: kanıdan (doxa) bilgiye (episteme) yükseliş. Bölünmüş çizgi benzetmesi bilginin basamaklarını gösterir." },
    { yil: "MÖ 4. yy", ad: "Aristoteles, İkinci Analitikler", metin: "Bilimsel bilgi kanıtlamaya dayanır; kanıtlamanın dayandığı ilk ilkeler ise tümevarım ve akılla (nous) kavranır. Temelcilik fikrinin ilk biçimi." },
    { yil: "MÖ 3. yy – MS 2. yy", ad: "Antik şüphecilik", metin: "Pyrrhon, Arkesilaos, Karneades ve Sekstos Empirikos: her savın karşısına eşit güçte bir sav konabiliyorsa yargıyı askıya almak (epokhe) gerekir." },
    { yil: "1641", ad: "Descartes, Meditasyonlar", metin: "Yöntemsel şüphe: duyular, düşler, kötü cin. Geriye kalan tek kesinlik: “Düşünüyorum, öyleyse varım.” Bilgi sarsılmaz bir temele oturtulmak istenir." },
    { yil: "1690 – 1748", ad: "Locke, Berkeley, Hume", metin: "Empiristler: zihin boş bir levhadır, bilgi deneyimden gelir. Hume tümevarımın ve nedenselliğin akılla temellendirilemeyeceğini gösterir." },
    { yil: "1781", ad: "Kant, Saf Aklın Eleştirisi", metin: "Sentetik a priori yargılar nasıl mümkündür? Kopernikçi devrim: nesneler bilgimize uyar; uzay, zaman ve kategoriler deneyimin koşullarıdır." },
    { yil: "1963", ad: "Gettier’nin iki sayfası", metin: "“Gerekçelendirilmiş doğru inanç bilgi midir?” Gettier’nin karşı örnekleri, şans eseri doğru çıkan gerekçeli inançların bilgi sayılamayacağını gösterir." },
    { yil: "1969 – bugün", ad: "Çağdaş epistemoloji", metin: "Quine’in doğallaştırılmış epistemolojisi, Goldman’ın güvenilirciliği, içselcilik–dışsalcılık tartışması, erdem ve toplumsal epistemoloji." } ] },
  metafizik: { alt: "İlk ilkeden olmayan nesnelere: varlık sorusunun izinde.", duraklar: [
    { yil: "MÖ 6. yy", ad: "Thales ve İyonyalılar", metin: "Her şeyin ilkesi (arkhe) nedir? Su, apeiron, hava: değişen dünyanın altında kalıcı bir şey aranır." },
    { yil: "MÖ 5. yy", ad: "Parmenides ve Herakleitos", metin: "“Olan vardır, olmayan yoktur” ile “her şey akar” karşı karşıya: varlık ile oluşun büyük gerilimi." },
    { yil: "MÖ 4. yy", ad: "Platon ve Aristoteles", metin: "Platon’un idealar dünyası; Aristoteles’in “varlık olmak bakımından varlık” bilimi: töz, dört neden, madde ve form, ilk hareket ettiren." },
    { yil: "11. – 13. yy", ad: "İbn Sînâ ve Aquinas", metin: "Varlık ile mahiyetin ayrımı, zorunlu ve mümkün varlık. İbn Sînâ’nın ayrımı Latin dünyasında Aquinas’ın metafiziğine yön verir." },
    { yil: "1641 – 1714", ad: "Descartes, Spinoza, Leibniz", metin: "İki töz, tek töz, sonsuz monadlar: yeniçağ rasyonalizmi tözün ne olduğunu yeniden sorar." },
    { yil: "1781", ad: "Kant’ın sınırları", metin: "Kendinde şeyler bilinemez; metafizik, aklın deneyimi aşan sorulara yönelik doğal ama sınırlanması gereken eğilimidir." },
    { yil: "1904 – 1905", ad: "Meinong ve Russell", metin: "Meinong: yuvarlak kare gibi olmayan nesneler de nesnedir. Russell “On Denoting”de betimlemeler kuramıyla bu nesnelerden kurtulmak ister." },
    { yil: "1948", ad: "Quine, “Ne Var?”", metin: "Ontolojik bağlanma ölçütü: “var olmak, bağlı bir değişkenin değeri olmaktır.” Hangi şeylerin var olduğunu en iyi kuramlarımız söyler." },
    { yil: "1970 – 1986", ad: "Kripke ve Lewis", metin: "Zorunluluk ve olası dünyalar: Kripke’nin katı göstericileri, Lewis’in modal gerçekçiliği. Modal metafizik yeniden merkezde." },
    { yil: "Bugün", ad: "Soyut nesneler ve temellendirme", metin: "Sayılar ve kurgusal karakterler var mı? Temellendirme, meta-metafizik ve Meinongçuluğun dönüşü (Parsons, Zalta, Priest, Berto)." } ] },
  zihin: { alt: "Ruhtan beyne, beyinden bilince: zihin–beden sorununun haritası.", duraklar: [
    { yil: "MÖ 4. yy", ad: "Aristoteles, Ruh Üzerine", metin: "Ruh canlı bedenin formudur; balmumu ile üzerindeki mühür gibi, beden ile ruhun bir olup olmadığını sormak gereksizdir." },
    { yil: "1641", ad: "Descartes’ın ikiciliği", metin: "Düşünen şey ile yer kaplayan şey iki ayrı tözdür. Peki nasıl etkileşirler? Epifiz bezi yanıtı kimseyi doyurmaz." },
    { yil: "1670 – 1714", ad: "Spinoza, Malebranche, Leibniz", metin: "Paralelizm, vesilecilik, önceden kurulmuş uyum: etkileşim sorununa rasyonalist çözümler." },
    { yil: "1949", ad: "Ryle, “Makinedeki hayalet”", metin: "Zihin ayrı bir nesne değil, davranış eğilimlerimizdir; Kartezyen görüş bir kategori yanlışıdır. Davranışçılık yükselir." },
    { yil: "1950 – 1959", ad: "Turing ve özdeşlik kuramı", metin: "Turing makinelerin düşünüp düşünemeyeceğini sorar; Place ve Smart zihinsel durumların beyin durumlarıyla özdeş olduğunu savunur." },
    { yil: "1967", ad: "Putnam ve işlevselcilik", metin: "Acı, beyindeki belirli bir madde değil, bir işlevdir; farklı malzemelerde gerçekleşebilir (çoklu gerçekleşebilirlik)." },
    { yil: "1974 – 1982", ad: "Yarasa ve Mary", metin: "Nagel: yarasa olmak nasıl bir şeydir? Jackson: renkleri hiç görmemiş bilim insanı Mary kırmızıyı görünce yeni bir şey öğrenir mi? Nitelik (qualia) sorunu." },
    { yil: "1980", ad: "Searle’ün Çin odası", metin: "Kuralları izleyerek simgeleri işlemek anlamak mıdır? Sözdizimi anlambilime yetmez; güçlü yapay zekâya itiraz." },
    { yil: "1995", ad: "Chalmers’ın zor problemi", metin: "Beynin işlevlerini açıklamak kolay problemdir; bu işlevlere neden bir deneyimin eşlik ettiği zor problemdir. Felsefi zombiler." },
    { yil: "Bugün", ad: "Bilinç kuramları ve yapay zekâ", metin: "Küresel çalışma alanı, bütünleşik bilgi kuramı, 4E biliş ve büyük dil modelleri: bilinç ölçülebilir mi, makinelerde olabilir mi?" } ] },
  latince: { alt: "Latium’un köylerinden bilimin ve hukukun ortak diline.", duraklar: [
    { yil: "MÖ 8. yy", ad: "Latium ve Roma", metin: "Latince, Tiber kıyısındaki Latium bölgesinin İtalik dilidir; efsaneye göre Roma MÖ 753’te kurulur." },
    { yil: "MÖ 7. – 6. yy", ad: "İlk yazıtlar", metin: "Lapis Niger ve Praeneste fibulası: Etrüskler aracılığıyla Yunan alfabesinden gelen harflerle yazılmış en eski Latince." },
    { yil: "MÖ 3. – 2. yy", ad: "Eski Latince", metin: "Plautus ve Terentius’un komedyaları; Yunan edebiyatı Latinceye aktarılmaya başlar." },
    { yil: "MÖ 1. yy", ad: "Altın Çağ", metin: "Cicero’nun söylevleri, Caesar’ın düzyazısı, Vergilius’un Aeneis’i: Klasik Latincenin ölçüsü bu yüzyılda konur." },
    { yil: "MS 1. – 2. yy", ad: "Gümüş Çağ", metin: "Seneca, Tacitus, Plinius: daha yoğun ve süslü bir üslup; imparatorluk Latincesi Akdeniz’in her yanında konuşulur." },
    { yil: "MS 4. – 5. yy", ad: "Geç Latince", metin: "Hieronymus’un Vulgata’sı, Augustinus’un İtirafları. Halk Latincesi (sermo vulgaris) Roman dillerinin tohumu olur." },
    { yil: "9. yy", ad: "Karolenj Rönesansı", metin: "Alcuin ve Şarlman’ın okulları metinleri düzeltir; bugünkü küçük harflerin atası olan Karolenj yazısı doğar." },
    { yil: "12. – 15. yy", ad: "Skolastik Latince", metin: "Üniversitelerin dili: Aquinas’ın Summa’sı, çevirilerle gelen Aristoteles ve Arap felsefesi. Teknik felsefe terimleri Latincede şekillenir." },
    { yil: "15. – 17. yy", ad: "Hümanizm ve bilim", metin: "Petrarca ve Erasmus Cicero’nun Latincesine döner; Kopernik, Kepler ve Newton’un Principia’sı (1687) Latince yazılır." },
    { yil: "Bugün", ad: "Yaşayan miras", metin: "Linnaeus’un ikili adlandırması, hukuk ve tıp terimleri, Vatikan: Latince, konuşanı az ama izi her yerde bir dildir." } ] },
  yunanca: { alt: "Linear B tabletlerinden Platon’un Attikasına ve bugüne.", duraklar: [
    { yil: "MÖ 1450", ad: "Linear B", metin: "Miken sarayların hesap tabletleri: bilinen en eski Yunanca. Hece yazısı 1952’de Michael Ventris tarafından çözüldü." },
    { yil: "MÖ 8. yy", ad: "Alfabe ve Homeros", metin: "Fenike harflerine ünlüler eklenerek ilk gerçek alfabe doğar. İlyada ve Odysseia yazıya geçer." },
    { yil: "MÖ 5. – 4. yy", ad: "Attika Yunancası", metin: "Tragedyacılar, Thukydides, Platon ve Aristoteles: felsefenin dili. Felsefi kavramların çoğu bu dönemin sözcükleridir." },
    { yil: "MÖ 4. yy – MS 4. yy", ad: "Koine", metin: "İskender’in fetihleriyle ortak dil olur; Septuaginta ve Yeni Ahit bu “ortak” Yunancayla yazılır." },
    { yil: "4. – 15. yy", ad: "Bizans Yunancası", metin: "Konstantinopolis’te bin yıl boyunca antik metinler kopyalanır, yorumlanır ve korunur." },
    { yil: "1397 – 1453", ad: "İtalya’ya göç", metin: "Manuel Khrysoloras Floransa’da Yunanca öğretir; İstanbul’un fethiyle bilginler ve elyazmaları Rönesans İtalyası’na ulaşır." },
    { yil: "19. yy", ad: "Dil sorunu", metin: "Arılaştırılmış Katharevousa ile halkın dili Dimotiki arasındaki uzun tartışma." },
    { yil: "1976 – 1982", ad: "Modern Yunanca", metin: "Dimotiki resmî dil olur; tek vurgulu (monotonik) yazıma geçilir. Antik Yunanca okullarda ayrı bir ders olarak kalır." } ] },
  arapca: { alt: "Çöl şiirinden Beytülhikme’ye, oradan modern Arapçaya.", duraklar: [
    { yil: "328", ad: "Nemâra yazıtı", metin: "Nebati harfleriyle yazılmış erken Arapça: “bütün Arapların kralı” İmruülkays’ın mezar taşı." },
    { yil: "6. yy", ad: "Cahiliye şiiri", metin: "Muallakât: Kâbe’ye asıldığı söylenen yedi uzun kaside. Arap dilinin şiirsel zenginliğinin ilk büyük tanığı." },
    { yil: "7. yy", ad: "Kur’an ve yazının düzenlenmesi", metin: "Dil standartlaşır; Ebü’l-Esved ed-Düelî’ye atfedilen noktalama ve hareke sistemi okumayı güvenceye alır." },
    { yil: "8. yy", ad: "Basra ve Kûfe okulları", metin: "Halîl b. Ahmed ilk sözlüğü (Kitâbü’l-Ayn), Sîbeveyhi ilk büyük dilbilgisini (el-Kitâb) yazar." },
    { yil: "830 civarı", ad: "Beytülhikme", metin: "Bağdat’ta Huneyn b. İshak ve çevresi Aristoteles, Galenos ve Öklid’i Arapçaya çevirir; Arapça bilimin dili olur." },
    { yil: "9. – 10. yy", ad: "Kindî ve Fârâbî", metin: "“Arapların filozofu” Kindî ve “ikinci öğretmen” Fârâbî Yunan felsefesini Arapça düşünür, mantık terimlerini kurar." },
    { yil: "11. – 12. yy", ad: "İbn Sînâ, Gazzâlî, İbn Rüşd", metin: "Felsefenin doruğu ve eleştirisi. Toledo’daki çeviriler bu eserleri Latince aracılığıyla Avrupa’ya taşır." },
    { yil: "19. yy", ad: "Nahda", metin: "Uyanış hareketi: matbaa, gazeteler, sözlükler. Modern Standart Arapça biçimlenir." },
    { yil: "Bugün", ad: "Fushâ ve lehçeler", metin: "Yazıda ortak Modern Standart Arapça, gündelik hayatta bölgesel lehçeler: 400 milyonu aşkın konuşur." } ] },
  biyoloji: { alt: "Aristoteles’in hayvanlarından CRISPR’a: yaşamı anlama serüveni.", duraklar: [
    { yil: "MÖ 4. yy", ad: "Aristoteles", metin: "Hayvanların Tarihi: yüzlerce türü gözlemler, sınıflandırır; biyolojinin ilk sistemli çalışması." },
    { yil: "MS 2. yy", ad: "Galenos", metin: "Anatomi ve fizyoloji; yaklaşık 1400 yıl boyunca tıbbın otoritesi olarak kalır." },
    { yil: "1665 – 1676", ad: "Hooke ve Leeuwenhoek", metin: "Mikroskop altında mantar dokusundaki “hücreler” ve bir damla sudaki “küçük hayvancıklar”." },
    { yil: "1735 – 1753", ad: "Linnaeus", metin: "Systema Naturae ve ikili adlandırma: her canlıya bir cins ve tür adı (Homo sapiens)." },
    { yil: "1838 – 1855", ad: "Hücre kuramı", metin: "Schleiden ve Schwann: bütün canlılar hücrelerden oluşur. Virchow: her hücre bir hücreden gelir." },
    { yil: "1859", ad: "Darwin ve Wallace", metin: "Türlerin Kökeni: doğal seçilimle evrim. Yaşamın çeşitliliği ortak atadan dallanan bir ağaçtır." },
    { yil: "1866", ad: "Mendel", metin: "Bezelyelerle kalıtımın yasaları; 1900’de yeniden keşfedilince genetiğin temeli olur." },
    { yil: "1953", ad: "DNA’nın çift sarmalı", metin: "Watson ve Crick, Rosalind Franklin ile Wilkins’in verilerine dayanarak DNA’nın yapısını ortaya koyar." },
    { yil: "2003 – 2012", ad: "Genom ve CRISPR", metin: "İnsan Genom Projesi tamamlanır; Doudna ve Charpentier genleri kesip düzenleyen CRISPR-Cas9’u geliştirir." } ] },
  astronomi: { alt: "Babil kulelerinden James Webb’e: göğün haritası.", duraklar: [
    { yil: "MÖ 2. binyıl", ad: "Babil gökbilimi", metin: "Gezegenlerin hareketleri kil tabletlere yazılır; takvimler ve tutulma tahminleri." },
    { yil: "MÖ 3. yy", ad: "Aristarkhos ve Eratosthenes", metin: "Güneş merkezli ilk öneri; Eratosthenes gölge boylarıyla Dünya’nın çevresini şaşırtıcı bir doğrulukla ölçer." },
    { yil: "MS 150", ad: "Batlamyus, Almagest", metin: "Dünya merkezli, dış merkezli çemberler ve episikllerle göğün matematiksel modeli; 1400 yıl kullanılır." },
    { yil: "9. – 15. yy", ad: "İslam dünyasında gökbilim", metin: "Bettânî, Abdurrahman es-Sûfî’nin yıldız kataloğu, Merâga ve Uluğ Bey’in Semerkant rasathanesi." },
    { yil: "1543", ad: "Kopernik", metin: "De revolutionibus: Güneş merkeze, Dünya gezegenlerin arasına taşınır." },
    { yil: "1609 – 1610", ad: "Kepler ve Galileo", metin: "Eliptik yörüngeler; teleskopla Jüpiter’in uyduları, Venüs’ün evreleri ve Ay’ın dağları." },
    { yil: "1687", ad: "Newton", metin: "Evrensel kütleçekim: elmayı düşüren kuvvet Ay’ı yörüngede tutar." },
    { yil: "1915 – 1929", ad: "Einstein ve Hubble", metin: "Genel görelilik uzay-zamanı büker; Hubble gökadaların uzaklaştığını, evrenin genişlediğini gösterir." },
    { yil: "1965", ad: "Kozmik arka plan ışıması", metin: "Penzias ve Wilson’ın antenindeki uğultu: Büyük Patlama’nın yankısı." },
    { yil: "2015 – bugün", ad: "Yeni gözler", metin: "Kütleçekim dalgaları (LIGO), bir kara deliğin ilk görüntüsü (2019) ve James Webb Uzay Teleskobu." } ] },
  fizik: { alt: "Kaldıraçtan Higgs bozonuna: doğanın yasalarının peşinde.", duraklar: [
    { yil: "MÖ 3. yy", ad: "Arşimet", metin: "Kaldıraç ve kaldırma kuvveti: “Bana bir dayanak noktası verin, Dünya’yı yerinden oynatayım.”" },
    { yil: "1011 – 1021", ad: "İbn Heysem", metin: "Kitâbü’l-Menâzır: görmenin ışığın göze girmesiyle olduğunu deneylerle gösterir; deneysel yöntemin öncüsü." },
    { yil: "1638", ad: "Galileo", metin: "Eğik düzlemler ve serbest düşme: cisimler, ağırlıklarından bağımsız olarak aynı ivmeyle düşer." },
    { yil: "1687", ad: "Newton, Principia", metin: "Üç hareket yasası ve evrensel kütleçekim: gök ile yeryüzü aynı yasalara uyar." },
    { yil: "1824 – 1850", ad: "Termodinamik", metin: "Carnot, Joule ve Clausius: enerji korunur, entropi artar; buhar makinesinden evrenin okuna." },
    { yil: "1865", ad: "Maxwell", metin: "Elektrik, manyetizma ve ışık tek bir kuramda birleşir: ışık bir elektromanyetik dalgadır." },
    { yil: "1905", ad: "Einstein’ın mucize yılı", metin: "Özel görelilik, fotoelektrik olay, Brown hareketi ve E = mc²." },
    { yil: "1925 – 1927", ad: "Kuantum mekaniği", metin: "Heisenberg, Schrödinger, Bohr: olasılık dalgaları ve belirsizlik ilkesi. Kopenhag yorumu tartışması başlar." },
    { yil: "1970 – 2012", ad: "Standart Model ve Higgs", metin: "Temel parçacıklar ve kuvvetlerin kuramı; 2012’de CERN’de Higgs bozonunun keşfiyle taçlanır." } ] },
  geometri: { alt: "Nil’in taşkınlarından Öklid dışı uzaylara.", duraklar: [
    { yil: "MÖ 2. binyıl", ad: "Mısır ve Babil", metin: "Tarla ölçümü, piramitler, Plimpton 322 tableti: pratik geometri ve Pisagor üçlüleri." },
    { yil: "MÖ 6. yy", ad: "Thales ve Pisagor", metin: "Geometrik önermeler ilk kez kanıtlanır; sayı ve biçimin uyumu bir dünya görüşüne dönüşür." },
    { yil: "MÖ 300", ad: "Öklid, Elemanlar", metin: "Tanımlar, beş postulat ve ortak kavramlardan yüzlerce önerme: aksiyomatik yöntemin iki bin yıllık örneği." },
    { yil: "MÖ 3. yy", ad: "Arşimet ve Apollonios", metin: "Kürenin hacmi, π’nin yaklaşık değeri; Konikler ile elips, parabol ve hiperbol." },
    { yil: "9. – 12. yy", ad: "Sâbit b. Kurra ve Ömer Hayyam", metin: "Paralellik postulatını kanıtlama denemeleri, cebirsel denklemlerin geometrik çözümü." },
    { yil: "1637", ad: "Descartes", metin: "La Géométrie: koordinatlarla şekiller denklemlere dönüşür; analitik geometri doğar." },
    { yil: "1820’ler", ad: "Lobaçevski, Bolyai, Gauss", metin: "Paralellik postulatı olmadan da tutarlı bir geometri kurulabilir: Öklid dışı geometriler." },
    { yil: "1854 – 1872", ad: "Riemann ve Klein", metin: "Eğri uzaylar ve Erlangen programı: geometri, dönüşümler altında değişmeyenlerin incelenmesidir." },
    { yil: "1899 – bugün", ad: "Hilbert ve sonrası", metin: "Geometrinin Temelleri ile tam aksiyomlaştırma; topoloji, fraktallar ve bilgisayar geometrisi." } ] },
  cografya: { alt: "Kil tabletteki dünyadan uydu haritalarına.", duraklar: [
    { yil: "MÖ 6. yy", ad: "Anaksimandros ve Hekataios", metin: "Bilinen dünyanın ilk haritaları: Okyanus nehriyle çevrili yuvarlak bir kara." },
    { yil: "MÖ 3. yy", ad: "Eratosthenes", metin: "“Coğrafya” sözcüğünü kullanır; Dünya’nın çevresini ölçer ve enlem–boylam fikrine yaklaşır." },
    { yil: "MS 150", ad: "Batlamyus, Geographia", metin: "Sekiz bin yerin koordinatları ve harita izdüşümleri; Rönesans’ta yeniden keşfedilir." },
    { yil: "1154", ad: "İdrîsî", metin: "Sicilya kralı II. Roger için Tabula Rogeriana: dönemin en ayrıntılı dünya haritası." },
    { yil: "1300 – 1513", ad: "Portolanlar ve Piri Reis", metin: "Pusula gülleri ve kerte hatlarıyla deniz haritaları; Piri Reis’in 1513 haritası Amerika kıyılarını gösterir." },
    { yil: "1569", ad: "Mercator", metin: "Pusula rotalarını düz çizgi olarak gösteren izdüşüm: denizcilerin haritası, bugünkü web haritalarının atası." },
    { yil: "1799 – 1859", ad: "Humboldt ve Ritter", metin: "Doğayı bir bütün olarak ölçen yolculuklar, Kosmos; modern fiziki ve beşerî coğrafyanın kuruluşu." },
    { yil: "1912", ad: "Wegener", metin: "Kıtaların kayması: kıyıların yapboz gibi örtüşmesi rastlantı değildir; levha tektoniğine giden yol." },
    { yil: "1972 – bugün", ad: "Uydular ve CBS", metin: "Landsat, GPS ve coğrafi bilgi sistemleri: harita artık canlı, katmanlı bir veritabanıdır." } ] },
  film: { alt: "Koşan attan Altın Palmiye’ye: hareketli görüntünün kısa tarihi.", duraklar: [
    { yil: "1878", ad: "Muybridge’in atı", metin: "Koşan bir atın ardışık fotoğrafları: dört ayağın aynı anda yerden kesildiği an görünür olur." },
    { yil: "1895", ad: "Lumière kardeşler", metin: "Paris’te Grand Café’de ilk halka açık, paralı sinema gösterimi; trenin gara girişi." },
    { yil: "1902", ad: "Méliès, Ay’a Yolculuk", metin: "Sihirbaz Méliès’in hileli çekimleri: sinema belgelemekten düş kurmaya geçer." },
    { yil: "1920 – 1925", ad: "Dışavurumculuk ve montaj", metin: "Dr. Caligari’nin Muayenehanesi’nin eğri dekorları; Eisenstein’ın Potemkin Zırhlısı’nda montajın gücü." },
    { yil: "1927", ad: "Sesli sinema", metin: "Caz Şarkıcısı ile konuşan film; sessiz dönemin görsel dili yeni bir ses dünyasıyla buluşur." },
    { yil: "1941 – 1948", ad: "Kane ve yeni gerçekçilik", metin: "Yurttaş Kane’in derin odak çekimleri; İtalya’da sokakta, amatör oyuncularla Bisiklet Hırsızları." },
    { yil: "1959 – 1970’ler", ad: "Yeni Dalga ve yazar sineması", metin: "Godard, Truffaut, Bergman, Tarkovski: yönetmen bir yazar gibi kendi dilini kurar." },
    { yil: "1950 – 2014", ad: "Türkiye’de sinema", metin: "Yeşilçam’ın altın yılları, Yılmaz Güney’in Yol’u ve Nuri Bilge Ceylan’ın Kış Uykusu ile gelen Altın Palmiye." },
    { yil: "1983 – bugün", ad: "Film felsefesi ve dijital çağ", metin: "Deleuze’ün hareket-imge ve zaman-imgesi, Cavell’in denemeleri; dijital kamera ve akış platformları." } ] }
};
