/* SÖZLÜKÇE — her alanın terimleri. Yeni terim eklemek için ilgili listeye bir satır ekle:
     { terim: "Terim", koken: "Köken (isteğe bağlı)", aciklama: "Tanım.", ornek: "Örnek ya da not (isteğe bağlı)" }
   Sıralama sahnede kendiliğinden alfabetik yapılır. */
window.SOZLUKCE = {
  felsefe: [
    { terim: "A priori", koken: "Lat. “öncekinden”", aciklama: "Deneyimden bağımsız olarak bilinebilen. Bir önermenin doğruluğu, dünyaya bakmadan, yalnızca akılla kavranabiliyorsa a priori bilinir.", ornek: "“Bütün bekârlar evli değildir.” · “7 + 5 = 12.”" },
    { terim: "A posteriori", koken: "Lat. “sonrakinden”", aciklama: "Ancak deneyim ve gözlemle bilinebilen.", ornek: "“Su 100 °C'de kaynar (deniz seviyesinde).”" },
    { terim: "Analitik ve sentetik", aciklama: "Kant'ın ayrımı: analitik yargıda yüklem öznenin kavramında zaten içerilir; sentetik yargı özne kavramına yeni bir şey ekler. Kant'a göre matematik a priori sentetik yargılardan oluşur." },
    { terim: "Diyalektik", koken: "Yun. dialektikē, “tartışma sanatı”", aciklama: "Platon'da soru-cevapla hakikate yükselme yöntemi; Hegel'de düşüncenin ve gerçekliğin çelişkiler aracılığıyla gelişmesi." },
    { terim: "Doxa", koken: "Yun. δόξα", aciklama: "Sanı, kanı. Platon'da gerekçesi kavranmamış, değişken görünüşlere dayanan inanç; bilginin (epistēmē) karşıtı." },
    { terim: "Empirizm", koken: "Yun. empeiria, “deneyim”", aciklama: "Bütün kavramların ve bilginin deneyimden geldiğini savunan görüş. Başlıca temsilcileri: Locke, Berkeley, Hume." },
    { terim: "Epistemoloji", koken: "Yun. epistēmē (bilgi) + logos", aciklama: "Bilgi felsefesi: bilginin doğasını, kaynaklarını, sınırlarını ve gerekçelendirmeyi inceler." },
    { terim: "Fenomenoloji", koken: "Yun. phainomenon, “görünen”", aciklama: "Husserl'in kurduğu, bilinç deneyimlerini ve onlarda nesnelerin nasıl göründüğünü önyargısız biçimde betimlemeyi amaçlayan yöntem ve akım." },
    { terim: "İdea (form)", koken: "Yun. eidos, idea", aciklama: "Platon'da değişen duyusal şeylerin örnek aldığı, değişmez, akılla kavranan asıl gerçeklik." },
    { terim: "Kategori", koken: "Yun. katēgoria, “yükleme”", aciklama: "Varlığa ya da düşünceye dair en genel sınıflar. Aristoteles on kategori sayar (töz, nicelik, nitelik, ilişki…); Kant'ta anlama yetisinin on iki saf kavramı." },
    { terim: "Modalite", koken: "Lat. modus, “kip”", aciklama: "Zorunluluk, olanak ve olumsallık gibi kavramlar. “Zorunlu olarak doğru”, “olanaklı olarak doğru” ayrımlarını inceler; olası dünyalar semantiğiyle çözümlenir." },
    { terim: "Nominalizm", koken: "Lat. nomen, “ad”", aciklama: "Tümellerin (kırmızılık, insanlık) ayrı gerçeklikleri olmadığını, yalnızca tekil şeylerin var olduğunu ve tümellerin addan ibaret olduğunu savunan görüş." },
    { terim: "Olmayan nesne", aciklama: "Var olmadığı hâlde hakkında düşünülebilen ve konuşulabilen nesne: altın dağ, Sherlock Holmes, yuvarlak kare. Meinong'un nesne kuramının merkezî kavramı." },
    { terim: "Ontoloji", koken: "Yun. on, ontos (varolan) + logos", aciklama: "Varlık bilimi: neyin var olduğunu ve var olanların temel türlerini inceler. Terim 17. yüzyılda ortaya çıktı." },
    { terim: "Qualia", koken: "Lat. qualis, “ne tür”", aciklama: "Bilinçli deneyimlerin öznel, niteliksel yanı: kırmızıyı görmenin, kahvenin tadının “nasıl bir şey olduğu”." },
    { terim: "Rasyonalizm", koken: "Lat. ratio, “akıl”", aciklama: "Bilginin temel kaynağının akıl olduğunu ve bazı bilgilerin a priori olarak edinilebileceğini savunan görüş: Descartes, Spinoza, Leibniz." },
    { terim: "Teleoloji", koken: "Yun. telos (amaç) + logos", aciklama: "Doğayı ve olayları amaçlar ya da erekler üzerinden açıklama. Aristoteles'in ereksel nedeni." },
    { terim: "Töz", koken: "Yun. ousia; Lat. substantia", aciklama: "Kendi başına var olan, niteliklerin taşıyıcısı olan şey. Aristoteles'te birincil tözler tekil varlıklardır (şu insan, şu at)." },
    { terim: "Tümel", aciklama: "Birden çok tekil şeyde ortak olarak bulunabilen özellik ya da tür: kırmızılık, üçgenlik, insanlık. Tümellerin varlık durumu felsefenin en eski tartışmalarındandır." }
  ],
  doga: [
    { terim: "Atom", koken: "Yun. atomos, “bölünemez”", aciklama: "Kimyasal elementlerin en küçük birimi: proton ve nötronlardan oluşan bir çekirdek ile çevresindeki elektronlar. Adına rağmen bölünebilir." },
    { terim: "DNA", aciklama: "Deoksiribonükleik asit: canlıların kalıtsal bilgisini dört bazın (A, T, G, C) dizilişiyle taşıyan çift sarmal molekül. Yapısı 1953'te açıklandı." },
    { terim: "Ekosistem", aciklama: "Bir bölgedeki canlılar ile onları çevreleyen cansız ortamın (su, toprak, iklim) madde ve enerji alışverişi içindeki bütünü." },
    { terim: "Entropi", aciklama: "Bir sistemin düzensizliğinin ölçüsü; termodinamiğin ikinci yasasına göre yalıtılmış sistemlerde azalmaz. Boltzmann: S = k log W." },
    { terim: "Evrim", aciklama: "Canlı topluluklarının kalıtsal özelliklerinin kuşaklar boyunca değişmesi. Başlıca mekanizmaları doğal seçilim, mutasyon, gen akışı ve genetik sürüklenmedir." },
    { terim: "Fotosentez", aciklama: "Bitkilerin, alglerin ve bazı bakterilerin ışık enerjisini kullanarak karbondioksit ve sudan şeker ve oksijen üretmesi." },
    { terim: "Gen", aciklama: "Kalıtımın temel birimi: bir özelliğin (çoğunlukla bir proteinin) üretimi için gerekli bilgiyi taşıyan DNA bölümü." },
    { terim: "Hücre", koken: "İng. cell, Lat. cella, “küçük oda”", aciklama: "Canlılığın en küçük yapı ve işlev birimi. Her hücre bir başka hücreden gelir." },
    { terim: "Işık yılı", aciklama: "Işığın bir yılda boşlukta aldığı yol; yaklaşık 9,46 trilyon km. Bir zaman değil, uzaklık birimidir." },
    { terim: "Kara delik", aciklama: "Kütleçekiminin o kadar güçlü olduğu bir uzay-zaman bölgesi ki, olay ufkunu geçen hiçbir şey, ışık bile, geri dönemez." },
    { terim: "Kuvvet", aciklama: "Bir cismin hareket durumunu değiştiren etki. Newton'un ikinci yasası: F = m·a. Doğada bilinen dört temel kuvvet: kütleçekimi, elektromanyetizma, zayıf ve güçlü çekirdek kuvvetleri." },
    { terim: "Mutasyon", koken: "Lat. mutare, “değiştirmek”", aciklama: "DNA dizisinde kalıcı değişiklik. Çoğu etkisizdir; bazıları zararlı, azı yararlıdır. Evrimin ham malzemesidir." },
    { terim: "Süpernova", aciklama: "Kütleli bir yıldızın ömrünün sonunda ya da bazı çift yıldız sistemlerinde görülen, kısa sürede bütün bir galaksi kadar parlayabilen dev patlama." },
    { terim: "Tür", aciklama: "Biyolojik tür kavramına göre birbirleriyle çiftleşip verimli döl verebilen ve diğer gruplardan üreme bakımından yalıtılmış canlı toplulukları. Türün nasıl tanımlanacağı biyoloji felsefesinin tartışma konusudur." },
    { terim: "Yerçekimi ivmesi", aciklama: "Yeryüzünde serbest düşen cisimlerin kazandığı ivme; yaklaşık g ≈ 9,81 m/s². Hava direnci yoksa kütleden bağımsızdır." }
  ],
  formel: [
    { terim: "Aksiyom", koken: "Yun. axiōma, “değerli sayılan”", aciklama: "Bir kuramda kanıtlanmadan kabul edilen ve öteki önermelerin kendisinden türetildiği temel önerme.", ornek: "Öklid'in beş postulatı." },
    { terim: "Algoritma", koken: "Harezmî'nin adının Latince biçiminden", aciklama: "Bir problemi çözmek için sonlu sayıda, açık ve adım adım uygulanabilen talimatlar dizisi." },
    { terim: "Asal sayı", aciklama: "1'den büyük olup yalnızca 1'e ve kendisine bölünebilen doğal sayı: 2, 3, 5, 7, 11… Öklid sonsuz sayıda asal olduğunu kanıtladı." },
    { terim: "Eksiklik teoremleri", aciklama: "Gödel (1931): aritmetiği içeren tutarlı her biçimsel sistemde doğru olup sistem içinde kanıtlanamayan önermeler vardır; böyle bir sistem kendi tutarlılığını da kanıtlayamaz." },
    { terim: "Fonksiyon", aciklama: "Bir kümenin her öğesini başka bir kümenin tam olarak bir öğesiyle eşleyen kural: f(x) = x²." },
    { terim: "Geçerlilik", aciklama: "Mantıkta, öncüller doğruyken sonucun yanlış olmasının olanaksız olduğu çıkarım biçimi. Geçerlilik doğruluktan farklıdır: yanlış öncüllerle de geçerli çıkarım yapılabilir." },
    { terim: "Kanıt (ispat)", aciklama: "Bir önermenin aksiyomlardan ve daha önce kanıtlanmış önermelerden, kabul edilen çıkarım kurallarıyla adım adım türetilmesi." },
    { terim: "Küme", aciklama: "Belirli nesnelerin bir bütün olarak ele alınması. Cantor'un kümeler kuramı modern matematiğin ortak dilidir; sonsuzlukların da farklı büyüklükleri olduğunu gösterdi." },
    { terim: "Limit", aciklama: "Bir dizinin ya da fonksiyonun, değişken belirli bir değere yaklaştıkça yaklaştığı değer. Türev ve integralin temelidir." },
    { terim: "Olasılık", aciklama: "Bir olayın gerçekleşme şansının 0 ile 1 arasındaki ölçüsü. Modern aksiyomatik temelini Kolmogorov (1933) kurdu." },
    { terim: "Önerme", aciklama: "Doğru ya da yanlış olabilen bildirim cümlesi ya da onun ifade ettiği içerik.", ornek: "“Kar beyazdır.”" },
    { terim: "Pi (π)", aciklama: "Bir çemberin çevresinin çapına oranı; yaklaşık 3,14159. İrrasyonel ve aşkın bir sayıdır; bu yüzden pergel ve cetvelle daireyi kareye çevirmek olanaksızdır (Lindemann, 1882)." },
    { terim: "Teorem", koken: "Yun. theōrēma, “bakılan, seyredilen”", aciklama: "Kanıtlanmış matematiksel önerme.", ornek: "Pisagor teoremi: a² + b² = c²." },
    { terim: "Tümevarım (matematiksel)", aciklama: "Bir önermenin ilk doğal sayı için doğru olduğunu ve n için doğruysa n+1 için de doğru olduğunu göstererek bütün doğal sayılar için kanıtlama yöntemi." },
    { terim: "Türev", aciklama: "Bir fonksiyonun bir noktadaki anlık değişim hızı; grafiğin o noktadaki eğimi. Newton ve Leibniz birbirinden bağımsız geliştirdi." }
  ],
  sosyal: [
    { terim: "Arz ve talep", aciklama: "Bir mala satıcıların sunmak istediği miktar (arz) ile alıcıların almak istediği miktarın (talep) fiyatla ilişkisi; piyasa fiyatı ikisinin dengelendiği noktada oluşur." },
    { terim: "Bilinçdışı", aciklama: "Freud'da bilincin erişemediği, ama davranışı, rüyaları ve dil sürçmelerini etkileyen istek, anı ve düşünceler alanı." },
    { terim: "Demokrasi", koken: "Yun. dēmos (halk) + kratos (güç)", aciklama: "Siyasal iktidarın halka dayandığı yönetim biçimi. Antik Atina'da doğrudan, modern devletlerde çoğunlukla temsilî biçimde uygulanır." },
    { terim: "Enflasyon", aciklama: "Fiyatlar genel düzeyinin sürekli yükselmesi; paranın satın alma gücünün düşmesi." },
    { terim: "Etnografi", koken: "Yun. ethnos (halk) + graphein (yazmak)", aciklama: "Bir topluluğun gündelik hayatını, uzun süre içinde yaşayarak ve katılarak gözlemleyip betimleyen araştırma yöntemi." },
    { terim: "Hegemonya", koken: "Yun. hēgemonia, “önderlik”", aciklama: "Gramsci'de bir toplumsal grubun yalnızca zorla değil, kendi değerlerini ortak duyu hâline getirerek rıza yoluyla kurduğu egemenlik." },
    { terim: "İdeoloji", aciklama: "Bir toplumsal grubun dünyayı anlama ve açıklama biçimini oluşturan fikirler bütünü. Terimi 1796'da Destutt de Tracy “fikirler bilimi” anlamında önerdi; Marx onu gerçekliği çarpıtan bilinç anlamında kullandı." },
    { terim: "Kültür", koken: "Lat. cultura, “ekip biçme”", aciklama: "Bir topluluğun öğrenilen ve kuşaktan kuşağa aktarılan inanç, değer, alışkanlık, dil ve üretimlerinin bütünü." },
    { terim: "Meşruiyet", aciklama: "Bir iktidarın, yönetilenler tarafından haklı ve kabul edilebilir görülmesi. Weber üç tip sayar: geleneksel, karizmatik ve yasal-ussal." },
    { terim: "Projeksiyon (harita)", aciklama: "Kürenin yüzeyini düzleme aktarma yöntemi. Hiçbir projeksiyon açıları, alanları ve uzaklıkları aynı anda koruyamaz; her harita bir seçimdir." },
    { terim: "Stratigrafi", koken: "Lat. stratum (katman) + Yun. graphein", aciklama: "Arkeoloji ve jeolojide toprak katmanlarının sırasını inceleyerek göreli yaş belirleme: genellikle alttaki katman daha eskidir." },
    { terim: "Toplum sözleşmesi", aciklama: "Siyasal otoritenin, bireylerin doğa durumundan çıkmak için yaptığı varsayımsal bir anlaşmaya dayandığı fikri: Hobbes, Locke, Rousseau." },
    { terim: "Yapısalcılık", aciklama: "Anlamı tek tek öğelerde değil, öğeler arasındaki ilişkiler sisteminde arayan yaklaşım: dilbilimde Saussure, antropolojide Lévi-Strauss." }
  ],
  estetik: [
    { terim: "Aura", aciklama: "Walter Benjamin'de (1935) sanat yapıtının burada ve şimdi olmasından gelen biricikliği; teknik yeniden üretimle (fotoğraf, film) zayıflar." },
    { terim: "Beğeni yargısı", aciklama: "Kant'ta (Yargı Gücünün Eleştirisi, 1790) “bu güzeldir” yargısı: çıkar gözetmeyen, kavrama dayanmayan ama herkesin onayını isteyen bir yargı." },
    { terim: "Estetik", koken: "Yun. aisthēsis, “duyum, algı”", aciklama: "Güzellik, sanat ve duyusal algı üzerine felsefe. Terimi bu anlamda 18. yüzyılda Baumgarten kullandı." },
    { terim: "Katharsis", koken: "Yun. κάθαρσις, “arınma”", aciklama: "Aristoteles'in Poetika'sında tragedyanın, acıma ve korku duygularını uyandırarak izleyicide sağladığı arınma." },
    { terim: "Kontrpuan", koken: "Lat. punctus contra punctum", aciklama: "Müzikte bağımsız melodilerin aynı anda, birbirini tamamlayarak ilerlemesi. Bach'ın fügleri en bilinen örnekleridir." },
    { terim: "Kuleşov etkisi", aciklama: "Aynı ifadesiz yüz çekiminin ardından gelen görüntüye (bir tabak çorba, bir tabut, bir çocuk) göre izleyicinin ona farklı duygular yüklemesi: anlam montajdan doğar." },
    { terim: "Metafor", koken: "Yun. metaphora, “aktarma”", aciklama: "Bir şeyi başka bir şeyin adıyla anlatma: “Zaman bir nehirdir.”" },
    { terim: "Mimesis", koken: "Yun. μίμησις, “öykünme”", aciklama: "Sanatın doğayı ya da insan eylemlerini taklit etmesi, temsil etmesi. Platon kuşkuyla, Aristoteles öğrenmenin kaynağı olarak görür." },
    { terim: "Mizansen", koken: "Fr. mise en scène, “sahneye koyma”", aciklama: "Kadrajda görünen her şeyin düzenlenmesi: dekor, ışık, oyuncuların konumu ve hareketi, kostüm." },
    { terim: "Montaj", aciklama: "Film parçalarının seçilip birbirine eklenmesi. Eisenstein'a göre iki çekimin çarpışmasından üçüncü bir anlam doğar." },
    { terim: "Perspektif", aciklama: "Üç boyutlu uzayı düz bir yüzeyde derinlik izlenimiyle gösterme yöntemi. Doğrusal perspektif Rönesans'ta Brunelleschi ile geliştirildi, Alberti tarafından kuralları yazıldı (1435)." },
    { terim: "Yüce", aciklama: "Burke (1757) ve Kant'ta ölçüsüz büyüklük ya da güç karşısında duyulan, korkuyla karışık hayranlık: fırtınalı deniz, uçurum, yıldızlı gök." }
  ]
};
