/* Doğa Bilimleri odasının kalan kapıları: Jeoloji (Siccar Point, 1788) ve Kimya (Lavoisier'nin laboratuvarı, Paris, 1780'ler). */
(function () {
  var S = window.SAHNE; if (!S || !S.kit || !S.merkezeEkle) return;
  var h = S.h, K = S.kit;

  /* ════════ JEOLOJİ: Siccar Point, İskoçya, 1788 ════════ */
  S.kaydet("jeoloji", {
    ad: "Jeoloji", ust: "doga-bilimleri", yer: "Siccar Point · İskoçya · Haziran 1788 · gün batımı", vurgu: "#D8B088", alan: "doga-bilimleri",
    alt: "Dik duran gri kayaların üstünde yatay kırmızı kumtaşı: aralarında milyonlarca yıl. Hutton burada “zamanın uçurumu”na baktı.",
    parcacik: { tur: "kum", adet: 50 }, isaret: "halka",
    sozler: [
      { metin: "…we find no vestige of a beginning,—no prospect of an end.", dil: "en", ceviri: "…ne bir başlangıcın izini buluyoruz ne de bir sonun görüntüsünü.", kaynak: "James Hutton · Yerin Kuramı, 1788" },
      { metin: "The mind seemed to grow giddy by looking so far into the abyss of time.", dil: "en", ceviri: "Zamanın uçurumuna bu kadar derinden bakınca zihin başı dönmüş gibiydi.", kaynak: "John Playfair · Hutton’un hayatı, 1805" }
    ],
    arka: function () {
      var s = K.gokAksam("jl") + K.gunes(360, 470, 38, "#ffc890");
      s += '<rect y="500" width="1600" height="400" fill="#3a4a5a"/>';
      for (var w = 0; w < 8; w++) s += '<path class="dalga-x" style="--d:-' + w * 0.6 + 's" d="M-160 ' + (520 + w * 44) + 'q40 -6 80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0" fill="none" stroke="rgba(255,220,180,.2)" stroke-width="2"/>';
      /* uzakta sönmüş volkan */
      s += '<path d="M180 510L280 430H320L420 510Z" fill="#3a2a30"/><g class="duman"><path d="M300 430c-10 -30 20 -40 10 -70" stroke="#c8b0a0" stroke-width="10" fill="none" opacity=".35" stroke-linecap="round"/></g>';
      /* kayalık: alt katmanlar dik (gri), üstte yatay kırmızı kumtaşı */
      s += '<defs><clipPath id="jlK"><path d="M680 900L760 640L900 600L1000 590L1600 560V900Z"/></clipPath></defs>';
      s += '<path d="M680 900L760 640L900 600L1000 590L1600 560V900Z" fill="#5a5a60"/>';
      s += '<g clip-path="url(#jlK)">';
      for (var i = 0; i < 40; i++) s += '<path d="M' + (640 + i * 26) + ' 920L' + (700 + i * 26) + ' 560" stroke="' + (i % 3 ? "#6a6a72" : "#4a4a52") + '" stroke-width="' + (8 + (i % 4) * 3) + '"/>';
      s += "</g>";
      s += '<path d="M740 610L900 560L1000 550L1600 520V600L1000 612L900 624Z" fill="#a8583a"/>';
      for (var k = 0; k < 6; k++) s += '<path d="M' + (760 + k * 10) + " " + (400 + k * 36) + "L1600 " + (380 + k * 30) + '" stroke="' + (k % 2 ? "#b8683a" : "#984a2e") + '" stroke-width="30"/>';
      s += '<path d="M740 420L1600 330V360L740 440Z" fill="#6a7a4a"/><path d="M760 400L1600 310" stroke="#8a9a5a" stroke-width="10"/>';
      /* uyumsuzluk çizgisi */
      s += '<path d="M760 612L900 600L1000 590L1600 568" stroke="#f0d890" stroke-width="3" stroke-dasharray="8 6" opacity=".7"/>';
      /* kayıkta üç adam */
      s += '<g transform="translate(620 650)"><g class="yuz" style="--s:5s"><path d="M-70 0C-40 14 40 14 70 0L60 -8H-60Z" fill="#4a2e1a"/>' + [-34, 0, 34].map(function (x, i) { return '<path d="M' + x + ' -8V-34" stroke="#2a2020" stroke-width="12"/><circle cx="' + x + '" cy="-42" r="8" fill="#c8a080"/><path d="M' + (x - 8) + ' -48h16v-6h-16Z" fill="#1a1414"/>'; }).join("") + '<path d="M-60 -20L-100 20" stroke="#6a4a2a" stroke-width="3"/></g></g>';
      /* ammonit fosili */
      s += '<g transform="translate(880 830)"><ellipse cx="0" cy="10" rx="70" ry="24" fill="#6a6a70"/><g transform="translate(0 -4)"><path d="M0 0a4 4 0 0 1 8 0a8 8 0 0 1 -16 0a12 12 0 0 1 24 0a16 16 0 0 1 -32 0a20 20 0 0 1 40 0" fill="none" stroke="#e8d8b0" stroke-width="3"/></g></g>';
      /* Wegener'in haritası (Afrika ile Güney Amerika) */
      s += '<g transform="translate(1080 760) rotate(-4)"><rect x="-80" y="-60" width="160" height="110" fill="#e8dcc0" stroke="#5a3a22" stroke-width="5"/><rect x="-74" y="-54" width="148" height="98" fill="#8ab0c8"/><path d="M-60 -40C-40 -44 -24 -30 -22 -14C-20 0 -30 10 -34 30L-44 34C-50 10 -62 -10 -60 -40Z" fill="#6a8a4a"/><path d="M-14 -44C10 -48 40 -40 44 -20C48 0 30 10 22 34L10 30C4 10 -2 -6 -12 -14C-20 -24 -24 -36 -14 -44Z" fill="#8a9a4a"/><path d="M-20 -20L-10 -20" stroke="#a8302a" stroke-width="3"/></g>';
      /* saha masası: sismograf ve zirkon */
      s += K.masa(1260, 790, 260, "#5a3a22");
      s += '<g transform="translate(1330 780)"><rect x="-40" y="-40" width="80" height="40" fill="#3a3a3a"/><ellipse cx="0" cy="-40" rx="36" ry="8" fill="#efe8dc"/><path class="dalga-x" d="M-34 -40l6 -6 6 10 6 -14 6 18 6 -12 6 6 6 -4 6 2" stroke="#a8302a" stroke-width="1.5" fill="none"/><path d="M20 -40V-70L0 -46" stroke="#8a8a8a" stroke-width="3" fill="none"/></g>';
      s += '<g transform="translate(1450 772)"><path d="M0 -26L10 -10L6 10H-6L-10 -10Z" fill="#e8a870" opacity=".85"/><circle r="26" fill="#ffc890" opacity=".2" class="hale"/></g>';
      s += '<g transform="translate(1390 776) rotate(30)"><rect x="-4" y="-30" width="8" height="40" fill="#6a4a2a"/><rect x="-16" y="-36" width="32" height="10" fill="#8a8a8a"/></g>';
      return h.svg(s);
    },
    eserler: [
      { x: 56, y: 67, ad: "Uyumsuzluk", panel: '<h3>Hutton’un uyumsuzluğu</h3><p>Haziran 1788’de <b>James Hutton</b>, matematikçi <b>John Playfair</b> ve jeolog <b>James Hall</b> ile kayıkla Siccar Point’e geldi. Dik duran gri grovaklar (Silüriyen) ile üstlerinde neredeyse yatay uzanan kırmızı kumtaşları (Devoniyen) arasındaki sınıra baktılar.</p><p>Okuma: alttaki katmanlar önce deniz dibinde yatay çökeldi, sonra sıkışıp dikleşti, yükseldi ve aşındı; ardından tekrar batıp yeni çökeller aldı. Bütün bunlar yavaş, bugün de işleyen süreçlerle olduysa Dünya’nın yaşı binlerce değil, akıl almaz ölçüde uzun olmalıydı: <b>derin zaman</b>.</p><p class="pn-not">Bugün biliyoruz ki iki katman arasındaki boşluk yaklaşık 65 milyon yıldır.</p>' },
      { x: 78, y: 48, ad: "Kırmızı katmanlar", panel: '<h3>Katmanları okumak</h3><p><b>Nicolaus Steno</b> (1669) tortul kayaların temel ilkelerini koydu: katmanlar yatay çökelir; alttaki üsttekinden eskidir (<b>üst üste gelme</b>); yanal olarak süreklidir.</p><p><b>Charles Lyell</b> (<i>Jeolojinin İlkeleri</i>, 1830–33) Hutton’un fikrini sistemleştirdi: <b>tekdüzecilik</b>, yani geçmişi bugün gözlediğimiz yavaş süreçlerle açıklamak. Genç Darwin kitabın ilk cildini Beagle yolculuğunda okudu.</p><p>Bugünkü görüş ikisini birleştirir: yavaş süreçler çoğunlukla işler, ama asteroid çarpmaları ve büyük volkanik patlamalar gibi ani felaketler de tarihin parçasıdır.</p>' },
      { x: 55, y: 90, ad: "Ammonit", panel: '<h3>Fosiller ve zamanın ölçeği</h3><p>Steno 1667’de köpekbalığı başı incelerken halkın “dil taşı” dediği taşların köpekbalığı dişi olduğunu gösterdi: fosiller canlıların kalıntısıdır.</p><p>Kanal kazılarında çalışan <b>William Smith</b> belirli fosillerin hep aynı katmanlarda bulunduğunu fark etti ve 1815’te İngiltere’nin ilk jeoloji haritasını çizdi. Fosiller uzak yerlerdeki katmanları eşleştirmeyi sağlar.</p><p>Ammonitler, 66 milyon yıl önce Kretase sonundaki kitlesel yok oluşta dinozorlarla birlikte ortadan kalktı. Jeolojik zaman ölçeği (eon, zaman, devir, çağ) büyük ölçüde fosil topluluklarının değişimine göre bölümlenir.</p>' },
      { x: 19, y: 48, ad: "Uzak volkan", panel: '<h3>Kaya döngüsü</h3><p>Hutton kayaların sürekli bir döngüde olduğunu gördü: yüzeyde aşınan kayalar denizde çökelir, gömülür, ısı ve basınçla sertleşir, erir, yükselir ve yeniden aşınır.</p><ul><li><b>Magmatik</b> kayalar: magmanın soğumasıyla (granit, bazalt).</li><li><b>Tortul</b> kayalar: çökellerin sıkışmasıyla (kumtaşı, kireçtaşı).</li><li><b>Başkalaşım</b> kayaları: ısı ve basınçla dönüşenler (mermer, şist).</li></ul><p>Hutton’un döneminde <b>Neptüncüler</b> (Werner: bütün kayalar okyanustan çökeldi) ile <b>Plütoncular</b> (Hutton: iç ısının rolü) tartışıyordu. Edinburgh’daki Arthur’s Seat sönmüş bir volkanın kalıntısıdır.</p>' },
      { x: 67, y: 83, ad: "Wegener’in haritası", panel: '<h3>Kıtalar hareket eder</h3><p>Güney Amerika ile Afrika’nın kıyıları yapboz gibi birbirine uyuyor. <b>Alfred Wegener</b> (1912, <i>Kıtaların ve Okyanusların Kökeni</i> 1915) kıtaların bir zamanlar tek bir süper kıta, <b>Pangea</b> olduğunu ve birbirinden uzaklaştığını savundu: iki kıtada aynı fosiller, aynı kaya dizileri, buzul izleri.</p><p>Hareketi açıklayacak bir mekanizma bulamadığı için alay edildi. 1960’larda okyanus tabanı araştırmaları (Harry Hess, 1962: okyanus ortası sırtlarda yeni kabuk oluşuyor; tabandaki manyetik şeritler) <b>levha tektoniği</b>ni kanıtladı. Wegener 1930’da Grönland seferinde ölmüştü.</p>' },
      { x: 83, y: 82, ad: "Sismograf", panel: '<h3>Depremler ve Dünya’nın içi</h3><p>Levhaların sınırlarında gerilim birikir ve aniden boşalır. Türkiye, Kuzey ve Doğu Anadolu fayları boyunca bu sınırların üzerindedir: 1939 Erzincan, 17 Ağustos 1999 Gölcük, 6 Şubat 2023 Kahramanmaraş depremleri.</p><p>Deprem dalgaları Dünya’nın içini görmemizi sağlar. <b>P dalgaları</b> (basınç) katı ve sıvıdan, <b>S dalgaları</b> (kayma) yalnız katıdan geçer. Dış çekirdekte S dalgalarının kaybolması onun sıvı olduğunu gösterdi; Danimarkalı sismolog <b>Inge Lehmann</b> 1936’da katı bir iç çekirdek bulunduğunu keşfetti.</p>' },
      { x: 91, y: 83, ad: "Zirkon kristali", panel: '<h3>Dünya kaç yaşında?</h3><p>17. yüzyılda James Ussher İncil’deki soy kütüklerinden yaratılışı MÖ 4004’e tarihlendi. Kelvin 1862’de Dünya’nın soğuma hızından 20–400 milyon yıl hesapladı; radyoaktiviteyi bilmiyordu.</p><p>Radyometrik tarihleme, kararsız atomların sabit hızla bozunmasına dayanır. <b>Clair Patterson</b> 1956’da göktaşlarındaki kurşun izotoplarından Dünya’nın yaşını yaklaşık <b>4,55 milyar yıl</b> buldu (bugünkü değer 4,54).</p><p>Batı Avustralya’daki Jack Hills zirkonları yaklaşık 4,4 milyar yaşındadır: Dünya’nın bilinen en eski parçaları, o zaman bile sıvı su olduğuna işaret ediyor.</p>' },
      { x: 39, y: 68, ad: "Kayık", panel: '<h3>Jeoloji ve insan: Antroposen</h3><p>Hutton’un kayığındaki üç adam jeolojinin kurucu sahnesini yaşadı. Bugünkü soru başka: insanlık kendi başına jeolojik bir güç mü oldu?</p><p>Atmosfer kimyacısı Paul Crutzen 2000’de <b>Antroposen</b> (“insan çağı”) adını önerdi: fosil yakıtlar, nükleer denemeler, plastik, beton ve tür kaybı kayalarda iz bırakıyor. Önerilen başlangıç 1950’ler ve Kanada’daki Crawford Gölü’nün tortullarıydı.</p><p>Mart 2024’te Uluslararası Stratigrafi Komisyonu’nun ilgili alt komisyonu Antroposen’i resmî bir jeolojik çağ olarak kabul etmedi; terim yine de yerbilimlerinde ve kamusal tartışmada canlı.</p>' }
    ]
  });

  /* ════════ KİMYA: Lavoisier'nin laboratuvarı, Paris ════════ */
  S.kaydet("kimya", {
    ad: "Kimya", ust: "doga-bilimleri", yer: "Paris · Lavoisier’nin laboratuvarı · 1780’ler · gece", vurgu: "#A8E0B8", alan: "doga-bilimleri",
    alt: "Masada imbikler, hassas bir terazi ve bir hava pompası; duvarda henüz yazılmamış bir tablo. Madde neden yapılmıştır, nasıl dönüşür?",
    parcacik: { tur: "atesbocegi", adet: 20 }, isaret: "kristal",
    sozler: [
      { metin: "Rien ne se perd, rien ne se crée, tout se transforme.", dil: "fr", ceviri: "Hiçbir şey yok olmaz, hiçbir şey yoktan var olmaz; her şey dönüşür.", kaynak: "Lavoisier’ye atfedilir · Traité élémentaire de chimie, 1789’dan" },
      { metin: "Alle Ding’ sind Gift und nichts ohn’ Gift; allein die Dosis macht, dass ein Ding kein Gift ist.", dil: "de", ceviri: "Her şey zehirdir, zehirsiz hiçbir şey yoktur; bir şeyi zehir olmaktan çıkaran yalnızca dozdur.", kaynak: "Paracelsus · Septem Defensiones, 1538" }
    ],
    arka: function () {
      var s = K.duvar("km", "#3a3226", "#18140e");
      s += K.pencere(1300, 150, 190, 330, true);
      /* periyodik tablo posteri */
      s += '<g transform="translate(1100 220)"><rect x="-130" y="-90" width="260" height="170" fill="#e8dcc0" stroke="#5a3a22" stroke-width="6"/>';
      var dz = [[0, 17], [0, 1, 12, 13, 14, 15, 16, 17], [0, 1, 12, 13, 14, 15, 16, 17], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]];
      dz.forEach(function (sat, r) { sat.forEach(function (c) { s += '<rect x="' + (-120 + c * 13.3) + '" y="' + (-78 + r * 22) + '" width="12" height="20" fill="' + (c < 2 ? "#e8a878" : c > 11 ? "#88c0a8" : "#c8b8e8") + '" opacity=".85"/>'; }); });
      s += '<rect x="-94" y="36" width="12" height="20" fill="none" stroke="#a8302a" stroke-width="2" stroke-dasharray="3 2"/></g>';
      s += '<rect y="740" width="1600" height="160" fill="#140f0a"/>' + K.masa(300, 700, 1000, "#4a3020") + K.raf(40, 380, 200, 300, 61, 4);
      /* imbik */
      s += '<g transform="translate(420 700)"><path d="M-30 -10a34 34 0 1 1 30 0Z" fill="#a8d8c8" opacity=".35" stroke="#d8f0e8" stroke-width="2"/><path d="M-4 -70L70 -40" stroke="#d8f0e8" stroke-width="6" opacity=".6"/><path d="M-10 -80h12v14h-12Z" fill="#d8f0e8" opacity=".5"/><ellipse cx="-12" cy="-26" rx="22" ry="8" fill="#6ac8a0" opacity=".6"/><path d="M-40 0H24" stroke="#3a2a1a" stroke-width="6"/></g>' + h.alev(408, 698, .3, 0.1) + '<g transform="translate(496 700)"><path d="M-12 0V-24C-12 -40 12 -40 12 -24V0Z" fill="#a8d8c8" opacity=".3" stroke="#d8f0e8"/><circle class="dus" style="--d:-.4s" cx="-10" cy="-54" r="2.4" fill="#8ae0b8"/></g>';
      /* hassas terazi (cam kutuda) */
      s += '<g transform="translate(640 700)"><rect x="-60" y="-110" width="120" height="110" fill="#a8c8d8" opacity=".12" stroke="#d8e8f0" stroke-width="2"/><path d="M0 0V-90" stroke="#c8a060" stroke-width="4"/><g class="sallan" style="--a:3deg;--s:5s"><path d="M-44 -86H44" stroke="#c8a060" stroke-width="3"/><path d="M-44 -86V-40M44 -86V-40" stroke="#c8a060"/><ellipse cx="-44" cy="-38" rx="16" ry="4" fill="#c8a060"/><ellipse cx="44" cy="-38" rx="16" ry="4" fill="#c8a060"/><rect x="-50" y="-48" width="12" height="10" fill="#8a8a8a"/></g></g>';
      /* benzen modeli */
      s += '<g transform="translate(860 660)"><g class="don" style="--s:24s;transform-origin:0 0">' + [0, 60, 120, 180, 240, 300].map(function (a) { var r = a * Math.PI / 180, x = Math.cos(r) * 34, y = Math.sin(r) * 34; return '<path d="M0 0" /><line x1="' + x.toFixed(1) + '" y1="' + y.toFixed(1) + '" x2="' + (Math.cos(r + Math.PI / 3) * 34).toFixed(1) + '" y2="' + (Math.sin(r + Math.PI / 3) * 34).toFixed(1) + '" stroke="#d8d8d8" stroke-width="4"/><circle cx="' + x.toFixed(1) + '" cy="' + y.toFixed(1) + '" r="10" fill="#2a2a2a" stroke="#6a6a6a"/><circle cx="' + (x * 1.6).toFixed(1) + '" cy="' + (y * 1.6).toFixed(1) + '" r="6" fill="#f0f0f0"/>'; }).join("") + '<circle r="18" fill="none" stroke="#8ae0b8" stroke-width="2" stroke-dasharray="4 4"/></g><path d="M0 40V40" /><rect x="-6" y="40" width="12" height="0"/></g>';
      /* hava pompası */
      s += '<g transform="translate(1060 700)"><rect x="-60" y="-10" width="120" height="10" fill="#6a4a2a"/><path d="M-44 -10V-80A44 44 0 0 1 44 -80V-10Z" fill="#c8e0f0" opacity=".2" stroke="#e8f4ff" stroke-width="2"/><circle cx="0" cy="-40" r="8" fill="#e8c870"/><path d="M60 -10V-100M60 -100L100 -120" stroke="#8a6a4a" stroke-width="8"/></g>';
      /* mor boya şişesi ve radyum */
      s += '<g transform="translate(1200 700)"><path d="M-18 0V-40C-18 -54 -6 -56 -6 -70H6C6 -56 18 -54 18 -40V0Z" fill="#8a3aa8" opacity=".85"/><rect x="-7" y="-80" width="14" height="10" fill="#8a6a4a"/></g>';
      s += '<g transform="translate(1296 700)"><rect x="-9" y="-40" width="18" height="40" rx="6" fill="#7af0c8" opacity=".6"/><circle cy="-20" r="30" fill="#7af0c8" opacity=".16" class="hale"/></g>';
      /* buğday demeti */
      s += '<g transform="translate(1460 830)">' + [-20, -10, 0, 10, 20].map(function (a) { return '<g transform="rotate(' + a + ')"><path d="M0 60V-60" stroke="#c8a040" stroke-width="3"/><ellipse cy="-70" rx="7" ry="18" fill="#e0b848"/></g>'; }).join("") + '<path d="M-16 20H16" stroke="#8a5a2a" stroke-width="6"/></g>';
      return h.svg(s);
    },
    eserler: [
      { x: 26, y: 70, ad: "İmbik", panel: '<h3>Simyadan kimyaya</h3><p>“Kimya” sözcüğü Arapça <i>el-kîmyâ</i>’dan gelir. Simyacılar metalleri altına dönüştürmenin ve ölümsüzlük iksirinin peşindeydi, ama bu arayışta damıtma, süzme, kristallendirme gibi yöntemleri geliştirdiler.</p><p><b>Câbir b. Hayyân</b>’a atfedilen Arapça külliyat (8.–10. yüzyıllar) deneyi ve sınıflandırmayı öne çıkarır; <b>Ebû Bekir er-Râzî</b> maddeleri hayvansal, bitkisel ve mineral diye ayırır. <b>Paracelsus</b> (16. yy) simyayı ilaç yapımına yöneltir: “doz zehri yapar.”</p><p>Newton da ömrü boyunca simya üzerine yüz binlerce sözcük yazdı; Keynes ona “son büyücü” dedi.</p>' },
      { x: 40, y: 68, ad: "Terazi", panel: '<h3>Lavoisier ve kütlenin korunumu</h3><p><b>Antoine Lavoisier</b> tepkimeleri kapalı kaplarda, çok hassas terazilerle tarttı: tepkimeden önceki ve sonraki toplam kütle aynıdır. Yanma, havadaki bir gazla, onun <b>oksijen</b> adını verdiği gazla birleşmedir; yanan maddeden “flojiston” çıkmaz.</p><p><i>Traité élémentaire de chimie</i> (1789) 33 “element” sayar ve Guyton de Morveau ile birlikte kurduğu adlandırma sistemiyle modern kimyanın dilini kurar. Eşi <b>Marie-Anne Paulze Lavoisier</b> deneylerin çizimlerini yaptı ve İngilizce makaleleri çevirdi.</p><p>Vergi toplayıcısı olduğu için 1794’te Devrim mahkemesince giyotinle idam edildi. Lagrange: “O başı kesmek bir an sürdü; benzerini yetiştirmek için yüz yıl yetmeyebilir.”</p>' },
      { x: 54, y: 72, ad: "Benzen halkası", panel: '<h3>Kekulé ve kimyasal yapı</h3><p>Atomlar molekülde nasıl dizilir? <b>August Kekulé</b> 1858’de karbonun dört bağ yaptığını ve karbon zincirleri oluşturduğunu önerdi. 1865’te benzenin (C₆H₆) altı karbonunun bir <b>halka</b> oluşturduğunu yazdı; sonradan bunu kendi kuyruğunu ısıran bir yılan düşüne bağladı.</p><p>Linus Pauling (<i>Kimyasal Bağın Doğası</i>, 1939) bağları kuantum mekaniğiyle açıkladı: benzende elektronlar halkanın tamamına yayılmıştır, bu yüzden bütün bağlar eşit uzunluktadır.</p><p>Yapı işlevi belirler: aynı atomlardan oluşan farklı düzenler (izomerler) bambaşka maddeler olabilir.</p>' },
      { x: 66, y: 68, ad: "Hava pompası", panel: '<h3>Boyle: şüpheci kimyacı</h3><p><b>Robert Boyle</b> (<i>The Sceptical Chymist</i>, 1661) Aristoteles’in dört elementini ve simyacıların üç ilkesini sorgular; maddenin küçük parçacıklardan oluştuğunu savunur ve deneyi bilginin ölçütü yapar.</p><p>Robert Hooke’un yaptığı hava pompasıyla cam fanustaki havayı boşaltır: mum söner, zil sesi duyulmaz olur, kuş bayılır. 1662’de gaz yasasını yayımlar: sabit sıcaklıkta bir gazın basıncı ile hacminin çarpımı sabittir (<b>PV = k</b>).</p><p>Hava pompası deneyleri, Royal Society’de bilginin tanıklar önünde yapılan kamusal deneylerle üretilmesi fikrinin de simgesi oldu.</p>' },
      { x: 75, y: 73, ad: "Mor şişe", panel: '<h3>Sentezin çağı</h3><p>1828’de <b>Friedrich Wöhler</b>, inorganik bir tuzdan (amonyum siyanat) üre elde etti: canlı organizmaların ürettiği bir madde laboratuvarda yapılmıştı. Organik maddeleri yalnızca “yaşam gücü”nün yapabileceği inancı sarsıldı.</p><p>1856’da 18 yaşındaki <b>William Perkin</b> kinin sentezlemeye çalışırken kömür katranından parlak bir mor boya, <b>mauveine</b> buldu. Sentetik boya sanayisi doğdu; kimya sanayisi ve ilaç sanayisi onu izledi.</p>' },
      { x: 81, y: 73, ad: "Işıldayan şişe", panel: '<h3>Marie Curie ve radyoaktivite</h3><p>Becquerel 1896’da uranyum tuzlarının kendiliğinden ışınım yaydığını fark etti. <b>Marie Skłodowska Curie</b> ve <b>Pierre Curie</b> tonlarca uranyum cevheri artığını işleyerek 1898’de iki yeni element buldular: Marie’nin vatanının adını taşıyan <b>polonyum</b> ve <b>radyum</b>. “Radyoaktivite” sözcüğü de Marie’nindir.</p><p>Marie Curie Nobel alan ilk kadındır ve iki farklı bilim dalında Nobel alan tek kişidir (Fizik 1903, Kimya 1911). Defterleri bugün hâlâ radyoaktiftir ve kurşun kutularda saklanır.</p>' },
      { x: 69, y: 24, ad: "Periyodik tablo", panel: '<h3>Mendeleyev’in tablosu (1869)</h3><p><b>Dmitri Mendeleyev</b> bilinen 63 elementi atom ağırlıklarına göre sıralarken özelliklerin düzenli aralıklarla tekrarlandığını gördü ve benzer elementleri aynı sütuna koydu. Cesaretli adımı: uymayan yerlerde <b>boşluk</b> bıraktı ve oraya gelecek elementlerin özelliklerini önceden bildirdi.</p><p>Öngördüğü “eka-silisyum” 1886’da <b>germanyum</b> olarak bulundu; yoğunluğu ve atom ağırlığı tahminine çok yakındı. Bugün tablo, atom numarasına (proton sayısı) göre sıralanır ve 118 element içerir.</p><p>Tablodaki düzeni, elektronların kabuklara yerleşmesi açıklar: aynı sütundaki elementler dış kabuklarında benzer elektron dizilişine sahiptir.</p>' },
      { x: 91, y: 84, ad: "Buğday demeti", panel: '<h3>Havadan ekmek: Haber–Bosch</h3><p>Bitkiler azota muhtaçtır, havanın %78’i azottur ama bu azot neredeyse tepkimeye girmez. <b>Fritz Haber</b> 1909’da yüksek basınç ve katalizörle havadaki azottan <b>amonyak</b> üretti; <b>Carl Bosch</b> süreci 1913’te sanayi ölçeğine taşıdı.</p><p>Yapay gübre, bugün dünya nüfusunun yaklaşık yarısını besleyen tarımı mümkün kılıyor. Aynı süreç patlayıcı yapımında da kullanıldı; Haber Birinci Dünya Savaşı’nda kimyasal silahların geliştirilmesine de öncülük etti. Kimyanın iki yüzü tek bir hayatta.</p>' }
    ]
  });

  S.merkezeEkle("doga-bilimleri", [
    { hedef: "jeoloji", aciklama: "Siccar Point, 1788: derin zaman, katmanlar, levhalar.",
      sanat: K.kapi("#D8B088", '<g>' + [0, 1, 2, 3].map(function (i) { return '<path d="M-60 ' + (i * 16 - 40) + 'H60" stroke="' + ["#a8583a", "#b8683a", "#984a2e", "#c8784a"][i] + '" stroke-width="12"/>'; }).join("") + [0, 1, 2, 3, 4, 5].map(function (i) { return '<path d="M' + (-54 + i * 20) + ' 60L' + (-44 + i * 20) + ' 24" stroke="#8a8a92" stroke-width="10"/>'; }).join("") + '<path d="M-60 22H60" stroke="#f0d890" stroke-width="2" stroke-dasharray="6 4"/></g>') },
    { hedef: "kimya", aciklama: "Lavoisier’nin laboratuvarı: element, bağ, tablo.",
      sanat: K.kapi("#A8E0B8", '<path d="M-16 -60V-20L-50 44C-54 54 -48 60 -38 60H38C48 60 54 54 50 44L16 -20V-60Z" fill="#a8e0b8" fill-opacity=".2" stroke="#f0d890" stroke-width="3"/><path d="M-38 30H38L50 50H-50Z" fill="#6ac8a0" opacity=".7"/><circle cx="-8" cy="10" r="5" fill="#d8f0e8"/><circle cx="10" cy="-6" r="3" fill="#d8f0e8"/>') }
  ]);
})();
