/* Sosyal Bilimler odasının kalan kapıları: Arkeoloji (Göbeklitepe), Dilbilimi (gece müzesinde Rosetta Taşı), Hukuk (eski bir adliye),
   İlahiyat (Kurtuba Ulu Camii), Siyaset ve Sosyoloji (sanayi kenti, akşam), Psikoloji ve Psikanaliz (Berggasse 19). */
(function () {
  var S = window.SAHNE; if (!S || !S.kit || !S.merkezeEkle) return;
  var h = S.h, K = S.kit;

  /* ════════ ARKEOLOJİ: Göbeklitepe, şafak ════════ */
  S.kaydet("arkeoloji", {
    ad: "Arkeoloji", ust: "sosyal-bilimler", yer: "Göbeklitepe · Şanlıurfa · şafak · kazı mevsimi", vurgu: "#E0B078", alan: "sosyal-bilimler",
    alt: "Taş halkaların ortasında T biçimli dikilitaşlar yükseliyor; üzerlerinde tilkiler, yaban domuzları, akbabalar. On iki bin yıl önce, yazıdan ve tarımdan önce.",
    parcacik: { tur: "kum", adet: 60 }, isaret: "halka",
    sozler: [
      { metin: "The archaeologist is not digging up things, he is digging up people.", dil: "en", ceviri: "Arkeolog nesneleri değil, insanları kazıp çıkarır.", kaynak: "Mortimer Wheeler · Topraktan Arkeoloji, 1954" },
      { metin: "Zuerst kam der Tempel, dann die Stadt.", dil: "de", ceviri: "Önce tapınak geldi, sonra şehir.", kaynak: "Klaus Schmidt’in Göbeklitepe özeti" }
    ],
    arka: function () {
      var s = K.gokAksam("ar") + K.gunes(1320, 420, 40, "#ffd49a");
      s += K.tepe(470, "#8a6a4a", 51, 50) + K.tepe(540, "#a8845a", 53, 40) + '<rect y="540" width="1600" height="360" fill="#b8946a"/>';
      /* kazı çukuru ve taş halka */
      s += '<ellipse cx="900" cy="660" rx="420" ry="120" fill="#6a4a30"/><ellipse cx="900" cy="650" rx="380" ry="100" fill="#8a6a48"/>';
      for (var i = 0; i < 26; i++) { var a = i / 26 * Math.PI * 2, x = 900 + Math.cos(a) * 390, y = 650 + Math.sin(a) * 104; s += '<rect x="' + (x - 18).toFixed(0) + '" y="' + (y - 22).toFixed(0) + '" width="36" height="26" rx="4" fill="' + (i % 2 ? "#c8b090" : "#b8a080") + '"/>'; }
      /* çevre dikilitaşları */
      var T = function (x, y, o, kab) { return '<g transform="translate(' + x + " " + y + ") scale(" + o + ')"><rect x="-18" y="-200" width="36" height="200" fill="#d8c4a0"/><rect x="-60" y="-240" width="120" height="44" rx="4" fill="#e0ccaa"/><path d="M-18 -200V0" stroke="rgba(0,0,0,.12)" stroke-width="8"/>' + (kab || "") + "</g>"; };
      s += T(620, 640, .55) + T(1180, 640, .55) + T(720, 610, .45) + T(1080, 610, .45);
      var tilki = '<path d="M-12 -150l6 -12 4 10 10 -2 -6 12c8 8 6 30 -6 40 -4 6 -10 8 -12 4 4 -10 4 -30 4 -52Z" fill="#a8906a"/><path d="M-10 -130c-4 20 -2 40 4 56" stroke="#a8906a" stroke-width="4" fill="none"/>';
      s += T(840, 660, 1.05, tilki + '<path d="M-10 -40h20M-10 -30h20" stroke="#a8906a" stroke-width="3"/>') + T(960, 660, 1.05, '<path d="M-6 -100c-6 -10 6 -20 12 -10 6 12 -4 24 -12 10Z" fill="#a8906a"/><path d="M-30 -226c10 -6 20 -6 30 0" stroke="#a8906a" stroke-width="3" fill="none"/>');
      /* boğa başı sandığı */
      s += '<g transform="translate(300 660)"><rect x="-80" y="-10" width="160" height="70" fill="#7a5a3a"/><path d="M-80 10H80" stroke="#5a3a22" stroke-width="3"/><g transform="translate(0 -30)"><path d="M-30 -10C-60 -20 -70 -50 -56 -64C-50 -40 -36 -30 -20 -28ZM30 -10C60 -20 70 -50 56 -64C50 -40 36 -30 20 -28Z" fill="#e8dcc0"/><path d="M-24 -30C-26 10 -10 30 0 30C10 30 26 10 24 -30Z" fill="#c8583a"/><circle cx="-10" cy="-10" r="3" fill="#2a1a10"/><circle cx="10" cy="-10" r="3" fill="#2a1a10"/></g></g>';
      /* Hisarlık tabelası */
      s += '<g transform="translate(560 610)"><path d="M0 0V90" stroke="#5a3a22" stroke-width="8"/><rect x="-70" y="-40" width="140" height="40" fill="#e8dcc0" stroke="#5a3a22" stroke-width="4"/><text y="-14" text-anchor="middle" font-family="Georgia,serif" font-size="14" fill="#3a2414">HİSARLIK → TROIA</text></g>';
      /* buluntu masası: çanak parçaları, kil tablet, C14 tüpü */
      s += K.masa(1140, 650, 360, "#6a4a2a");
      s += '<g transform="translate(1180 640)">' + [[-24, 0, 20], [0, -6, 26], [26, 2, 18]].map(function (p) { return '<path d="M' + (p[0] - p[2] / 2) + " " + p[1] + "q" + p[2] / 2 + " -12 " + p[2] + ' 0l-4 8h-' + (p[2] - 8) + 'Z" fill="#b8582a"/><path d="M' + (p[0] - p[2] / 3) + " " + (p[1] - 2) + "h" + (p[2] * 0.6) + '" stroke="#2a1a10" stroke-width="1.5"/>'; }).join("") + "</g>";
      s += '<g transform="translate(1300 632)"><rect x="-26" y="-18" width="52" height="30" rx="6" fill="#a8845a"/><g stroke="#5a3a22" stroke-width="1.4">' + [0, 1, 2, 3].map(function (r) { return '<path d="M-20 ' + (-10 + r * 7) + "h" + (30 + (r % 2) * 8) + '" stroke-dasharray="3 2 1 2"/>'; }).join("") + "</g></g>";
      s += '<g transform="translate(1420 640)"><rect x="-8" y="-40" width="16" height="40" rx="6" fill="#d8f0f0" opacity=".6" stroke="#fff"/><rect x="-8" y="-16" width="16" height="16" rx="6" fill="#4a3a2a"/><text x="0" y="-46" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#2a1a10">¹⁴C</text></g>';
      /* kazı ızgarası */
      s += '<g transform="translate(1340 820)"><rect x="-170" y="-50" width="340" height="80" fill="#8a6a48"/>' + [-170, -85, 0, 85, 170].map(function (x) { return '<path d="M' + x + ' -60V40" stroke="#5a3a22" stroke-width="5"/>'; }).join("") + '<path d="M-170 -50H170M-170 -10H170M-170 30H170M-170 -50V30M-85 -50V30M0 -50V30M85 -50V30M170 -50V30" stroke="#f0f0e0" stroke-width="1.5"/><rect x="40" y="-30" width="30" height="16" fill="#e8dcc0" opacity=".8"/></g>';
      /* dron */
      s += '<g transform="translate(1250 220)"><g class="yuz" style="--s:4s"><rect x="-22" y="-8" width="44" height="14" rx="4" fill="#2a2a30"/><path d="M-22 -2L-48 -12M22 -2L48 -12M-22 2L-48 12M22 2L48 12" stroke="#2a2a30" stroke-width="4"/>' + [[-48, -12], [48, -12], [-48, 12], [48, 12]].map(function (p) { return '<ellipse cx="' + p[0] + '" cy="' + (p[1] - 6) + '" rx="18" ry="3" fill="#c8c8d0" opacity=".6"/>'; }).join("") + '<circle cy="10" r="4" fill="#a8302a"/><path d="M-4 14L-60 180M4 14L60 180" stroke="#8af0a8" stroke-width="1" opacity=".3"/></g></g>';
      return h.svg(s);
    },
    eserler: [
      { x: 57, y: 50, ad: "T biçimli dikilitaş", panel: '<h3>Göbeklitepe</h3><p>Şanlıurfa yakınlarındaki höyükte 1995’ten itibaren Alman Arkeoloji Enstitüsü’nden <b>Klaus Schmidt</b> ve Şanlıurfa Müzesi kazılar yürüttü. En eski yapı katmanı yaklaşık <b>MÖ 9600</b>’e, yani Stonehenge’den altı bin yıl öncesine tarihleniyor.</p><p>Yuvarlak yapıların ortasında 5 metreyi aşan T biçimli dikilitaşlar insan bedenini temsil eder: bazılarının yanlarında kollar, eller ve kemerler kabartılmıştır. Üzerlerinde tilki, yaban domuzu, yılan, turna ve akbaba figürleri var.</p><p>Bunu avcı-toplayıcılar yaptı. Schmidt’e göre anıtsal toplanma yerleri yerleşik hayattan ve tarımdan önce gelmiş olabilir; sonraki kazılar alanda konutlar ve su sarnıçları da buldu. Göbeklitepe 2018’de UNESCO Dünya Mirası Listesi’ne girdi.</p>' },
      { x: 19, y: 68, ad: "Boğa başı", panel: '<h3>Çatalhöyük</h3><p>Konya Ovası’ndaki Çatalhöyük (yaklaşık MÖ 7100–5950) sokaksız bir kasabadır: evlere damlardan girilirdi. Duvarlarda boğa başları (<i>bucranium</i>), av sahneleri ve bir yanardağ resmi olarak yorumlanan ünlü duvar resmi bulundu. Ölüler evlerin tabanı altına gömülürdü.</p><p>James Mellaart 1958’de keşfetti ve 1960’larda kazdı. 1993–2017’de <b>Ian Hodder</b> yönetimindeki kazılar <b>düşünümsel arkeoloji</b>yi uyguladı: yorum, kazı sırasında başlar; farklı bakış açıları (yerel halk, uzmanlar, sanatçılar) sürece katılır.</p>' },
      { x: 35, y: 64, ad: "Tabela", panel: '<h3>Truva: Hisarlık</h3><p>Çanakkale yakınındaki Hisarlık Tepesi’nde üst üste binmiş dokuz ana yerleşim katmanı var. İşadamı <b>Heinrich Schliemann</b> 1870’lerde Homeros’un Troia’sını ararken en alt katmanlara hızla inmek için büyük bir yarık açtı ve üstteki katmanları büyük ölçüde tahrip etti.</p><p>1873’te bulduğu hazineye “Priamos’un Hazinesi” dedi ve Osmanlı’dan kaçırdı; oysa hazine Homeros’un Troia’sından bin yıldan fazla eskiydi. Bugün bir bölümü Moskova’daki Puşkin Müzesi’ndedir.</p><p>Wilhelm Dörpfeld’den Manfred Korfmann’a (1988–2005) süren kazılar kenti yeniden okudu. Arkeoloji hazine avından bağlam bilimine böyle dönüştü.</p>' },
      { x: 74, y: 70, ad: "Çanak çömlek", panel: '<h3>Parçalar ve sıralar</h3><p>Çanak çömlek parçası arkeoloğun en sadık tanığıdır: kırılır ama yok olmaz, biçimi ve bezemesi moda gibi değişir.</p><p><b>Flinders Petrie</b> 1899’da Mısır’daki mezarları, içlerindeki çömlek türlerinin benzerliğine göre sıraya koydu: <b>seriasyon</b> ya da “sıralı tarihleme.” Kesin yıl vermez ama göreli bir kronoloji kurar.</p><p><b>Stratigrafi</b>: kazıda katmanlar tek tek, ters sırayla kaldırılır; bir buluntunun değeri, hangi katmanda ve neyin yanında bulunduğuna, yani <b>bağlamına</b> bağlıdır. Bağlamından koparılan eser bilgi değerini yitirir; kaçak kazı bu yüzden bir yıkımdır.</p>' },
      { x: 81, y: 69, ad: "Kil tablet", panel: '<h3>Kültepe tabletleri</h3><p>Kayseri yakınındaki Kültepe (antik <b>Kaniş</b>) Anadolu’da yazılı tarihin başladığı yerdir. MÖ 20.–18. yüzyıllarda Asurlu tüccarlar burada bir ticaret kolonisi (<i>kârum</i>) kurdu: Asur’dan kalay ve kumaş getirip Anadolu’nun gümüş ve altınıyla takas ettiler.</p><p>Evlerinden 23.000’i aşkın kil tablet çıktı: mektuplar, sözleşmeler, borç senetleri, mahkeme kayıtları, hatta aile kavgaları. Tabletlerdeki yerel adlar bilinen en eski Hint-Avrupa dili sözcükleri arasındadır. Kültepe tabletleri 2015’te UNESCO Dünya Belleği Listesi’ne alındı.</p>' },
      { x: 89, y: 67, ad: "Örnek tüpü", panel: '<h3>Radyokarbon tarihleme</h3><p>Canlılar yaşadıkları sürece atmosferden karbon alır; içlerindeki radyoaktif <b>karbon-14</b>’ün oranı sabittir. Ölünce alım durur ve C-14 yaklaşık <b>5.730 yıllık</b> yarı ömürle bozunur. Kalan miktar ölçülerek bir kemiğin, kömürün ya da tohumun yaşı bulunur.</p><p><b>Willard Libby</b> yöntemi 1949’da geliştirdi (Nobel, 1960). Atmosferdeki C-14 oranı zamanla değiştiği için sonuçlar ağaç halkalarıyla <b>kalibre</b> edilir. Yöntem yaklaşık 50.000 yıla kadar geri gider.</p><p>Arkeolojinin elindeki öteki saatler: ağaç halkaları (dendrokronoloji), termolüminesans, DNA analizi.</p>' },
      { x: 84, y: 90, ad: "Kazı ızgarası", panel: '<h3>Izgara ve kayıt</h3><p><b>Mortimer Wheeler</b> ve <b>Kathleen Kenyon</b>’un geliştirdiği kutu yönteminde alan eşit karelere bölünür; kareler arasında bırakılan duvarlar (<i>balk</i>) katmanların kesitini gösterir.</p><p>Kazı, kazdığını yok eden bir deneydir: aynı katmanı ikinci kez kazamazsın. Bu yüzden her buluntunun üç boyutlu konumu, her katmanın rengi ve dokusu, fotoğraf ve çizimle kaydedilir. Kayıt, kazının kendisidir.</p><p>Günümüzde fotogrametri, 3B tarama ve coğrafi bilgi sistemleri defterin yanına eklendi.</p>' },
      { x: 78, y: 24, ad: "Dron", panel: '<h3>Havadan arkeoloji</h3><p>Birinci Dünya Savaşı’ndaki hava fotoğrafları, ekin izlerinde toprağın altındaki duvarları gösterdi: gömülü bir duvarın üstünde bitkiler daha kısa, bir hendeğin üstünde daha gür büyür.</p><p><b>Lidar</b> (lazerle uzaktan algılama) ağaç örtüsünün altını görmemizi sağlar. 2018’de Guatemala’daki bir tarama, ormanın altında 60.000’i aşkın Maya yapısını, yolları ve tarım teraslarını ortaya çıkardı; Kamboçya’da Angkor çevresinde kayıp kent dokuları bulundu.</p><p>Uydu görüntüleri kaçak kazıları izlemek ve savaşta zarar gören alanları belgelemek için de kullanılıyor.</p>' }
    ]
  });

  /* ════════ DİLBİLİMİ: gece müzesinde Rosetta Taşı ════════ */
  S.kaydet("dilbilimi", {
    ad: "Dilbilimi", ust: "sosyal-bilimler", yer: "Bir müze salonu · gece · Rosetta Taşı’nın önünde", vurgu: "#B0C8E8", alan: "sosyal-bilimler",
    alt: "Camekânda üç yazılı bir taş, duvarda dallanan bir dil ağacı, köşede bir gramofon. Dil nasıl bir sistemdir; nasıl öğrenilir, nasıl değişir?",
    parcacik: { tur: "harf", adet: 60 }, isaret: "halka",
    sozler: [
      { metin: "Dans la langue il n’y a que des différences.", dil: "fr", ceviri: "Dilde yalnızca farklılıklar vardır.", kaynak: "Saussure · Genel Dilbilim Dersleri, 1916" },
      { metin: "Colorless green ideas sleep furiously.", dil: "en", ceviri: "Renksiz yeşil fikirler öfkeyle uyur.", kaynak: "Chomsky · Sözdizimsel Yapılar, 1957" },
      { metin: "…sie muss daher von endlichen Mitteln einen unendlichen Gebrauch machen.", dil: "de", ceviri: "…bu yüzden sonlu araçlardan sonsuz bir kullanım yapmalıdır.", kaynak: "Wilhelm von Humboldt, 1836" }
    ],
    arka: function () {
      var s = K.duvar("dl", "#2a2a36", "#12121a");
      s += '<rect y="660" width="1600" height="240" fill="#1a1820"/><path d="M0 660H1600" stroke="#4a4858" stroke-width="5"/>';
      for (var x = 0; x < 1600; x += 100) s += '<path d="M' + x + ' 660L' + (x - 160) + ' 900" stroke="#12101a" stroke-width="2"/>';
      /* dil ağacı (duvar resmi) */
      s += '<g transform="translate(1250 360)" stroke="#b0c8e8" stroke-width="3" fill="none" opacity=".75"><path d="M0 170V40M0 40L-110 -40M0 40L0 -60M0 40L110 -40M-110 -40L-160 -100M-110 -40L-60 -110M0 -60L-30 -130M0 -60L40 -130M110 -40L90 -110M110 -40L170 -100"/>' + [[-160, -100], [-60, -110], [-30, -130], [40, -130], [90, -110], [170, -100]].map(function (p) { return '<circle cx="' + p[0] + '" cy="' + p[1] + '" r="9" fill="#b0c8e8"/>'; }).join("") + '<path d="M-40 170H40"/></g>';
      /* renk kartları */
      s += '<g transform="translate(1000 320)">' + ["#c8302a", "#e8a030", "#e8d840", "#4a9a4a", "#3a6ac8", "#8a4aa8", "#6a4a2a", "#e8e8e8", "#1a1a1a"].map(function (c, i) { return '<rect x="' + (-72 + (i % 3) * 50) + '" y="' + (-72 + Math.floor(i / 3) * 50) + '" width="40" height="40" fill="' + c + '"/>'; }).join("") + "</g>";
      /* Kaşgarlı'nın yuvarlak haritası */
      s += '<g transform="translate(220 480)"><rect x="-100" y="-100" width="200" height="200" fill="#6a4a24"/><rect x="-90" y="-90" width="180" height="180" fill="#e8dcc0"/><circle r="78" fill="#d8c8a0" stroke="#8a6a3a" stroke-width="3"/><circle r="78" fill="none" stroke="#6a9ac8" stroke-width="8" opacity=".5"/><path d="M-40 -30C-10 -50 30 -40 50 -10C40 20 10 40 -20 30C-40 20 -50 0 -40 -30Z" fill="#b8a878"/><circle cx="4" cy="-6" r="5" fill="#a8302a"/></g>';
      /* camekânda Rosetta Taşı */
      s += '<g transform="translate(800 640)"><rect x="-150" y="-280" width="300" height="290" fill="#b8d0e8" opacity=".08" stroke="#d8e8f8" stroke-width="2"/><rect x="-170" y="10" width="340" height="30" fill="#2a2830"/><path d="M-120 0V-200L-60 -250H90L120 -210V0Z" fill="#2a2a30"/>' +
        [0, 1, 2, 3, 4, 5].map(function (r) { return '<path d="M-100 ' + (-200 + r * 12) + 'h' + (180 - r * 6) + '" stroke="#8a8a92" stroke-width="3" stroke-dasharray="4 3"/>'; }).join("") + [0, 1, 2, 3, 4].map(function (r) { return '<path d="M-104 ' + (-120 + r * 10) + 'h208" stroke="#7a7a82" stroke-width="2" stroke-dasharray="2 2"/>'; }).join("") + [0, 1, 2, 3, 4].map(function (r) { return '<path d="M-106 ' + (-60 + r * 11) + 'h212" stroke="#9a9aa2" stroke-width="2" stroke-dasharray="6 2 2 2"/>'; }).join("") +
        '<ellipse cx="-30" cy="-190" rx="22" ry="8" fill="none" stroke="#e8c870" stroke-width="2"/></g>';
      /* palmiye yaprağı el yazması (vitrin) */
      s += '<g transform="translate(500 700)"><rect x="-90" y="-50" width="180" height="60" fill="#b8d0e8" opacity=".08" stroke="#d8e8f8"/><rect x="-100" y="10" width="200" height="60" fill="#2a2830"/>' + [0, 1, 2].map(function (i) { return '<rect x="-74" y="' + (-40 + i * 16) + '" width="148" height="12" rx="6" fill="#c8a868"/><path d="M-66 ' + (-34 + i * 16) + 'h132" stroke="#5a3a1a" stroke-dasharray="3 2"/>'; }).join("") + "</g>";
      /* satranç */
      s += '<g transform="translate(1060 740)"><path d="M-6 0V70M-40 70H30" stroke="#1a1414" stroke-width="10"/><ellipse rx="70" ry="16" fill="#5a4a3a"/>';
      var t = '<g transform="scale(1 .32) rotate(45)">'; for (var i = 0; i < 6; i++) for (var j = 0; j < 6; j++) t += '<rect x="' + (i * 10 - 30) + '" y="' + (j * 10 - 30) + '" width="10" height="10" fill="' + ((i + j) % 2 ? "#2a1a10" : "#e8dcc0") + '"/>';
      s += t + '</g><path d="M-10 -4v-16h4v-6h8v6h4v16Z" fill="#e8dcc0"/><circle cx="16" cy="-14" r="6" fill="#1a1010"/><path d="M12 -2l1 -10h6l1 10Z" fill="#1a1010"/></g>';
      /* kara tahta: Chomsky ağacı */
      s += '<g transform="translate(1350 610)"><path d="M-60 0L-80 110M60 0L80 110" stroke="#4a3a2a" stroke-width="6"/><rect x="-120" y="-150" width="240" height="160" fill="#1e3226" stroke="#6a4a2a" stroke-width="8"/><g stroke="#e8f0e8" stroke-width="2" fill="#e8f0e8" font-family="Georgia,serif" font-size="13" text-anchor="middle"><text x="0" y="-122" stroke="none">S</text><path d="M0 -118L-50 -84M0 -118L50 -84"/><text x="-50" y="-70" stroke="none">NP</text><text x="50" y="-70" stroke="none">VP</text><path d="M50 -66L20 -34M50 -66L80 -34"/><text x="20" y="-20" stroke="none">V</text><text x="80" y="-20" stroke="none">NP</text></g></g>';
      /* gramofon */
      s += '<g transform="translate(1470 760)"><rect x="-40" y="0" width="80" height="40" fill="#5a3a22"/><path d="M10 0V-40" stroke="#c8a060" stroke-width="4"/><path d="M10 -40C30 -60 60 -120 30 -140C0 -150 -30 -120 10 -40Z" fill="#c8a060"/><ellipse cy="0" rx="36" ry="6" fill="#1a1414"/></g>';
      return h.svg(s);
    },
    eserler: [
      { x: 50, y: 60, ad: "Rosetta Taşı", panel: '<h3>Rosetta Taşı</h3><p>1799’da Napoléon’un Mısır seferi sırasında Reşit (Rosetta) yakınında bulundu; bugün British Museum’dadır. Üzerinde MÖ 196 tarihli bir rahipler kararnamesi <b>üç yazıyla</b> yazılıdır: hiyeroglif, demotik ve Eski Yunanca.</p><p>Yunanca bölüm okunabildiği için çözümün anahtarı oldu. Thomas Young ilk adımları attı; <b>Jean-François Champollion</b> 1822’de hiyerogliflerin hem sesleri hem de anlamları gösteren karma bir yazı olduğunu gösterdi. Kıptice bilgisi, Mısırca sözcükleri tanımasını sağladı.</p><p>Yazı çözümlemenin öteki büyük öyküleri: Çivi yazısı (19. yüzyıl ortası), Lineer B (Michael Ventris, 1952).</p>' },
      { x: 78, y: 28, ad: "Dil ağacı", panel: '<h3>Dil aileleri</h3><p>1786’da Kalküta’da yargıç <b>William Jones</b>, Sanskritçe, Yunanca ve Latincenin “belki artık var olmayan ortak bir kaynaktan” türemiş olabileceğini söyledi. <b>Hint-Avrupa</b> ailesinin keşfi tarihsel dilbilimi başlattı.</p><p><b>Grimm yasası</b> (1822): Germen dillerinde ünsüzler düzenli olarak kaydı: Latince <i>pater</i> ~ İngilizce <i>father</i>, <i>piscis</i> ~ <i>fish</i>. Ses değişimleri yasalar gibi düzenlidir. August Schleicher (1853) dilleri bir soy ağacında gösterdi.</p><p>Türkçe, Türk dilleri ailesindedir; Altay dilleri üst ailesi tartışmalıdır. Dünyada bugün yaklaşık 7.000 dil konuşuluyor; yaklaşık yarısı tehlike altında.</p>' },
      { x: 14, y: 53, ad: "Kaşgarlı’nın haritası", panel: '<h3>Dîvânu Lugâti’t-Türk</h3><p><b>Kaşgarlı Mahmud</b> 1072–1077 yıllarında Bağdat’ta Abbasi halifesine sunmak için Türkçeyi Araplara öğreten bir sözlük yazdı: Türk dillerinin bilinen ilk kapsamlı sözlüğü ve dilbilgisi. Sözcükleri boylara göre karşılaştırır, ses farklılıklarını not eder, atasözleri ve şiirler aktarır.</p><p>Kitaptaki yuvarlak <b>dünya haritası</b> Balasagun’u merkeze alır; Türk boylarının yurtlarını gösteren bilinen en eski haritalardan biridir.</p><p>Tek nüshası 1914’te İstanbul’da bir sahafta ortaya çıktı ve bugün Millet Kütüphanesi’ndedir.</p>' },
      { x: 31, y: 76, ad: "Palmiye yaprakları", panel: '<h3>Pāṇini</h3><p>MÖ yaklaşık 4. yüzyılda Hint dilbilimci <b>Pāṇini</b>, <i>Aṣṭādhyāyī</i> (“Sekiz Bölüm”) adlı eserinde Sanskritçenin dilbilgisini yaklaşık 4.000 kısa kuralla betimledi. Kurallar birbirine başvuran, bir üst dil ve kısaltmalarla işleyen, neredeyse biçimsel bir dizgedir.</p><p>Leonard Bloomfield onu “insan zekâsının en büyük anıtlarından biri” saydı. Pāṇini’nin yöntemleri, bilgisayar dillerini tanımlamak için kullanılan Backus–Naur biçimiyle karşılaştırılır.</p>' },
      { x: 66, y: 81, ad: "Satranç", panel: '<h3>Saussure: dil bir sistemdir</h3><p><b>Ferdinand de Saussure</b>’ün Cenevre’deki dersleri, ölümünden sonra öğrencilerinin notlarından derlenerek yayımlandı (<i>Genel Dilbilim Dersleri</i>, 1916).</p><ul><li><b>Dil (langue)</b> ve <b>söz (parole)</b>: toplumsal sistem ile bireysel kullanım.</li><li><b>Gösteren</b> (ses imgesi) ile <b>gösterilen</b> (kavram) arasındaki bağ nedensizdir: “ağaç”, “tree”, “arbre”.</li><li><b>Eşzamanlı</b> ve <b>artzamanlı</b> inceleme.</li></ul><p>Satranç benzetmesi: bir taşın ne olduğu, tahtadaki öbür taşlarla ilişkisine bağlıdır; fildişinden ya da tahtadan yapılmış olması önemsizdir. Yapısalcılık buradan antropolojiye ve edebiyat kuramına yayıldı.</p>' },
      { x: 84, y: 60, ad: "Kara tahta", panel: '<h3>Chomsky ve üretici dilbilgisi</h3><p><b>Noam Chomsky</b> (<i>Sözdizimsel Yapılar</i>, 1957) dilbilgisini, bir dildeki bütün ve yalnızca dilbilgisel tümceleri üreten sonlu bir kurallar dizgesi olarak tanımladı. “Renksiz yeşil fikirler öfkeyle uyur” anlamsızdır ama dilbilgiseldir: sözdizimi anlamdan bağımsız incelenebilir.</p><p>1959’da Skinner’ın davranışçı dil kuramını eleştirdi: çocuklar duydukları sınırlı ve kusurlu örneklerden sonsuz sayıda yeni tümce kurmayı öğrenir (<b>uyaran yoksulluğu</b>). Önerisi: insanlar doğuştan bir <b>evrensel dilbilgisi</b> taşır.</p><p>Tartışma sürüyor: kullanıma dayalı ve istatistiksel öğrenme kuramları, büyük dil modelleri bu soruyu yeniden açtı.</p>' },
      { x: 92, y: 80, ad: "Gramofon", panel: '<h3>Sesbilim</h3><p>Dillerin sesleri <b>Uluslararası Fonetik Alfabesi</b> (IPA, 1888) ile yazılır: her ses için tek bir simge. Türkçe “ı” /ɯ/, “ş” /ʃ/, “ğ” ise çoğu zaman önceki ünlüyü uzatır.</p><p><b>Sesbirim</b> (fonem) anlam ayırt eden en küçük ses birimidir: <i>kar</i> ile <i>gar</i> yalnızca /k/ ile /g/ ile ayrılır. Nikolay Trubetskoy ve Roman Jakobson (Prag Okulu, 1930’lar) sesbirimleri özellik karşıtlıklarıyla çözümledi.</p><p>Türkçenin ses uyumu: ekler kökün ünlüsüne uyar (<i>ev-ler</i>, <i>at-lar</i>); Fince, Macarca ve Moğolcada da benzer uyumlar var.</p>' },
      { x: 62, y: 33, ad: "Renk kartları", panel: '<h3>Dil düşünceyi biçimlendirir mi?</h3><p><b>Sapir–Whorf varsayımı</b>: konuştuğumuz dil dünyayı nasıl algıladığımızı ve düşündüğümüzü etkiler. Güçlü biçimi (dil düşünceyi belirler) büyük ölçüde terk edildi; zayıf biçimi deneylerle sınanıyor.</p><p>Brent Berlin ve Paul Kay (1969) dillerin renk terimlerinin rastgele değil, evrensel bir sırayla eklendiğini buldu: önce açık–koyu, sonra kırmızı, sonra yeşil ya da sarı… Rusçada açık mavi (<i>goluboy</i>) ile koyu mavi (<i>siniy</i>) ayrı sözcüklerdir ve konuşucular bu tonları biraz daha hızlı ayırt eder (2007).</p><p class="pn-not">“Eskimoların kar için yüzlerce sözcüğü var” iddiası büyük ölçüde bir mittir: Geoffrey Pullum buna “büyük Eskimo sözcük aldatmacası” der.</p>' }
    ]
  });

  /* ════════ HUKUK: eski bir adliye, gece ════════ */
  S.kaydet("hukuk", {
    ad: "Hukuk", ust: "sosyal-bilimler", yer: "Eski bir adliye · duruşma salonu · gece", vurgu: "#D8C8A0", alan: "sosyal-bilimler",
    alt: "Kürsünün yanında gözleri bağlı bir kadın heykeli, köşede kara bir taş, rahlede kalın ciltler. Hukuk nedir, adaletle aynı şey mi?",
    parcacik: { tur: "toz", adet: 60 }, isaret: "halka", sozYer: "sag",
    sozler: [
      { metin: "Iustitia est constans et perpetua voluntas ius suum cuique tribuendi.", dil: "la", ceviri: "Adalet, herkese hakkını vermek yönündeki sürekli ve kalıcı iradedir.", kaynak: "Ulpianus · Digesta 1.1.10" },
      { metin: "Pour qu’on ne puisse abuser du pouvoir, il faut que, par la disposition des choses, le pouvoir arrête le pouvoir.", dil: "fr", ceviri: "İktidarın kötüye kullanılmaması için, şeylerin düzeni içinde iktidarın iktidarı durdurması gerekir.", kaynak: "Montesquieu · Kanunların Ruhu XI.4, 1748" },
      { metin: "Fiat iustitia, et pereat mundus.", dil: "la", ceviri: "Adalet yerini bulsun, dünya yıkılsa da.", kaynak: "İmparator I. Ferdinand’ın düsturu, 16. yy" }
    ],
    arka: function () {
      var s = K.duvar("hk", "#3a2e24", "#17110c");
      s += K.pencere(560, 90, 150, 300, true) + K.pencere(900, 90, 150, 300, true) + K.pencere(1240, 90, 150, 300, true);
      s += '<rect y="640" width="1600" height="260" fill="#241810"/>';
      /* kürsü */
      s += '<g transform="translate(800 640)"><rect x="-260" y="-160" width="520" height="160" fill="#5a3a22"/><rect x="-280" y="-176" width="560" height="22" fill="#6a4a2a"/>' + [-200, -100, 0, 100, 200].map(function (x) { return '<rect x="' + (x - 40) + '" y="-140" width="80" height="120" fill="none" stroke="#3a2414" stroke-width="5"/>'; }).join("") + '<rect x="-70" y="-300" width="140" height="130" fill="#4a2e1a"/><path d="M-70 -300Q0 -340 70 -300" stroke="#6a4a2a" stroke-width="10" fill="none"/></g>';
      /* tokmak */
      s += '<g transform="translate(800 460)"><ellipse cx="0" cy="8" rx="24" ry="6" fill="#3a2414"/><g transform="rotate(-20)"><rect x="-26" y="-12" width="52" height="20" rx="6" fill="#8a5a2e"/><rect x="-4" y="6" width="8" height="40" fill="#6a4020"/></g></g>';
      /* Iustitia heykeli */
      s += '<g transform="translate(560 640)"><rect x="-50" y="-60" width="100" height="60" fill="#8a8078"/><path d="M-24 -60C-30 -140 -20 -200 0 -220C20 -200 30 -140 24 -60Z" fill="#c8c0b0"/><circle cy="-234" r="16" fill="#d8d0c4"/><rect x="-16" y="-240" width="32" height="6" fill="#4a4a6a"/><path d="M18 -190L40 -310" stroke="#b8b0a0" stroke-width="4"/><g class="sallan" style="--a:4deg;--s:5s"><path d="M-20 -200L-60 -200M-60 -200L-80 -170M-60 -200L-40 -170" stroke="#c8a060" stroke-width="2"/><ellipse cx="-60" cy="-168" rx="18" ry="4" fill="#c8a060"/></g></g>';
      /* Hammurabi steli */
      s += '<g transform="translate(1150 640)"><path d="M-50 0V-220C-50 -260 50 -260 50 -220V0Z" fill="#1e1e22"/><g transform="translate(0 -210)"><circle cx="-16" cy="0" r="10" fill="#3a3a40"/><path d="M-26 10v30h20v-30ZM10 -6c8 0 14 10 14 20v26h-24Z" fill="#3a3a40"/></g>' + [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].map(function (r) { return '<path d="M-40 ' + (-150 + r * 14) + 'h80" stroke="#4a4a50" stroke-width="2" stroke-dasharray="3 2 1 2"/>'; }).join("") + '<rect x="-60" y="0" width="120" height="16" fill="#3a3a40"/></g>';
      /* jüri sıraları */
      s += '<g transform="translate(250 720)">' + [0, 1].map(function (r) { return '<rect x="' + (-150 + r * 20) + '" y="' + (-60 + r * 40) + '" width="300" height="18" fill="#5a3a22"/><rect x="' + (-150 + r * 20) + '" y="' + (-90 + r * 40) + '" width="300" height="30" fill="#4a2e1a"/>'; }).join("") + "</g>";
      s += K.raf(20, 360, 190, 280, 71, 4);
      /* Magna Carta vitrini */
      s += '<g transform="translate(700 780)"><rect x="-80" y="-40" width="160" height="70" fill="#b8d0e8" opacity=".08" stroke="#d8e8f8"/><rect x="-90" y="30" width="180" height="50" fill="#3a2a1e"/><rect x="-66" y="-30" width="132" height="54" fill="#e8dcc0"/>' + [0, 1, 2, 3, 4].map(function (r) { return '<path d="M-58 ' + (-22 + r * 9) + 'h116" stroke="#6a5a3a" stroke-dasharray="2 1"/>'; }).join("") + '<circle cx="50" cy="16" r="7" fill="#a8302a"/></g>';
      /* rahle: Corpus ve Mecelle */
      s += '<g transform="translate(1380 720)"><path d="M0 0V120M-40 120H40" stroke="#4a2e1a" stroke-width="10"/><path d="M-110 0L110 -30V-10L-110 20Z" fill="#6a4a2a"/><g transform="rotate(-8)"><rect x="-100" y="-40" width="90" height="40" fill="#6a1e1e"/><path d="M-100 -34h90" stroke="#d9b25e"/><text x="-55" y="-14" text-anchor="middle" font-family="Georgia,serif" font-size="10" fill="#d9b25e">CORPVS</text><rect x="10" y="-52" width="90" height="40" fill="#1e3a2a"/><path d="M10 -46h90" stroke="#d9b25e"/><text x="55" y="-26" text-anchor="middle" font-family="Georgia,serif" font-size="11" fill="#d9b25e">MECELLE</text></g></g>';
      return h.svg(s);
    },
    eserler: [
      { x: 35, y: 47, ad: "Iustitia", panel: '<h3>Adaletin simgeleri</h3><p>Roma’da <b>Iustitia</b>, Yunan’da <b>Themis</b> ve <b>Dike</b>. Elindeki <b>terazi</b> tarafların iddialarının tartılmasını, <b>kılıç</b> kararın yaptırım gücünü simgeler. <b>Göz bağı</b> ise 16. yüzyılda eklendi; ilk başta bir alay (adalet kördür!) olarak, sonra tarafsızlığın simgesi olarak.</p><p>Aristoteles adaleti ikiye ayırır: <b>dağıtıcı</b> adalet (onur ve malların hak edilene göre paylaşılması) ve <b>düzeltici</b> adalet (bir haksızlığın giderilmesi). John Rawls (<i>Bir Adalet Kuramı</i>, 1971) adaleti “toplumsal kurumların ilk erdemi” sayar ve “cehalet peçesi” ardında seçilecek ilkeleri arar.</p>' },
      { x: 72, y: 50, ad: "Kara taş", panel: '<h3>Hammurabi Yasası</h3><p>Babil kralı <b>Hammurabi</b> (hd. yaklaşık MÖ 1792–1750) yasalarını 2,25 metrelik bir bazalt stele kazıttı; tepede kral, adalet tanrısı Şamaş’tan yetki alırken betimlenir. Stel 1901’de Susa’da bulundu ve bugün Louvre’dadır.</p><p>282 madde; ticaret, ücretler, evlilik, miras, hekimlik, inşaat. “Eğer bir adam bir özgür adamın gözünü çıkarırsa, onun gözünü çıkarırlar” (<b>kısas</b>); ama köle ya da sıradan halk için ceza para olabilir: eşitlik değil, sınıflara göre adalet.</p><p>Daha eski yasa metinleri de var: Ur-Nammu (yaklaşık MÖ 2100). Önemli olan, yasanın yazılı ve herkesin görebileceği bir yerde olmasıdır.</p>' },
      { x: 50, y: 51, ad: "Tokmak", panel: '<h3>Doğal hukuk ve hukuki pozitivizm</h3><p>Hukuk nedir? <b>Doğal hukuk</b> geleneğine göre (Cicero, Aquinas, Grotius) insan yasası, akılla bilinebilen daha yüksek bir ahlaki düzene uymalıdır: adaletsiz yasa yasa değildir.</p><p><b>Hukuki pozitivizme</b> göre hukukun varlığı ile ahlaki değeri ayrı sorulardır. <b>Hans Kelsen</b> (<i>Saf Hukuk Kuramı</i>, 1934): bir hukuk düzeni, geçerliliğini birbirinden alan normlar hiyerarşisidir. <b>H. L. A. Hart</b> (<i>Hukuk Kavramı</i>, 1961): birincil kurallar ile bunları tanıyan, değiştiren ve uygulayan ikincil kuralların birliği.</p><p>Nazi dönemi sonrası <b>Gustav Radbruch</b> (1946): yasa, adaletle çelişkisi dayanılmaz ölçüye vardığında hukuk olma niteliğini yitirir.</p>' },
      { x: 44, y: 83, ad: "Magna Carta", panel: '<h3>Magna Carta (1215)</h3><p>İngiltere kralı John, isyan eden baronlarla Runnymede’de bir anlaşma yapmak zorunda kaldı. Metin birkaç ay sonra papa tarafından geçersiz sayıldı; ama yeniden düzenlenip onaylanarak yüzyıllar içinde hukukun üstünlüğünün simgesine dönüştü.</p><p>Ünlü 39. madde: “Hiçbir özgür insan, eşitlerinin yasal kararı ya da ülkenin yasası olmaksızın tutuklanmayacak, hapsedilmeyecek, mülkünden yoksun bırakılmayacak… ” Kralın da yasaya bağlı olduğu fikri, 1689 Haklar Bildirgesi’ne ve ABD Anayasası’na uzanır.</p><p>İnsan hakları çizgisi: 1789 Fransız bildirisi, 1948 <b>İnsan Hakları Evrensel Beyannamesi</b>, 1950 Avrupa İnsan Hakları Sözleşmesi.</p>' },
      { x: 82, y: 75, ad: "Corpus", panel: '<h3>Roma hukuku</h3><p>Bizans imparatoru <b>Iustinianus</b> 529–534 yıllarında yüzyılların Roma hukukunu derletti: <i>Codex</i> (imparator buyrukları), <i>Digesta</i> (hukukçuların görüşleri, 50 kitap), <i>Institutiones</i> (ders kitabı) ve sonradan <i>Novellae</i>. Bütüne <b>Corpus Iuris Civilis</b> denir.</p><p>11. yüzyılda <i>Digesta</i>’nın bir elyazması İtalya’da yeniden bulunur; <b>Bologna</b>’da Irnerius’un dersleriyle Avrupa’nın ilk üniversitesi doğar (geleneksel tarih 1088). Kıta Avrupası’nın medeni hukuku bu mirasın üzerinde yükselir.</p><p>Roma’nın bıraktığı kavramlar hâlâ kullanılıyor: <i>persona</i>, <i>obligatio</i>, <i>dominium</i>, <i>pacta sunt servanda</i>.</p>' },
      { x: 90, y: 72, ad: "Mecelle", panel: '<h3>Mecelle ve Medeni Kanun</h3><p><b>Mecelle-i Ahkâm-ı Adliyye</b> (1869–1876), <b>Ahmed Cevdet Paşa</b> başkanlığındaki bir kurulun Hanefi fıkhının borçlar, eşya ve yargılama hükümlerini madde madde yazdığı 1.851 maddelik bir kanundur. İslam hukukunun ilk büyük kodifikasyonudur.</p><p>İlk 100 maddesi genel kurallardır; örneğin “Zarar izale olunur” (zarar giderilir) ya da “Kadim, kıdemi üzere terk olunur.” Mecelle, Osmanlı’dan ayrılan bazı ülkelerde 20. yüzyılın ikinci yarısına dek yürürlükte kaldı.</p><p>Türkiye 1926’da İsviçre Medeni Kanunu’nu uyarlayan <b>Türk Kanunu Medenisi</b>’ni kabul etti: tek eşlilik, resmî nikâh ve mirasta eşitlik getirdi.</p>' },
      { x: 16, y: 72, ad: "Jüri sırası", panel: '<h3>Beccaria: Suçlar ve Cezalar (1764)</h3><p>26 yaşındaki Milanolu <b>Cesare Beccaria</b> kısa bir kitapla ceza hukukunu değiştirdi: işkence gerçeği bulmaz, güçlü suçluyu kurtarır, zayıf masumu mahkûm eder. Cezalar suçla orantılı, açık ve önceden bilinir olmalı; caydırıcılık cezanın ağırlığından çok kesinliğinden gelir.</p><p>Ölüm cezasına karşı çıkan ilk sistemli metinlerden biridir. Voltaire yorumladı, Katerina ve Leopold yasalarında kullandı; Toscana 1786’da ölüm cezasını kaldıran ilk devlet oldu.</p><p><b>Masumiyet karinesi</b>, <b>kanunsuz suç ve ceza olmaz</b> (<i>nullum crimen, nulla poena sine lege</i>) ilkeleri bu çizgide yerleşti.</p>' },
      { x: 7, y: 52, ad: "Kitaplık", panel: '<h3>Montesquieu: kuvvetler ayrılığı</h3><p><b>Montesquieu</b> (<i>Kanunların Ruhu</i>, 1748) yasaların iklime, dine, ticarete, geleneklere göre değiştiğini karşılaştırmalı olarak inceler: toplum biliminin ve karşılaştırmalı hukukun öncülerindendir.</p><p>Özgürlüğün güvencesi: yasama, yürütme ve yargı güçlerinin ayrı ellerde olması ve birbirini dengelemesi. Aynı kişi ya da kurul üçünü birden elinde tutarsa özgürlük biter.</p><p>İlke ABD Anayasası’nın (1787) “fren ve denge” düzenine, oradan modern anayasacılığa geçti. Yargı bağımsızlığı bugün hukuk devletinin ölçütlerinden biridir.</p>' }
    ]
  });

  /* ════════ İLAHİYAT: Kurtuba Ulu Camii, gece ════════ */
  S.kaydet("ilahiyat", {
    ad: "İlahiyat", ust: "sosyal-bilimler", yer: "Kurtuba · Ulu Cami’nin kemerleri · 12. yüzyıl · gece", vurgu: "#B8D8C0", alan: "sosyal-bilimler",
    alt: "Kırmızı beyaz kemerler ormanı, altın mihrap, kandiller. Bu şehirde İbn Rüşd ile İbn Meymun aynı dilde düşündü. İnanç nasıl anlaşılır, yorumlanır, öğretilir?",
    parcacik: { tur: "toz", adet: 60 }, isaret: "yildiz",
    sozler: [
      { metin: "فإن الحق لا يضاد الحق بل يوافقه ويشهد له", dil: "ar", ceviri: "Hakikat hakikate karşıt olmaz; ona uyar ve ona tanıklık eder.", kaynak: "İbn Rüşd · Faslü’l-Makâl, 1178 civarı" },
      { metin: "Fides quaerens intellectum.", dil: "la", ceviri: "Anlayış arayan iman.", kaynak: "Anselmus · Proslogion’un ilk adı, 1078" },
      { metin: "He who knows one, knows none.", dil: "en", ceviri: "Yalnızca birini bilen hiçbirini bilmez.", kaynak: "Max Müller · Din Bilimine Giriş, 1873" }
    ],
    arka: function () {
      var s = '<rect width="1600" height="900" fill="#140e0a"/>';
      /* kemer sıraları (üç derinlik) */
      [[0.55, 250, 0.45], [0.8, 170, 0.7], [1.1, 90, 1]].forEach(function (k) {
        var o = k[0], y0 = k[1], op = k[2], w = 220 * o;
        for (var x = -w / 2; x < 1600 + w; x += w) {
          s += '<g opacity="' + op + '"><rect x="' + (x - 14 * o) + '" y="' + (y0 + 360 * o) + '" width="' + 28 * o + '" height="' + (900 - y0 - 360 * o) + '" fill="#8a7058"/>';
          for (var v = 0; v < 9; v++) { var a0 = Math.PI + v * Math.PI / 9, a1 = a0 + Math.PI / 9, r1 = w / 2, r2 = w / 2 - 34 * o, cx = x + w / 2, cy = y0 + 360 * o; s += '<path d="M' + (cx + Math.cos(a0) * r1).toFixed(1) + " " + (cy + Math.sin(a0) * r1).toFixed(1) + "A" + r1 + " " + r1 + " 0 0 1 " + (cx + Math.cos(a1) * r1).toFixed(1) + " " + (cy + Math.sin(a1) * r1).toFixed(1) + "L" + (cx + Math.cos(a1) * r2).toFixed(1) + " " + (cy + Math.sin(a1) * r2).toFixed(1) + "A" + r2 + " " + r2 + " 0 0 0 " + (cx + Math.cos(a0) * r2).toFixed(1) + " " + (cy + Math.sin(a0) * r2).toFixed(1) + 'Z" fill="' + (v % 2 ? "#e8dcc0" : "#a83a2a") + '"/>'; }
          s += "</g>";
        }
      });
      /* mihrap */
      s += '<g transform="translate(800 520)"><path d="M-90 120V-60A90 90 0 0 1 90 -60V120Z" fill="#2a1a10" stroke="#d9b25e" stroke-width="10"/><path d="M-60 120V-40A60 60 0 0 1 60 -40V120Z" fill="#c89a40" opacity=".35" class="hale"/><path d="M-110 -150H110V-100H-110Z" fill="#1e3a2a" stroke="#d9b25e" stroke-width="3"/>' + [-80, -40, 0, 40, 80].map(function (x) { return '<circle cx="' + x + '" cy="-125" r="10" fill="none" stroke="#d9b25e" stroke-width="2"/>'; }).join("") + "</g>";
      s += '<defs><linearGradient id="ilU" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#140e0a"/><stop offset=".3" stop-color="#140e0a" stop-opacity=".85"/><stop offset=".45" stop-color="#140e0a" stop-opacity="0"/></linearGradient></defs><rect width="1600" height="900" fill="url(#ilU)"/><rect y="680" width="1600" height="220" fill="#2a1a12"/>' + [0, 1, 2, 3, 4, 5, 6].map(function (i) { return '<rect x="' + (i * 240 - 40) + '" y="690" width="200" height="200" fill="' + ["#6a1e1e", "#1e3a4a", "#5a3a1a"][i % 3] + '" opacity=".35"/>'; }).join("");
      /* kandiller */
      [260, 540, 1060, 1340].forEach(function (x, i) { s += '<g class="asili" style="--s:' + (5 + i) + 's;--a:2deg"><path d="M' + x + ' 0V' + (200 + (i % 2) * 40) + '" stroke="#a8804a" stroke-width="2"/><path d="M' + (x - 22) + " " + (200 + (i % 2) * 40) + "h44l-8 26h-28Z" + '" fill="#c8a050"/><circle cx="' + x + '" cy="' + (216 + (i % 2) * 40) + '" r="30" fill="#ffd890" opacity=".22" class="hale"/></g>'; });
      /* rahle ve Mushaf */
      s += '<g transform="translate(600 740)"><path d="M-50 0L50 -40M-50 -40L50 0" stroke="#6a4020" stroke-width="10"/><path d="M-44 -46L0 -30L44 -46L44 -40L0 -24L-44 -40Z" fill="#1e4a2a"/><path d="M-40 -44L0 -30L40 -44" stroke="#efe2c2" stroke-width="3" fill="none"/></g>';
      /* fıkıh kitapları */
      s += K.kitaplar(760, 790, 5, 83);
      /* minder ve ney */
      s += '<g transform="translate(1000 790)"><rect x="-60" y="-10" width="120" height="24" rx="10" fill="#8a2a2a"/><path d="M-70 -20L70 -30" stroke="#c8a870" stroke-width="7" stroke-linecap="round"/>' + [-40, -24, -8, 8].map(function (x) { return '<circle cx="' + x + '" cy="' + (-22 - (x + 40) * 0.07) + '" r="2" fill="#5a3a1a"/>'; }).join("") + "</g>";
      /* kürsüde İncil elyazması */
      s += '<g transform="translate(1200 720)"><path d="M0 0V100M-30 100H30" stroke="#4a2e1a" stroke-width="8"/><path d="M-60 0L60 -20V-6L-60 14Z" fill="#6a4a2a"/><path d="M-50 -10L0 -26L50 -34V-28L0 -20L-50 -4Z" fill="#efe2c2"/><rect x="-6" y="-40" width="12" height="4" fill="#d9b25e"/><path d="M0 -44V-30M-6 -38H6" stroke="#d9b25e" stroke-width="2"/></g>';
      /* Tevrat tomarı */
      s += '<g transform="translate(1350 740)"><rect x="-44" y="-40" width="88" height="44" fill="#efe2c2"/><rect x="-56" y="-60" width="14" height="84" rx="6" fill="#6a3a1e"/><rect x="42" y="-60" width="14" height="84" rx="6" fill="#6a3a1e"/><path d="M-36 -30h72M-36 -20h72M-36 -10h60" stroke="#3a2a1a" stroke-width="1.5"/></g>';
      /* kitaplık ve usturlap */
      s += K.raf(1400, 460, 190, 220, 87, 3) + '<g transform="translate(1480 620)"><circle r="20" fill="#c8a050"/><circle r="14" fill="none" stroke="#6a4a1a"/><path d="M-14 0H14" stroke="#6a4a1a" stroke-width="2"/></g>';
      return h.svg(s);
    },
    eserler: [
      { x: 16, y: 55, ad: "Kemerler", panel: '<h3>Kurtuba: üç dinin şehri</h3><p>Emevi emiri I. Abdurrahman 785’te caminin yapımını başlattı; iki renkli çift kemerler yüzyıllar içinde genişletilerek bir “sütun ormanı”na dönüştü. 1236’da kent Kastilya’nın eline geçince yapı katedrale çevrildi.</p><p>10.–12. yüzyıllarda Kurtuba’da Arapça, Müslüman, Yahudi ve Hristiyan bilginlerin ortak diliydi. <b>İbn Rüşd</b> (1126–1198) burada kadılık yaptı ve Aristoteles şerhlerini yazdı; <b>Musa b. Meymun</b> (Maimonides, 1138–1204) burada doğdu ve <i>Delâletü’l-Hâirîn</i>’i (Şaşkınlara Kılavuz) Arapça yazdı.</p><p>Toledo’daki çevirmenler bu eserleri Latinceye aktardı; Aquinas ve Latin Avrupa İbn Rüşd’ü “Şârih” adıyla okudu.</p>' },
      { x: 50, y: 50, ad: "Mihrap", panel: '<h3>Kelam: akıl ve vahiy</h3><p><b>Kelam</b>, inanç ilkelerini akli delillerle savunan ve temellendiren İslam ilahiyatıdır. İlk büyük okul <b>Mutezile</b>: Tanrı’nın adaleti ve birliği, insanın özgür iradesi, iyinin ve kötünün akılla bilinebilmesi. Abbasi halifesi Me’mun döneminde Kur’an’ın “yaratılmış” olduğu görüşü resmîleşti ve karşı çıkanlar sorgulandı (mihne, 833).</p><p><b>Eş’arilik</b> (Eş’arî, ö. 935) ve <b>Mâtürîdîlik</b> (Mâtürîdî, ö. 944, Semerkant) Sünni kelamın iki ana okulu oldu; Türkler arasında Mâtürîdîlik yaygınlaştı.</p><p>Kelamın atomculuğu ve nedensellik tartışmaları, <b>Gazzâlî</b> ile İbn Rüşd arasındaki ünlü tartışmada doruğa ulaştı.</p>' },
      { x: 37, y: 78, ad: "Mushaf", panel: '<h3>Tefsir ve hadis</h3><p><b>Tefsir</b>, Kur’an’ın anlamını açıklama ilmidir. Taberî’nin (ö. 923) büyük tefsiri, sahabe ve tabiînden gelen rivayetleri toplar; Zemahşerî (ö. 1144) dil ve belağat üzerinde durur; Fahreddin er-Râzî (ö. 1210) felsefi ve kelami tartışmaları katar.</p><p><b>Hadis</b> ilmi, Hz. Muhammed’e atfedilen söz ve davranışların güvenilirliğini, onları aktaranların zincirini (<i>isnad</i>) inceleyerek sınar. Buhârî’nin (ö. 870) <i>el-Câmiu’s-Sahîh</i>’i en çok itibar edilen derlemelerdendir.</p><p>Günümüzde tarihsel ve hermenötik yöntemler de kullanılıyor: metin, bağlamı ve bugünkü okuru arasındaki ilişki.</p>' },
      { x: 48, y: 84, ad: "Fıkıh kitapları", panel: '<h3>Fıkıh ve usul</h3><p><b>Fıkıh</b>, ibadetlerden ticarete, aileden cezaya kadar dinî-hukuki hükümlerin bilgisidir. Sünni dünyada dört büyük mezhep yerleşti: Hanefi, Mâlikî, Şâfiî ve Hanbelî. Osmanlı’nın resmî mezhebi Hanefilikti.</p><p><b>Usûl-i fıkıh</b>, hükümlerin hangi kaynaklardan ve nasıl çıkarılacağını belirler: Kur’an, sünnet, <b>icmâ</b> (âlimlerin görüş birliği) ve <b>kıyas</b> (benzetme). İmam Şâfiî’nin <i>er-Risâle</i>’si (9. yy başı) bu alanın ilk sistemli eseri sayılır.</p><p>Şâtıbî (ö. 1388) hükümlerin amaçlarını (<i>makâsıd</i>) öne çıkardı: dinin, canın, aklın, neslin ve malın korunması.</p>' },
      { x: 62, y: 86, ad: "Ney", panel: '<h3>Tasavvuf</h3><p><b>Tasavvuf</b>, İslam’ın iç boyutunu, nefsin arınmasını ve Tanrı’ya yakınlığı öne çıkaran yoldur. Cüneyd-i Bağdâdî, Hallâc, Rabiatü’l-Adeviyye erken dönemin büyük adlarıdır.</p><p><b>Gazzâlî</b> (ö. 1111) bir bunalımdan sonra kürsüsünü bırakır ve <i>İhyâu Ulûmi’d-Dîn</i>’de fıkıh, kelam ve tasavvufu bir araya getirir. <b>İbn Arabî</b> (Mürsiye doğumlu, ö. 1240 Şam) varlık, isimler ve insan-ı kâmil üzerine derin bir metafizik kurar.</p><p><b>Mevlânâ</b>’nın <i>Mesnevî</i>’si neyin şikâyetiyle açılır: kamışlıktan koparılan ney ayrılığı anlatır. Yunus Emre ise aynı arayışı Anadolu Türkçesiyle söyler.</p>' },
      { x: 75, y: 77, ad: "İncil elyazması", panel: '<h3>Hristiyan teolojisi</h3><p>325’te İznik’te toplanan ilk ekümenik konsil, Oğul’un Baba ile “aynı özden” olduğunu karara bağlayan <b>İznik İnanç Bildirgesi</b>’ni kabul etti. 451 Kadıköy Konsili, Mesih’te iki doğanın birliğini tanımladı: teolojinin temel kararlarının bir bölümü bugünkü Türkiye topraklarında alındı.</p><p><b>Augustinus</b> lütuf ve günah üzerine Batı teolojisini biçimlendirdi. <b>Thomas Aquinas</b> Aristoteles’i Hristiyan düşüncesiyle bütünleştirdi. 1517’de Luther’in tezleriyle başlayan Reform, kutsal metin ile gelenek arasındaki ilişkiyi yeniden sordu.</p>' },
      { x: 84, y: 79, ad: "Tevrat tomarı", panel: '<h3>Yahudi düşüncesi</h3><p><b>Tevrat</b> (Tora), Yahudiliğin kutsal metninin ilk beş kitabıdır; sinagogda el yazması tomarlardan okunur. Sözlü geleneğin derlemesi <b>Mişna</b> (yaklaşık 200) ve onun üzerine yapılan tartışmalar <b>Talmud</b>’u oluşturur: sayfanın ortasında metin, çevresinde yüzyılların yorumları.</p><p><b>İbn Meymun</b> (Maimonides) inancın 13 ilkesini derledi ve <i>Şaşkınlara Kılavuz</i>’da kutsal metnin insan biçimli ifadelerinin mecazi okunması gerektiğini savundu; Tanrı’yı ancak olumsuz sıfatlarla (ne olmadığıyla) betimleyebiliriz.</p>' },
      { x: 93, y: 62, ad: "Kitaplık", panel: '<h3>Karşılaştırmalı dinler</h3><p><b>Bîrûnî</b> (973–1048) <i>Tahkîku mâ li’l-Hind</i>’de Hint dinlerini Sanskrit kaynaklarından, yargılamadan ve kendi sözleriyle anlatmaya çalıştı: dinler tarihinin ilk nesnel incelemelerinden biri. Şehristânî (ö. 1153) <i>el-Milel ve’n-Nihal</i>’de dinleri ve mezhepleri sınıflandırdı.</p><p>19. yüzyılda <b>Max Müller</b> “din bilimi”ni kurdu: “Yalnızca birini bilen hiçbirini bilmez.” Durkheim, Weber, Eliade ve William James dini toplumsal, tarihsel ve psikolojik yönleriyle incelediler.</p><p>Bugün ilahiyat fakültelerinde din sosyolojisi, din psikolojisi, dinler tarihi ve din felsefesi bu mirası sürdürür.</p>' }
    ]
  });

  /* ════════ SİYASET VE SOSYOLOJİ: sanayi kenti, akşam ════════ */
  S.kaydet("siyaset-sosyoloji", {
    ad: "Siyaset ve Sosyoloji", ust: "sosyal-bilimler", yer: "Bir sanayi kenti · 19. yüzyıl sonu · akşam", vurgu: "#C8A8A0", alan: "sosyal-bilimler",
    alt: "Fabrika bacaları tütüyor, köprüden işçiler geçiyor, bürolarda lambalar yanıyor. Toplum nasıl bir arada durur? Güç kimde ve neden?",
    parcacik: { tur: "kor", adet: 30 }, isaret: "halka",
    sozler: [
      { metin: "ἄνθρωπος φύσει πολιτικὸν ζῷον.", dil: "grc", ceviri: "İnsan doğası gereği siyasal bir varlıktır.", kaynak: "Aristoteles · Politika I.2, 1253a" },
      { metin: "Il faut traiter les faits sociaux comme des choses.", dil: "fr", ceviri: "Toplumsal olgular birer şey gibi ele alınmalıdır.", kaynak: "Durkheim · Sosyolojik Yöntemin Kuralları, 1895" },
      { metin: "Politik bedeutet ein starkes langsames Bohren von harten Brettern mit Leidenschaft und Augenmaß zugleich.", dil: "de", ceviri: "Siyaset, sert tahtaları tutku ve sağduyuyla, güçlü ve yavaş biçimde delmektir.", kaynak: "Max Weber · Meslek Olarak Siyaset, 1919" }
    ],
    arka: function () {
      var s = K.gokAksam("ss");
      /* telgraf telleri */
      s += '<path d="M0 190Q400 240 800 190T1600 190M0 206Q400 256 800 206T1600 206" stroke="#1a1418" stroke-width="2" fill="none"/>' + [300, 1300].map(function (x) { return '<path d="M' + x + ' 180V520M' + (x - 30) + ' 196H' + (x + 30) + '" stroke="#2a2024" stroke-width="8"/>'; }).join("");
      /* fabrika */
      s += '<g fill="#2a1e1e"><rect x="120" y="440" width="380" height="200"/><path d="M120 440l60 -50 60 50 60 -50 60 50 60 -50 60 50Z"/><rect x="170" y="310" width="34" height="140"/><rect x="400" y="340" width="30" height="110"/></g>';
      [[187, 310], [415, 340]].forEach(function (b, i) { s += '<g class="duman" style="animation-delay:-' + i * 1.5 + 's"><circle cx="' + b[0] + '" cy="' + (b[1] - 20) + '" r="22" fill="#6a5a5a" opacity=".45"/><circle cx="' + (b[0] + 24) + '" cy="' + (b[1] - 50) + '" r="30" fill="#6a5a5a" opacity=".3"/></g>'; });
      for (var w = 0; w < 6; w++) s += '<rect x="' + (150 + w * 55) + '" y="500" width="30" height="40" fill="#ffc870" opacity="' + (0.4 + (w % 3) * 0.2) + '"/>';
      /* kilise kulesi */
      s += '<g fill="#2e2228"><rect x="720" y="430" width="80" height="210"/><path d="M710 430L760 330L810 430Z"/><path d="M760 330V300M750 310H770" stroke="#2e2228" stroke-width="5"/></g><circle cx="760" cy="470" r="18" fill="#e8d8b0" opacity=".8"/>';
      /* büro binası */
      s += '<g transform="translate(1000 360)"><rect width="260" height="280" fill="#3a2e2e"/><path d="M-10 0H270L130 -50Z" fill="#2a2024"/>' + [0, 1, 2].map(function (r) { return [0, 1, 2, 3].map(function (c) { return '<rect x="' + (20 + c * 60) + '" y="' + (30 + r * 80) + '" width="40" height="56" fill="#ffd890" opacity="' + (((r + c) % 3) ? 0.75 : 0.25) + '"/><path d="M' + (24 + c * 60) + " " + (60 + r * 80) + "h32M" + (24 + c * 60) + " " + (72 + r * 80) + 'h32" stroke="#6a4a2a" stroke-width="3"/>'; }).join(""); }).join("") + "</g>";
      /* gözetleme kulesi */
      s += '<g transform="translate(1440 640)"><path d="M-60 0V-240H60V0Z" fill="#2a2226"/><path d="M-70 -240H70L0 -290Z" fill="#1e181c"/>' + [-40, -10, 20].map(function (x) { return '<rect x="' + x + '" y="-220" width="16" height="30" fill="#ffe0a0" opacity=".9"/>'; }).join("") + '<circle cx="0" cy="-205" r="80" fill="#ffe0a0" opacity=".08" class="hale"/></g>';
      /* ırmak ve köprü */
      s += '<rect y="640" width="1600" height="260" fill="#2a2a38"/><path class="dalga-x" d="M-160 840q40 -6 80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0t80 0" stroke="rgba(255,210,160,.25)" stroke-width="2" fill="none"/>';
      s += '<path d="M0 680H1600V700H0Z" fill="#4a3a36"/><path d="M200 700Q400 780 600 700M600 700Q800 780 1000 700M1000 700Q1200 780 1400 700" stroke="#4a3a36" stroke-width="14" fill="none"/>';
      for (var p = 0; p < 22; p++) { var x = 60 + p * 32 + (p % 3) * 6, hh = 34 + (p % 4) * 4; s += '<g class="yuz" style="--s:' + (3 + (p % 5)) + 's"><rect x="' + x + '" y="' + (680 - hh) + '" width="12" height="' + (hh - 10) + '" rx="4" fill="#1a1216"/><circle cx="' + (x + 6) + '" cy="' + (680 - hh - 4) + '" r="6" fill="#1a1216"/></g>'; }
      /* sandık ve kiosk */
      s += '<g transform="translate(900 800)"><rect x="-40" y="-44" width="80" height="60" fill="#8a6a4a"/><rect x="-24" y="-48" width="48" height="6" fill="#1a1010"/><g class="yuz" style="--s:3s"><rect x="-12" y="-78" width="24" height="30" fill="#efe8dc"/></g><path d="M-40 -14H40" stroke="#5a3a22" stroke-width="3"/></g>';
      s += '<g transform="translate(1170 780)"><rect x="-60" y="-100" width="120" height="120" fill="#3a4a3a"/><path d="M-72 -100H72L60 -126H-60Z" fill="#2a3a2a"/><rect x="-48" y="-80" width="96" height="60" fill="#efe2c2"/><path d="M-40 -70h80M-40 -60h60M-40 -50h70M-40 -40h50" stroke="#3a2a1a" stroke-width="2"/><text x="0" y="-108" text-anchor="middle" font-family="Georgia,serif" font-size="12" fill="#e8d8b0">GAZETE</text></g>';
      return h.svg(s);
    },
    eserler: [
      { x: 18, y: 55, ad: "Fabrika", panel: '<h3>Marx ve sınıf</h3><p>Genç <b>Friedrich Engels</b> ailesinin Manchester’daki fabrikasında çalışırken işçi mahallelerini gezdi ve <i>İngiltere’de Çalışan Sınıfın Durumu</i>’nu (1845) yazdı. <b>Marx</b> ile birlikte yazdıkları <i>Komünist Manifesto</i> 1848’de yayımlandı.</p><p>Marx’a göre kapitalist toplum iki büyük sınıfa ayrılır: üretim araçlarının sahibi burjuvazi ve emek gücünü satan proletarya. İşçi kendi emeğinin ürününe, üretim sürecine, türsel özüne ve öteki insanlara <b>yabancılaşır</b>.</p><p>Sınıf analizi 20. yüzyılda da yeniden tartışıldı: Weber (sınıf, statü, parti), Bourdieu (ekonomik, kültürel ve toplumsal sermaye).</p>' },
      { x: 47.5, y: 52, ad: "Kilise kulesi", panel: '<h3>Weber: Protestan ahlakı</h3><p><b>Max Weber</b> (<i>Protestan Ahlakı ve Kapitalizmin Ruhu</i>, 1904–05) kapitalizmin doğuşunda fikirlerin rolünü sorar: Kalvinist kurtuluşa seçilmişlik öğretisi, müminleri disiplinli çalışmaya, tasarrufa ve kazancı yeniden yatırıma yöneltti; dünyevi başarı seçilmişliğin işareti gibi görüldü.</p><p>Sonunda dinsel kökler unutulur ve geriye kurallar kalır: modern insan akılcılaşmış bir düzenin “<b>demir kafes</b>”indedir. Weber buna dünyanın <b>büyüsünün bozulması</b> der.</p>' },
      { x: 70, y: 52, ad: "Büro", panel: '<h3>Bürokrasi ve otorite</h3><p>Weber’e göre bir düzenin <b>meşru otorite</b>si üç türe dayanabilir: <b>geleneksel</b> (hep böyleydi), <b>karizmatik</b> (liderin olağanüstü niteliklerine inanç) ve <b>yasal-ussal</b> (kurallara ve makamlara bağlılık).</p><p>Modern devletin en saf biçimi <b>bürokrasi</b>dir: yazılı kurallar, hiyerarşi, uzmanlık, dosyalar, kişisel olmayan karar. En verimli örgütlenme biçimidir ama bireyi bir çarkın dişlisine çevirme tehlikesi taşır.</p><p>Devletin tanımı: belli bir toprak üzerinde meşru fiziksel şiddet tekelini başarıyla elinde tutan insan topluluğu (1919).</p>' },
      { x: 90, y: 46, ad: "Gözetleme kulesi", panel: '<h3>Panoptikon ve disiplin</h3><p><b>Jeremy Bentham</b> (1791) bir hapishane tasarladı: ortada bir kule, çevresinde halka biçiminde hücreler. Gardiyan her hücreyi görür ama mahkûmlar onu göremez; bu yüzden her an izleniyor olabileceklerini düşünerek kendilerini denetlerler.</p><p><b>Michel Foucault</b> (<i>Gözetleme ve Cezalandırma</i>, 1975) panoptikonu modern iktidarın simgesi yapar: iktidar artık bedene işkenceyle değil, gözetim, sınav, kayıt ve normlarla işler; okullar, kışlalar, hastaneler ve fabrikalar “disiplin” toplumunun kurumlarıdır.</p><p>Soru bugün dijital gözetim, veri ve algoritmalar için yeniden soruluyor.</p>' },
      { x: 30, y: 73, ad: "Köprüdeki kalabalık", panel: '<h3>Durkheim: dayanışma ve anomi</h3><p><b>Émile Durkheim</b> sosyolojiyi bağımsız bir bilim olarak kurdu (Bordeaux’da ilk sosyoloji kürsüsü, 1895 civarı). Geleneksel toplumlarda benzerliğe dayanan <b>mekanik dayanışma</b>, modern toplumlarda iş bölümünün ürettiği karşılıklı bağımlılığa dayanan <b>organik dayanışma</b> vardır.</p><p><i>İntihar</i> (1897): en bireysel görünen eylemin oranları bile toplumdan topluma, dinden dine düzenli farklar gösterir. Toplumsal bağların zayıfladığı, normların belirsizleştiği durum <b>anomi</b>dir.</p><p>Georg Simmel (“Büyük Kentler ve Zihinsel Hayat”, 1903) kentlinin uyarı bombardımanına karşı geliştirdiği kayıtsız, hesapçı tavrı inceler.</p>' },
      { x: 56, y: 88, ad: "Oy sandığı", panel: '<h3>Tocqueville ve demokrasi</h3><p>Genç Fransız aristokrat <b>Alexis de Tocqueville</b> 1831’de ABD hapishanelerini incelemek için gitti ve <i>Amerika’da Demokrasi</i>’yi (1835, 1840) yazdı. Eşitliğin yayılmasını durdurulamaz bir tarihsel eğilim olarak görür.</p><p>Demokrasinin tehlikeleri: <b>çoğunluğun tiranlığı</b> ve bireyleri yalnızlaştırıp devlete bağımlı kılan “yumuşak despotizm.” Panzehir: dernekler, yerel yönetimler, basın özgürlüğü.</p><p>Türkiye’de kadınlar 1930’da belediye, 1934’te milletvekili seçimlerinde seçme ve seçilme hakkı kazandı; birçok Avrupa ülkesinden önce.</p>' },
      { x: 73, y: 80, ad: "Gazete bayii", panel: '<h3>Kamusal alan ve hayali cemaatler</h3><p><b>Jürgen Habermas</b> (<i>Kamusallığın Yapısal Dönüşümü</i>, 1962): 18. yüzyılın kahvehaneleri, salonları ve gazeteleri, özel bireylerin kamusal meseleleri akılla tartıştığı bir <b>kamusal alan</b> yarattı. Kitle iletişimi ve reklam bu alanı daha sonra dönüştürdü.</p><p><b>Benedict Anderson</b> (<i>Hayali Cemaatler</i>, 1983): ulus, üyelerinin çoğunun birbirini hiç tanımayacağı ama aynı gazeteyi aynı sabah okuyarak kendini bir topluluk olarak hayal ettiği bir cemaattir. “Matbaa kapitalizmi” ulusal dilleri ve bilinçleri biçimlendirdi.</p>' },
      { x: 58, y: 22, ad: "Telgraf telleri", panel: '<h3>Ağlar ve modernlik</h3><p>Telgraf (1840’lar), demiryolu ve buharlı gemi dünyayı birbirine bağladı; Anthony Giddens bunu modernliğin “zaman-mekân sıkışması” diye anlatır: yerel ilişkiler uzak güçlere bağlanır.</p><p>Ağ düşüncesi sosyolojinin yöntemine de girdi. Mark Granovetter’in “<b>zayıf bağların gücü</b>” (1973): iş bulmada yakın arkadaşlardan çok uzak tanıdıklar işe yarar, çünkü onlar farklı bilgi kaynaklarına bağlanır. Manuel Castells <b>ağ toplumu</b>nu (1996) bilgi akışlarının örgütlediği yeni bir toplumsal yapı olarak tanımlar.</p>' }
    ]
  });

  /* ════════ PSİKOLOJİ VE PSİKANALİZ: Berggasse 19, Viyana ════════ */
  S.kaydet("psikoloji", {
    ad: "Psikoloji ve Psikanaliz", ust: "sosyal-bilimler", yer: "Viyana · Berggasse 19 · muayene odası · akşam", vurgu: "#C8B0D8", alan: "sosyal-bilimler",
    alt: "Üstü halıyla örtülü bir divan, masada antik figürinler, rafta bir metronom. İnsan zihni nasıl işler; neyi bilir, neyi bilmediğini bilmez?",
    parcacik: { tur: "toz", adet: 50 }, isaret: "halka", sozYer: "sag",
    sozler: [
      { metin: "Wo Es war, soll Ich werden.", dil: "de", ceviri: "O’nun olduğu yerde Ben olmalıdır.", kaynak: "Freud · Psikanalize Giriş Dersleri, yeni seri, 1933" },
      { metin: "ψυχῆς πείρατα ἰὼν οὐκ ἂν ἐξεύροιο, πᾶσαν ἐπιπορευόμενος ὁδόν· οὕτω βαθὺν λόγον ἔχει.", dil: "grc", ceviri: "Bütün yolları dolaşsan da ruhun sınırlarını bulamazsın; öyle derin bir logosu vardır.", kaynak: "Herakleitos · DK B45" },
      { metin: "My experience is what I agree to attend to.", dil: "en", ceviri: "Deneyimim, dikkat etmeye razı olduğum şeydir.", kaynak: "William James · Psikolojinin İlkeleri, 1890" }
    ],
    arka: function () {
      var s = K.duvar("ps", "#3a2a2a", "#1a1212");
      s += K.pencere(1220, 120, 170, 300, true);
      s += '<rect y="640" width="1600" height="260" fill="#241814"/><rect x="200" y="690" width="1000" height="200" fill="#6a1e24" opacity=".5"/><rect x="220" y="706" width="960" height="170" fill="none" stroke="#c8a060" stroke-width="3" opacity=".6"/>';
      s += K.raf(30, 330, 230, 330, 91, 4) + K.raf(1400, 440, 180, 220, 93, 3);
      /* Rorschach kartı */
      s += '<g transform="translate(980 420)"><rect x="-80" y="-60" width="160" height="120" fill="#6a4a24"/><rect x="-70" y="-50" width="140" height="100" fill="#f0ece4"/><path d="M0 -40C-10 -30 -40 -40 -50 -20C-60 0 -40 10 -30 30C-20 40 -6 20 0 30C6 20 20 40 30 30C40 10 60 0 50 -20C40 -40 10 -30 0 -40Z" fill="#1a1414"/><circle cx="-20" cy="0" r="6" fill="#f0ece4"/><circle cx="20" cy="0" r="6" fill="#f0ece4"/></g>';
      /* divan */
      s += '<g transform="translate(500 700)"><rect x="-230" y="-60" width="460" height="60" rx="10" fill="#5a2a1e"/><path d="M-230 -60C-260 -100 -250 -140 -210 -130L-200 -60Z" fill="#6a3424"/><rect x="-220" y="-86" width="420" height="30" rx="8" fill="#8a2a24"/><path d="M-200 -86H200" stroke="#c8a060" stroke-width="3" stroke-dasharray="10 6"/><rect x="-210" y="-112" width="80" height="30" rx="12" fill="#c8b090"/><path d="M-220 0v20M220 0v20" stroke="#2a1a10" stroke-width="12"/></g>';
      /* koltuk (analist) */
      s += '<g transform="translate(820 690)"><rect x="-50" y="-100" width="100" height="100" rx="12" fill="#3a4a3a"/><rect x="-60" y="-30" width="120" height="40" rx="8" fill="#4a5a4a"/></g>';
      /* masa: figürinler ve zar */
      s += K.masa(940, 610, 300, "#4a2e1a");
      s += '<g transform="translate(1100 606)">' + [[-40, 44, "#8a7a5a"], [-14, 60, "#6a8a7a"], [12, 36, "#a8804a"], [36, 50, "#7a6a5a"]].map(function (f) { return '<path d="M' + (f[0] - 8) + ' 0V-' + f[1] * 0.7 + "Q" + f[0] + " -" + (f[1] + 6) + " " + (f[0] + 8) + " -" + f[1] * 0.7 + 'V0Z" fill="' + f[2] + '"/><circle cx="' + f[0] + '" cy="-' + (f[1] - 2) + '" r="6" fill="' + f[2] + '"/>'; }).join("") + "</g>";
      s += '<g transform="translate(1000 594)"><rect x="-12" y="-12" width="24" height="24" rx="4" fill="#efe8dc" transform="rotate(14)"/><circle cx="-4" cy="-4" r="2.4" fill="#2a1a10"/><circle cx="4" cy="4" r="2.4" fill="#2a1a10"/></g>';
      s += '<g transform="translate(1200 600)"><path class="duman" d="M0 -8c-6 -10 6 -16 0 -28" stroke="#e8e0d0" stroke-width="2" fill="none"/><rect x="-16" y="-8" width="32" height="8" rx="4" fill="#6a4a2a"/></g>';
      /* metronom */
      s += '<g transform="translate(1480 432)"><path d="M-22 0L-10 -70H10L22 0Z" fill="#6a3a1e"/><g class="sallan" style="--a:22deg;--s:1s;transform-origin:0 -4px"><path d="M0 -4V-76" stroke="#d8c8a0" stroke-width="3"/><rect x="-6" y="-56" width="12" height="8" fill="#c8a060"/></g></g>';
      /* zil (Pavlov) */
      s += '<g transform="translate(180 720)"><rect x="-40" y="0" width="80" height="12" fill="#4a2e1a"/><path d="M0 0V-20" stroke="#8a6a3a" stroke-width="4"/><path d="M-26 -20C-26 -60 26 -60 26 -20Z" fill="#d8b050"/><circle cy="-20" r="5" fill="#8a6a3a"/></g>';
      /* oyuncak bloklar (Piaget) */
      s += '<g transform="translate(700 820)">' + [[-40, 0, "#c8402a"], [-4, 0, "#3a6ac8"], [32, 0, "#e8b030"], [-22, -34, "#4a9a4a"], [14, -34, "#c8402a"], [-4, -68, "#e8b030"]].map(function (b) { return '<rect x="' + b[0] + '" y="' + b[1] + '" width="34" height="34" rx="3" fill="' + b[2] + '"/>'; }).join("") + "</g>";
      /* voltaj paneli (Milgram) */
      s += '<g transform="translate(1300 770)"><rect x="-90" y="-50" width="180" height="70" fill="#3a3a40"/><rect x="-80" y="-40" width="160" height="16" fill="#1a1a1e"/>' + [0, 1, 2, 3, 4, 5, 6, 7].map(function (i) { return '<rect x="' + (-74 + i * 19) + '" y="-12" width="12" height="18" fill="' + (i > 5 ? "#c8302a" : "#d8d8e0") + '"/>'; }).join("") + '<text x="0" y="-28" text-anchor="middle" font-family="sans-serif" font-size="9" fill="#e8c870">15 V ··· 450 V</text></g>';
      return h.svg(s);
    },
    eserler: [
      { x: 31, y: 72, ad: "Divan", panel: '<h3>Freud ve bilinçdışı</h3><p><b>Sigmund Freud</b> 1891’den 1938’e dek Viyana’da Berggasse 19’da yaşadı ve hastalarını dinledi. Hasta divana uzanır, analist arkasında oturur: <b>serbest çağrışım</b> yöntemi, aklına geleni sansürlemeden söyleme kuralı.</p><p><i>Düşlerin Yorumu</i> (1899’da basıldı, 1900 tarihli): düş, bastırılmış bir isteğin kılık değiştirmiş gerçekleşmesidir; bilinçdışına giden “kral yolu.” 1923’te zihni üç yapıyla anlatır: <b>O</b> (id: dürtüler), <b>Ben</b> (ego: gerçeklik), <b>Üstben</b> (süperego: vicdan ve idealler).</p><p>1938’de Nazilerden kaçarak Londra’ya yerleşti. Evi bugün Freud Müzesi’dir; ünlü divanı Londra’dadır.</p>' },
      { x: 69, y: 62, ad: "Figürinler", panel: '<h3>Jung ve arketipler</h3><p>Freud yüzlerce antik figürin toplamıştı; kazıyı psikanalize benzetirdi: katman katman geçmişe inmek. <b>Carl Gustav Jung</b> Freud’la 1907’de tanıştı ve kısa sürede onun en yakın çalışma arkadaşı, “veliahdı” oldu; 1913’te libido ve din konusundaki görüş ayrılıkları yüzünden yolları ayrıldı.</p><p>Jung kişisel bilinçdışının altında bir <b>kolektif bilinçdışı</b> olduğunu savundu: mitlerde, masallarda ve düşlerde tekrar eden <b>arketipler</b> (gölge, anima/animus, bilge yaşlı, kahraman). İçedönük ve dışadönük tipleri de o tanımladı.</p>' },
      { x: 11, y: 76, ad: "Zil", panel: '<h3>Koşullanma ve davranışçılık</h3><p>Rus fizyolog <b>İvan Pavlov</b> sindirim araştırmalarıyla 1904’te Nobel aldı. Deney sırasında köpeklerin yemek görünmeden, onu getiren kişiyi ya da bir uyaranı duyunca salya salgıladığını fark etti: <b>klasik koşullanma</b>. (Ünlü “zil” imgesi aslında daha çok metronom, ıslık ve elektrikli uyaranlarla yapılan deneylerden gelir.)</p><p><b>John B. Watson</b> (1913) psikolojinin konusunun bilinç değil, gözlenebilir davranış olması gerektiğini ilan etti. <b>B. F. Skinner</b> ödül ve cezayla davranışın biçimlendirilmesini (<b>edimsel koşullanma</b>) inceledi.</p>' },
      { x: 92, y: 44, ad: "Metronom", panel: '<h3>Deneysel psikolojinin doğuşu</h3><p>1879’da <b>Wilhelm Wundt</b> Leipzig’de ilk deneysel psikoloji laboratuvarını kurdu. Metronomun vuruşlarını dinleyen denekler, iç gözlemle bilinçlerindeki gerilim ve rahatlama duygularını bildiriyordu; tepki süreleri milisaniyelerle ölçülüyordu.</p><p>Amerika’da <b>William James</b> (<i>Psikolojinin İlkeleri</i>, 1890) bilinci bir “<b>akış</b>” olarak betimledi ve alışkanlık, dikkat, benlik ve duygu üzerine hâlâ okunan bölümler yazdı. Bilişsel devrim (1950’ler) zihni bilgi işleyen bir sistem olarak ele alarak davranışçılıktan sonra “zihni” psikolojiye geri getirdi.</p>' },
      { x: 61, y: 47, ad: "Mürekkep lekesi", panel: '<h3>Projektif testler</h3><p>İsviçreli psikiyatr <b>Hermann Rorschach</b> 1921’de on simetrik mürekkep lekesinden oluşan testini yayımladı. Belirsiz bir uyarana verilen yanıtların kişinin algı ve düşünce biçimine dair ipuçları verdiği düşünülüyordu.</p><p>Test uzun süre yaygın biçimde kullanıldı; bugün geçerliliği ve güvenilirliği tartışmalıdır. Psikolojik ölçmenin temel soruları buradan açıkça görülür: bir test ölçmek istediğini mi ölçüyor (<b>geçerlilik</b>), tutarlı sonuçlar veriyor mu (<b>güvenilirlik</b>)?</p><p>Kişilik araştırmasında bugün en çok kullanılan model “Beş Büyük” özelliktir: açıklık, sorumluluk, dışadönüklük, uyumluluk, duygusal denge.</p>' },
      { x: 44, y: 88, ad: "Bloklar", panel: '<h3>Çocuk nasıl düşünür?</h3><p><b>Jean Piaget</b> çocukların hatalarının rastlantısal değil, sistemli olduğunu gördü. Bilişsel gelişimi evrelere ayırdı: duyusal-motor (0–2), işlem öncesi (2–7), somut işlemler (7–11), soyut işlemler (11+). Beş yaşındaki çocuk, uzun ince bardağa aktarılan suyun “arttığını” düşünür: <b>korunum</b> henüz yoktur.</p><p><b>Lev Vygotsky</b> öğrenmenin toplumsal yanını vurguladı: çocuğun tek başına yapabildiği ile bir yetişkin ya da akranının yardımıyla yapabildiği arasındaki alan, <b>yakınsal gelişim alanı</b>dır. İyi öğretim bu alanda işler.</p>' },
      { x: 81, y: 83, ad: "Voltaj paneli", panel: '<h3>İtaat, durum ve yinelenme</h3><p>1961’de Yale’de <b>Stanley Milgram</b> katılımcılardan, yanlış yanıt veren bir “öğrenci”ye giderek artan elektrik şoku vermelerini istedi (şoklar sahteydi, öğrenci bir oyuncuydu). İlk deneyde katılımcıların %65’i 450 volta kadar devam etti.</p><p>Philip Zimbardo’nun Stanford hapishane deneyi (1971) de durumun gücüne örnek gösterildi; sonradan yöntemi ağır biçimde eleştirildi. Bu deneyler araştırma etiği kurullarının ve bilgilendirilmiş onamın yerleşmesinde rol oynadı.</p><p>2015’te 100 psikoloji çalışmasını yeniden yapan <i>Open Science Collaboration</i>, sonuçların yalnızca yaklaşık üçte birini yineleyebildi: <b>yinelenme krizi</b>, ön kayıt ve açık veri gibi reformları hızlandırdı.</p>' },
      { x: 62, y: 65, ad: "Zar", panel: '<h3>Kahneman ve Tversky: yargının kısayolları</h3><p><b>Daniel Kahneman</b> ve <b>Amos Tversky</b> 1970’lerde insanların belirsizlik altında sistemli biçimde yanıldığını gösterdi. <b>Temsil edicilik</b> (“Linda feminist bir banka memuru” olasılığını “banka memuru”ndan yüksek bulmak), <b>kullanılabilirlik</b> (akla kolay gelen daha olası sanılır), <b>çapalama</b>.</p><p><b>Beklenti kuramı</b> (1979): kayıplar, eşit büyüklükteki kazançlardan yaklaşık iki kat daha fazla acıtır. Kahneman 2002’de Nobel Ekonomi Ödülü’nü aldı (Tversky 1996’da ölmüştü).</p><p><i>Hızlı ve Yavaş Düşünme</i> (2011): hızlı, sezgisel <b>Sistem 1</b> ile yavaş, çaba isteyen <b>Sistem 2</b>.</p>' }
    ]
  });

  var I = function (ic) { return '<g stroke="#f0d890" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round">' + ic + "</g>"; };
  S.merkezeEkle("sosyal-bilimler", [
    { hedef: "arkeoloji", aciklama: "Göbeklitepe: dikilitaşlar, katmanlar, Kültepe tabletleri.", sanat: K.kapi("#E0B078", I('<path d="M-12 50V-20M12 50V-20M-40 -20H40V-44H-40Z"/><path d="M-60 60H60"/><path d="M-6 -4l6 -10 6 10"/>')) },
    { hedef: "dilbilimi", aciklama: "Rosetta Taşı: yazılar, dil aileleri, Saussure, Chomsky.", sanat: K.kapi("#B0C8E8", '<path d="M-44 60V-40L-20 -64H30L44 -46V60Z" fill="#2a2a30" stroke="#f0d890" stroke-width="3"/>' + [0, 1, 2, 3, 4, 5, 6].map(function (r) { return '<path d="M-34 ' + (-40 + r * 14) + 'h68" stroke="#b0c8e8" stroke-width="2" stroke-dasharray="4 3"/>'; }).join("")) },
    { hedef: "hukuk", aciklama: "Eski bir adliye: Hammurabi, Roma hukuku, Mecelle, Montesquieu.", sanat: K.kapi("#D8C8A0", I('<path d="M0 -60V50M-26 50H26M-56 -40H56M-56 -40L-70 -6H-42ZM56 -40L42 -6H70Z"/><rect x="-10" y="-70" width="20" height="10"/>')) },
    { hedef: "ilahiyat", aciklama: "Kurtuba’nın kemerleri: kelam, tefsir, fıkıh, tasavvuf.", sanat: K.kapi("#B8D8C0", '<g>' + [-40, 0, 40].map(function (x) { return '<path d="M' + (x - 20) + ' 50V-10A20 20 0 0 1 ' + (x + 20) + ' -10V50" fill="none" stroke="#f0d890" stroke-width="3"/><path d="M' + (x - 20) + ' -10A20 20 0 0 1 ' + x + ' -30" stroke="#c8402a" stroke-width="5" fill="none"/>'; }).join("") + '</g>') },
    { hedef: "siyaset-sosyoloji", aciklama: "Sanayi kenti: Marx, Weber, Durkheim, Foucault.", sanat: K.kapi("#C8A8A0", I('<path d="M-60 50V0L-40 -14V0L-20 -14V0L0 -14V50Z"/><path d="M-50 -14V-50M20 50V-40H56V50"/><path d="M28 -30h8M40 -30h8M28 -14h8M40 -14h8"/>')) },
    { hedef: "psikoloji", aciklama: "Berggasse 19: Freud, Jung, Pavlov, Piaget, Kahneman.", sanat: K.kapi("#C8B0D8", '<text y="30" text-anchor="middle" font-family="Georgia,serif" font-size="86" fill="#f0d890">ψ</text>') }
  ]);
})();
